Repository ccxt/ccxt, pull requests merged in 2019-11, with the labels that each got.

#6082 okex badSymbol
  js/okex3.js
Labels: enhancement

#5730 save raw content from response
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#6107 Exmo: OnMaintenance
  js/exmo.js
Labels: enhancement

#6108 Bitmax: BadSymbol
  js/bitmax.js
Labels: enhancement

#6109 okex3: fix BadSymbol
  js/okex3.js
Labels: enhancement

#6110 okex3: no peer should be ExchangeNotAvailable
  js/okex3.js
Labels: enhancement

#6111 Whitebit: Fix error handling and add BadSymbol
  js/whitebit.js
Labels: enhancement

#6112 Tidebit: fix error handling
  js/tidebit.js
Labels: enhancement

#6113 ftx: fix fetch trades
  js/ftx.js
Labels: enhancement

#6119 bitbay - improved parse for createOrder
  js/bitbay.js
  js/test/Exchange/test.ticker.js
Labels: enhancement

#6123 bitbay - minor type fix
  js/bitbay.js
Labels: enhancement

#6127 KuCoin - Replace 'sequence' with 'time' in fetch_order_book
  js/kucoin.js
  php/kucoin.php
  python/ccxt/kucoin.py
Labels: enhancement

#6149 Huobi Pro fetchMarkets max amount
  js/huobipro.js
Labels: enhancement

#6160 add space to delete transpile php
  build/transpile.js
Labels: bug

#6159 Exmo new markets
  js/exmo.js
Labels: enhancement

#5951 Add BigONE V3 API
  js/bigone.js
Labels: enhancement

#5757 Add exchange: bw.com
  js/bw.js
Labels: new exchange

#6172 [cex] infer order type using price field
  js/cex.js
Labels: enhancement

#6174 bigONE parseTrade improvement
  js/bigone.js
Labels: enhancement

#6190 Fix: Add bw.com base files
  php/bw.php
  python/ccxt/async_support/bw.py
  python/ccxt/bw.py
Labels: bug

#6191 build/push.sh: Add generated php/python files
  build/push.sh
Labels: enhancement
