Repository ccxt/ccxt, pull requests merged in 2019-10, with the labels that each got.

#5878 Add missing Exchange properties and method definitions
  ccxt.d.ts
  js/binance.js
Labels: enhancement

#5893 Binance future api
  js/binance.js
Labels: enhancement

#5897 Hitbtc: handle errors
  build/transpile.js
  js/hitbtc.js
Labels: enhancement

#5906 Exmo fees more fixes
  js/exmo.js
Labels: enhancement

#5899 Typescript add urls test
  ccxt.d.ts
  js/lykke.js
Labels: enhancement

#5913 iso8601(): don't convert number to a string just to parse it again.
  ccxt.d.ts
  js/base/functions/time.js
Labels: enhancement

#5918 Add bitz transactions
  js/bitz.js
Labels: enhancement

#5921 Set has.fetchTime when fetchTime() exists.
  js/coinbase.js
  js/okex3.js
  js/stronghold.js
Labels: enhancement

#5929 BitBay fetchTrades rewrite
  js/bitbay.js
Labels: enhancement

#5933 Cannot transfer funds between spot and main accounts on Bibox. (#5931)
  js/bibox.js
Labels: enhancement

#5939 Update binance doc
  js/binance.js
Labels: enhancement

#5941 Update RightBTC doc
  js/rightbtc.js
Labels: enhancement

#5943 Update Bibox doc
  js/bibox.js
Labels: enhancement

#5961 Update definitions for order functions
  ccxt.d.ts
Labels: enhancement

#5963 bitfinex2 fetchMyTrades true
  js/bitfinex2.js
Labels: enhancement

#5967 CoinFalcon parseTrade feeCurrencyCode fix
  js/coinfalcon.js
Labels: enhancement

#5964 [coinfloor] implementing some error handling around placing orders
  js/coinfloor.js
Labels: enhancement

#5968 [coinfloor] new error
  js/coinfloor.js
Labels: enhancement

#5975 idex implement fetchTrades
  js/idex.js
Labels: enhancement

#5888 improve postinstall by using async/await
  postinstall.js
Labels: enhancement

#5980 Define precisions based on dictionary instead of inferring from API
  js/bitso.js
  php/bitso.php
  python/ccxt/bitso.py
Labels: enhancement

#5413 New exchange: Bitmax
  js/bitmax.js
Labels: new exchange

#5989 parse_timeframe: dont allow wrong unit
  js/base/functions/misc.js
  js/test/base/functions/test.generic.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#5990 python: filter_by: use python filter and dont group array
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#6005 ZB: Add limit to FetchOrderBook
  js/zb.js
Labels: enhancement

#6012 Fix php autload bug
  php/errors.php
Labels: bug

#6015 [cex] improved error handling
  js/cex.js
Labels: enhancement

#5784 [new exchange] Bytetrade
  build/transpile.js
  js/base/Exchange.js
  js/base/functions/crypto.js
  js/base/functions/encode.js
  js/bytetrade.js
  js/static_dependencies/BN/bn.js
  js/static_dependencies/elliptic/lib/elliptic/curve/base.js
  js/static_dependencies/elliptic/lib/elliptic/curve/edwards.js
  js/static_dependencies/elliptic/lib/elliptic/curve/mont.js
  js/static_dependencies/elliptic/lib/elliptic/curve/short.js
  js/static_dependencies/elliptic/lib/elliptic/ec/index.js
  js/static_dependencies/elliptic/lib/elliptic/ec/key.js
  js/static_dependencies/elliptic/lib/elliptic/ec/signature.js
  js/static_dependencies/elliptic/lib/elliptic/utils.js
  js/static_dependencies/elliptic/lib/hmac-drbg/hmac-drbg.js
  js/test/base/functions/test.number.js
  php/Exchange.php
  php/static_dependencies/elliptic-php/lib/EC.php
  python/ccxt/base/decimal_to_precision.py
  python/ccxt/base/exchange.py
  python/ccxt/static_dependencies/ecdsa/util.py
Labels: new exchange

#6020 [cex] improved error handling
  js/cex.js
Labels: enhancement

#6028 Fix: transpile removed space between not and the following bracket
  build/transpile.js
Labels: enhancement

#6027 Bytetrade: parseTransactionStatusByType more readable
  js/bytetrade.js
Labels: enhancement

#6026 Rename pow/modulo/divide through integer*
  build/transpile.js
  js/base/Exchange.js
  js/bytetrade.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#6030 whitebit: fix handle_error error
  js/whitebit.js
Labels: bug

#6025 Bytetrade: remove redundant safe*2
  js/bytetrade.js
Labels: enhancement

#6029 Binary concat array
  build/transpile.js
  js/base/functions/encode.js
  js/bytetrade.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#6033 Indodax: BadSymbol
  js/indodax.js
Labels: enhancement

#6054 update import
  examples/py/basic-chart.py
Labels: enhancement

#6060 php store cookies in cookiejar without calling curl_close
  php/base/Exchange.php
Labels: enhancement

#6061 [cex] error handling for RateLimitExceeded
  js/base/errorHierarchy.js
  js/cex.js
  wiki/Manual.md
Labels: enhancement
