Repository ccxt/ccxt, pull requests merged in 2020-09, with the labels that each got.

#7588 add xlm_address and xlm_withdrawal bitstamp support
  js/bitstamp.js
Labels: enhancement

#7578 Independent Reserve - Fix to FetchOrder, added FetchOpenOrders & FetchClosedOrders
  js/independentreserve.js
Labels: enhancement

#7474 Binance coin-margined/delivery api
  js/binance.js
Labels: enhancement

#7537 implement idex v2 API
  build/transpile.js
  js/base/Exchange.js
  js/base/functions/encode.js
  js/base/functions/time.js
  js/bytetrade.js
  js/idex2.js
  js/test/Exchange/test.ohlcv.js
  js/wavesexchange.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: new exchange

#7592 remove regex match in base class
  js/base/Exchange.js
Labels: enhancement

#7594 bitmart parseTrade maker/taker
  js/bitmart.js
Labels: enhancement

#7598 bitmart parseTicker volume fix
  js/bitmart.js
Labels: bug

#7603 fix wiki decimal_digits
  wiki/Manual.md
Labels: bug

#7604 update huoibpro.js
  js/huobipro.js
Labels: enhancement

#7615 Add BadSymbol to manual error hierarchy
  wiki/Manual.md
Labels: enhancement

#7617 Digifinex fetchTicker/fetchTickers fix, new v3 endpoint
  js/digifinex.js
Labels: bug

#7623 Improve error matches
  js/binance.js
  js/bitfinex.js
  js/bitmex.js
  js/bitstamp.js
  js/gemini.js
  js/huobipro.js
  js/kucoin.js
  js/okex.js
  js/poloniex.js
Labels: enhancement

#7626 add base method findTimeframe
  build/transpile.js
Labels: enhancement

#7634 remove unnecessary decode when base64 encoding
  js/bit2c.js
  js/bitget.js
  js/bitmax.js
  js/bl3p.js
  js/btcmarkets.js
  js/coinbasepro.js
  js/dsx.js
  js/eterbase.js
  js/itbit.js
  js/kraken.js
  js/kucoin.js
  js/okex.js
  js/qtrade.js
  js/xbtce.js
  python/ccxt/base/exchange.py
Labels: enhancement

#7519 Bittrex api v3
  js/bittrex.js
  js/test/Exchange/test.fetchMyTrades.js
Labels: enhancement
