Repository ccxt/ccxt, pull requests merged in 2020-08, with the labels that each got.

#7203 New Exchange: bitget.com
  js/bitget.js
Labels: new exchange

#7418 digifinex typo fix
  js/digifinex.js
Labels: bug

#7372 [btcmarkets] new api (work in progress)
  js/btcmarkets.js
Labels: enhancement

#7436 add python/php test_order tests
  build/transpile.js
  js/test/Exchange/test.order.js
  php/test/test.php
  php/test/test_order.php
  php/test/test_trade.php
  python/test/test.py
  python/test/test_async.py
  python/test/test_order.py
Labels: enhancement

#7442 fix a numberToString bug
  build/transpile.js
  js/base/functions/number.js
  js/test/base/functions/test.number.js
  php/base/Exchange.php
  php/test/fail_on_all_errors.php
Labels: bug

#7450 bitmax: fix signature: only the end of the path is required
  js/bitmax.js
Labels: bug

#7531 fix httpAgentKeepAlive
  js/base/Exchange.js
Labels: bug
