Repository ccxt/ccxt, pull requests merged in 2020-10, with the labels that each got.

#7600 safeSymbol implementation
  build/transpile.js
  js/base/Exchange.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#7648 kraken support parsing of description string for createOrder
  js/kraken.js
Labels: enhancement

#7645 change input to stringToBase64 to be a string
  js/base/functions/crypto.js
  js/base/functions/encode.js
  js/bitfinex.js
  js/bithumb.js
  js/btcmarkets.js
  js/btcturk.js
  js/buda.js
  js/coinfloor.js
  js/coinone.js
  js/crex24.js
  js/fcoin.js
  js/gemini.js
  js/lakebtc.js
  js/luno.js
  js/probit.js
  js/test/base/test.base.js
  js/timex.js
Labels: enhancement

#7693 safeSymbol support returning market structure
  js/base/Exchange.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#7738 Add API end point for Deposits at Phemex
  js/phemex.js
Labels: enhancement

#7741 Add new Phemex API private endpoint
  js/phemex.js
Labels: enhancement

#7613 Bitstamp upgrade
  examples/js/bitstamp-private-api.js
  examples/js/bitstamp-public-api.js
  js/bitstamp.js
  js/bitstamp1.js
Labels: enhancement

#7760 [coinbasepro] very basic fetchCurrencies implemention with active flag
  js/coinbasepro.js
Labels: enhancement

#7788 Bitforex IP not allow handle
  js/bitforex.js
Labels: enhancement

#7820 Coinfalcon fetchOpenOrders fix
  js/coinfalcon.js
Labels: bug

#7870 make the fee rate configurable
  js/bytetrade.js
Labels: enhancement

#7868 Add bitcoincom exchange
  js/bitcoincom.js
Labels: new exchange

#7877 coinbase pro fetchTransactions code undefined
  js/coinbasepro.js
Labels: enhancement

#7881 coinbase pro - add support for fetchWithdrawals and fetchDeposits
  js/coinbasepro.js
Labels: enhancement
