Repository ccxt/ccxt, pull requests merged in 2020-12, with the labels that each got.

#7984 Add new exchange vcc.exchange
  js/test/Exchange/test.ohlcv.js
  js/vcc.js
Labels: new exchange

#8071 Bybit clientOrderId on createOrder
  js/bybit.js
Labels: enhancement

#8113 Add CDAX exchange (rebranded from Huobi Russia)
  js/cdax.js
Labels: new exchange

#8123 Bitmart improvements
  js/bitmart.js
Labels: enhancement

#8130 bitmart: cancelOrder: fix alternative spot response
  js/bitmart.js
Labels: bug

#8065 Adding Gopax exchange to CCXT
  js/gopax.js
Labels: new exchange

#8128 positions manual
  wiki/Manual.md
Labels: enhancement

#8153 Updata bibox fetchCurrencies
  js/bibox.js
Labels: enhancement
