Repository ccxt/ccxt, pull requests merged in 2020-03, with the labels that each got.

#6542 pro badge
  README.md
  build/export-exchanges.js
  js/base/Exchange.js
  js/binance.js
  js/binanceje.js
  js/binanceus.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitmex.js
  js/bittrex.js
  js/coinbaseprime.js
  js/coinbasepro.js
  js/gateio.js
  js/kraken.js
  js/kucoin.js
  js/poloniex.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
  wiki/Exchange-Markets-By-Country.md
  wiki/Exchange-Markets.md
  wiki/Manual.md
Labels: enhancement

#6547 Python async SOCKS proxy remote DNS failed bug fix
  doc/install.rst
  wiki/Install.md
Labels: enhancement

#6553 pro docs
  wiki/ccxt.pro.install.md
Labels: ccxt.pro

#6560 Gate.io parseTrade enhancement
  js/gateio.js
Labels: enhancement

#6570 Binance market closed exception
  js/binance.js
Labels: enhancement

#6569 bw: add RateLimitExceeded exception
  js/bw.js
Labels: enhancement

#5495 new exchange: hollaex
  js/hollaex.js
Labels: new exchange

#6597 make one http request in an async context
  js/base/Exchange.js
  python/ccxt/async_support/base/exchange.py
Labels: enhancement

#6519 python base exchange: expose lists of base and quote currencies
  js/base/Exchange.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#5546 [WIP] [Deribit] Implementation for version 2 API
  js/deribit2.js
Labels: enhancement

#6605 [coinfloor] removed old market
  js/coinfloor.js
Labels: enhancement

#6606 Fix python async load_markets
  python/ccxt/async_support/base/exchange.py
Labels: bug, enhancement

#6607 OKEX new endpoints
  js/okex3.js
Labels: enhancement

#6256 Bybit solution (reference to PR #5985)
  js/bybit.js
Labels: new exchange

#5985 Add Exchange Bybit support
  js/bybit.js
Labels: new exchange

#6563 okcoinusd: use okex3
  js/okcoincny.js
  js/okcoinusd.js
  js/okex3.js
Labels: enhancement

#6624 Fix bitmax signature encoding
  js/bitmax.js
Labels: bug

#6629 Fix: py3 unicode error at braziliex sign method
  js/braziliex.js
Labels: bug

#6633 [coinmate] fetchOrders, fetchOpenOrders, fetchMyTrades, error handling
  js/coinmate.js
Labels: enhancement

#6635 [coinmate] improved fetchOrder
  js/coinmate.js
Labels: enhancement

#6640 support witness dappId customization
  js/bytetrade.js
Labels: enhancement

#6639 upbit urls
  js/upbit.js
Labels: enhancement

#6649 Gate.io BEAR, BULL mapping
  js/gateio.js
Labels: enhancement

#6650 Crex24 BULL mapping
  js/crex24.js
Labels: enhancement

#6656 modify getBaseMethods
  build/transpile.js
Labels: enhancement

#6661 bcex fees and logo updated
  js/bcex.js
Labels: enhancement

#6662 ftx support pro
  js/ftx.js
Labels: enhancement

#6657 adhere to php style guides
  build/transpile.js
Labels: enhancement

#6682 btcmarkets: createOrder occasionally fails with "incorrect number of decimal points"
  js/btcmarkets.js
Labels: bug

#6685 coinmate - non default fees
  js/coinmate.js
Labels: enhancement

#6687 PHP/Exchange verbosity option
  php/base/Exchange.php
Labels: enhancement

#6690 Fix OKEX USDT swap base error
  js/okex.js
  python/ccxt/okex.py
Labels: bug

#6688 relocation verbose
  js/base/Exchange.js
  php/base/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#6693 Prepare Hitbtc2 exchange for ws in ccxt.pro
  js/bequant.js
  js/hitbtc2.js
Labels: enhancement

#6705 Update okex.js
  js/okex.js
Labels: bug

#6706 coinmate - error handling for InsufficientFunds
  js/coinmate.js
Labels: enhancement

#6709 deribit: fetch_deposits: update exception text
  js/deribit.js
Labels: bug

#6711 bittrex: createOrderV3: fix market ceiling order
  js/bittrex.js
Labels: enhancement
