Repository ccxt/ccxt, pull requests merged in 2020-02, with the labels that each got.

#6449 Stex - fetchFundingFees
  js/stex.js
Labels: enhancement

#6459 parse8601 incorrect parse milliseconds
  js/test/base/functions/test.datetime.js
  python/ccxt/base/exchange.py
Labels: enhancement

#6463 Add few missing properties
  ccxt.d.ts
Labels: enhancement

#6485 XTZ (Tezos) description in bitfinex.js updated
  js/bitfinex.js
Labels: enhancement

#6486 Fix TICK_SIZE floating point error
  js/base/functions/number.js
  js/test/base/functions/test.number.js
  php/base/Exchange.php
Labels: bug

#6455 Add topq exchange
  ccxt.js
  js/bw.js
  js/topq.js
Labels: new exchange

#6371 bleutrade v3 implemention
  js/bleutrade.js
Labels: enhancement

#6505 Add public, private and web URLs for Gemini's test API
  js/gemini.js
Labels: bug

#6454 Exchange.indexBy : accept elements that are array in Python
  js/base/functions/type.js
  python/ccxt/base/exchange.py
Labels: enhancement

#6369 bitfinex2: Implement some methods
  js/bitfinex2.js
Labels: enhancement

#6516 generate errors in transpile for intellisense
  appveyor.yml
  build/transpile.js
  js/test/base/functions/test.number.js
  php/base/errors.php
  python/ccxt/base/errors.py
Labels: enhancement

#6312 remove javascript dependencies
  build/transpile.js
  js/base/Exchange.js
  js/base/functions/generic.js
  js/base/functions/number.js
  js/bytetrade.js
  js/idex.js
  js/test/base/functions/test.crypto.js
  js/test/base/functions/test.number.js
  js/theocean.js
  php/base/Exchange.php
  php/test/decimal_to_precision.php
  php/test/test_crypto.php
  python/ccxt/base/decimal_to_precision.py
  python/ccxt/base/exchange.py
  python/test/test_crypto.py
  python/test/test_decimal_to_precision.py
Labels: enhancement

#6517 BitBay add fetchOHLCV, fix error types
  js/bitbay.js
Labels: enhancement

#6521 Bugfix okex loadmarkets
  js/okcoinusd.js
  python/ccxt/okcoinusd.py
Labels: bug

#6526 Support for carrying messages when transferring asset
  js/bytetrade.js
Labels: enhancement

#6541 ByteTrade fix fetchMarkets
  js/bytetrade.js
Labels: bug
