Repository ccxt/ccxt, pull requests merged in 2020-06, with the labels that each got.

#7046 A bug in loadMarkets() for Kuna Exchange fixed (GOL quote coin added)
  js/kuna.js
Labels: bug

#7062 Enhance coinone exchange market/ticker/orderbook/trades
  examples/js/coinone-fetch-tickers.js
  examples/js/coinone-markets.js
  examples/php/coinone-fetch-tickers.php
  examples/php/coinone-markets.php
  examples/py/coinone-fetch-tickers.py
  examples/py/coinone-markets.py
  js/coinone.js
Labels: enhancement

#7080 kraken: implement fetchTime().
  js/kraken.js
Labels: enhancement

#6609 update to bitmax new api
  js/bitmax.js
  php/bitmax.php
  python/ccxt/async_support/bitmax.py
  python/ccxt/bitmax.py
Labels: enhancement

#7126 remove unnecessary args to parseOHLCV so the sig is the same as other parsing methods
  js/_1btcxe.js
  js/acx.js
  js/aofex.js
  js/base/Exchange.js
  js/bibox.js
  js/bigone.js
  js/binance.js
  js/bitbank.js
  js/bitbay.js
  js/bitfinex.js
  js/bitforex.js
  js/bitmart.js
  js/bitmax.js
  js/bitmex.js
  js/bittrex.js
  js/bitvavo.js
  js/bitz.js
  js/bleutrade.js
  js/btcalpha.js
  js/btcmarkets.js
  js/btcturk.js
  js/bw.js
  js/bybit.js
  js/bytetrade.js
  js/cex.js
  js/coinbasepro.js
  js/coinex.js
  js/coss.js
  js/crex24.js
  js/currencycom.js
  js/digifinex.js
  js/dsx.js
  js/eterbase.js
  js/exmo.js
  js/fcoin.js
  js/ftx.js
  js/gateio.js
  js/hbtc.js
  js/hitbtc.js
  js/huobipro.js
  js/kraken.js
  js/kucoin.js
  js/lbank.js
  js/mercado.js
  js/okex.js
  js/poloniex.js
  js/probit.js
  js/qtrade.js
  js/rightbtc.js
  js/stex.js
  js/theocean.js
  js/tidebit.js
  js/timex.js
  js/upbit.js
  js/wavesexchange.js
  js/whitebit.js
  js/xbtce.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#7125 remove web3 checks when not neccessary
  js/base/Exchange.js
  js/wavesexchange.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#7134 Poloniex parseTrade fee fix
  js/poloniex.js
Labels: enhancement

#6389 New exchange phemex
  js/phemex.js
Labels: new exchange

#7166 waves fix fetchBalance
  js/wavesexchange.js
Labels: bug, enhancement

#7174 [coinbasepro] error mappings
  js/coinbasepro.js
Labels: enhancement

#7184 Huobi Japan
  js/huobijp.js
Labels: new exchange
