Repository ccxt/ccxt, pull requests merged in 2020-05, with the labels that each got.

#6803 New Exchange: HBTC
  js/hbtc.js
Labels: new exchange

#5608 Add ProBit exchange
  js/probit.js
Labels: new exchange

#6937 gemini avoid making wrong symbols
  js/gemini.js
  python/tox.ini
Labels: bug

#5904 New Exchange: Eterbase
  js/base/Exchange.js
  js/base/functions/time.js
  js/eterbase.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: new exchange

#6936 feat: test markets for taker and maker fees & some small docker fixes
  .dockerignore
  Dockerfile
  js/test/Exchange/test.market.js
  wiki/Manual.md
Labels: enhancement

#6949 [dsx] parseTransaction v3 api fix
  js/dsx.js
Labels: enhancement

#6950 Lykke new endpoints, timeframes
  js/lykke.js
Labels: enhancement

#6187 Exchange qTrade.io
  js/qtrade.js
Labels: new exchange

#6971 fix to_wei
  js/test/base/functions/test.number.js
  python/ccxt/base/exchange.py
Labels: bug

#6963 Bithumb: limits and precision
  js/bithumb.js
Labels: enhancement

#6689 [dsx] new implementation
  js/dsx.js
Labels: enhancement

#6997 [gateio] added fetch currencies
  js/gateio.js
Labels: enhancement

#7005 ccxt.d.ts: add parseTimeframe().
  ccxt.d.ts
Labels: enhancement

#7008 binance future fetchOpenOrders type bug fix (futures should be future)
  js/binance.js
Labels: bug

#7017 qTrade parseOHLCV fix
  js/qtrade.js
Labels: bug

#7026 Update luno.js with new supported API calls
  js/luno.js
Labels: enhancement
