Repository ccxt/ccxt, pull requests merged in 2020-04, with the labels that each got.

#6756 [bluetrade] added api call
  js/bleutrade.js
Labels: enhancement

#6767 kucoin add new endpoints
  js/kucoin.js
Labels: enhancement

#6768 aofex add fetchOrderTrades
  js/aofex.js
Labels: enhancement

#6776 [cex] improved return value for create order
  js/cex.js
Labels: enhancement

#6788 to_wei more precision
  js/test/base/functions/test.number.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#6780 transpile imported errors in python's init.py
  build/export-exchanges.js
  python/ccxt/__init__.py
  python/ccxt/async_support/__init__.py
Labels: enhancement

#6801 added missing curly brace
  examples/py/async-basic.py
Labels: bug

#6810 [kraken] fix: change from webpage to zendesk api to fetch minOrderAmounts
  js/kraken.js
Labels: bug, enhancement

#6816 transpile Object.values
  build/transpile.js
Labels: enhancement

#6824 Add Poloniex Maintenance Error
  js/poloniex.js
Labels: enhancement

#6804 [kraken] added fetchOrderTrades
  appveyor.yml
  examples/js/kraken-fetch-order-trades.js
  js/kraken.js
Labels: enhancement

#6837 Bithumb createOrder return structure
  js/bithumb.js
Labels: enhancement

#6840 [okex] add testnet support
  js/okex.js
Labels: enhancement

#6842 Bithumb fetchOrder, fetchOpenOrders
  js/bithumb.js
Labels: enhancement

#6843 Implement cancelUnifiedOrder and fetchUnifiedOrder
  js/base/Exchange.js
  js/bithumb.js
  php/base/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement
