Repository ccxt/ccxt, pull requests merged in 2021-11, with the labels that each got.

#10403 fix #10402
  js/binance.js
  php/Exchange.php
Labels: bug

#10410 bitmart safeOrder2
  js/bitmart.js
Labels: enhancement

#10409 bitmart safeOrder2
  js/bitmart.js
Labels: enhancement

#10411 bibox-safeOrder2
  js/bibox.js
Labels: enhancement

#10412 bigone safeOrder2
  js/bigone.js
Labels: enhancement

#10413 bit2c safeOrder2
  js/bit2c.js
Labels: enhancement

#10419 Fixes two breaking errors in coinbasepro fetchLedgerEntry method
  js/coinbasepro.js
Labels: bug

#10417 bitget safeOrder2
  js/bitget.js
Labels: enhancement

#10420 gateio EGG -> Goose Finance
  js/gateio.js
Labels: enhancement

#10421 crex24 EGG -> NestEGG Coin
  js/crex24.js
Labels: enhancement

#10422 wavesexchange EGG -> Waves Ducks
  js/wavesexchange.js
Labels: enhancement

#10423 currencycom coins mapping
  js/currencycom.js
Labels: enhancement

#10424 yobit EGG -> EggCoin
  js/yobit.js
Labels: enhancement

#10425 btcmarkets safeOrder2
  js/btcmarkets.js
Labels: enhancement

#10407 Gate.io fetchOHLCV fixes
  js/gateio.js
Labels: enhancement

#10405 okex implement setLeverage setMarginMode setPositionMode
  js/binance.js
  js/okex.js
Labels: enhancement

#10314 Added setLeverage method to gateio
  js/gateio.js
Labels: enhancement

#10435 btctradeua safeOrder2
  js/btctradeua.js
Labels: enhancement

#10438 buda safeOrder2
  js/buda.js
Labels: enhancement

#10385 Added fetchFundingHistory to okex
  js/okex.js
Labels: enhancement

#10446 optimize php precise
  appveyor.yml
  php/Precise.php
Labels: enhancement

#10447 coinfalcon safeOrder2
  js/coinfalcon.js
Labels: enhancement

#10449 coinone safeOrder2
  js/coinone.js
Labels: enhancement

#7743 added latoken v2
  js/latoken2.js
  keys.json
Labels: new exchange

#10451 digifinex safeOrder2
  js/digifinex.js
Labels: enhancement

#10450 delta safeOrder2
  js/delta.js
Labels: enhancement

#10448 coinmate safeOrder2
  js/coinmate.js
Labels: enhancement

#10455 huobi safeOrder2
  js/huobi.js
Labels: enhancement

#10454 hollaex safeOrder2
  js/hollaex.js
Labels: enhancement

#10351 Support for zip responses
  js/base/Exchange.js
Labels: enhancement

#10452 eqonex safeOrder2
  js/eqonex.js
Labels: enhancement

#10364 Gateio futures order methods
  js/gateio.js
Labels: enhancement

#10434 kucoin fetchMarkets, fetchTickers enhancement
  js/kucoin.js
Labels: enhancement

#10463 independentreserve safeOrder2
  js/independentreserve.js
Labels: enhancement

#10464 indodax safeOrder2
  js/indodax.js
Labels: enhancement

#10462 gateio edits
  js/gateio.js
Labels: enhancement, help wanted

#10474 probit rate limits
  js/probit.js
Labels: enhancement

#10490 tidex safeOrder2
  js/tidex.js
Labels: enhancement

#10465 itbit safeOrder2
  js/itbit.js
Labels: enhancement

#10467 lbank safeOrder2
  js/lbank.js
Labels: enhancement

#10468 luno safeOrder2
  js/luno.js
Labels: enhancement

#10500 zb safeOrder
  js/zb.js
Labels: enhancement

#10499 yobit safeOrder2
  js/yobit.js
Labels: enhancement

#10470 novadax safeOrder2
  js/novadax.js
Labels: enhancement

#10491 vcc safeOrder2
  js/vcc.js
Labels: enhancement

#10492 fix for gateio.fetchFundingRateHistory
  js/gateio.js
Labels: enhancement

#10493 Added fetchFundingHistory to okex
  js/okex.js
Labels: enhancement

#10507 tidebit safeOrder2
  js/tidebit.js
Labels: enhancement

#10506 probit safeOrder2
  js/probit.js
Labels: enhancement

#10564 update phemex symbols to be compliant with new naming scheme
  js/phemex.js
Labels: enhancement

#10567 save ftxus-alias-clone
  js/ftxus.js
Labels: enhancement

#10534 Gemini fetchDepositAddressesByNetwork
  js/base/Exchange.js
  js/gemini.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#10572 python 3.10 asyncio.run native support
  build/transpile.js
  python/ccxt/async_support/base/exchange.py
  python/ccxt/async_support/base/throttler.py
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  wiki/Install.md
  wiki/Manual.md
Labels: enhancement

#10607 bitmart safeTrade
  js/bitmart.js
Labels: enhancement

#10594 bitbns safeTrade
  js/bitbns.js
Labels: enhancement

#10603 bitforex safeTrade
  js/bitforex.js
Labels: enhancement

#10583 aofex safeTrade
  js/aofex.js
Labels: enhancement

#10587 bigone safeTrade
  js/bigone.js
Labels: enhancement

#10584 ascendex safeTrade
  js/ascendex.js
Labels: enhancement

#10604 bitget safeTrade
  js/bitget.js
Labels: enhancement

#10595 bitfinex safeTrade
  js/bitfinex.js
Labels: enhancement

#10606 bithumb safeTrade
  js/bithumb.js
Labels: enhancement

#10624 binance coinm fix #10623
  js/binance.js
Labels: bug

#10609 bitbay safeTrade
  js/bitbay.js
Labels: enhancement

#10626 FTX: added PnL endpoint
  js/ftx.js
Labels: enhancement

#10631 kucoin error mapping
  js/kucoin.js
Labels: enhancement

#10635 binance add support for unified postOnly flag
  js/binance.js
Labels: enhancement

#10638 Fix gateio fetch_ticker for linear/delivery type
  js/gateio.js
  python/ccxt/gateio.py
Labels: bug

#10489 Gateio stoploss
  js/gateio.js
Labels: enhancement

#10651 bitfinex1 postOnly
  js/bitfinex.js
Labels: enhancement

#10652 bitfinex2 postOnly
  js/bitfinex2.js
Labels: enhancement

#10653 coinbasepro postOnly
  js/coinbasepro.js
Labels: enhancement

#10657 latoken fetchTrades fix
  js/latoken.js
Labels: bug

#10374 Updated margin paths in gateio
  js/gateio.js
Labels: enhancement

#10688 huobi min price fix
  js/huobi.js
Labels: bug

#10696 add safeTrade bitso
  js/bitso.js
Labels: enhancement

#10701 binance average calculation fix
  js/binance.js
Labels: bug

#10698 Kraken: Use cost from response instead of calculating it
  js/kraken.js
Labels: enhancement

#10709 Btcalpha safe trade
  js/btcalpha.js
Labels: enhancement

#10708 Bittrex safe trade
  js/bittrex.js
Labels: enhancement

#10630 Bitbns safe trade fetchtrades support fix
  js/bitbns.js
Labels: enhancement

#10742 fix: update fetchTickers for Gate.io to prevent python KeyError
  js/gateio.js
Labels: bug

#10744 kraken max amount
  js/kraken.js
Labels: bug

#10745 bw add safeTrade
  js/bw.js
Labels: enhancement

#10735 more links to docs.ccxt.com
  doc/conf.py
  wiki/FAQ.md
  wiki/Install.md
  wiki/Manual.md
  wiki/ccxt.pro.manual.md
Labels: enhancement
