Repository ccxt/ccxt, pull requests merged in 2021-07, with the labels that each got.

#9501 independentreserve update exchange endpoints - add limits to fetchMarkets()
  js/independentreserve.js
Labels: enhancement

#9538 bibox fetchMarkets with right precisions
  js/bibox.js
Labels: enhancement

#9542 bitmart parseTransaction typo fix
  js/bitmart.js
Labels: bug

#9563 okex5-balance-edit
  js/okex5.js
Labels: bug

#9573 Okex v5: No need to parse lastTradeTs
  js/okex5.js
Labels: bug

#9586 implement gateiov4
  js/gateio4.js
Labels: new exchange

#9599 gateio4 bugfix
  js/gateio4.js
Labels: bug

#9587 implement binance unified endpoint fetchSavings
  js/binance.js
Labels: enhancement

#9632 binance number as string fixes and additions
  js/binance.js
Labels: enhancement

#9684 gateio fetchMyTrades limit
  js/gateio.js
Labels: enhancement

#9673 parseNumber to fees
  js/aax.js
  js/ascendex.js
  js/bibox.js
  js/bigone.js
  js/binance.js
  js/bit2c.js
  js/bitbay.js
  js/bitbns.js
  js/bitcoincom.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitflyer.js
  js/bitforex.js
  js/bitget.js
  js/bithumb.js
  js/bitmart.js
  js/bitpanda.js
  js/bittrex.js
  js/bitvavo.js
  js/bitz.js
  js/btcalpha.js
  js/btcturk.js
  js/bw.js
  js/coincheck.js
  js/currencycom.js
  js/digifinex.js
  js/exmo.js
  js/exx.js
  js/latoken.js
  js/lbank.js
  js/novadax.js
  js/paymium.js
  js/poloniex.js
  js/probit.js
  js/stex.js
  js/tidebit.js
  js/tidex.js
  js/upbit.js
  js/whitebit.js
Labels: enhancement

#9687 liquid fetchCurrencies name
  js/liquid.js
Labels: enhancement

#9671 remove hardcoded fees
  js/bigone.js
  js/bitbay.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitforex.js
  js/bitstamp.js
  js/bitz.js
  js/btcalpha.js
  js/exx.js
  js/lbank.js
  js/therock.js
  js/zb.js
Labels: enhancement

#9695 add costs to synchronous python throttler
  python/ccxt/base/exchange.py
Labels: enhancement

#9696 add costs to synchronous php throttler
  php/Exchange.php
Labels: enhancement

#9700 bitmart add fetchFundingFee
  js/bitmart.js
Labels: enhancement

#9701 crex24 new endpoints, add fetchFundingFees
  js/crex24.js
Labels: enhancement

#9714 simplify precise edits #9712
  js/base/Precise.js
  php/Precise.php
  python/ccxt/base/precise.py
Labels: enhancement
