Repository ccxt/ccxt, pull requests merged in 2021-02, with the labels that each got.

#7079 PHP async support
  README.md
  build/git-ignore-generated-files.js
  build/transpile.js
  build/vss.js
  ccxt.php
  composer.json
  examples/php/binance-fetch-ticker-async.php
  examples/php/coinbasepro-sandbox-fetch-ticker-async.php
  examples/php/load-all-at-once-async.php
  php/async/base/Exchange.php
  wiki/Install.md
  wiki/Manual.md
Labels: enhancement

#7997 Add new exchange AAX
  js/aax.js
Labels: new exchange

#8393 binance fetch deposit address
  js/binance.js
Labels: enhancement

#8394 ftx parseTransactions internal transfer
  js/ftx.js
Labels: enhancement

#8395 [bitbank] Support new pair & bug fix
  js/bitbank.js
Labels: bug, enhancement

#8405 IDEX support BSC
  js/idex.js
Labels: enhancement

#8432 Phemex - new private API end point
  js/phemex.js
Labels: enhancement

#8425 createOrder better signature
  js/base/Exchange.js
  python/ccxt/base/exchange.py
Labels: enhancement

#8417 [binance] fix makerOrTaker in parseTrade
  js/binance.js
Labels: enhancement

#8459 Add REST response intercept
  js/base/Exchange.js
  php/async/base/Exchange.php
  php/base/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#8472 export python tests for ccxtpro
  CONTRIBUTING.md
  build/git-ignore-generated-files.js
  build/transpile.js
  php/test/test_sync.php
  python/ccxt/__init__.py
  python/test/__init__.py
  python/test/test_sync.py
  run-tests.js
Labels: enhancement

#8418 [binance] fetch currencies
  js/binance.js
Labels: enhancement

#6967 Add equos exchange
  js/equos.js
Labels: new exchange

#8528 php base class methods
  build/transpile.js
  php/base/Exchange.php
Labels: enhancement

#8530 zb fetchClosedOrders
  js/zb.js
Labels: enhancement
