Repository ccxt/ccxt, pull requests merged in 2021-12, with the labels that each got.

#10629 fetchBorrowRate, fetchBorrowRates
  examples/js/exchange-capabilities.js
  examples/js/library-capabilities.js
  js/base/Exchange.js
  js/bibox.js
  js/binance.js
  js/bitstamp.js
  js/bittrex.js
  js/bybit.js
  js/coinbase.js
  js/ftx.js
  js/gateio.js
  js/hitbtc.js
  js/kraken.js
  js/kucoin.js
  js/okex.js
  js/phemex.js
  js/test/Exchange/test.borrowRate.js
  js/test/Exchange/test.fetchBorrowRate.js
  js/test/Exchange/test.fetchBorrowRates.js
  js/test/test.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#10676 Huobi fetchBorrowRates
  js/huobi.js
Labels: enhancement

#10718 added trigger check to gateio stop order
  js/gateio.js
Labels: bug

#10383 Added fetchPositions to gateio
  js/gateio.js
Labels: enhancement

#10753 coinex add cancelAllOrders fix #10738
  js/coinex.js
Labels: enhancement

#10806 Huobi fetch funding rate
  js/huobi.js
Labels: enhancement

#10830 bitrue fetchStatus
  js/bitrue.js
Labels: enhancement

#10831 Huobi funding rate
  js/huobi.js
Labels: enhancement

#10805 Added method get_type to exchange
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#10771 coinex add margin account support to fetchBalance
  js/coinex.js
Labels: enhancement

#10829 Exchange base classes updates for FetchCurrencies = emulated & better capability outputs
  examples/js/exchange-capabilities-csv.js
  examples/js/exchange-capabilities.js
  examples/js/library-capabilities.js
  js/aofex.js
  js/base/Exchange.js
  js/cdax.js
  js/coinone.js
  js/huobijp.js
  js/indodax.js
  js/oceanex.js
  js/test/Exchange/test.fetchCurrencies.js
  php/Exchange.php
  php/async/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#10849 Mexc fetchFundingRateHistory
  js/mexc.js
Labels: enhancement

#10913 Exmo safeTrade
  js/exmo.js
Labels: enhancement

#10897 WIP: mexc fetchTickers fix #10837
  js/mexc.js
Labels: enhancement

#10912 Sandbox Mode for okex
  js/okex.js
Labels: enhancement

#10919 Parse position `entryPrice` for FTX
  js/ftx.js
Labels: enhancement

#10925 binance fetchOrderTrades for spot markets
  js/binance.js
Labels: enhancement

#10930 Deribit rateLimit, safeTrade, and safeOrder2
  js/deribit.js
Labels: enhancement

#10704 binance.fetchBorrowRateHistory
  js/binance.js
  js/bittrex.js
  js/ftx.js
  js/gateio.js
  js/kraken.js
Labels: enhancement

#10918 Phemex - editOrder implementation
  js/phemex.js
Labels: enhancement

#10936 updated hitbtc fetchMarkets for unified symbols
  js/hitbtc3.js
Labels: enhancement

#10916 Deribit fetchMarkets redo with new symbols
  js/deribit.js
Labels: enhancement

#10941 Mexc fetchMarkets unified structure
  js/mexc.js
Labels: enhancement

#10893 Feature: Whitebit private API integration
  js/whitebit.js
Labels: enhancement

#10950 ftx: add fetchOrderTrades
  js/ftx.js
Labels: enhancement

#10952 aax fetchMarkets contracts
  js/aax.js
Labels: enhancement

#10954 poloniex safeOrder2
  js/poloniex.js
Labels: enhancement

#10967 Huobi withdraw address
  js/base/Exchange.js
  js/huobi.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#10965 Ascendex fetchFundingRate()
  js/ascendex.js
Labels: enhancement

#10981 CLI :: Feature :: Allow authentication using environment variables
  examples/js/cli.js
  examples/php/cli.php
  examples/py/cli.py
Labels: enhancement

#10992 wavesexchange.fetchMarkets matches unified structure, added response output
  js/wavesexchange.js
Labels: enhancement

#10988 currencycom safeOrder2
  js/currencycom.js
Labels: enhancement

#10991 Idex.fetchMarkets matches unified structure
  js/idex.js
Labels: enhancement

#10993 zb.fetchMarkets unified structure
  js/zb.js
Labels: enhancement

#10964 Whitebit private API: Error handling and minor fixes
  js/whitebit.js
Labels: enhancement

#10958 Bitvavo.fetchMarkets properties match unified structure
  js/bitvavo.js
Labels: enhancement

#10998 timex safeOrder2
  js/timex.js
Labels: enhancement

#11002 Binance: added rebate/taxQuery endpoint
  js/binance.js
Labels: enhancement

#11003 Idex fix createOrder
  js/idex.js
Labels: enhancement

#10956 Bistamp safeOrder2
  js/base/Exchange.js
  js/base/functions/generic.js
  js/bitstamp.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#10995 Ascendex fetchClosedOrders() Swap Functionality
  js/ascendex.js
Labels: enhancement

#10980 Move balance parse logic into parseBalance
  js/binance.js
Labels: enhancement

#11009 remove safeBalance legacy flag
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#11013 ascendex parse network
  js/ascendex.js
Labels: enhancement

#10994 Ascendex fetchOpenOrders() added functionality for swaps
  js/ascendex.js
Labels: enhancement

#11014 poloniex safeOrder2-2
  js/poloniex.js
Labels: enhancement

#10997 Ascendex cancelAllOrders() Swap Functionality
  js/ascendex.js
Labels: enhancement

#11012 bitmart network parsing
  js/bitmart.js
Labels: enhancement

#11016 remove safeOrder v1
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#11022 Whitebit :: FetchClosedOrders fix
  js/whitebit.js
Labels: enhancement

#11019 gateio fetchOHLCV since edits
  js/gateio.js
Labels: enhancement

#10996 Ascendex fetchOrder() Swap Functionality
  js/ascendex.js
Labels: enhancement

#10999 Ascendex cancelOrder() Swap Functionality
  js/ascendex.js
Labels: enhancement

#11024 ftx safeNetwork
  js/ftx.js
Labels: enhancement

#11006 Feature :: Whitebit new public API
  js/whitebit.js
Labels: enhancement

#11035 Waves.Exchange - Added fetchOrder ( & fetchClosedOrder & fetchOpenOrder )
  js/wavesexchange.js
Labels: enhancement

#10605 Kucoinfutures
  js/kucoin.js
  js/kucoinfutures.js
  keys.json
Labels: enhancement, new exchange

#11037 Phemex :: Add example and small fix
  examples/py/phemex-open-cancel-close-positions.py
  js/phemex.js
Labels: bug, enhancement

#10126 New exchange blockchaincom
  js/blockchaincom.js
Labels: new exchange

#11050 Phemex :: add setLeverage and example
  examples/py/phemex-leverage-orders.py
  js/phemex.js
Labels: enhancement

#11046 Phemex :: TakeProfit and StopLoss support when creating orders
  examples/py/phemex-open-cancel-close-positions.py
  js/phemex.js
Labels: enhancement

#11073 Ascendex createOrder() Perpetual Swaps
  js/ascendex.js
Labels: enhancement

#11076 bytetrade remove toWei
  examples/js/create-order-with-retry.js
  js/bytetrade.js
Labels: enhancement

#11077 huobi postOnly limit-maker
  js/huobi.js
Labels: enhancement

#11068 Added error codes
  js/binance.js
Labels: enhancement

#11011 implement cryptocom
  js/cryptocom.js
Labels: new exchange

#11086 Added gateio options endpoints
  js/gateio.js
Labels: enhancement

#11090 Add fetchAssetValuation for okex
  js/okex.js
Labels: enhancement

#11088 Hitbtc3 fetchFundingRateHistory
  js/hitbtc3.js
Labels: enhancement
