Repository ccxt/ccxt, pull requests merged in 2022-03, with the labels that each got.

#12144 Mexc: contracts error: AccountNotEnabled
  js/mexc.js
Labels: enhancement

#12158 Fix wrong order ID parsing in gate.io
  js/gateio.js
Labels: bug

#12153 Bitmart - fetchTradingFees
  js/bitmart.js
Labels: enhancement

#12150 blockchaincom: update rate limits
  js/blockchaincom.js
Labels: enhancement

#12152 Bitbank - fetchTradingFees
  js/bitbank.js
Labels: enhancement

#12159 idex - fetchTradingFees
  js/idex.js
Labels: enhancement

#12149 blockchaincom: unify 'stopPrice'
  js/blockchaincom.js
Labels: enhancement

#12161 ZB cancelOrder
  js/zb.js
Labels: enhancement

#12154 bitvavo - fetchTradingFees
  js/bitvavo.js
Labels: enhancement

#12160 gemini - fetchTradingFees
  js/gemini.js
Labels: enhancement

#12171 run-tests for individual languages
  package.json
Labels: enhancement

#12170 bitget - fetchTradingFees
  js/bitget.js
Labels: enhancement

#12169 coinspot - fetchTradingFee
  js/coinspot.js
Labels: enhancement

#12176 Php Exchange :: Add sleep method
  php/Exchange.php
  php/async/Exchange.php
Labels: enhancement

#12184 bitbns - fetchTradingFee
  js/bitbns.js
Labels: enhancement

#12183 bybit - fetchTradingFees
  js/bybit.js
Labels: enhancement

#12182 bigone - fetchTradingFees
  js/bigone.js
Labels: enhancement

#12181 coinex - fetchTradingFees
  js/coinex.js
Labels: enhancement

#12179 coincheck - fetchTradingFees
  js/coincheck.js
Labels: enhancement

#12185 bytetrade - fetchTradingFees
  js/bytetrade.js
Labels: enhancement

#12190 Bitmex :: fetchTickers and sign fixes
  js/bitmex.js
Labels: bug

#12177 Okcoin: add safeTrade
  js/okcoin.js
Labels: enhancement

#12172 ZB fetchOHLCV
  js/zb.js
Labels: enhancement

#12191 zonda - fetchTradingFees
  js/zonda.js
Labels: enhancement

#12192 zaif - fetchTradingFees
  js/zaif.js
Labels: enhancement

#12194 Yobit - fetchTradingFees
  js/yobit.js
Labels: enhancement

#12195 xena - fetchTradingFees
  js/xena.js
Labels: enhancement

#12196 Woo - fetchTradingFees
  js/woo.js
Labels: enhancement

#12197 ZB fetchMarkOHLCV, fetchIndexOHLCV
  js/zb.js
Labels: enhancement

#12145 ZB fetchLedger
  js/zb.js
Labels: enhancement

#12198 ZB 'has'
  js/zb.js
Labels: enhancement

#12033 currencycom - order related
  js/currencycom.js
Labels: enhancement

#12203 `$this->$id` in fetch_ohlcv
  php/Exchange.php
  php/async/Exchange.php
Labels: bug

#12147 `resolvePath` in base
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#12213 stex - fetchTradingFee
  js/stex.js
Labels: enhancement

#12221 ZB fetchBorrowRate
  js/zb.js
Labels: enhancement

#12218 mercado - fetchTradingFee
  js/mercado.js
Labels: enhancement

#12230 aax: patch fetchFundingRateHistory
  js/aax.js
Labels: enhancement

#12232 binance: patch fetchFundingRateHistory
  js/binance.js
Labels: enhancement

#12231 ascendex: patch filterBySymbolSinceLimit
  js/ascendex.js
Labels: enhancement

#12233 bittrex: patch fetchMyTrades
  js/bittrex.js
Labels: enhancement

#12236 hitbtc3: patch fetchFundingRateHistory
  js/hitbtc3.js
Labels: enhancement

#12235 gateio: patch filterBySymbolSinceLimit
  js/gateio.js
Labels: enhancement

#12244 yobit: patch fetchMyTrades
  js/yobit.js
Labels: enhancement

#12243 whitebit: patch fetchClosedOrders
  js/whitebit.js
Labels: enhancement

#12242 okx: patch filterBySymbolSinceLimit
  js/okx.js
Labels: enhancement

#12241 mexc: patch fetchFundingRateHistory
  js/mexc.js
Labels: enhancement

#12240 mercado: patch fetchMyTrades
  js/mercado.js
Labels: enhancement

#12239 indodax: patch fetchClosedOrders
  js/indodax.js
Labels: enhancement

#12238 huobijp: patch fetchTrades
  js/huobijp.js
Labels: enhancement

#12237 huobi: patch filterBySymbolSinceLimit
  js/huobi.js
Labels: enhancement

#12234 cdax: patch fetchTrades
  js/cdax.js
Labels: enhancement

#12245 zb: patch fetchFundingRateHistory
  js/zb.js
Labels: enhancement

#12246 exmo: patch fetchOpenOrders
  js/exmo.js
Labels: enhancement

#12260 gateio.stoploss rule fix
  js/gateio.js
Labels: bug

#12249 ZB fetchBalance
  js/zb.js
Labels: enhancement

#12216 therock - fetchTradingFees
  js/therock.js
Labels: enhancement

#12263 Revert "gateio.stoploss rule fix"
  js/gateio.js
Labels: bug

#12247 lbank: patch fetchClosedOrders
  js/lbank.js
Labels: enhancement

#12251 ZB transfer
  js/zb.js
Labels: enhancement

#12075 binance - deprecate safeFloat2
  js/binance.js
Labels: enhancement, todo

#12270 btctradeua - fetchTradingFees
  js/btctradeua.js
Labels: enhancement

#12271 buda - fetchTradingFee
  js/buda.js
Labels: enhancement

#12269 bl3p - fetchTradingFees
  js/bl3p.js
Labels: enhancement

#12268 gateio.fetchPosition num contracts absolute value
  js/gateio.js
Labels: enhancement

#12277 Phemex :: stop-orders example
  examples/py/phemex-create-stop-order.py
Labels: enhancement

#12272 bw - fetchTradingFees
  js/bw.js
Labels: enhancement

#12273 coinfalcon - fetchTradingFees
  js/coinfalcon.js
Labels: enhancement

#12280 okx: fix return by network
  js/okx.js
Labels: bug

#12285 added `react/http` in instructions
  wiki/Manual.md
Labels: enhancement

#12292 hitbtc - fetchTradingFee
  js/hitbtc.js
Labels: enhancement

#12294 hollaex - fetchTradingFees
  js/hollaex.js
Labels: enhancement

#12298 kucoin - fetchTradingFees
  js/kucoin.js
Labels: enhancement

#12297 itbit - fetchTradingFees
  js/itbit.js
Labels: enhancement

#12296 indodax - fetchTradingFees
  js/indodax.js
Labels: enhancement

#12293 gateio fetchFundingHistory fixes
  js/gateio.js
Labels: enhancement

#12288 coinbasepro - fetchTradingFees
  js/coinbasepro.js
Labels: enhancement

#12286 bitflyer - fetchTradingFee
  js/bitflyer.js
Labels: enhancement

#12300 gateio.transfer unified response
  js/gateio.js
Labels: enhancement

#12299 unify accountType names "funding", "spot", "margin", and "future"
  js/bitfinex2.js
  js/cryptocom.js
  js/gateio.js
  js/hitbtc3.js
  js/huobi.js
  js/okx.js
Labels: enhancement

#12283 Gateio :: fetchMarkets refactor
  js/gateio.js
Labels: enhancement

#12295 independent reserve - fetchTradingFees
  js/independentreserve.js
Labels: enhancement

#12224 okcoin: update ratelimits
  js/okcoin.js
Labels: enhancement

#12305 latoken - fetchTradingFees
  js/latoken.js
Labels: enhancement

#12307 added `react/http` in composer
  composer.json
Labels: enhancement

#12308 Bitflyer: fix futures market parsing without alias
  js/bitflyer.js
Labels: bug

#12306 Base - flag for ssl validation
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#12291 exmo - fetchTradingFees
  js/exmo.js
Labels: enhancement

#12314 gateio.fetchMarkets php fix
  js/gateio.js
Labels: bug

#12313 fetch_leverage_tiers fix (python)
  python/ccxt/base/exchange.py
Labels: bug

#12312 Bybit fetchFundingRate: fundingTimestamp
  js/bybit.js
Labels: enhancement

#12315 Test.bash
  examples/js/cli.js
  examples/py/cli.py
  multilang.sh
Labels: enhancement

#12322 Gateio :: fix fetchMarkets
  js/gateio.js
Labels: bug

#12139 New exchange - bkex
  examples/php/cli.php
  js/base/Exchange.js
  js/bkex.js
  multilang.sh
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: new exchange

#8207 Bkex v2 integration
  js/bkex.js
Labels: new exchange

#12329 gateio cancelOrder stop order matches fetchOrder
  js/gateio.js
Labels: enhancement

#12330 phemex: migrate to new trading / convert apis
  js/phemex.js
Labels: enhancement

#12319 Fix gateio parse-order
  js/gateio.js
Labels: bug

#12335 ndax - fetchTradingFees
  js/ndax.js
Labels: enhancement

#12338 bkex - fetchTradingFees
  js/bkex.js
Labels: enhancement

#11952 bitopro: add bitopro exchange
  js/bitopro.js
Labels: new exchange

#12344 gemini: fix no-body POST requests
  js/gemini.js
Labels: bug

#12346 Gate.io: fix private urls
  js/gateio.js
Labels: bug

#12351 lykke price bug fix
  js/lykke.js
Labels: bug

#12350 probit TOR -> Torex
  js/probit.js
Labels: enhancement

#12353 Kucoin balance
  js/kucoinfutures.js
Labels: bug

#12349 latoken error mapping
  js/latoken.js
Labels: enhancement

#12348 bibox remove GTC mapping
  js/bibox.js
Labels: enhancement

#12354 Gateio.setLeverage cross leverage
  js/gateio.js
Labels: bug

#12358 Okx :: fix ticker volume / add safeTicker volume calculation
  js/base/Exchange.js
  js/okx.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#12359 cex error mapping
  js/cex.js
Labels: enhancement

#12333 crex24 - fetchTradingFees
  js/crex24.js
Labels: enhancement

#12361 yobit GMR -> Gimmer
  js/yobit.js
Labels: enhancement

#12316 Okx createOrder: unify 'stopPrice'
  js/okx.js
Labels: enhancement

#12365 Hitbtc3 fetchTradingFee
  js/hitbtc3.js
Labels: enhancement

#12364 Hitbtc3 fetchTradingFees
  js/hitbtc3.js
Labels: enhancement

#12373 mexc- remove `fetchMarketsByType`
  js/mexc.js
Labels: bug

#12387 probit - fetchTradingFee
  js/probit.js
Labels: enhancement

#12386 kuna - fetchTradingFees
  js/kuna.js
Labels: enhancement

#12385 qtrade - fetchTradingFees
  js/qtrade.js
Labels: enhancement

#12389 Hitbtc3 cancelAllOrders
  js/hitbtc3.js
Labels: enhancement

#12388 Hitbtc3 cancelOrder
  js/hitbtc3.js
Labels: enhancement

#12384 lbank - fetchTradingFees
  js/lbank.js
Labels: enhancement

#12383 zb - fetchTradingFees
  js/zb.js
Labels: enhancement

#12371 Hitbtc3 fetchMyTrades
  js/hitbtc3.js
Labels: bug, enhancement

#12370 Hitbtc3 fetchOrderTrades
  js/hitbtc3.js
Labels: enhancement

#12368 Hitbtc3 fetchOrder
  js/hitbtc3.js
Labels: enhancement

#12369 Hitbtc3 fetchClosedOrders
  js/hitbtc3.js
Labels: enhancement

#12367 Hitbtc3 fetchOpenOrder
  js/hitbtc3.js
Labels: enhancement

#12366 Hitbtc3 fetchOpenOrders
  js/hitbtc3.js
Labels: enhancement

#12395 poloniex error mapping
  js/poloniex.js
Labels: enhancement

#12396 Bitstamp: added error for "Wrong API key format"
  js/bitstamp.js
Labels: enhancement

#12398 currencycom AMC mapping
  js/currencycom.js
Labels: enhancement

#12392 Hitbtc3 createReduceOnlyOrder
  js/hitbtc3.js
Labels: enhancement

#12397 ftx AMC mapping
  js/ftx.js
Labels: enhancement

#12401 Hitbtc3 editOrder
  js/hitbtc3.js
Labels: enhancement

#12404 mexc new endpoints
  js/mexc.js
Labels: enhancement

#12400 okx: switch all futures -> future
  js/okx.js
Labels: enhancement

#12049 currencycom - fetchMarkets
  js/currencycom.js
Labels: enhancement

#12411 currencycom - `fetchAccounts` change of `info`
  js/currencycom.js
Labels: enhancement

#12416 Poloniex: error "This account is closed"
  js/poloniex.js
Labels: enhancement

#12417 Gateio :: fix setLeverage
  js/gateio.js
Labels: bug

#12420 bitmart - fix `private` signature
  js/bitmart.js
Labels: bug

#12415 FTX: add "Get deposit address list" API endpoint
  js/ftx.js
Labels: enhancement

#12426 deribit.fetchMarkets symbol fix
  js/deribit.js
Labels: bug

#12438 hitbtc error mapping
  js/hitbtc.js
Labels: enhancement

#12439 hitbtc3 error mapping
  js/hitbtc3.js
Labels: enhancement

#12425 gateio added new api endpoints
  js/gateio.js
Labels: enhancement

#12446 bitopro - fetchTradingFee
  js/bitopro.js
Labels: enhancement

#12447 novadax - fetchTradingFees
  js/novadax.js
Labels: enhancement
