Repository ccxt/ccxt, pull requests merged in 2022-01, with the labels that each got.

#11092 cryptocom add futures api
  js/cryptocom.js
Labels: enhancement

#11106 huobi fetchPosition
  js/huobi.js
Labels: enhancement

#10875 New ftx symbols
  js/base/Exchange.js
  js/ftx.js
  js/ftxus.js
Labels: enhancement

#11125 loadTimeDifference moved to base.exchange
  build/transpile.js
  js/aax.js
  js/base/Exchange.js
  js/binance.js
  js/bitrue.js
  js/bybit.js
  js/currencycom.js
  js/huobi.js
  js/indodax.js
  js/kucoin.js
  js/kucoinfutures.js
  js/latoken.js
  js/okex.js
  php/Exchange.php
  php/async/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#11165 mexc type unification
  js/mexc.js
Labels: enhancement

#11173 Deribit parsePosition and safeTicker
  js/deribit.js
Labels: enhancement

#11152 Deribit Historical Volatility
  js/deribit.js
Labels: enhancement

#11172 Add fetchDeposits to AAX exchange
  js/aax.js
Labels: enhancement

#11180 AAX fetchwidrawals, remove duplicate line in bitget
  js/aax.js
  js/bitget.js
Labels: enhancement

#11184 aax: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/aax.js
Labels: enhancement

#11185 ascendex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/ascendex.js
Labels: enhancement

#11189 bibox: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bibox.js
Labels: enhancement

#11190 bitmart: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bitmart.js
Labels: enhancement

#11191 binance: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/binance.js
Labels: enhancement

#11192 bitpanda: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bitpanda.js
Labels: enhancement

#11198 Ftx update ratelimiter
  js/ftx.js
Labels: enhancement

#11194 bittrex: update deposit/withdraw flags ccxt/ccxt#11107
  js/bittrex.js
Labels: enhancement

#11195 bitfinex2: update deposit/withdraw flags ccxt/ccxt#11107
  js/bitfinex2.js
Labels: enhancement

#11199 bitget: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bitget.js
Labels: enhancement

#11200 bitvavo: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bitvavo.js
Labels: enhancement

#11206 bitstamp: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bitstamp.js
Labels: enhancement

#11203 cex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/cex.js
Labels: enhancement

#11204 coinbase: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/coinbase.js
Labels: enhancement

#11205 coinbasepro: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/coinbasepro.js
Labels: enhancement

#11208 cdax: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/cdax.js
Labels: enhancement

#11211 hitbtc: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/hitbtc.js
Labels: enhancement

#11213 ftx: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/ftx.js
Labels: enhancement

#11215 delta: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/delta.js
Labels: enhancement

#11209 Gate.io add safeTrade
  js/gateio.js
Labels: enhancement

#11219 Gateio handleMarketTypeAndParams
  js/gateio.js
Labels: enhancement

#11214 digifinex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/digifinex.js
Labels: enhancement

#11217 eqonex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/eqonex.js
Labels: enhancement

#11218 crex24: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/crex24.js
Labels: enhancement

#11207 bytetrade: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bytetrade.js
Labels: enhancement

#11137 Exchange :: Wazirx :: implementation
  examples/py/wazirx-create-cancel-orders.py
  js/wazirx.js
Labels: new exchange

#11212 gateio: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/gateio.js
Labels: bug, enhancement

#11230 fix[Gate.io]: transfer between wallets
  js/gateio.js
Labels: bug

#11232 gateio add handleMarketTypeAndParams
  js/gateio.js
Labels: enhancement

#11235 Btcmarkets :: Add safeTicker
  js/btcmarkets.js
Labels: enhancement

#11236 Bitflyer :: add safe ticker
  js/bitflyer.js
Labels: enhancement

#11238 Bittrex :: add safeTicker
  js/bittrex.js
Labels: enhancement

#11239 Btcbox :: add safeTicker
  js/btcbox.js
Labels: enhancement

#11243 Bw :: add safeTicker
  js/bw.js
Labels: enhancement

#11244 Bybit :: add safeTicker
  js/bybit.js
Labels: enhancement

#11245 Bytetrade :: add safeTicker
  js/bytetrade.js
Labels: enhancement

#11246 Cex :: add safeTicker
  js/cex.js
Labels: enhancement

#11240 Make tests with titles
  js/test/test.js
Labels: enhancement

#11253 Digifinex :: add safeTicker
  js/digifinex.js
Labels: enhancement

#11250 Crex24 safeTicker
  js/crex24.js
Labels: enhancement

#11257 [FTX] Change text matched in RateLimitExceeded
  js/ftx.js
Labels: enhancement

#11262 latoken1: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/latoken1.js
Labels: enhancement

#11263 latoken: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/latoken.js
Labels: enhancement

#11265 kraken: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/kraken.js
Labels: enhancement

#11269 whitebit: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/whitebit.js
Labels: enhancement

#11272 tidex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/tidex.js
Labels: enhancement

#11266 idex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/idex.js
Labels: enhancement

#11284 zb: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/zb.js
Labels: enhancement

#11267 huobijp: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/huobijp.js
Labels: enhancement

#11273 stex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/stex.js
Labels: enhancement

#11252 Kraken safeTicker
  js/kraken.js
Labels: enhancement

#11249 Coinex safeTicker
  js/coinex.js
Labels: enhancement

#11283 xena: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/xena.js
Labels: enhancement

#11281 ndax: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/ndax.js
Labels: enhancement

#11277 poloniex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/poloniex.js
Labels: enhancement

#11274 ripio: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/ripio.js
Labels: enhancement

#11320 okex errors remapping
  js/okex.js
Labels: enhancement

#11275 qtrade: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/qtrade.js
Labels: enhancement

#11258 hitbtc3: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/hitbtc3.js
Labels: enhancement

#11259 huobi: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/huobi.js
Labels: enhancement

#11261 liquid: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/liquid.js
Labels: enhancement

#11271 timex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/timex.js
Labels: enhancement

#11270 vcc: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/vcc.js
Labels: enhancement

#11286 Hollaex :: add safeTicker
  js/hollaex.js
Labels: enhancement

#11279 okex3: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/okex3.js
Labels: enhancement

#11319 Ripio :: add safeTicker
  js/ripio.js
Labels: enhancement

#11317 Phemex :: add safeTicker
  js/phemex.js
Labels: enhancement

#11316 Okex3 :: add safeTicker
  js/okex3.js
Labels: enhancement

#11315 Okex :: add safeTicker
  js/okex.js
Labels: enhancement

#11313 okex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/okex.js
Labels: enhancement

#11327 Mexc fetchTickers : handleMarketTypeAndParams
  js/mexc.js
Labels: enhancement

#11295 Oceanex :: add safeTicker
  js/oceanex.js
Labels: enhancement

#11202 bw: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/bw.js
Labels: enhancement

#11311 Idex safe trade
  js/idex.js
Labels: enhancement

#11290 Latoken1 :: add safeTicker
  js/latoken1.js
Labels: enhancement

#11329 add type hinting for variants of create_order
  python/ccxt/async_support/base/exchange.py
Labels: enhancement

#11299 Kucoin type uni
  js/kucoin.js
  js/kucoinfutures.js
Labels: enhancement

#11289 Kuna :: add safeTicker
  js/kuna.js
Labels: enhancement

#11260 hollaex: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/hollaex.js
Labels: enhancement

#11248 Buda safeTicker
  js/buda.js
Labels: enhancement

#11332 binance error mapping
  js/binance.js
Labels: enhancement

#11312 Idex safeTicker
  js/idex.js
Labels: enhancement

#11335 add missing Gate.io error
  js/gateio.js
Labels: enhancement

#11343 Binance: new bswap endpoints
  js/binance.js
Labels: enhancement

#11302 bittrex fetchMarkets unified structure
  js/bittrex.js
Labels: enhancement

#11216 exmo: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/exmo.js
Labels: enhancement

#11349 Mexc fetchTime : handleMarketTypeAndParams
  js/mexc.js
Labels: enhancement

#11288 Independentreserve :: add safeTicker
  js/independentreserve.js
Labels: enhancement

#11291 Lbank :: add safeTicker
  js/lbank.js
Labels: enhancement

#11336 mexc add safeTrade
  js/mexc.js
Labels: enhancement

#11310 Bitbns fetchMarkets unified
  js/bitbns.js
Labels: enhancement

#11350 Mexc fetchBalance : handleMarketTypeAndParams
  js/mexc.js
Labels: enhancement

#11338 Phemex fetchMarkets unified structure
  js/phemex.js
Labels: enhancement

#11294 Ndax :: add safeTicker
  js/ndax.js
Labels: enhancement

#11303 Ndax fetchMarkets unified response
  js/ndax.js
Labels: enhancement

#11339 eqonex.fetchMarkets unified structure
  js/eqonex.js
Labels: enhancement

#11256 Rename bitcoin.com to FMFW.io
  js/bitcoincom.js
  js/fmfwio.js
Labels: enhancement

#11221 Deribit fetchPositions / parsePositions
  js/deribit.js
Labels: enhancement

#11292 Luno :: add safeTicker
  js/luno.js
Labels: enhancement

#11293 Lykke :: add safeTicker
  js/lykke.js
Labels: enhancement

#11264 kucoin: add deposit/withdraw flag in currencies ccxt/ccxt#11107
  js/kucoin.js
Labels: enhancement

#11318 Poloniex :: add safeTicker
  js/poloniex.js
Labels: enhancement

#11353 safeTicker string math
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#11358 add fields bitpanda markets
  js/bitpanda.js
Labels: enhancement

#11361 zonda markets
  js/base/Exchange.js
  js/zonda.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#11362 bitrue markets
  js/bitrue.js
Labels: enhancement

#11363 bitstamp markets
  js/bitstamp.js
Labels: enhancement

#11306 Added binance vanilla options api paths
  js/binance.js
Labels: enhancement

#11364 Ascendex fetchBalance : handleMarketTypeAndParams
  js/ascendex.js
Labels: enhancement

#11300 bybit type unification
  js/bybit.js
Labels: enhancement

#11379 safeTicker strings
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#11381 digifinex.fetchMarkets unified structure
  js/digifinex.js
Labels: enhancement

#11387 bl3p has futures methods
  js/bl3p.js
Labels: enhancement

#11384 bitso.fetchMarkets unified
  js/bitso.js
Labels: enhancement

#11390 Bitget fetchBalance : handleMarketTypeAndParams
  js/bitget.js
Labels: enhancement

#11385 independentreserve.fetchMarkets unified
  js/independentreserve.js
Labels: enhancement

#11370 binance giftcard api
  js/binance.js
Labels: enhancement

#11376 ascendex safeTicker
  js/ascendex.js
Labels: enhancement

#11380 hollaex.fetchMarkets unified structure
  js/hollaex.js
Labels: enhancement

#11407 Bytetrade add safeTrade
  js/bytetrade.js
Labels: enhancement

#11388 blockchaincom.fetchMarkets unified
  js/blockchaincom.js
Labels: enhancement

#11377 aax safeTicker
  js/aax.js
Labels: enhancement

#11400 bit2c: use string in safeTicker ccxt/ccxt#11379
  js/bit2c.js
Labels: enhancement

#11401 bitbank: use string in safeTicker ccxt/ccxt#11379
  js/bitbank.js
Labels: enhancement

#11403 bitfinex: use string in safeTicker ccxt/ccxt#11379
  js/bitfinex.js
Labels: enhancement

#11404 bitfinex2: use string in safeTicker ccxt/ccxt#11379
  js/bitfinex2.js
Labels: enhancement

#11405 bitflyer: use string in safeTicker ccxt/ccxt#11379
  js/bitflyer.js
Labels: enhancement

#11410 Bybit fetchMyTrades : handleMarketTypeAndParams
  js/bybit.js
Labels: enhancement

#11371 bitfinex2 update ratelimits
  js/bitfinex2.js
Labels: enhancement

#11411 Bybit fetchOrders : handleMarketTypeAndParams
  js/bybit.js
Labels: enhancement

#11413 bitpanda has leverage methods, reorder fetchMarkets
  js/bitpanda.js
Labels: enhancement

#11414 btcalpha fetchMarkets unified and has leverage methods
  js/btcalpha.js
Labels: enhancement

#11415 btcbox.has futures methods
  js/btcbox.js
Labels: enhancement

#11368 fundingRate, previousFundingRate and nextFundingRate naming fix #11298
  js/aax.js
  js/binance.js
  js/bybit.js
  js/ftx.js
  js/gateio.js
  js/huobi.js
  js/kucoinfutures.js
  js/okex.js
Labels: enhancement

#11480 phemex error mapping
  js/phemex.js
Labels: enhancement

#11417 btcmarkets.fetchMarkets unified, has leverage methods
  js/btcmarkets.js
Labels: enhancement

#11416 exchange-capabilities, colors, windows, spot and option at front
  examples/js/exchange-capabilities.js
Labels: enhancement

#11418 btctradeua.has leverage methods
  js/btctradeua.js
Labels: enhancement

#11420 btcturk markets
  js/btcturk.js
Labels: enhancement

#11422 bitfinex markets
  js/bitfinex.js
Labels: enhancement

#11423 Bibox markets
  js/bibox.js
Labels: enhancement
