Repository ccxt/ccxt, pull requests merged in 2022-10, with the labels that each got.

#15115 python decimal_to_precision checks for decimal type in assertions
  python/ccxt/base/decimal_to_precision.py
Labels: bug, enhancement

#15159 bitmart: add api endpoints for contract (futures)
  js/bitmart.js
Labels: enhancement

#15158 bitmart: add fetchTradingFee
  js/bitmart.js
Labels: enhancement

#14930 huobi.createOrder market buy string math
  js/huobi.js
Labels: enhancement

#14895 bitmart.createOrder string math
  js/bitmart.js
Labels: enhancement

#14892 binance.createOrder market buy string math
  js/binance.js
Labels: enhancement

#15191 Missing import :: add ccxt.pro.base.exchange
  python/ccxt/pro/__init__.py
Labels: bug

#15186 gate - watchOrderBook - reset subscription on error
  js/pro/gate.js
Labels: bug

#15190 Ccxt.pro :: Fix ts declarations
  build/transpileWS.js
  ccxt.d.ts
Labels: bug, important

#15054 digifinex - fetchCurrencies
  js/digifinex.js
Labels: bug, enhancement

#15213 OKX :: fix orderbook checksum
  js/pro/okx.js
Labels: bug

#15211 bybit: use premiumIndex instead premium
  js/bybit.js
Labels: bug

#15203 binance: update sapi api endpoints
  js/binance.js
Labels: enhancement

#15217 Bitget :: add missing endpoint
  js/bitget.js
Labels: enhancement

#15228 updated ftxus fees
  js/ftxus.js
Labels: bug

#15230 Exchange :: add missing await
  js/base/Exchange.js
Labels: bug

#15237 Bybit :: fix tp sl orders
  js/bybit.js
Labels: bug

#15163 bitget - wallet endpoints
  js/bitget.js
Labels: enhancement

#15243 Bybit :: fix load markets placement
  js/bybit.js
Labels: bug

#15248 TS :: fix pro types
  build/transpileWS.js
  ccxt.d.ts
Labels: bug

#15252 mexc networks updated to working values
  js/mexc.js
Labels: bug

#15253 ndax.has["fetchTickers"] == false
  js/ndax.js
Labels: enhancement

#14966 okx.createOrder market buy string math
  js/okx.js
Labels: enhancement

#14915 bybit createSpotOrder & parseLedgerEntry string math
  js/bybit.js
Labels: enhancement

#15270 mexc["options"]["networks"] added BSC
  js/mexc.js
Labels: enhancement

#15269 mexc3 withdrawal networks update
  js/mexc3.js
Labels: bug

#15272 Huobi offset
  js/huobi.js
Labels: bug

#15263 huobi - min cost and amount
  js/huobi.js
Labels: bug

#15268 Bibox transfer
  js/bibox.js
Labels: enhancement

#15281 gate - fix wallet endpoint
  js/gate.js
Labels: bug

#15016 independentreserve.parseOrder string math
  js/independentreserve.js
Labels: enhancement

#15289 ftx: add api endpoints for Optimized Access
  js/ftx.js
Labels: enhancement

#15271 Aax currencies
  js/aax.js
Labels: bug

#15015 btcalpha.createOrder string math
  js/btcalpha.js
Labels: enhancement

#15029 lbank2 fetchBalance response comment
  js/lbank2.js
Labels: enhancement

#15295 Bitmart :: orderbook timestamp
  js/bitmart.js
Labels: bug

#15296 Mexc3 :: add missing await
  js/mexc3.js
Labels: bug

#15294 Bybit :: fix orderbook timestamp
  js/bybit.js
Labels: bug

#15302 many-exchanges-many-accounts.php linting
  examples/ccxt.pro/php/many-exchanges-many-accounts.php
Labels: bug

#15288 bybit: update amount for spot market
  js/bybit.js
Labels: bug

#15283 kucoinfutures - min max sizes
  js/kucoinfutures.js
Labels: bug

#15317 binance: add new endpoints for giftcard
  js/binance.js
Labels: enhancement

#15330 Okx: fetchPositions, enable margin and option support
  js/okx.js
Labels: enhancement

#15325 wavesexchange - error code
  js/wavesexchange.js
Labels: enhancement

#15298 gate - error handling
  js/gate.js
Labels: enhancement

#14976 phemex.createOrder market buy string math
  js/phemex.js
Labels: enhancement

#15324 Cache - new updates by symbol
  js/pro/base/Cache.js
  js/pro/test/base/test.Cache.js
  php/pro/ArrayCache.php
  php/pro/ArrayCacheBySymbolById.php
  python/ccxt/pro/base/cache.py
Labels: bug, ccxt.pro

#15344 bybit: add api for latest symbol info by basecoin
  js/bybit.js
Labels: enhancement

#15348 AAX :: fix handleBalance
  js/pro/aax.js
Labels: bug

#15341 Bibox v4 fetch ticker
  js/bibox.js
Labels: enhancement

#15363 bybit: add account type
  js/bybit.js
Labels: enhancement

#15362 bitmart: fix parseTransaction ccxt/ccxt#15307
  js/bitmart.js
Labels: bug

#15360 Bibox create order fixes
  js/bibox.js
Labels: bug

#15358 bybit - watchMyTrades and watchOrders channels
  js/pro/bybit.js
Labels: bug, ccxt.pro

#15356 bybit - set bybit keep alive
  js/pro/bybit.js
Labels: bug, ccxt.pro

#15364 Binance :: fix balance snapshot crash
  js/pro/binance.js
Labels: bug

#15372 okx: update order tag ccxt/ccxt#15367
  js/okx.js
Labels: enhancement

#15369 bibox fetchBalance v4
  js/bibox.js
Labels: enhancement

#15368 docstrings - added docstrings to watch functions
  js/pro/aax.js
  js/pro/ascendex.js
  js/pro/binance.js
  js/pro/bitfinex.js
  js/pro/bitmart.js
  js/pro/bitmex.js
  js/pro/bitopro.js
  js/pro/bitstamp.js
  js/pro/bittrex.js
  js/pro/bitvavo.js
  js/pro/bybit.js
  js/pro/coinbasepro.js
  js/pro/cryptocom.js
  js/pro/currencycom.js
  js/pro/ftx.js
  js/pro/gate.js
  js/pro/hitbtc.js
  js/pro/hollaex.js
  js/pro/huobi.js
  js/pro/huobijp.js
  js/pro/idex.js
  js/pro/kraken.js
  js/pro/kucoin.js
  js/pro/mexc.js
  js/pro/ndax.js
  js/pro/okcoin.js
  js/pro/okx.js
  js/pro/phemex.js
  js/pro/ripio.js
  js/pro/upbit.js
  js/pro/zb.js
Labels: WS

#15386 bybit added options["networks"]
  js/bybit.js
Labels: bug

#15297 gate - watchOrders for all symbols
  js/pro/gate.js
Labels: enhancement, WS

#15378 bibox transfer edit
  js/bibox.js
Labels: enhancement

#15371 okx: minor update
  js/okx.js
Labels: enhancement

#15315 binance - watchOrders - unify symbol, handleMarketTypeAndParams and doc string
  js/pro/binance.js
Labels: WS

#15000 bitfinex2 parseTransaction string math
  js/bitfinex2.js
Labels: enhancement

#15370 Bibox fetch ledger
  js/bibox.js
Labels: enhancement

#15375 ftx - conditional orders
  js/base/Exchange.js
  js/ftx.js
Labels: bug

#15285 deribit - websockets
  js/deribit.js
  js/pro/deribit.js
Labels: WS

#15401 kucoin parseDepositAddress unification
  js/kucoin.js
Labels: enhancement

#15412 mexc3: update for wallet endpoints
  js/mexc3.js
Labels: enhancement

#15419 bitget: remove testnet ccxt/ccxt#15415
  js/bitget.js
Labels: enhancement

#15408 example for fetching all deposit addresses asynchronously with fetchDepositAddress on coinex
  examples/js/coinex-fetch-all-deposit-addresses-using-fetchDepositAddress.js
Labels: enhancement

#15382 Bibox fetch cancel orders v4
  js/bibox.js
Labels: enhancement

#14853 bybit: update edit contract order
  js/bybit.js
Labels: enhancement

#15436 Push.sh :: add pro/ back to git after build
  build/push.sh
Labels: bug, critical

#15339 okx.has fetchTradingLimits: false
  js/okx.js
Labels: enhancement

#15421 bitget: add wallet subTransfer
  js/bitget.js
Labels: enhancement

#15460 bitvavo - unify symbol
  js/pro/bitvavo.js
Labels: bug, WS

#15457 bitstamp - unify symbol
  js/pro/bitstamp.js
Labels: bug, WS

#15455 bitopro - unify symbol
  js/pro/bitopro.js
Labels: bug, WS

#15454 bitmex - unify symbol
  js/pro/bitmex.js
Labels: bug, WS

#15453 bitmart - unify symbol
  js/pro/bitmart.js
Labels: bug, WS

#15451 ascendex - unify symbol
  js/pro/ascendex.js
Labels: bug, WS

#15450 aax - unify symbol
  js/pro/aax.js
Labels: bug, WS

#15485 Fix webWorker usage
  js/pro/base/WsClient.js
Labels: bug

#15480 postinstall - script update
  postinstall.js
Labels: enhancement

#15469 okx: fix ccxt/ccxt#15468
  js/okx.js
Labels: bug

#15474 kucoin: use v2 symbols
  js/kucoin.js
Labels: enhancement

#15497 Bitget :: fix timeframes
  js/bitget.js
Labels: bug

#15488 kraken - unify symbol
  js/pro/kraken.js
Labels: bug, WS

#15478 idex - unify symbol
  js/pro/idex.js
Labels: bug, WS

#15477 huobijp - unify symbol
  js/pro/huobijp.js
Labels: bug, WS

#15475 exmo - unify symbol
  js/pro/exmo.js
Labels: bug, WS

#15473 currencycom - unify symbol
  js/pro/currencycom.js
Labels: bug, WS

#15472 cryptocom - unify symbol
  js/pro/cryptocom.js
Labels: bug, WS

#15471 coinex - unify symbol
  js/pro/coinex.js
Labels: bug, WS

#15470 coinbasepro - unify symbol
  js/pro/coinbasepro.js
Labels: bug, WS

#15459 biitrex - unify symbol
  js/pro/bittrex.js
Labels: bug, WS
