Repository ccxt/ccxt, pull requests merged in 2022-04, with the labels that each got.

#12573 exmo - transfer
  js/exmo.js
Labels: enhancement

#12497 ascendex - transfer
  js/ascendex.js
Labels: enhancement

#12585 novadax: add safeTrades
  js/novadax.js
Labels: enhancement

#12581 Hitbtc3 setLeverage
  js/hitbtc3.js
Labels: enhancement

#12590 Fetch isolated positions
  js/aax.js
  js/ascendex.js
  js/binance.js
  js/bit2c.js
  js/bitbank.js
  js/bithumb.js
  js/bitpanda.js
  js/bitso.js
  js/bitstamp.js
  js/bitstamp1.js
  js/bittrex.js
  js/bitvavo.js
  js/bl3p.js
  js/btcalpha.js
  js/btcbox.js
  js/btcmarkets.js
  js/btctradeua.js
  js/btcturk.js
  js/buda.js
  js/bytetrade.js
  js/coinbase.js
  js/coincheck.js
  js/coinfalcon.js
  js/coinmate.js
  js/coinone.js
  js/coinspot.js
  js/crex24.js
  js/cryptocom.js
  js/gemini.js
  js/hitbtc.js
  js/hollaex.js
  js/huobi.js
  js/idex.js
  js/independentreserve.js
  js/indodax.js
  js/itbit.js
  js/kraken.js
  js/kuna.js
  js/lbank.js
  js/luno.js
  js/mercado.js
  js/mexc.js
  js/ndax.js
  js/novadax.js
  js/okx.js
  js/probit.js
  js/qtrade.js
  js/ripio.js
  js/stex.js
  js/tidebit.js
  js/tidex.js
  js/timex.js
  js/vcc.js
  js/wavesexchange.js
  js/yobit.js
  js/zonda.js
  wiki/Manual.md
Labels: enhancement

#12601 bitrue fetchWithdrawals fix
  js/bitrue.js
Labels: bug

#12607 Fixes #12409 (deribit crash on stop-market orders)
  js/base/Exchange.js
Labels: bug

#12602 ascendex - transfer describe
  js/ascendex.js
Labels: enhancement

#12599 Hitbtc3 fetchPosition
  js/hitbtc3.js
Labels: enhancement

#12584 Hitbtc3 fetchMarkOHLCV, fetchIndexOHLCV, fetchPremiumIndexOHLCV
  js/hitbtc3.js
Labels: enhancement

#12502 aax - fetchTransfers
  js/aax.js
Labels: enhancement

#12596 novadax: update ratelimits
  js/novadax.js
Labels: enhancement

#12611 Hitbtc3 'has'
  js/hitbtc3.js
Labels: enhancement

#12608 vcc - transfer
  js/vcc.js
Labels: enhancement

#12615 Update python's Precise class to allow native comparisons
  python/ccxt/base/precise.py
  python/ccxt/test/test_decimal_to_precision.py
Labels: enhancement

#12587 gateio.createReduceOnlyOrder
  js/gateio.js
Labels: enhancement

#12589 Borrow Interest docs
  wiki/Manual.md
Labels: enhancement

#12555 waves exchange - transfer, fetchTransfer, fetchTransfers
  js/wavesexchange.js
Labels: enhancement

#12609 poloniex - transfer
  js/poloniex.js
Labels: enhancement

#12595 Gateio :: fetchBalance :: add cross margin and funding
  js/gateio.js
Labels: enhancement

#12622 Mexc: error for trade read permission
  js/mexc.js
Labels: enhancement

#12633 Zaif: ratelimits
  js/zaif.js
Labels: enhancement

#12636 GMT/STEPN mapping
  js/bibox.js
  js/bittrex.js
  js/crex24.js
  js/exmo.js
  js/hitbtc.js
  js/hitbtc3.js
  js/latoken.js
  js/lbank.js
  js/mexc.js
Labels: enhancement

#12635 Huobi :: lowercase ids
  js/huobi.js
Labels: enhancement

#12639 Phemex: added error
  js/phemex.js
Labels: enhancement

#12634 add ohlcv building example for websocket
  wiki/ccxt.pro.manual.md
Labels: enhancement

#12640 typo corrections
  js/base/Exchange.js
  js/bigone.js
  js/buda.js
  js/bybit.js
  js/ftx.js
  js/gateio.js
  js/gemini.js
  js/huobi.js
  js/okx.js
  js/whitebit.js
  js/zb.js
Labels: enhancement

#12644 Okx fetch borrow interest
  js/okx.js
  php/Exchange.php
Labels: enhancement

#12642 huobi - fetchBorrowRate doesnt exist in file
  js/huobi.js
Labels: bug

#12632 Okx cancelOrders 'stopOrder'
  js/okx.js
Labels: enhancement

#12650 therock: add ratelimits
  js/therock.js
Labels: enhancement

#12655 Deribit :: fix market price
  js/deribit.js
Labels: bug

#12631 Okx fetchOpenOrders 'stopOrder'
  js/okx.js
Labels: enhancement

#12625 ftx.fetchBorrowRateHistories bug fixes related to a max limit of 48
  js/ftx.js
Labels: bug

#12664 Add __repr__ to Precise
  python/ccxt/base/precise.py
Labels: enhancement

#12665 bkex - this.marketIds
  js/bkex.js
Labels: enhancement

#12662 okex comment formatting
  js/okx.js
Labels: enhancement

#12660 gateio accountsByType swap: futures and future: delivery
  js/gateio.js
Labels: bug

#12653 Mexc fetchOpenOrders
  js/mexc.js
Labels: enhancement

#12671 update examples to use unified symbols. Fixes: #12666
  examples/ccxt.pro/js/okex-create-futures-order.js
  examples/ccxt.pro/py/okex-create-swap-order.py
  examples/php/bitmex-create-order.php
  examples/py/async-okex-positional-orders.py
  examples/py/bitmex-create-order.py
  examples/py/ftx-close-position-reduceOnly.py
  examples/py/ftx-conditional-orders.py
Labels: enhancement

#12661 gateio fetchBalanceHelper swap total fixes #12648
  js/gateio.js
Labels: bug

#12672 bitstamp.parseLedgerEntry safeStringLower for currency id index for amount. fixes #12667
  js/bitstamp.js
Labels: bug

#12668 wavesexchange: add safeTrade and examples
  js/wavesexchange.js
Labels: enhancement

#12663 Deposit no longer unified
  js/aax.js
  js/binance.js
  js/bitfinex2.js
  js/bkex.js
  js/bw.js
  js/coinbase.js
  js/coinbasepro.js
  js/currencycom.js
  js/huobi.js
  js/okx.js
  js/whitebit.js
  js/woo.js
  wiki/Manual.md
Labels: enhancement

#12659 CCXT Pro buildOHLCVC/build_ohlcvc example
  examples/ccxt.pro/js/build-ohlcv-many-symbols.js
  examples/ccxt.pro/py/build-ohlcv-many-symbols.py
Labels: enhancement

#12617 gateio.createOrder docstring. fixes:#12616
  js/gateio.js
Labels: enhancement

#12501 binance.parseTrades taker key for fetchTrades
  js/binance.js
Labels: enhancement

#12673 Mexc fetchCanceledOrders, fetchClosedOrders
  js/mexc.js
Labels: enhancement

#12641 Huobi fetch borrow interest
  js/huobi.js
Labels: enhancement

#12682 ndax: add safeTrade
  js/ndax.js
Labels: enhancement

#12694 Huobi :: fix fetchBalance
  js/huobi.js
Labels: bug

#12681 Mexc fetchOpenOrders 'stop'
  js/mexc.js
Labels: enhancement

#12692 [ftx] Don't crash on expiring delivery future in `fetch_markets`
  js/ftx.js
Labels: bug, enhancement

#12691 hollaex withdraw
  js/hollaex.js
Labels: enhancement

#12699 Edit bitvavo comment on rateLimit
  js/bitvavo.js
Labels: enhancement

#12690 Mexc cancelAllOrders
  js/mexc.js
Labels: enhancement

#12705 liquid - transfer
  js/liquid.js
Labels: enhancement

#12704 coinmate - transfer
  js/coinmate.js
Labels: enhancement

#12693 Build OHLCVC examples :: CompleteCandles option
  examples/ccxt.pro/js/build-ohlcv-many-symbols.js
  examples/ccxt.pro/py/build-ohlcv-many-symbols.py
Labels: enhancement

#12680 Mexc fetchOrder
  js/mexc.js
Labels: enhancement

#12703 coinfalcon - fetchDepositAddress, transfer functions
  js/coinfalcon.js
Labels: enhancement

#12713 coinbasepro.deposit docstring @returns link syntax update
  js/coinbasepro.js
Labels: bug

#12701 Mexc fetchClosedOrders, fetchCanceledOrders
  js/mexc.js
Labels: enhancement

#12714 xena: add safeTrade
  js/xena.js
Labels: enhancement

#12554 ftx - transfer
  js/ftx.js
Labels: enhancement

#12627 php&python docstring transpiler regexes
  build/transpile.js
  examples/js/delta-maintenance-margin-rate-max-leverage.js
  js/aax.js
  js/ascendex.js
  js/binance.js
  js/coinbasepro.js
  js/gateio.js
  js/kucoinfutures.js
  js/mexc.js
  js/okx.js
  js/xena.js
Labels: enhancement

#12717 additional error-code
  js/kucoin.js
Labels: enhancement

#12301 Borrow Rate parsers separated
  js/binance.js
  js/ftx.js
  js/okx.js
Labels: enhancement

#12720 Transpiler modify to accept argument from `pro`
  build/transpile.js
Labels: enhancement

#12736 bitbns - transfer
  js/bitbns.js
Labels: enhancement

#12735 bit2c - transfer
  js/bit2c.js
Labels: enhancement

#12739 bitforex - transfer
  js/bitforex.js
Labels: enhancement

#12744 upbit - transfer
  js/upbit.js
Labels: enhancement

#12741 bithumb - transfer
  js/bithumb.js
Labels: enhancement

#12732 bitstamp: fix #12718
  js/bitstamp.js
Labels: bug

#12737 Okx fetchCanceledOrders 'stop'
  js/okx.js
Labels: enhancement

#12746 Fix Binance trade sell/buy side parsing
  js/binance.js
Labels: bug

#12745 Mexc cancelOrder
  js/mexc.js
Labels: enhancement

#12754 kuna: add safeTrade
  js/kuna.js
Labels: enhancement

#12770 Kucoinfutures cancel all stop orders, fetch all stop orders
  js/kucoinfutures.js
Labels: enhancement

#12747 Gateio :: add nonce to orderBook
  js/gateio.js
Labels: enhancement

#12782 yobit: add safeTrade
  js/yobit.js
Labels: enhancement

#12755 `safeTransaction` (for `fetchTransactions`)
  build/transpile.js
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#12783 `fetchStatus` added `info`
  js/aax.js
  js/binance.js
  js/bitbns.js
  js/bitfinex2.js
  js/bitmart.js
  js/bitrue.js
  js/delta.js
  js/deribit.js
  js/digifinex.js
  js/kucoin.js
  js/kucoinfutures.js
  js/mexc.js
  js/okx.js
  js/wazirx.js
  js/whitebit.js
Labels: enhancement

#12766 safeStatus
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#12756 `safeTransfer` for `fetchTransfers`
  build/transpile.js
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#12786 `safeStatus` in `transpile.js`
  build/transpile.js
Labels: enhancement

#12789 yobit: add ratelimits
  js/yobit.js
Labels: enhancement

#12788 bitmex - transfer
  js/bitmex.js
Labels: enhancement

#12784 Bitfinex2 markets
  js/bitfinex2.js
Labels: enhancement

#12707 novadax - transfer
  js/novadax.js
Labels: enhancement

#12740 bitget - transfer
  js/bitget.js
Labels: enhancement

#12742 zonda - transfer
  js/zonda.js
Labels: enhancement

#11852 binance.createOrder stoploss unification
  js/binance.js
Labels: enhancement

#11100 aax.fetchPositions and aax.fetchPosition
  js/aax.js
Labels: enhancement

#12796 Running CCXT in a web worker :: example
  examples/html/webworker/index.html
  examples/html/webworker/worker.js
Labels: enhancement

#12805 [binance] withdraw parse
  js/binance.js
Labels: enhancement

#12808 [bitflyer] withdraw parse
  js/bitflyer.js
Labels: enhancement

#12809 ripio: add safeTrade
  js/ripio.js
Labels: enhancement

#12807 [bitfinex] withdraw parse
  js/bitfinex.js
Labels: enhancement

#12810 [bithumb] withdraw parse
  js/bithumb.js
Labels: enhancement

#12798 Gateio :: fix fetchCurrencies
  js/gateio.js
Labels: bug

#12797 Gate.io: Fetch order with clientOrderId in params
  js/gateio.js
Labels: enhancement

#12811 [bitmex] withdraw parse
  js/bitmex.js
Labels: enhancement

#12794 ZB fetchClosedOrders 'stop'
  js/zb.js
Labels: enhancement

#12812 [bitrue] withdraw parse
  js/bitrue.js
Labels: enhancement

#12816 vcc - withdraw
  js/vcc.js
Labels: enhancement

#12818 [bitstamp] withdraw parse
  js/bitstamp.js
Labels: enhancement

#12821 [cdax] withdraw parse
  js/cdax.js
Labels: enhancement

#12820 [blockchaincom] withdraw parse
  js/blockchaincom.js
Labels: enhancement

#12819 [bittrex] withdraw parse
  js/bittrex.js
Labels: enhancement

#12822 [coinbasepro] withdraw parse
  js/coinbasepro.js
Labels: enhancement

#12853 [zonda] withdraw parse
  js/zonda.js
Labels: enhancement

#12852 [zaif] withdraw parse
  js/zaif.js
Labels: enhancement

#12851 [whitebit] withdraw parse
  js/whitebit.js
Labels: enhancement

#12850 [wavesexchange] withdraw parse
  js/wavesexchange.js
Labels: enhancement

#12849 [tidex] withdraw parse
  js/tidex.js
Labels: enhancement

#12848 [tidebit] withdraw parse
  js/tidebit.js
Labels: enhancement

#12847 [poloniex] withdraw parse
  js/poloniex.js
Labels: enhancement

#12846 [okcoin] withdraw parse
  js/okcoin.js
Labels: enhancement

#12844 [mercado] withdraw parse
  js/mercado.js
Labels: enhancement

#12843 [lbank] withdraw parse
  js/lbank.js
Labels: enhancement

#12842 [kucoin] withdraw parse
  js/kucoin.js
Labels: enhancement

#12841 [kraken] withdraw parse
  js/kraken.js
Labels: enhancement

#12840 [indodax] withdraw parse
  js/indodax.js
Labels: enhancement

#12839 [idex] withdraw parse
  js/idex.js
Labels: enhancement

#12838 [huobijp] withdraw parse
  js/huobijp.js
Labels: enhancement

#12834 [hitbtc3] withdraw parse
  js/hitbtc3.js
Labels: enhancement

#12833 [hitbtc] withdraw parse
  js/hitbtc.js
Labels: enhancement

#12832 ZB fetchCanceledOrders 'stop'
  js/zb.js
Labels: enhancement

#12837 [huobi] withdraw parse
  js/huobi.js
Labels: enhancement

#12830 ZB fetchOpenOrders 'stop'
  js/zb.js
Labels: enhancement

#12827 [gemini] withdraw parse
  js/gemini.js
Labels: enhancement

#12826 [gateio] withdraw parse
  js/gateio.js
Labels: enhancement

#12825 [exmo] withdraw parse
  js/exmo.js
Labels: enhancement

#12824 [deribit] withdraw parse
  js/deribit.js
Labels: enhancement

#12823 [cryptocom] withdraw parse
  js/cryptocom.js
Labels: enhancement

#12804 [bibox] withdraw parse
  js/bibox.js
Labels: enhancement

#12860 ZB cancelAllOrders 'stop'
  js/zb.js
Labels: enhancement

#12862 docs minor fix
  wiki/Manual.md
Labels: bug

#12793 yobit cancelOrder cleanup
  js/yobit.js
Labels: enhancement

#12858 ZB fetchOrder 'stop'
  js/zb.js
Labels: enhancement

#12845 [ndax] withdraw parse
  js/ndax.js
Labels: enhancement

#12792 ZB fetchOrders 'stop'
  js/zb.js
Labels: enhancement

#12813 [bitso] withdraw parse
  js/bitso.js
Labels: enhancement

#12738 Manual update - transfer
  wiki/Manual.md
Labels: enhancement

#12706 bigone - transfer
  js/bigone.js
Labels: enhancement

#12806 [bitbank] withdraw parse
  js/bitbank.js
  js/bitfinex.js
Labels: enhancement

#12800 ascendex - refactor transfer
  js/ascendex.js
Labels: enhancement

#12801 binance - refactor transfer
  js/binance.js
Labels: enhancement
