Repository ccxt/ccxt, pull requests merged in 2022-05, with the labels that each got.

#13069 huobi error mapping
  js/huobi.js
Labels: enhancement

#13066 add `timestamp === undefined` check in `test.positions.js`
  js/test/Exchange/test.position.js
Labels: bug

#13070 binance - remove `fetchBorrowRateHistories`
  js/binance.js
Labels: bug

#13078 examples/js/sort-swap-markets-by-hourly-price-change-example.js removed ohlcv console log
  examples/js/sort-swap-markets-by-hourly-price-change.js
Labels: enhancement

#13058 Coinex createOrder
  js/coinex.js
Labels: enhancement

#13080 Coinex fetchTickers
  js/coinex.js
Labels: enhancement

#13081 Kucoinfutures fetchClosedOrders & fetchOrderByStatus params.till
  js/kucoin.js
  js/kucoinfutures.js
Labels: enhancement

#13079 bitmart: update Ticker methods to support swap
  js/bitmart.js
Labels: enhancement

#13057 gateio getMarginType
  js/gateio.js
Labels: enhancement

#13086 Coinex setMarginMode
  js/coinex.js
Labels: enhancement

#13096 Coinex 'has'
  js/coinex.js
Labels: enhancement

#13060 binance.parsePositionRisk check if quotePrecision is undefined
  js/binance.js
Labels: bug

#13090 uniform exception messages format & bugfixes
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#13029 gateio cross_margin and crossMargin in accountByType
  js/gateio.js
Labels: enhancement

#13083 Gateio create order uses getMarginType
  js/gateio.js
Labels: enhancement

#13098 Python transfer example
  examples/py/binance-universal-transfer.py
Labels: enhancement

#13102 Gateio transfer margin symbol
  js/gateio.js
Labels: bug

#13107 Whitebit parse ticker
  js/whitebit.js
Labels: bug

#13115 Filter `fetchPositions` by input symbols
  js/okx.js
Labels: enhancement

#13103 Gateio margin fetch order
  js/gateio.js
Labels: enhancement

#13106 Coinex fetchTransfers
  js/coinex.js
Labels: enhancement

#13105 Coinex transfer
  js/coinex.js
Labels: enhancement

#13116 Bybit cancelAllOrders
  js/bybit.js
Labels: enhancement

#13120 removal of fetchFundingRateHistories
  js/novadax.js
  js/therock.js
  js/upbit.js
Labels: bug

#13019 hollaex - fetchWithdrawal, transfer
  js/hollaex.js
Labels: enhancement

#13113 Gateio fetch tickers
  js/gateio.js
Labels: enhancement

#13104 gateio.prepareRequest accepts type and params as parameters, gateio.multiOrderSpotPrepareRequest
  js/gateio.js
Labels: enhancement

#13112 Gateio fetch order book
  js/gateio.js
Labels: enhancement

#13110 Gateio fetch funding history
  js/gateio.js
Labels: enhancement

#13109 Gateio fetch funding rates
  js/gateio.js
Labels: enhancement

#13125 Gateio fetch balance new prepare request
  js/gateio.js
Labels: enhancement

#13126 gateio.fetchFundingRateHistory new prepareRequest
  js/gateio.js
Labels: enhancement

#13127 Gateio get margin type params account omitted
  js/gateio.js
Labels: enhancement

#13129 gateio.setLeverage marginType can be cross_margin
  js/gateio.js
Labels: enhancement

#13130 gateio.fetchPositions new prepareRequest
  js/gateio.js
Labels: enhancement

#13132 gateio.cancelAllOrders new prepareRequest, accepts cross margin type
  js/gateio.js
Labels: enhancement

#13131 gateio.fetchLeverageTiers new prepareRequest
  js/gateio.js
Labels: enhancement

#13138 Bybit :: fetchMarkets update
  js/bybit.js
Labels: enhancement

#13137 createStopOrder: false
  js/bitmart.js
  js/coinbase.js
  js/huobijp.js
  js/wavesexchange.js
  js/woo.js
Labels: enhancement

#13148 Phemex createReduceOnlyOrder
  js/phemex.js
Labels: enhancement

#13149 Phemex fetchFundingRate
  js/phemex.js
Labels: enhancement

#13144 Bybit :: fetchTicker and fetchTickers update
  js/bybit.js
Labels: enhancement

#13154 Bybit :: USDC markets update
  js/bybit.js
Labels: enhancement

#13156 Bybit :: fetchMyTrades update
  js/bybit.js
Labels: enhancement

#13150 Phemex fetchFundingHistory
  js/phemex.js
Labels: enhancement

#13172 Bybit :: fetchMarketLeverageTiers update
  js/bybit.js
Labels: enhancement

#13179 send params to gemini postV1Orders
  js/gemini.js
Labels: enhancement

#13176 ndax - transfer
  js/ndax.js
Labels: enhancement

#13175 probit - transfer
  js/probit.js
Labels: enhancement

#13174 xena transfer
  js/xena.js
Labels: enhancement

#13173 qtrade - fetchTransfer
  js/qtrade.js
Labels: enhancement

#13133 Gateio cancel order
  js/gateio.js
Labels: enhancement

#13169 Bybit :: fetchFundingRate update
  js/bybit.js
Labels: enhancement

#13178 zb: update ratelimits
  js/zb.js
Labels: enhancement

#13164 BKEX fetchStatus
  js/bkex.js
Labels: enhancement

#12920 lbank v2
  js/lbank2.js
Labels: new exchange

#13196 Remove DRK as common currency for DASH #13157
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#13146 Bybit :: fetchOrderBook update
  js/bybit.js
Labels: enhancement

#13195 kucoin: patch error code InvalidOrder
  js/kucoin.js
Labels: enhancement

#13192 poloniex error mapping
  js/poloniex.js
Labels: enhancement

#13187 changed marginType to marginMode everywhere
  examples/js/gateio-open-close-contract.js
  examples/js/huobi-open-close-contract.js
  js/aax.js
  js/ascendex.js
  js/binance.js
  js/binanceusdm.js
  js/bitget.js
  js/bybit.js
  js/coinex.js
  js/currencycom.js
  js/deribit.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/huobi.js
  js/kucoinfutures.js
  js/mexc.js
  js/okx.js
  js/phemex.js
  js/zb.js
Labels: enhancement

#13185 Phemex setMarginMode
  js/phemex.js
Labels: enhancement

#13186 Phemex reduceMargin, addMargin
  js/phemex.js
Labels: enhancement

#13189 Gateio fetchMyTrades cross margin
  js/gateio.js
Labels: enhancement

#13033 gateio transfer can take symbols as fromAccount or toAccount, or take params.symbol
  js/gateio.js
Labels: enhancement

#13201 Ascendex parsePosition
  js/ascendex.js
Labels: enhancement

#13191 gateio fetchOrdersByStatus cross margin able, filters orders by marginType for spot
  js/gateio.js
Labels: enhancement

#13204 ftx error mapping
  js/ftx.js
Labels: enhancement

#13207 Bitget parsePosition
  js/bitget.js
Labels: enhancement

#13210 Bitget fetchLeverage
  js/bitget.js
Labels: enhancement

#13208 Rename `fetchFundingFees/fetch_funding_fees` into `fetchTransactionFees/fetch_transaction_fees`
  build/transpile.js
  js/aax.js
  js/ascendex.js
  js/base/Exchange.js
  js/bibox.js
  js/binance.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitmart.js
  js/bitopro.js
  js/bitrue.js
  js/bitso.js
  js/bitstamp.js
  js/bittrex.js
  js/bkex.js
  js/buda.js
  js/bw.js
  js/crex24.js
  js/cryptocom.js
  js/currencycom.js
  js/exmo.js
  js/ftx.js
  js/gateio.js
  js/huobi.js
  js/kucoin.js
  js/kucoinfutures.js
  js/lbank2.js
  js/liquid.js
  js/lykke.js
  js/oceanex.js
  js/okx.js
  js/stex.js
  js/test/Exchange/test.fetchFundingFees.js
  js/test/test.js
  js/wazirx.js
  js/whitebit.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13212 mexc: unfify timeInForce & postOnly
  js/mexc.js
Labels: enhancement

#13221 yobit - transfer
  js/yobit.js
Labels: enhancement

#13220 therock - transfer
  js/therock.js
Labels: enhancement

#13218 delta - transfer, withdraw
  js/delta.js
Labels: enhancement

#13217 latoken error mapping
  js/latoken.js
Labels: enhancement

#13213 binance: add giftcard cryptography rsa-public-key
  js/binance.js
Labels: enhancement

#12376 Exchange upgrade - MEXC v3
  js/mexc3.js
Labels: enhancement

#13225 Bitget fetchFundingRate
  js/bitget.js
Labels: enhancement

#13227 gateio.fetchOpenOrders parsing fixed. fixes: #13223
  js/gateio.js
Labels: enhancement

#13228 aax.fetchMarkets parse numbers in limits, add leverage min/max for swap
  js/aax.js
Labels: enhancement

#13226 Bitget fetchFundingRateHistory
  js/bitget.js
Labels: enhancement

#13234 Bybit :: fetchWithdrawals update
  js/bybit.js
Labels: enhancement

#13215 Add safeMethodN methods
  build/transpile.js
  js/base/Exchange.js
  js/base/functions/type.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13236 Minor corrections across base files
  js/base/Exchange.js
  js/binance.js
  js/test/Exchange/test.fetchBalance.js
  js/test/Exchange/test.fetchBorrowInterest.js
  js/test/Exchange/test.fetchBorrowRate.js
  js/test/Exchange/test.fetchBorrowRates.js
  js/test/Exchange/test.fetchClosedOrders.js
  js/test/Exchange/test.fetchCurrencies.js
  js/test/Exchange/test.fetchDeposits.js
  js/test/Exchange/test.fetchFundingFees.js
  js/test/Exchange/test.fetchFundingRateHistory.js
  js/test/Exchange/test.fetchL2OrderBook.js
  js/test/Exchange/test.fetchLedger.js
  js/test/Exchange/test.fetchLeverageTiers.js
  js/test/Exchange/test.fetchMarketLeverageTiers.js
  js/test/Exchange/test.fetchMarkets.js
  js/test/Exchange/test.fetchMyTrades.js
  js/test/Exchange/test.fetchOHLCV.js
  js/test/Exchange/test.fetchOpenOrders.js
  js/test/Exchange/test.fetchOrderBook.js
  js/test/Exchange/test.fetchOrderBooks.js
  js/test/Exchange/test.fetchOrders.js
  js/test/Exchange/test.fetchPositions.js
  js/test/Exchange/test.fetchStatus.js
  js/test/Exchange/test.fetchTicker.js
  js/test/Exchange/test.fetchTickers.js
  js/test/Exchange/test.fetchTrades.js
  js/test/Exchange/test.fetchTradingFee.js
  js/test/Exchange/test.fetchTradingFees.js
  js/test/Exchange/test.fetchTransactions.js
  js/test/Exchange/test.fetchWithdrawals.js
  js/test/Exchange/test.loadMarkets.js
  js/test/errors/test.InsufficientFunds.js
  js/test/errors/test.InvalidOrder.js
  js/test/errors/test.OrderNotFound.js
  php/Exchange.php
  php/async/Exchange.php
  php/test/test_async.php
  php/test/test_sync.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
Labels: enhancement

#13237 Bitget reduceMargin, addMargin
  js/bitget.js
Labels: enhancement

#13238 Bitget createOrder: unify 'stopPrice'
  js/bitget.js
Labels: enhancement

#13245 fix php safe_X_N
  php/Exchange.php
Labels: bug

#13250 fetchBalance bug fix
  js/huobi.js
Labels: bug

#13246 bigone error mapping
  js/bigone.js
Labels: enhancement

#13243 remove ratelimit requirement from `editorder`
  js/base/Exchange.js
  php/Exchange.php
  php/async/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#13242 mexc fetchSpotMarkets enhancement
  js/mexc.js
Labels: enhancement

#13240 Minor edits in base tests
  php/test/test_async.php
  python/ccxt/test/test_async.py
Labels: enhancement

#13247 CONTRIBUTING.md add safeMethodN reference
  CONTRIBUTING.md
Labels: enhancement

#13163 Bybit :: fetchBalance update and openapi signing
  js/bybit.js
Labels: enhancement

#13259 Fix import
  examples/py/fetch-ohlcv-kraken.py
Labels: bug

#13272 cex error mapping
  js/cex.js
Labels: enhancement

#13290 fix fetchOrderBook
  js/kucoin.js
Labels: enhancement

#13289 deribit - update describe
  js/deribit.js
Labels: enhancement

#13288 mexc3: add amount precision to markets
  js/mexc3.js
Labels: bug

#13297 huobi: update entryPrice in parsePosition
  js/huobi.js
Labels: bug

#13282 Bitget cancelOrder
  js/bitget.js
Labels: enhancement

#13281 stex - createMarketOrder
  js/stex.js
Labels: enhancement

#13277 btcbox - transfer, withdraw, fetchTransactions
  js/btcbox.js
Labels: enhancement

#13293 Bitmex fetch funding rate history
  js/base/Exchange.js
  js/bitmex.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13280 btcmarkets - withdraw
  js/btcmarkets.js
Labels: enhancement

#13262 Bybit :: setLeverage update
  js/bybit.js
Labels: enhancement

#13283 huobi fetchBalance params marginMode
  js/huobi.js
Labels: enhancement

#13295 Bitmex fetchFundingRates
  js/bitmex.js
Labels: enhancement

#13285 stex - fetchDeposit, fetchWithdrawal
  js/stex.js
Labels: enhancement

#13287 Allow to filter exchange-capabilities by exchange
  examples/js/exchange-capabilities.js
Labels: enhancement

#13269 indodax - fetchTransactions
  js/indodax.js
Labels: enhancement

#12356 kucoinfutures parseMargin
  js/kucoinfutures.js
Labels: enhancement

#13300 rename `parseModifyMargin` > `parseMarginModification`
  build/transpile.js
  js/ascendex.js
  js/binance.js
  js/bitget.js
  js/coinex.js
  js/hitbtc3.js
  js/mexc.js
  js/okx.js
  js/phemex.js
  js/zb.js
Labels: enhancement

#13299 `currencyToPrecision` update with networkCode
  js/.eslintrc
  js/base/Exchange.js
  js/binance.js
  js/bitrue.js
  js/bitvavo.js
  js/cdax.js
  js/huobi.js
  js/huobijp.js
  js/wavesexchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13303 Update okx.php
  js/okx.js
  php/async/okx.php
Labels: bug

#13306 bkex: patch percentage in ticker
  js/bkex.js
Labels: bug

#12814 coinmate - withdraw
  js/coinmate.js
Labels: enhancement

#13271 Add bit2c.fetchDepositAddress
  js/bit2c.js
Labels: enhancement

#13308 Phemex fetchLeverageTiers, fetchMarketLeverageTiers
  js/phemex.js
Labels: enhancement

#13219 therock - withdraw
  js/therock.js
Labels: enhancement

#13310 Phemex fetchTransfers
  js/phemex.js
Labels: enhancement

#13048 New exchange - CoinFLEX
  build/transpile.js
  js/base/Exchange.js
  js/coinflex.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: new exchange

#13153 `checkOrderTypeAndPrice` in base
  build/transpile.js
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13121 Coinex fetchLeverageTiers, fetchMarketLeverageTiers
  js/base/Exchange.js
  js/coinex.js
Labels: enhancement

#13312 Ftx fetchMyTrades till param, default till removed
  js/ftx.js
Labels: enhancement

#13323 Cryptocom :: fix fetchTickers
  js/cryptocom.js
Labels: bug

#13317 isPostOnly fixes
  js/base/Exchange.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#12880 bitfinex2 - `parseTransfer` for `transfer`
  js/bitfinex2.js
Labels: enhancement

#13333 Exchange createReduceOnlyOrder
  js/ascendex.js
  js/base/Exchange.js
  js/binance.js
  js/coinex.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/phemex.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13294 Base fetch funding rate
  js/ascendex.js
  js/base/Exchange.js
  php/Exchange.php
  php/async/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: enhancement

#13337 Bybit :: refactor custom parseOrderBook
  js/bybit.js
Labels: enhancement

#13340 Gateio - limit for futures requests
  js/gateio.js
Labels: enhancement

#13141 okx: add new api endpoints for broker
  js/okx.js
Labels: enhancement

#13343 fetchBorrowRateHistory docstrings
  js/binance.js
  js/ftx.js
  js/okx.js
Labels: enhancement

#13344 docstring arrays and return types
  build/transpile.js
Labels: enhancement

#13335 correction of incorrect referenced method-strings
  js/ascendex.js
  js/binance.js
  js/bitbns.js
  js/bitmart.js
  js/bitpanda.js
  js/bitrue.js
  js/bkex.js
  js/buda.js
  js/bw.js
  js/bytetrade.js
  js/coinbasepro.js
  js/cryptocom.js
  js/deribit.js
  js/huobi.js
  js/indodax.js
  js/itbit.js
  js/okx.js
  js/phemex.js
  js/whitebit.js
  js/xena.js
Labels: bug

#13355 Bybit :: cleanup
  js/bybit.js
Labels: enhancement

#13357 ascendex fetchMarkets edits
  js/ascendex.js
Labels: enhancement

#13359 Bybit :: improve fetchOrders error message
  js/bybit.js
Labels: enhancement

#12684 fetchOpenInterestHistory docs
  wiki/Manual.md
Labels: enhancement

#12685 Binance fetch open interest history
  js/base/Exchange.js
  js/binance.js
  js/test/Exchange/test.fetchOpenInterestHistory.js
  js/test/Exchange/test.openInterest.js
  js/test/test.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#13364 `fetchLeverageTiers` to `fetchMarketLeverageTiers` and few things
  js/base/Exchange.js
  js/bybit.js
  js/huobi.js
  js/kucoinfutures.js
  js/okx.js
  php/Exchange.php
  php/async/Exchange.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: bug

#13370 fetchFundingRateHistory docstrings
  js/aax.js
  js/binance.js
  js/bitget.js
  js/bitmex.js
  js/coinex.js
  js/coinflex.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/huobi.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/zb.js
Labels: enhancement

#13365 setMargin
  build/transpile.js
  js/aax.js
  js/base/Exchange.js
  js/phemex.js
  js/test/Exchange/test.marginModification.js
  php/Exchange.php
  python/ccxt/base/exchange.py
  wiki/Manual.md
Labels: enhancement

#13376 bitmex: fix empty return when call fetchTickers ccxt/ccxt#13373
  js/bitmex.js
Labels: bug

#13291 fetchAccounts unification
  CONTRIBUTING.md
  build/transpile.js
  js/base/Exchange.js
  js/coinbase.js
  js/coinbasepro.js
  js/deribit.js
  js/huobi.js
  js/test/Exchange/test.account.js
  js/test/Exchange/test.fetchAccounts.js
  js/test/Exchange/test.leverageTier.js
  js/test/test.js
  php/Exchange.php
  php/test/test_async.php
  php/test/test_sync.php
  python/ccxt/base/exchange.py
  wiki/Manual.md
Labels: enhancement

#13361 aax - fetchAccounts
  js/aax.js
Labels: enhancement

#13377 Bitmex parse positions
  js/bitmex.js
Labels: enhancement

#13385 [DOCS] typo on javascripts' load markets function
  doc/manual.rst
  wiki/Manual.md
Labels: enhancement
