Repository ccxt/ccxt, pull requests merged in 2022-06, with the labels that each got.

#13506 Coinex createOrder
  js/coinex.js
Labels: enhancement

#13500 Coinex transfer
  js/coinex.js
Labels: bug, enhancement

#13504 Coinex fetchBorrowRate
  js/coinex.js
Labels: enhancement

#13515 Bybit :: add price to precision
  js/bybit.js
Labels: bug

#13527 bibox createStopOrder: false
  js/bibox.js
Labels: enhancement

#13529 Coinex cancelAllOrders
  js/coinex.js
Labels: enhancement

#13522 Coinex fetchMyTrades
  js/coinex.js
Labels: enhancement

#13536 bybit - order status
  js/bybit.js
Labels: enhancement

#13540 Bitget fetchOHLCV since fix
  js/bitget.js
  wiki/Exchange-Markets.md
Labels: bug

#13549 mexc fetchOrder parser - dealAvgPrice used for average and no longer used for cost
  js/mexc.js
Labels: bug

#13534 mexc3 - fix precision, commission and other things
  js/mexc3.js
Labels: bug

#13582 bitfinex LUNA, UST mapping
  js/bitfinex.js
Labels: enhancement

#13599 kucoin: update request stop in stop order
  js/kucoin.js
Labels: enhancement

#13581 kraken LUNA, UST mapping
  js/kraken.js
Labels: enhancement

#13584 bitstamp UST mapping
  js/bitstamp.js
Labels: enhancement

#13559 fix kucoinfutures fetch_trades missing timestamp
  js/kucoinfutures.js
Labels: bug

#13523 Huobi fetchSettlementHistory
  js/huobi.js
Labels: enhancement

#13538 Coinex fetchOpenOrders, fetchClosedOrders
  js/coinex.js
Labels: enhancement

#13608 Fixed Coinbase Pro's `fetchDeposits()` and `fetchWithdrawals()`
  js/coinbasepro.js
Labels: bug

#13617 okx stop orders
  js/okx.js
Labels: enhancement

#13611 markets response sample for gemini
  js/gemini.js
Labels: enhancement

#13607 TICK_SIZE - exmo
  js/exmo.js
Labels: enhancement

#13546 Digifinex fetchMarkets
  js/digifinex.js
Labels: enhancement

#13609 TICK_SIZE - gateio
  js/gateio.js
Labels: enhancement

#13616 TICK_SIZE - itbit
  js/itbit.js
Labels: enhancement

#13615 TICK_SIZE - indodax
  js/indodax.js
Labels: enhancement

#13618 TICK_SIZE - independentreserve
  js/independentreserve.js
Labels: enhancement

#13626 Added support for ENS, MANA, LRC and SHIB
  js/bitstamp.js
Labels: enhancement

#13648 TICK_SIZE - kuna
  js/kuna.js
Labels: enhancement

#13630 ftx.fetchBorrowRateHistory docstring minor fix
  js/ftx.js
Labels: bug, enhancement

#13654 TICK_SIZE - liquid
  js/liquid.js
Labels: enhancement

#13625 TICK_SIZE - kucoin
  js/kucoin.js
Labels: enhancement

#13657 binance fetchMyDustTrades docstring
  js/binance.js
Labels: enhancement

#13649 ticksize - latoken updates
  js/latoken.js
Labels: enhancement

#13660 TICK_SIZE - mercado
  js/mercado.js
Labels: enhancement

#13644 futuresTransfer docstring
  js/binance.js
Labels: enhancement

#13636 setLeverage docstrings
  js/aax.js
  js/ascendex.js
  js/binance.js
  js/bitget.js
  js/bitmex.js
  js/bybit.js
  js/coinex.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/huobi.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/phemex.js
  js/zb.js
Labels: enhancement

#13658 TICK_SIZE - luno
  js/luno.js
Labels: enhancement

#13673 Bitmex: added error
  js/bitmex.js
Labels: enhancement

#13671 therock - fetchOHLCV
  js/therock.js
Labels: enhancement

#13670 TICK_SIZE - ripio
  js/ripio.js
Labels: enhancement

#13669 TICK_SIZE - qtrade
  js/qtrade.js
Labels: enhancement

#13667 TICK_SIZE - poloniex
  js/poloniex.js
Labels: enhancement

#13664 TICK_SIZE - okcoin
  js/okcoin.js
Labels: enhancement

#13663 TICK_SIZE - oceanex
  js/oceanex.js
Labels: enhancement

#13651 TICK_SIZE - lbank2
  js/lbank2.js
Labels: enhancement

#13650 fetchTransactionFees docstrings
  js/bibox.js
  js/binance.js
  js/bitfinex.js
  js/bitso.js
  js/bitstamp.js
  js/buda.js
  js/crex24.js
  js/exmo.js
  js/gateio.js
  js/lbank2.js
  js/stex.js
  js/whitebit.js
Labels: enhancement

#13646 fetchTradingFee docstrings
  js/binance.js
  js/bitflyer.js
  js/bitget.js
  js/bitstamp.js
  js/bittrex.js
  js/coinex.js
  js/coinmate.js
  js/gateio.js
  js/hitbtc.js
  js/hitbtc3.js
  js/huobi.js
  js/kraken.js
  js/kucoin.js
  js/latoken.js
  js/lbank2.js
  js/liquid.js
  js/okx.js
  js/qtrade.js
  js/stex.js
  js/therock.js
  js/timex.js
  js/upbit.js
  js/vcc.js
Labels: enhancement

#13643 fetchFundingRate docstrings
  js/aax.js
  js/binance.js
  js/bitget.js
  js/bybit.js
  js/coinex.js
  js/coinflex.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/huobi.js
  js/kucoinfutures.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/phemex.js
  js/zb.js
Labels: enhancement

#13674 Digifinex fetchBorrowInterest
  js/digifinex.js
Labels: enhancement

#13665 TICK_SIZE - paymium
  js/paymium.js
Labels: enhancement

#13645 fetchTradingFees docstrings
  js/ascendex.js
  js/binance.js
  js/bit2c.js
  js/bitbank.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitget.js
  js/bitopro.js
  js/bitpanda.js
  js/bitso.js
  js/bitstamp.js
  js/bittrex.js
  js/bitvavo.js
  js/bl3p.js
  js/blockchaincom.js
  js/bw.js
  js/bytetrade.js
  js/cex.js
  js/coinbasepro.js
  js/coincheck.js
  js/coinex.js
  js/coinfalcon.js
  js/crex24.js
  js/currencycom.js
  js/deribit.js
  js/eqonex.js
  js/exmo.js
  js/ftx.js
  js/gateio.js
  js/gemini.js
  js/hitbtc3.js
  js/hollaex.js
  js/idex.js
  js/independentreserve.js
  js/lbank2.js
  js/liquid.js
  js/luno.js
  js/mexc.js
  js/mexc3.js
  js/oceanex.js
  js/poloniex.js
  js/ripio.js
  js/therock.js
  js/whitebit.js
  js/woo.js
  js/yobit.js
Labels: enhancement

#13635 setMarginMode docstrings
  js/ascendex.js
  js/binance.js
  js/bitget.js
  js/bitmex.js
  js/bybit.js
  js/coinex.js
  js/okx.js
  js/phemex.js
Labels: enhancement

#13662 TICK_SIZE - novadax
  js/novadax.js
Labels: enhancement

#13659 TICK_SIZE - lykke
  js/lykke.js
Labels: enhancement

#13634 setPositionMode docstrings
  js/binance.js
  js/okx.js
Labels: enhancement

#13633 reduce margin docstrings
  js/ascendex.js
  js/binance.js
  js/bitget.js
  js/coinex.js
  js/exmo.js
  js/hitbtc3.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/zb.js
Labels: enhancement

#13628 fetchBorrowInterest docstrings
  js/binance.js
  js/ftx.js
  js/huobi.js
  js/okx.js
Labels: enhancement

#13638 fetchPositionsRisk docstrings
  js/binance.js
Labels: enhancement

#13632 add margin docstrings
  js/ascendex.js
  js/binance.js
  js/bitget.js
  js/coinex.js
  js/exmo.js
  js/hitbtc3.js
  js/kucoinfutures.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/zb.js
Labels: enhancement

#13631 fetchBorrowRate docstrings
  js/binance.js
  js/coinex.js
  js/okx.js
  js/zb.js
Labels: enhancement

#13629 binance giftCode method docstrings
  js/binance.js
Labels: enhancement

#13677 Coinflex :: fix sandbox authentication
  js/coinflex.js
Labels: bug

#13641 fetchLeverageTiers docstrings
  js/ascendex.js
  js/binance.js
  js/coinex.js
  js/gateio.js
  js/huobi.js
  js/mexc.js
  js/mexc3.js
  js/phemex.js
  js/xena.js
Labels: enhancement

#13640 fetchPositions docstrings
  js/aax.js
  js/ascendex.js
  js/binance.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitflyer.js
  js/bitget.js
  js/bitmex.js
  js/bybit.js
  js/coinex.js
  js/coinflex.js
  js/currencycom.js
  js/delta.js
  js/deribit.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/huobi.js
  js/kraken.js
  js/kucoinfutures.js
  js/mexc.js
  js/mexc3.js
  js/okcoin.js
  js/okx.js
  js/phemex.js
  js/zb.js
Labels: enhancement

#13639 fetchAccountPositions docstrings
  js/binance.js
Labels: enhancement

#13637 fetchFundingHistory docstrings
  js/aax.js
  js/binance.js
  js/coinex.js
  js/coinflex.js
  js/ftx.js
  js/gateio.js
  js/huobi.js
  js/kucoinfutures.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/phemex.js
Labels: enhancement

#13642 fetchFundingRates docstrings
  js/ascendex.js
  js/binance.js
  js/bitmex.js
  js/coinflex.js
  js/gateio.js
  js/huobi.js
  js/zb.js
Labels: enhancement

#13679 TICK_SIZE - stex
  js/stex.js
Labels: enhancement

#13681 Flip sign for OKX fees
  js/okx.js
Labels: bug

#13683 TICK_SIZE - tidebit
  js/tidebit.js
Labels: enhancement

#13684 TICK_SIZE - tidex
  js/tidex.js
Labels: enhancement

#13696 TICK_SIZE - zb
  js/zb.js
Labels: enhancement

#13697 TICK_SIZE - zonda
  js/zonda.js
Labels: enhancement

#13692 TICK_SIZE - woo
  js/woo.js
Labels: enhancement

#13691 TICK_SIZE - whitebit
  js/whitebit.js
Labels: enhancement

#13690 ticksize - wazirx
  js/wazirx.js
Labels: enhancement

#13688 TICK_SIZE - vcc
  js/vcc.js
Labels: enhancement

#13687 TICK_SIZE- upbit
  js/upbit.js
Labels: enhancement

#13685 TICK_SIZE - timex
  js/timex.js
Labels: enhancement

#13699 fetchOrderTrades docstrings
  js/binance.js
  js/bitfinex2.js
  js/bitget.js
  js/bitmart.js
  js/bitpanda.js
  js/bitso.js
  js/bittrex.js
  js/bybit.js
  js/cdax.js
  js/coinbasepro.js
  js/crex24.js
  js/deribit.js
  js/exmo.js
  js/ftx.js
  js/hitbtc.js
  js/hitbtc3.js
  js/huobi.js
  js/huobijp.js
  js/kraken.js
  js/mexc.js
  js/mexc3.js
  js/ndax.js
  js/novadax.js
  js/okcoin.js
  js/okx.js
  js/poloniex.js
  js/stex.js
  js/whitebit.js
  js/woo.js
Labels: enhancement

#13700 cancelAllOrders docstrings
  js/aax.js
  js/ascendex.js
  js/bigone.js
  js/binance.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitmart.js
  js/bitmex.js
  js/bitopro.js
  js/bitpanda.js
  js/bitstamp.js
  js/bittrex.js
  js/bitvavo.js
  js/bybit.js
  js/cdax.js
  js/coinbasepro.js
  js/coinex.js
  js/coinflex.js
  js/crex24.js
  js/cryptocom.js
  js/delta.js
  js/deribit.js
  js/ftx.js
  js/gateio.js
  js/hitbtc3.js
  js/hollaex.js
  js/huobi.js
  js/huobijp.js
  js/kraken.js
  js/kucoin.js
  js/kucoinfutures.js
  js/latoken.js
  js/lbank2.js
  js/lykke.js
  js/mexc.js
  js/mexc3.js
  js/ndax.js
  js/oceanex.js
  js/phemex.js
  js/poloniex.js
  js/stex.js
  js/vcc.js
  js/wazirx.js
  js/xena.js
  js/zb.js
Labels: enhancement

#13693 TICK_SIZE - xena
  js/xena.js
Labels: enhancement

#13682 TICK_SIZE - therock
  js/therock.js
Labels: enhancement

#13703 Digifinex fetchBorrowRate, fetchBorrowRates
  js/digifinex.js
Labels: enhancement

#13715 fetchTransactionFee docstrings
  js/bitmart.js
  js/coinflex.js
  js/kucoin.js
  js/kucoinfutures.js
Labels: enhancement

#13714 fetchTransactions docstrings
  js/ascendex.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitmex.js
  js/bitstamp.js
  js/btcmarkets.js
  js/coinbasepro.js
  js/coinmate.js
  js/crex24.js
  js/currencycom.js
  js/exmo.js
  js/gemini.js
  js/hitbtc.js
  js/hitbtc3.js
  js/indodax.js
  js/itbit.js
  js/latoken.js
  js/lykke.js
  js/novadax.js
  js/poloniex.js
  js/therock.js
  js/vcc.js
  js/woo.js
Labels: enhancement

#13716 fetchPosition docstrings
  js/aax.js
  js/bitget.js
  js/coinex.js
  js/coinflex.js
  js/delta.js
  js/deribit.js
  js/hitbtc3.js
  js/huobi.js
  js/mexc.js
  js/mexc3.js
  js/okcoin.js
  js/okx.js
  js/poloniex.js
  js/zb.js
Labels: enhancement

#13718 fetchMarketLeverageTiers docstrings
  js/bybit.js
  js/huobi.js
  js/kucoinfutures.js
  js/okx.js
Labels: enhancement

#13606 TICK_SIZE - eqonex
  js/eqonex.js
Labels: enhancement

#13612 ticksize - hitbtc3 updates
  js/hitbtc3.js
Labels: enhancement

#13678 TICK_SIZE - mexc3
  js/mexc3.js
Labels: enhancement

#13720 fetchOpenOrder docstrings
  js/bitfinex2.js
  js/bkex.js
  js/hitbtc.js
  js/hitbtc3.js
  js/hollaex.js
  js/poloniex.js
Labels: enhancement

#13722 fetchBorrowRates docstrings
  js/coinex.js
  js/digifinex.js
  js/ftx.js
  js/huobi.js
  js/okx.js
  js/zb.js
Labels: enhancement

#13731 lbank2: fix signing
  js/lbank2.js
Labels: bug

#13706 Bitfinex upgrade to v2 and detach v1
  js/bitfinex2.js
Labels: enhancement

#13734 remove comment
  js/ascendex.js
Labels: enhancement

#13739 fetchClosedOrder docstrings
  js/bitfinex2.js
  js/poloniex.js
  js/stex.js
Labels: enhancement

#13764 TICK_SIZE - bittrex
  js/bittrex.js
Labels: enhancement

#13760 blockchaincom and woo cancelOrders renamed to cancelAllOrders
  js/blockchaincom.js
  js/woo.js
Labels: bug

#13742 createDepositAddress docstrings
  js/bitfinex.js
  js/bitfinex2.js
  js/bitpanda.js
  js/bittrex.js
  js/buda.js
  js/coinbase.js
  js/coinbasepro.js
  js/coinex.js
  js/deribit.js
  js/gemini.js
  js/hitbtc.js
  js/kraken.js
  js/kucoin.js
  js/kucoinfutures.js
  js/ndax.js
  js/paymium.js
  js/poloniex.js
  js/stex.js
  js/upbit.js
  js/xena.js
  js/yobit.js
Labels: enhancement

#13737 fetchOrderBooks docstrings
  js/exmo.js
  js/hitbtc3.js
  js/hollaex.js
  js/oceanex.js
  js/poloniex.js
  js/tidex.js
  js/upbit.js
  js/yobit.js
Labels: enhancement

#13736 fetchAccounts docstrings
  js/aax.js
  js/ascendex.js
  js/cdax.js
  js/coinbase.js
  js/coinbasepro.js
  js/coinflex.js
  js/currencycom.js
  js/deribit.js
  js/huobi.js
  js/huobijp.js
  js/kucoin.js
  js/kucoinfutures.js
  js/luno.js
  js/mexc3.js
  js/ndax.js
  js/novadax.js
  js/okx.js
  js/woo.js
  js/xena.js
Labels: enhancement

#13744 fetchOrders docstrings
  js/aax.js
  js/bigone.js
  js/binance.js
  js/bitflyer.js
  js/bitmex.js
  js/bitopro.js
  js/bitvavo.js
  js/btcalpha.js
  js/btcbox.js
  js/btcmarkets.js
  js/btcturk.js
  js/buda.js
  js/bw.js
  js/bybit.js
  js/bytetrade.js
  js/cdax.js
  js/cex.js
  js/coinbasepro.js
  js/coinflex.js
  js/coinmate.js
  js/crex24.js
  js/cryptocom.js
  js/digifinex.js
  js/eqonex.js
  js/ftx.js
  js/hollaex.js
  js/huobi.js
  js/huobijp.js
  js/itbit.js
  js/latoken.js
  js/lbank.js
  js/lbank2.js
  js/liquid.js
  js/luno.js
  js/mercado.js
  js/mexc3.js
  js/ndax.js
  js/novadax.js
  js/oceanex.js
  js/phemex.js
  js/qtrade.js
  js/ripio.js
  js/therock.js
  js/wavesexchange.js
  js/wazirx.js
  js/woo.js
  js/zb.js
Labels: enhancement

#13564 TICK_SIZE - bitforex
  js/bitforex.js
Labels: enhancement

#13563 TICK_SIZE - bitflyer
  js/bitflyer.js
Labels: enhancement

#13568 TICK_SIZE - bitopro
  js/bitopro.js
Labels: enhancement

#13758 coinbase fetchMySells and fetchMyBuys docstrings
  js/coinbase.js
Labels: enhancement

#13575 TICK_SIZE - btcmarkets
  js/btcmarkets.js
Labels: enhancement

#13577 TICK_SIZE - btcturk
  js/btcturk.js
Labels: enhancement

#13576 TICK_SIZE - btctradeua
  js/btctradeua.js
Labels: enhancement

#13572 TICK_SIZE - bl3p
  js/bl3p.js
Labels: enhancement

#13571 TICK_SIZE - bkex
  js/bkex.js
Labels: enhancement

#13579 TICK_SIZE - bw
  js/bw.js
Labels: enhancement

#13759 cancelOrders docstrings
  js/bitget.js
  js/bitmex.js
  js/bitopro.js
  js/bitpanda.js
  js/bkex.js
  js/btcmarkets.js
  js/cdax.js
  js/coinflex.js
  js/crex24.js
  js/digifinex.js
  js/huobi.js
  js/huobijp.js
  js/mexc3.js
  js/oceanex.js
  js/okx.js
  js/timex.js
Labels: enhancement

#13754 fetchL3OrderBook docstrings
  js/blockchaincom.js
  js/kuna.js
Labels: enhancement

#13753 fetchDeposit docstrings
  js/bitmart.js
  js/blockchaincom.js
  js/exmo.js
  js/qtrade.js
  js/stex.js
Labels: enhancement

#13751 fetchCanceledOrders docstrings
  js/aax.js
  js/bitmart.js
  js/blockchaincom.js
  js/eqonex.js
  js/exmo.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
  js/upbit.js
  js/zb.js
Labels: enhancement

#13761 fetchTransfers docstrings
  js/aax.js
  js/binance.js
  js/coinex.js
  js/coinflex.js
  js/cryptocom.js
  js/deribit.js
  js/latoken.js
  js/mexc.js
  js/mexc3.js
  js/phemex.js
  js/qtrade.js
  js/woo.js
Labels: enhancement

#13755 huobi.fetchBorrowRatesPerSymbol docstring
  js/huobi.js
Labels: enhancement

#13596 TICK_SIZE - cryptocom
  js/cryptocom.js
Labels: enhancement

#13756 TICK_SIZE - bitso updates
  js/bitso.js
Labels: enhancement

#13602 TICK_SIZE - delta
  js/delta.js
Labels: enhancement

#13597 TICK_SIZE - currencycom
  js/currencycom.js
Labels: enhancement

#13740 fetchDepositAddresses docstrings
  js/coinone.js
  js/hollaex.js
  js/paymium.js
  js/probit.js
  js/upbit.js
Labels: enhancement

#13762 fetchDepositAddressesByNetwork docstrings
  js/bybit.js
  js/cryptocom.js
  js/huobi.js
  js/mexc.js
  js/mexc3.js
  js/okx.js
Labels: enhancement

#13595 TICK_SIZE - crex24
  js/crex24.js
Labels: enhancement

#13594 TICK_SIZE - coinspot
  js/coinspot.js
Labels: enhancement

#13773 TICK_SIZE - coinone
  js/coinone.js
Labels: enhancement

#13593 TICK_SIZE - coinmate
  js/coinmate.js
Labels: enhancement

#13589 TICK_SIZE - coinex
  js/coinex.js
Labels: enhancement

#13588 TICK_SIZE - coincheck
  js/coincheck.js
Labels: enhancement

#13587 TICK_SIZE - coinbase
  js/coinbase.js
Labels: enhancement

#13569 TICK_SIZE - bitpanda
  js/bitpanda.js
Labels: enhancement

#13570 TICK_SIZE - bitstamp
  js/bitstamp.js
  js/bitstamp1.js
Labels: enhancement

#13558 TICK_SIZE - bigone
  js/bigone.js
Labels: enhancement

#13556 TICK_SIZE - bibox
  js/bibox.js
Labels: enhancement

#13604 TICK_SIZE - digifinex
  js/digifinex.js
Labels: enhancement

#13578 TICK_SIZE - buda
  js/buda.js
Labels: enhancement

#13574 TICK_SIZE - btcbox
  js/btcbox.js
Labels: enhancement

#13573 TICK_SIZE - btcalpha
  js/btcalpha.js
Labels: enhancement

#13565 TICK_SIZE - bitget
  js/bitget.js
Labels: enhancement

#13680 Add `parseTradingFee` on FTX
  build/transpile.js
  js/ftx.js
Labels: enhancement

#13561 TICK_SIZE - bitbank
  js/bitbank.js
Labels: enhancement

#13774 binance missing the new keyword on throwing exceptions
  js/binance.js
Labels: bug

#13765 @see transpile to python
  build/transpile.js
Labels: enhancement

#13741 Fetch borrow rate histories docs
  js/ftx.js
  js/okx.js
Labels: enhancement

#13729 Bitvavo: adding stop-orders
  js/bitvavo.js
Labels: enhancement

#13619 TICK_SIZE - idex
  js/idex.js
Labels: enhancement

#13560 TICK_SIZE - bit2c
  js/bit2c.js
Labels: enhancement
