Repository ccxt/ccxt, pull requests merged in 2022-07, with the labels that each got.

#14140 bitfinex2: unify market
  js/bitfinex2.js
Labels: enhancement

#14135 bigone: use market['symbol']
  js/bigone.js
Labels: enhancement

#14184 therock: unify market
  js/therock.js
Labels: enhancement

#14124 hitbtc: unify market
  js/hitbtc.js
Labels: enhancement

#14126 kucoin: unify market
  js/kucoin.js
Labels: enhancement

#14155 btcturk: use market['symbol']
  js/btcturk.js
Labels: enhancement

#14123 Bitget :: fix php request
  js/bitget.js
Labels: bug

#14164 delta: unify market
  js/delta.js
Labels: enhancement

#14128 ripio: unify market
  js/ripio.js
Labels: enhancement

#14129 poloniex: unify market
  js/poloniex.js
Labels: enhancement

#14125 hollaex: unify market
  js/hollaex.js
Labels: enhancement

#14111 ascendex.fetchTime implemented
  js/ascendex.js
Labels: enhancement

#12562 Bibox v3
  js/bibox.js
Labels: enhancement

#14132 okx.fetchDeposit
  js/okx.js
Labels: enhancement

#14191 Zonda :: fix api call
  js/zonda.js
Labels: bug

#14186 zaif: unify market
  js/zaif.js
Labels: enhancement

#14181 novadax: unify market
  js/novadax.js
Labels: enhancement

#14180 mercado: unify market
  js/mercado.js
Labels: enhancement

#14178 kuna: unify market
  js/kuna.js
Labels: enhancement

#14169 itbit: unify market
  js/itbit.js
Labels: enhancement

#14168 eqonex: use market['symbol']
  js/eqonex.js
Labels: enhancement

#14131 okx.fetchWithdrawal
  js/okx.js
Labels: enhancement

#14170 indodax: unify market
  js/indodax.js
Labels: enhancement

#14182 xena: unify market
  js/xena.js
Labels: enhancement

#14157 cex: unify market
  js/cex.js
Labels: enhancement

#14166 deribit: use market['symbol']
  js/deribit.js
Labels: enhancement

#14163 coinspot: unify market
  js/coinspot.js
Labels: enhancement

#14147 blockchaincom: unify market
  js/blockchaincom.js
Labels: enhancement

#14145 bkex: use market['symbol']
  js/bkex.js
Labels: enhancement

#14144 bitpanda: unify market
  js/bitpanda.js
Labels: enhancement

#14171 independentreserve: use market['symbol']
  js/independentreserve.js
Labels: enhancement

#14167 digifinex: use market['symbol']
  js/digifinex.js
Labels: enhancement

#14161 crex24: use market['symbol']
  js/crex24.js
Labels: enhancement

#14159 coinfalcon: unify market
  js/coinfalcon.js
Labels: enhancement

#14156 coincheck: unify market
  js/coincheck.js
Labels: enhancement

#14154 buda: unify market
  js/buda.js
Labels: enhancement

#14153 btctradeua: use market['symbol']
  js/btctradeua.js
Labels: enhancement

#14149 btcbox: use market['symbol']
  js/btcbox.js
Labels: enhancement

#14148 btcalpha: unify market
  js/btcalpha.js
Labels: enhancement

#14146 bl3p: use market['symbol']
  js/bl3p.js
Labels: enhancement

#14139 bitbank: unify market
  js/bitbank.js
Labels: enhancement

#14142 bitforex: unify market
  js/bitforex.js
Labels: enhancement

#14150 btcex: use market['symbol']
  js/btcex.js
Labels: enhancement

#14143 bitso: unify market
  js/bitso.js
Labels: enhancement

#14172 liquid: unify market
  js/liquid.js
Labels: enhancement

#14158 cdax: use market['symbol']
  js/cdax.js
Labels: enhancement

#14152 bw: use market['symbol']
  js/bw.js
Labels: enhancement

#14138 bitbns: use market['symbol']
  js/bitbns.js
Labels: enhancement

#14137 bit2c: unify market
  js/bit2c.js
Labels: enhancement

#14187 probit: use market['symbol']
  js/probit.js
Labels: enhancement

#14185 zonda: unify market
  js/zonda.js
Labels: enhancement

#14179 kucoinfutures: unify market
  js/kucoinfutures.js
Labels: enhancement

#14174 luno: unify market
  js/luno.js
Labels: enhancement

#14173 lykke: unify market
  js/lykke.js
Labels: enhancement

#14151 bytetrade: use market['symbol']
  js/bytetrade.js
Labels: enhancement

#14162 coinone: unify market
  js/coinone.js
Labels: enhancement

#14141 bitflyer: unify market
  js/bitflyer.js
Labels: enhancement

#14136 bibox: use market['symbol']
  js/bibox.js
Labels: enhancement

#14189 paymium: unify market
  js/paymium.js
Labels: enhancement

#14134 setMargin docstrings
  js/aax.js
  js/phemex.js
Labels: enhancement

#14105 huobi - precision (TICK_SIZE) shorten
  js/huobi.js
Labels: enhancement

#13735 ZB borrowMargin
  js/zb.js
Labels: enhancement

#14175 lbank2: use market['symbol']
  js/lbank2.js
Labels: enhancement

#14177 latoken: use market['symbol']
  js/latoken.js
Labels: enhancement

#14165 exmo: use market['symbol']
  js/exmo.js
Labels: enhancement

#14183 tidebit: unify market
  js/tidebit.js
Labels: enhancement

#14176 lbank: unify market
  js/lbank.js
Labels: enhancement

#14160 coinmate: unify market
  js/coinmate.js
Labels: enhancement

#14044 Woox repayMargin
  js/woo.js
Labels: enhancement

#13992 delta: add fetch position / margin mode
  js/delta.js
Labels: enhancement

#14194 fetchMyBuys and fetchMySells removed from has
  js/aax.js
  js/binance.js
  js/huobi.js
  js/okx.js
Labels: enhancement

#13998 gate: add fetch position / margin mode
  js/gate.js
Labels: enhancement

#14043 Gate borrowMargin, repayMargin
  js/gate.js
Labels: enhancement

#14056 mexc3: add fetchPositionMode & fetchMarginMode & setPositionMode
  js/mexc3.js
Labels: enhancement

#14213 binance: add new api endpoints
  js/binance.js
Labels: enhancement

#14215 Bitmex :: fix balance parsing
  js/bitmex.js
Labels: bug

#14214 ftx: add support ticket api endpoints
  js/ftx.js
Labels: enhancement

#14217 woo: patch fetchMarkets
  js/woo.js
Labels: bug

#14133 okx.has false methods
  js/okx.js
Labels: enhancement

#14097 BITBNS accept exchange code 204 - empty response as valid
  js/bitbns.js
  python/ccxt/bitbns.py
Labels: bug

#14076 zb: add setPositionMode
  js/zb.js
Labels: enhancement

#14218 bybit: add new api endpoints
  js/bybit.js
Labels: enhancement

#14221 Coinfalcon :: fix typo
  js/coinfalcon.js
Labels: bug

#14225 Xena :: fix timestamp
  js/xena.js
Labels: bug

#14224 Indodax :: fix parseTransaction
  js/indodax.js
Labels: bug

#14230 test.marginModification :: fix
  js/test/Exchange/test.marginModification.js
Labels: bug

#14229 Woo :: fix parseTransactionStatus
  js/woo.js
Labels: bug

#14228 Latoken :: fix parseTransfer
  js/latoken.js
Labels: bug

#14232 Kucoinfutures :: fix addMargin
  js/kucoinfutures.js
Labels: bug

#14240 Okx: unify marginMode in createOrder
  js/okx.js
Labels: enhancement

#14193 bibox v4 endpoints work
  js/bibox.js
Labels: bug

#14243 `loadmarkets` removal
  js/base/Exchange.js
  js/bkex.js
  js/coinflex.js
  js/mexc3.js
  js/test/Exchange/test.loadMarkets.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#14238 Manual: borrowMargin, repayMargin
  js/binance.js
  js/coinex.js
  js/gate.js
  js/huobi.js
  js/okx.js
  js/woo.js
  js/zb.js
  wiki/Manual.md
Labels: enhancement

#14254 ftx - unrealizedPnl fix
  js/ftx.js
Labels: bug

#14260 Tidex :: fix missing argument
  js/tidex.js
Labels: bug

#14272 ftx - remove `recentPnl`
  js/ftx.js
Labels: bug

#14285 Okx :: fix margin check
  js/okx.js
Labels: bug

#14283 Ftx :: fix parsePosition
  js/ftx.js
Labels: bug

#14301 Binance :: fix parseMarketLeverageTiers
  js/binance.js
Labels: bug

#14298 add ltc for kucoin
  js/kucoin.js
Labels: enhancement

#14302 Hollaex :: fix fetchOrderBooks
  js/hollaex.js
Labels: bug

#14300 Woo :: fix parseLedgerEntry
  js/woo.js
Labels: bug

#14299 Bybit :: fee fix
  js/bybit.js
Labels: bug

#14306 Deribit :: fix fetchStatus
  js/deribit.js
Labels: bug

#14305 Bitmart :: fix parseTicker
  js/bitmart.js
Labels: bug

#14309 Mexc :: fix parseMarginModification
  js/mexc.js
Labels: bug

#14310 Bytetrade :: fix safeString call
  js/bytetrade.js
Labels: bug

#14308 Independentreserver :: fix parseOrder
  js/independentreserve.js
Labels: bug

#14311 Gate :: fix fetchBalance
  js/gate.js
Labels: bug

#14307 Latoken :: fix handleErrors
  js/latoken.js
Labels: bug

#14313 Btcalpha :: fix timestamp
  js/btcalpha.js
Labels: bug

#14314 zb fetchOpenOrders fix
  js/zb.js
Labels: bug

#14278 Bitmart: borrowMargin, repayMargin
  js/bitmart.js
Labels: enhancement

#14317 bittrex - fix milliseconds precision
  js/bittrex.js
Labels: bug

#14277 Okx: fetchMarketLeverageTiers unify marginMode
  js/okx.js
Labels: enhancement

#14323 zb fetchClosedOrders fix for spot
  js/zb.js
Labels: bug

#14107 Crypto.com Margin
  js/cryptocom.js
Labels: enhancement

#14332 Whitebit :: fix handleErrors
  js/whitebit.js
Labels: bug

#14341 Update gate orderStatus for for futures trigger orders
  js/gate.js
Labels: enhancement

#14339 Binance :: fix timestamp
  js/binance.js
Labels: bug

#14338 Bitrue :: fix parseBalance
  js/bitrue.js
Labels: bug

#14334 Zb :: fix fetchCanceledOrders
  js/zb.js
Labels: bug

#14329 sort-swap-markets-by-hourly-price-change uses latest unfinished candle instead of penultimate candle
  examples/js/sort-swap-markets-by-hourly-price-change.js
Labels: enhancement

#14345 Bitmart: fetchBorrowRate
  js/bitmart.js
Labels: enhancement

#14353 Bybit :: fix positions filtering
  js/bybit.js
Labels: bug

#14351 Huobi :: fix market order parsing
  js/huobi.js
Labels: bug

#14364 probit fetchDepositAddress networks
  js/probit.js
Labels: enhancement

#14363 Btcturk :: fix parseOrder
  js/btcturk.js
Labels: bug

#14362 FundingFee(s) - > TransactionFee(s)
  js/bitstamp.js
  js/btcex.js
  js/buda.js
  js/exmo.js
  js/lbank2.js
Labels: bug

#14354 Bybit :: fix stop orders
  js/bybit.js
Labels: bug

#14370 Bitmart :: fix orderId type
  js/bitmart.js
Labels: bug

#14391 binance: fix data not found with symbols ccxt/ccxt#14384
  js/binance.js
Labels: bug

#14403 ftx: add api endpoints for twap ccxt/ccxt#14402
  js/ftx.js
Labels: enhancement

#14330 nest urls
  js/bibox.js
  js/bitflyer.js
  js/bitopro.js
  js/bitstamp1.js
  js/btcalpha.js
  js/btcex.js
  js/buda.js
  js/cex.js
  js/coincheck.js
  js/coinmate.js
  js/crex24.js
  js/itbit.js
  js/lbank.js
  js/liquid.js
  js/oceanex.js
  js/qtrade.js
  js/tidebit.js
  js/wazirx.js
Labels: enhancement

#14394 huobi: fix ccxt/ccxt#14387
  js/huobi.js
Labels: bug

#14379 bybit - fix missing loadmarkets
  js/bybit.js
Labels: bug

#14414 spelling error in coinbase.py
  python/ccxt/async_support/coinbase.py
Labels: bug

#14408 Bybit :: fix ticker volume
  js/bybit.js
Labels: bug

#14418 binance: fix wrong signature when calling staking ccxt/ccxt#14417
  js/binance.js
Labels: bug

#14427 Woo :: fix parseOrder
  js/woo.js
Labels: bug

#14434 bybit - add error codes
  js/bybit.js
Labels: bug

#14375 Bitmart: Margin
  js/bitmart.js
Labels: important

#14389 binance: add get portfolio collateralRate
  js/binance.js
Labels: enhancement

#14445 Gate :: fix signing
  js/gate.js
Labels: bug

#14447 Bitforex - fetch_closed_orders/fetch_open_orders symbol is required
  js/bitforex.js
  python/ccxt/bitforex.py
Labels: bug

#14415 Bybit: fetchBorrowInterest
  js/bybit.js
Labels: enhancement

#14450 ascendex: update symbols
  js/ascendex.js
Labels: enhancement

#14452 bitget: update symbols
  js/bitget.js
Labels: enhancement

#14453 bybit: update symbols
  js/bybit.js
Labels: enhancement

#14448 Kucoin: fetchBorrowRateHistory
  js/kucoin.js
Labels: enhancement
