Repository ccxt/ccxt, pull requests merged in 2022-09, with the labels that each got.

#14840 binance - fix isolated transfer
  js/binance.js
Labels: bug, critical

#14859 exmo Math -> Precise
  js/exmo.js
Labels: enhancement

#14874 woo.createOrder stringMul
  js/woo.js
Labels: enhancement

#14862 stex.parseOrder Math -> Precise
  js/stex.js
Labels: enhancement

#14837 Remove redundant slash
  examples/js/hitbtc2-withdraw.js
  examples/js/instantiate-all-at-once.js
  examples/js/live-orderbook.js
  js/okcoin.js
  js/woo.js
Labels: enhancement

#14850 huobi: add v3 endpoints
  js/huobi.js
Labels: enhancement

#14921 tokocrypto - jsdoc, endpoint and order updates
  js/tokocrypto.js
Labels: bug

#14937 itbit.describe fees uses parseNumber
  js/itbit.js
Labels: enhancement

#14936 zaif.describe fess uses parseNumber
  js/zaif.js
Labels: enhancement

#14932 mexc.describe["fees"] parseNumber
  js/mexc.js
Labels: enhancement

#14934 hitbtc.describe fees use parseNumber
  js/hitbtc.js
Labels: enhancement

#14941 huobi: fix parseDepositAddress ccxt/ccxt#14911
  js/huobi.js
Labels: bug

#14940 ftx: add historical_balances endpoints
  js/ftx.js
Labels: enhancement

#14928 kucoin.parseTransaction string math
  js/kucoin.js
Labels: enhancement

#14935 coinmate.describe uses parseNumber
  js/coinmate.js
Labels: enhancement

#14933 btctradeua fees use parseNumber
  js/btctradeua.js
Labels: enhancement

#14914 btcmarkets.calculateFee string math
  js/btcmarkets.js
Labels: enhancement

#14861 Ripio decimal
  js/ripio.js
Labels: enhancement

#14950 bybit: add apis
  js/bybit.js
Labels: enhancement

#14952 fix: coincheck fetchMyTrades response
  js/coincheck.js
Labels: bug

#14986 Deribit :: handle combo markets
  js/deribit.js
Labels: bug

#14953 Coinex :: fix setMarginMode
  js/coinex.js
Labels: bug

#14944 Bitstamp :: fix parseTrade for delisted markets
  js/bitstamp.js
Labels: bug

#14992 coinbase.fetchTicker swap bid and ask. fixes: #14988
  js/coinbase.js
Labels: bug

#14812 tests - removal of `fetchBalance` log
  js/test/Exchange/test.balance.js
  js/test/Exchange/test.fetchBalance.js
  js/test/Exchange/test.fetchTransactionFees.js
  js/test/test.js
Labels: bug

#14970 ripio.describe fees parseNumber
  js/ripio.js
Labels: enhancement

#14969 kraken.describe fees parse number
  js/kraken.js
Labels: enhancement

#14968 independentreserve.describe fees parseNumber
  js/independentreserve.js
Labels: enhancement

#14967 ndax.describe fees parseNumber
  js/ndax.js
Labels: enhancement

#14963 mexc3 fetchMarkets enhancement
  js/mexc3.js
Labels: enhancement

#14955 Fix rounding issue in Luno
  js/luno.js
Labels: bug

#15011 bybit: add get open interest limit info
  js/bybit.js
Labels: enhancement

#15013 base - code to currency fixes
  js/aax.js
  js/bigone.js
  js/bitso.js
  js/bittrex.js
  js/blockchaincom.js
  js/btcalpha.js
  js/bw.js
  js/lbank2.js
  js/mexc.js
  js/mexc3.js
  js/stex.js
Labels: bug

#15009 binance: add crypto loan endpoints
  js/binance.js
Labels: enhancement

#14926 zonda.fetchLedgerEntry string math, clean up
  js/zonda.js
Labels: enhancement

#13328 `handleOptionAndParams` in base
  js/base/Exchange.js
Labels: enhancement

#15040 exchanges - fix `code` instead of `currency`
  js/bitget.js
  js/buda.js
  js/gate.js
  js/hitbtc3.js
  js/novadax.js
  js/wavesexchange.js
Labels: important

#15039 poloniex: add accounts/activity
  js/poloniex.js
Labels: enhancement

#15036 bitget: add new apis for Trade
  js/bitget.js
Labels: enhancement

#15035 bitget: holdSide is not required when setLeverage
  js/bitget.js
Labels: bug

#15034 mexc3: add rebate apis
  js/mexc3.js
Labels: enhancement

#14971 btcbox.describe fees parseNumber
  js/bitget.js
  js/btcbox.js
Labels: enhancement

#15043 Bitget :: fix cancelOrders endpoint
  js/bitget.js
Labels: bug

#15051 coinone: pass market when create order ccxt/ccxt#15048
  js/coinone.js
Labels: bug

#15030 lbank2.fetchPublicTransactionFees parse number
  js/lbank2.js
Labels: bug

#15065 Bitget :: fix cancelOrders request
  js/bitget.js
Labels: bug

#15047 aax: update links
  js/aax.js
Labels: enhancement

#15006 Kraken fetchMarkets string math
  js/kraken.js
Labels: enhancement

#15076 Bitget: add Get ApiKey Info api
  js/bitget.js
Labels: enhancement

#15074 bybit: update function name ccxt/ccxt#15073
  js/bybit.js
Labels: bug

#12173 tidex2: update tidex public api for v2
  js/tidex2.js
Labels: new exchange

#11920 New exchange - krakenfutures
  js/krakenfutures.js
Labels: new exchange

#11825 New exchange - Bitazza
  ccxt.js
  js/bitazza.js
Labels: new exchange

#11808 Exchange :: BTSE
  js/btse.js
Labels: new exchange

#11697 Graviex exchange
  js/graviex.js
Labels: new exchange

#10963 Coinsbit
  js/coinsbit.js
  js/coinsbitin.js
Labels: new exchange

#15078 huobi - inArray
  js/huobi.js
Labels: bug

#15082 ftx - missing ID in positions
  js/ftx.js
Labels: important

#15094 bytetrade - orderbook timestamp
  js/bytetrade.js
Labels: bug

#15095 whitebit - ts
  js/lykke.js
  js/whitebit.js
Labels: bug

#15089 okx: add api endpoints
  js/okx.js
Labels: enhancement

#15090 mexc3: add enhanced batch order
  js/mexc3.js
Labels: enhancement

#15100 Poloniex :: fetchDeposits/withdrawals
  js/poloniex.js
Labels: bug

#15060 types: add position related function
  ccxt.d.ts
  js/base/Exchange.js
Labels: enhancement

#14582 base - undefined string in findBroadlyMatchedKey exception
  js/base/Exchange.js
Labels: bug

#15111 bybit - omit base_price from params fix #15070
  js/bybit.js
Labels: bug

#15117 bybit: add spot v3 api endpoints
  js/bybit.js
Labels: enhancement

#15120 huobi error mapping
  js/huobi.js
Labels: enhancement

#15151 Bybit order link id
  js/bybit.js
Labels: enhancement

#15149 binance.fetchMarkets: removed duplicate code
  js/binance.js
Labels: bug, enhancement

#15135 Btcturk fetchOHLCV new endpont
  js/btcturk.js
Labels: enhancement

#15114 okcoin added main to account types
  js/okcoin.js
Labels: enhancement

#15028 exchange.calculateFee string math
  js/base/Exchange.js
Labels: enhancement

#14904 Bl3p precise
  js/bl3p.js
Labels: enhancement

#15020 coinbase.parseLedgerEntry string math
  js/coinbase.js
Labels: enhancement

#15019 Bitstamp fetchOrder string math
  js/bitstamp.js
Labels: enhancement
