Repository ccxt/ccxt, pull requests merged in 2022-08, with the labels that each got.

#14541 coinbasepro - add endpoint for fetching conversion by id
  js/coinbasepro.js
Labels: enhancement

#14525 gate - fix fetchMytrades null fees
  js/gate.js
Labels: bug

#14542 bithumb - fix comma number
  js/bithumb.js
Labels: bug

#14521 Binance cancel all orders - isolated margin
  js/binance.js
Labels: enhancement

#14583 whitebit: stop orders (clean)
  js/whitebit.js
Labels: enhancement

#14485 bitmex - fetch_transactions return all transactions + fix fee decimal places
  js/bitmex.js
Labels: bug

#14535 base - handleSubTypeAndParams
  js/base/Exchange.js
Labels: enhancement

#14281 bibox - v4 private endpoints fix
  js/bibox.js
Labels: bug

#14220 bitcoincom - `alias:true`
  js/bitcoincom.js
Labels: enhancement

#14480 binance: add more portfolio margin apis
  js/binance.js
Labels: enhancement

#14511 cryptocom: update safeNetwork
  js/cryptocom.js
Labels: enhancement

#14396 Binance isolated fetch order
  js/binance.js
Labels: enhancement

#14602 gemini - fix nonce error
  js/gemini.js
Labels: bug

#14601 Huobi :: small improvements
  js/huobi.js
Labels: enhancement

#14606 gate: fix tag error
  js/gate.js
Labels: bug

#14399 Binance fetch orders - isolated marginMode
  js/binance.js
Labels: enhancement

#14397 Binance cancel order isolated
  js/binance.js
Labels: enhancement

#14395 Binance fetchOpenOrders isolated
  js/binance.js
Labels: enhancement

#14255 base - `undefined` for `createMarketOrder` price
  js/base/Exchange.js
Labels: bug

#14390 binance.createOrder, can specify cross or isolated for marginMode
  js/binance.js
Labels: enhancement

#14612 gate: fix ccxt/ccxt#14611
  js/gate.js
Labels: bug

#14620 gemini - small fix when to throw error message
  js/gemini.js
Labels: bug

#14604 huobipro exchange has name "Huobi Pro". fixes:14570
  js/huobipro.js
Labels: bug

#14239 Bibox v4 fetch ohlcv
  js/bibox.js
Labels: enhancement

#14398 Binance fetch balance update
  js/binance.js
Labels: enhancement

#14644 Correctly parse tag for FTX withdrawals
  js/ftx.js
Labels: enhancement

#14645 Update poloniex.php
  js/poloniex.js
Labels: bug

#14609 oks: add earn module
  js/okx.js
Labels: enhancement

#14588 Bybit borrowMargin and repayMargin
  js/bybit.js
Labels: enhancement

#14624 Gemini :: fix clientOrderId type
  js/gemini.js
Labels: bug

#14623 Fix includes() misusage
  js/latoken.js
  js/okx.js
Labels: bug

#14621 allow users to use marketIds as symbols in missing functions
  js/aax.js
  js/ascendex.js
  js/bibox.js
  js/bigone.js
  js/binance.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bithumb.js
  js/bitmart.js
  js/bitmex.js
  js/bitpanda.js
  js/bittrex.js
  js/bw.js
  js/bybit.js
  js/cdax.js
  js/cex.js
  js/coinbase.js
  js/coinbasepro.js
  js/coinex.js
  js/coinfalcon.js
  js/coinone.js
  js/delta.js
  js/deribit.js
  js/digifinex.js
  js/exmo.js
  js/gate.js
  js/hitbtc.js
  js/hitbtc3.js
  js/hollaex.js
  js/huobi.js
  js/huobijp.js
  js/kraken.js
  js/kucoin.js
  js/kuna.js
  js/lbank.js
  js/liquid.js
  js/luno.js
  js/novadax.js
  js/oceanex.js
  js/okcoin.js
  js/okx.js
  js/phemex.js
  js/poloniex.js
  js/qtrade.js
  js/ripio.js
  js/therock.js
  js/tidebit.js
  js/tidex.js
  js/upbit.js
  js/whitebit.js
  js/woo.js
  js/xena.js
  js/yobit.js
  js/zb.js
  js/zonda.js
Labels: enhancement

#14599 Update and sort FTX withdrawal method mapping
  js/ftx.js
Labels: enhancement

#14665 Order not found message
  js/bitstamp.js
Labels: bug

#14638 base/Exchange.handleMarginModeAndParams defaultMarginMode omitted, docstring definition
  js/base/Exchange.js
Labels: enhancement

#14671 Huobi margin fetch balance
  js/huobi.js
Labels: enhancement

#14677 poloniex parseOrder fix
  js/poloniex.js
Labels: bug

#14680 examples/py/fetch_longer_ohlcv_through_multiple_calls_and_save_to_csv.py
  examples/py/fetch_longer_ohlcv_through_multiple_calls_and_save_to_csv.py
Labels: enhancement

#14622 exchange - filterBySymbol, filterBySymbolSinceLimit, marketSymbols
  js/base/Exchange.js
Labels: enhancement

#14687 Okx :: fix fetchLeverage
  js/okx.js
Labels: bug

#14702 kucoin: add network when fetch transaction fee
  js/kucoin.js
Labels: enhancement

#14689 base - fetchTrades signature
  js/base/Exchange.js
Labels: bug

#14655 Remove undo file
  .gitignore
  js/.idex.js.un~
Labels: enhancement

#14700 Gemini :: fix nonce
  js/gemini.js
Labels: bug

#14696 mexc added endpoints
  js/mexc3.js
Labels: enhancement

#14711 tokocrypto.createOrder - brokerId = this.safeString (broker, marketType)
  js/timex.js
  js/tokocrypto.js
Labels: bug

#14708 poloniex: patch order status and rename fetchOpenOrder to fetchOrder
  js/poloniex.js
Labels: bug

#14723 Tokocrypto :: fix parseTrade
  js/tokocrypto.js
Labels: bug

#14728 Mexc3 :: fix cancelOrders/cancelAllOrders
  js/mexc3.js
Labels: bug

#14660 exchange.parseAccount changed to typeToAccount
  js/base/Exchange.js
  js/gate.js
  js/kucoin.js
Labels: enhancement

#14643 binance: update trades limit for dapi/fapi
  js/binance.js
Labels: enhancement

#14716 kraken Math.whatever -> Precise
  js/kraken.js
Labels: enhancement

#14735 Bitrue :: add fetchOHLCV
  js/bitrue.js
Labels: enhancement

#14731 Poloniex :: fix precision
  js/poloniex.js
Labels: bug, important

#14724 bitstamp.parseTransaction Math.whatever -> Precise
  js/bitstamp.js
Labels: enhancement

#14710 bitfinex.parseTransactions decimal precision
  js/bitfinex.js
Labels: enhancement

#14666 kucoin - fix ledger string
  js/kucoin.js
Labels: bug

#14753 bittrex: add more v3 apis
  js/bittrex.js
Labels: enhancement

#14703 OKX: Hongkong time
  js/okx.js
Labels: enhancement

#14764 Fix `margin/borrow/repaid` endpoint for kucoin
  js/kucoin.js
Labels: bug

#14768 woo: update ratelimit for get positions / get position
  js/woo.js
Labels: enhancement

#14688 kraken - ratelimits
  js/kraken.js
Labels: enhancement

#14774 Mexc3 :: fix fetchMyTrades
  js/mexc3.js
Labels: bug

#14258 phemex - fix order-types comment
  js/phemex.js
Labels: bug

#14785 ftx.has["createPostOnlyOrder"] added. fixes:#14742
  js/ftx.js
Labels: bug

#14715 huobi Math.whatever -> Precise
  js/huobi.js
Labels: enhancement

#14781 Hitbtc3 :: fix fee key
  js/hitbtc3.js
Labels: bug

#14792 mexc3: add new api endpoints
  js/mexc3.js
Labels: enhancement

#14796 [FIX] kraken.py: fixing amount variable type convertion
  js/kraken.js
Labels: bug

#14714 okx fetchCurrencies Math.whatever -> Precise
  js/okx.js
Labels: enhancement

#14805 bybit: add derivatives v3 apis
  js/bybit.js
Labels: enhancement

#14803 bybit.parseOrderStaus added PartiallyFilled: "open"
  js/bybit.js
Labels: bug

#14712 bitfinex2 replace Math.whatever with Precise
  js/bitfinex2.js
Labels: enhancement

#14795 bitmex describe updates
  js/bitmex.js
Labels: enhancement

#14640 php 5.5+
  README.md
  composer.json
  js/base/functions/generic.js
  php/Exchange.php
  python/ccxt/base/exchange.py
  wiki/Install.md
Labels: bug

#14818 Binance :: fix fetchMyTrades
  js/binance.js
Labels: bug

#13918 Exchange :: Alpaca
  js/alpaca.js
Labels: new exchange

#10625 Adds Alpaca Crypto Exchange
  js/alpaca.js
Labels: new exchange

#14827 ascendex - fix capitalize
  js/ascendex.js
Labels: bug

#14822 Tests :: read api keys from environment
  js/test/test.js
Labels: enhancement

#14216 Bibox v4 markets
  js/bibox.js
Labels: enhancement

#14519 Binance transfer isolated margin
  js/binance.js
Labels: enhancement

#14546 base - throttler capacity message
  js/base/functions/throttle.js
  php/async/Throttle.php
  python/ccxt/async_support/base/throttler.py
Labels: bug

#14830 poloniex: fix ccxt/ccxt#14829
  js/poloniex.js
Labels: bug

#14834 Bitmex :: protect convertValue
  js/bitmex.js
Labels: bug
