Repository ccxt/ccxt, pull requests merged in 2022-11, with the labels that each got.

#15493 upbit - unify symbol
  js/pro/upbit.js
Labels: bug, WS

#15491 phemex - unify symbol
  js/pro/phemex.js
Labels: bug, WS

#15495 zb - unify symbol
  js/pro/zb.js
Labels: bug, WS

#15490 okx - unify symbol
  js/pro/okx.js
Labels: bug, WS

#15489 okcoin - unify symbol
  js/pro/okcoin.js
Labels: bug, WS

#15515 cryptocom - fix watchOrderBook limit issue and marketId clash
  js/cryptocom.js
  js/pro/cryptocom.js
Labels: bug

#15518 Helpers :: add checkRequiredArgument methods
  js/base/Exchange.js
Labels: enhancement

#15492 ripio - unify symbol
  js/pro/ripio.js
Labels: bug, WS

#15434 base - fix fee calc
  js/base/Exchange.js
Labels: important

#15391 woo: add v3 apis
  js/woo.js
Labels: enhancement

#15525 base & okx - correct funding-rate
  js/okx.js
  js/test/Exchange/test.fetchFundingRateHistory.js
Labels: enhancement

#15529 Cryptocom :: fix fetchTicker
  js/cryptocom.js
Labels: bug

#15538 base - calculatefee warning
  js/base/Exchange.js
Labels: enhancement

#15536 kucoin.fetchBalance isolated margin, marginMode
  js/kucoin.js
Labels: bug, enhancement

#15530 created gateio-create-batch-order.js example
  examples/js/gateio-create-batch-order.js
Labels: enhancement

#15446 examples - php Websocket / watch method
  examples/ccxt.pro/php/watch-multiple-methods-multiple-exchanges.php
  examples/php/cache-exchange-instance-reuse.php
Labels: enhancement

#15542 Kucoin :: fix sandbox markets loading
  js/kucoin.js
Labels: bug

#15476 docstring - watchOHLCV
  js/pro/aax.js
  js/pro/ascendex.js
  js/pro/binance.js
  js/pro/bitmart.js
  js/pro/bitmex.js
  js/pro/bittrex.js
  js/pro/bitvavo.js
  js/pro/bybit.js
  js/pro/cryptocom.js
  js/pro/currencycom.js
  js/pro/gate.js
  js/pro/hitbtc.js
  js/pro/huobi.js
  js/pro/huobijp.js
  js/pro/idex.js
  js/pro/kraken.js
  js/pro/kucoin.js
  js/pro/mexc.js
  js/pro/ndax.js
  js/pro/okcoin.js
  js/pro/okx.js
  js/pro/phemex.js
Labels: enhancement, WS

#15554 base - calculate fee
  js/base/Exchange.js
Labels: bug, critical

#15562 mexc3: update error
  js/mexc3.js
Labels: enhancement

#15557 kraken - fix average price - issue #15543
  js/pro/kraken.js
Labels: bug, WS

#15571 okx.fetchOHLCV defaults to UTC instead of HK time
  js/okx.js
Labels: bug

#15553 lbank -fix trade (from `skipped` list)
  js/lbank.js
  keys.json
Labels: bug

#15556 Bitget demo and future markets
  js/bitget.js
Labels: enhancement

#15552 Mercado - fix ohlcv ts (from `skipped` list)
  js/mercado.js
  keys.json
Labels: bug

#15548 bitget - fix timeframes (from `skipped` list)
  js/bitget.js
  keys.json
Labels: bug

#15539 tests - fix funding rate history
  js/test/Exchange/test.fetchFundingRateHistory.js
Labels: bug

#15572 ftx.fetchOHLCV since has a default value if not assigned
  js/ftx.js
Labels: bug

#15584 Add binance endpoints 1107
  js/binance.js
Labels: enhancement

#15551 Luno- fix args (from `skipped` list)
  js/luno.js
  keys.json
Labels: bug

#15550 Btcalpha - fix ts & ob (from `skipped` list)
  js/btcalpha.js
  keys.json
Labels: bug

#15381 Bibox fetch withdrawls and fetch deposits
  js/bibox.js
Labels: enhancement

#15574 mexc3 fetchTransactionFee and fetchTransactionFees
  js/mexc3.js
Labels: enhancement

#15588 bibox commonCurrencies converts BUSDT -> USDT instead of the other way around
  js/bibox.js
Labels: bug

#15590 btcalpha - fix orderbook
  js/btcalpha.js
  js/test/Exchange/test.orderbook.js
Labels: bug

#15545 remove `skip` from keys
  keys.json
Labels: enhancement

#15605 okx: fix ccxt/ccxt#15589
  js/okx.js
Labels: bug

#15608 kucoin: minor update
  js/kucoin.js
Labels: enhancement

#15598 okx: add begin and end when call privateGetTradeOrdersHistory
  js/okx.js
Labels: enhancement

#15612 typo: missing ' on example
  examples/html/binance-cors-proxy.html
Labels: bug

#15614 digifinex - fix argsrequired
  js/digifinex.js
Labels: bug

#15613 test - fix fetchLeverageTiers
  js/test/Exchange/test.fetchFundingRateHistory.js
  js/test/Exchange/test.fetchLeverageTiers.js
Labels: enhancement

#15624 poloniex: add new apis
  js/poloniex.js
Labels: enhancement

#15620 exchange.safeCurrency extra check for currencies_by_id[currencyId] !== undefined
  js/base/Exchange.js
Labels: bug

#15566 deribit - parseOrder and parseTrade
  js/deribit.js
Labels: bug

#15628 Bybit :: fix watchMyTrades
  js/pro/bybit.js
Labels: bug

#15402 bybit - v1 update to v3
  js/bybit.js
Labels: enhancement

#15631 tests - fetchMarketLeverageTiers fix
  js/test/Exchange/test.fetchMarketLeverageTiers.js
Labels: important

#15617 HUOBI: fix `handleBalance` for linear cross swap
  js/pro/huobi.js
Labels: bug

#15636 kuna - fix ticker test
  js/test/Exchange/test.ticker.js
Labels: bug

#15639 bitget transfer
  js/bitget.js
Labels: enhancement

#15637 test- fix fetchFundingRateHistory
  js/test/Exchange/test.fetchFundingRateHistory.js
Labels: bug

#15633 deribit - fetchStatus fix (`tests` related)
  js/deribit.js
Labels: bug

#15638 test - skip broken exchanges
  js/test/Exchange/test.fetchTransactionFees.js
Labels: bug

#15647 Bybit :: fix cancelOrder
  js/bybit.js
Labels: bug

#15567 btcex - stex - double parseTrades
  js/btcex.js
  js/stex.js
Labels: bug

#15649 binanceus - fix private status check
  js/test/Exchange/test.fetchStatus.js
Labels: bug

#15655 bittrex - fix trade side
  js/bittrex.js
Labels: bug

#15653 exchange.marketCodes
  js/base/Exchange.js
Labels: enhancement

#15661 huobi - watchOrderBook
  js/pro/huobi.js
Labels: bug, WS

#15675 Bybit :: fix parseWsTicker
  js/pro/bybit.js
Labels: bug

#15340 bibox fetchTrades and fetchMyTrades upgrade to v4, fixes: #14095
  js/bibox.js
Labels: enhancement

#15697 bybit -fix
  js/bybit.js
Labels: bug

#15703 remove alias exchanges from test
  js/test/test.js
  php/test/test_async.php
  php/test/test_sync.php
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
Labels: enhancement

#15713 Kucoin :: fix fetchTransactionFee
  js/kucoin.js
Labels: bug

#15719 base WS - fix headers
  php/pro/Client.php
Labels: bug

#15735 ccxt.d.ts :: fix fetchMarkets
  ccxt.d.ts
Labels: bug

#15736 Poloniex : : fix parseTicker
  js/poloniex.js
Labels: bug

#15765 Gemini :: improve fetchTrades
  js/gemini.js
Labels: enhancement

#15763 binance: add new apis
  js/binance.js
Labels: enhancement

#15778 wazirx - fetchOHLCV
  js/wazirx.js
Labels: enhancement

#15720 php - example for async-await
  examples/php/async-await.php
Labels: enhancement

#15662 luno - websockets
  js/binance.js
  js/luno.js
  js/pro/luno.js
  js/pro/test/Exchange/test.watchOrderBook.js
  js/pro/test/Exchange/test.watchTrades.js
  php/pro/test/Exchange/test_watch_order_book.php
  php/pro/test/Exchange/test_watch_trades.php
  python/ccxt/pro/test/exchange/test_watch_order_book.py
  python/ccxt/pro/test/exchange/test_watch_trades.py
Labels: enhancement, WS

#15781 Okx pro: add algo orders
  js/okx.js
  js/pro/okx.js
Labels: enhancement

#15770 binance.borrowMargin and repayMargin uses handleMarginModeAndParams
  js/binance.js
Labels: bug

#15187 cex - websockets
  js/cex.js
  js/pro/cex.js
  js/pro/test/Exchange/test.watchOrderBook.js
  js/pro/test/Exchange/test.watchTicker.js
  php/pro/test/Exchange/test_watch_order_book.php
  php/pro/test/Exchange/test_watch_ticker.php
  python/ccxt/pro/test/exchange/test_watch_order_book.py
  python/ccxt/pro/test/exchange/test_watch_ticker.py
Labels: WS

#15792 bigone - fix sign
  js/bigone.js
Labels: bug

#14902 binance - precisions
  js/binance.js
Labels: bug, enhancement, critical

#15793 base - fix subtype
  js/base/Exchange.js
Labels: bug

#15811 handleSubTypeAndParams -default value
  js/base/Exchange.js
Labels: bug

#15666 wazirx - websockets
  js/pro/wazirx.js
  js/wazirx.js
Labels: enhancement, WS

#15803 base - handle margin mode fix
  js/base/Exchange.js
  js/bitmart.js
  js/digifinex.js
  js/hitbtc3.js
  js/mexc3.js
Labels: enhancement

#15723 cex - fix deposit address
  js/base/Exchange.js
  js/bybit.js
  js/cex.js
Labels: bug

#15774 bibox fetchDepositWithdrawFee
  js/bibox.js
Labels: enhancement

#15826 binance: add convert endpoints
  js/binance.js
Labels: enhancement

#15741 exchange.depositWithdrawFee and exchange.parseDepositWithdrawFees
  js/base/Exchange.js
Labels: enhancement

#15777 Bitmart deposit withdraw fee
  js/bitmart.js
Labels: enhancement

#15799 Bitstamp deposit withdraw fee
  js/bitstamp.js
Labels: enhancement

#15837 exchanges - missing Deposit & Withdraw
  js/bibox.js
  js/bitpanda.js
  js/woo.js
Labels: bug, important

#15835 Bitget :: update cancelAllOrders
  js/bitget.js
Labels: enhancement

#15841 wazirx - watchTrades
  js/pro/wazirx.js
Labels: bug, enhancement

#15828 Gate deposit withdraw fee
  js/gate.js
Labels: enhancement

#15812 safeStringLower and safeStringUpper convert defaultValue to lowercase and uppercase
  js/base/functions/type.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#15839 base - typo mistakes & signature of network code & id
  js/base/Exchange.js
Labels: bug

#15865 added ignore to networkCodeToId & networkIdToCode docstrings
  js/base/Exchange.js
Labels: bug

#15831 Lbank2 deposit withdraw fee
  js/lbank2.js
Labels: enhancement

#15870 coinex - address & memo
  js/coinex.js
Labels: bug

#15887 binance - skip tests temporarily
  keys.json
Labels: bug

#15880 binance: add check locked value of VIP collateral account
  js/binance.js
Labels: enhancement
