Repository ccxt/ccxt, pull requests merged in 2022-12, with the labels that each got.

#15210 bybit: integrate derivatives v3
  js/bybit.js
Labels: enhancement

#15900 use Array.isArray instead of this.isArray ccxt/ccxt#15898
  js/base/functions/type.js
  js/binance.js
  js/pro/deribit.js
Labels: bug

#15911 php precise constructor removes + symbol from integers
  php/Precise.php
Labels: bug

#15922 OKX :: fix fetchTickers
  js/okx.js
Labels: bug

#15919 Bybit: fix fetchPositions error
  js/bybit.js
Labels: bug

#15844 stex.fetchDepositWithdrawFee
  js/stex.js
Labels: enhancement

#15932 Bybit :: add spot balance
  js/bybit.js
Labels: bug

#15933 whitebit.parseTrade amount key uses correct value for fetchTrades
  js/whitebit.js
Labels: bug

#15798 Bitso deposit withdraw fees
  js/bitso.js
Labels: enhancement

#15668 bitrue - websockets
  js/bitrue.js
  js/pro/base/OrderBookSide.js
  js/pro/bitrue.js
Labels: WS

#13950 precision (TICK_SIZE) updates - changing numbers to sc.notation
  js/base/Exchange.js
  js/bibox.js
  js/bittrex.js
  js/btctradeua.js
  js/coinex.js
  js/coinfalcon.js
  js/coinone.js
  js/digifinex.js
  js/exmo.js
  js/gate.js
  js/indodax.js
  js/kraken.js
  js/mercado.js
  js/okcoin.js
  js/poloniex.js
  js/upbit.js
Labels: enhancement, critical

#15380 Bitget :: pro implementation
  js/bitget.js
  js/pro/base/Exchange.js
  js/pro/bitget.js
  js/pro/test/Exchange/test.watchOHLCV.js
  php/pro/ClientTrait.php
  python/ccxt/pro/base/exchange.py
  python/ccxt/pro/test/exchange/test_watch_ohlcv.py
Labels: new exchange

#15951 Bitfinex2 :: fix handleMyTrade
  js/pro/bitfinex2.js
Labels: bug

#15966 Bitmart :: fix spot balance
  js/bitmart.js
Labels: bug

#15969 Cex :: fix handleOrderUpdate crash
  js/pro/cex.js
Labels: bug

#15762 Add woox pro
  js/pro/test/Exchange/test.watchOHLCV.js
  js/pro/test/Exchange/test.watchOrderBook.js
  js/pro/test/Exchange/test.watchTicker.js
  js/pro/test/Exchange/test.watchTrades.js
  js/pro/woo.js
  js/woo.js
  php/pro/test/Exchange/test_watch_order_book.php
  php/pro/test/Exchange/test_watch_ticker.php
  php/pro/test/Exchange/test_watch_trades.php
  python/ccxt/pro/test/exchange/test_watch_ohlcv.py
  python/ccxt/pro/test/exchange/test_watch_order_book.py
  python/ccxt/pro/test/exchange/test_watch_ticker.py
  python/ccxt/pro/test/exchange/test_watch_trades.py
Labels: new exchange

#15971 Bitmart :: margin and signature fix
  js/bitmart.js
Labels: bug

#15977 bybit: make fetchFundingRateHistory public ccxt/ccxt#15974
  js/bybit.js
Labels: bug

#15975 Hitbtc :: fix client_order_id
  js/hitbtc3.js
Labels: bug

#15982 bybit: set networkId to uppercase
  js/bybit.js
Labels: enhancement

#15979 woo: update rate limit & api
  js/woo.js
Labels: enhancement

#15986 binance: add error code -1135
  js/binance.js
Labels: enhancement

#15958 bybit - ws - upgrade to v3
  js/base/Exchange.js
  js/bybit.js
  js/pro/bitget.js
  js/pro/bybit.js
Labels: enhancement, WS

#16005 Bybit Pro :: bug fixes
  js/pro/bybit.js
Labels: bug, important

#16008 Cryptocom :: add limit to ohlcv
  js/cryptocom.js
Labels: enhancement

#16002 Deribit :: fix fetchMyTrades
  js/deribit.js
Labels: bug

#16001 Binance :: fix precision type
  js/binance.js
Labels: bug, important

#16003 Binance :: fix parseBorrowRateHistory call
  js/binance.js
Labels: bug

#16026 Bybit :: fix spot trades
  js/bybit.js
Labels: bug

#16028 btcex: update timeframes ccxt/ccxt#16025
  js/btcex.js
Labels: bug

#16023 huobi: fix withdraw ccxt/ccxt#16016
  js/huobi.js
Labels: bug

#16035 Bkex :: fix fetchMarkets
  js/bkex.js
Labels: bug

#15867 exchange.assignDefaultDepositWithdrawFees created
  js/base/Exchange.js
Labels: bug, important

#15379 digifinex - currency precision
  js/digifinex.js
Labels: enhancement

#16060 Binance pro :: even distribution among connections
  js/pro/binance.js
Labels: enhancement

#16088 okx: add endpoints and errors
  js/okx.js
Labels: enhancement

#16091 bybit: add api endpoints
  js/bybit.js
Labels: enhancement

#16090 okx: add rfq apis
  js/okx.js
Labels: enhancement

#16089 removed defaultMarginMode from options
  js/coinex.js
  js/okx.js
Labels: bug

#16094 Huobi :: fix networkCodeToId call
  js/huobi.js
Labels: bug

#16085 okx: add history candles for mark/index price ccxt/ccxt#16082
  js/okx.js
Labels: bug

#16068 Binance: editOrder
  js/binance.js
Labels: enhancement

#15854 get_object_value_from_key_array php and py do not return empty string as a value
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#15843 mexc3.fetchDepositWithdrawFee
  js/mexc3.js
Labels: enhancement

#16100 Bybit :: fix empty OHLCV
  js/bybit.js
Labels: bug

#16101 Zb Ws :: add futures
  js/pro/test/Exchange/test.watchOHLCV.js
  js/pro/zb.js
  python/ccxt/pro/test/exchange/test_watch_ohlcv.py
Labels: enhancement

#16109 Bybit :: fix ohlcv timestamp
  js/bybit.js
Labels: bug

#16108 Fast transpiling using multi-processing
  build/transpile.js
  build/transpileWS.js
  package.json
Labels: enhancement

#16114 Poloniex :: fix undefined side
  js/phemex.js
Labels: bug

#15978 Bitmex fetch deposit address
  js/bitmex.js
Labels: enhancement

#16124 Gate WS :: add book ticker option
  js/gate.js
  js/pro/gate.js
  keys.json
Labels: enhancement

#16126 okx: add endpoionts and error codes
  js/okx.js
Labels: enhancement

#16125 okx - add symbol to orderbook
  js/pro/okx.js
Labels: bug, WS

#15845 whitebit.fetchDepositWtihdrawFees
  js/whitebit.js
Labels: enhancement

#15830 Kucoin + kucoinfutures fetchDepositWithdrawFee
  js/kucoin.js
  js/kucoinfutures.js
Labels: enhancement

#16135 Network codes to ids
  js/base/Exchange.js
Labels: enhancement

#16141 digifinex - correct tera
  js/digifinex.js
Labels: bug

#16140 huobi - fee inclusive withdraw
  js/huobi.js
Labels: enhancement

#16128 ascendex parseTransaction unification
  js/ascendex.js
Labels: enhancement

#16129 bitfinex parseTransaction unification
  js/bitfinex.js
Labels: enhancement

#15862 gemini - fetchMarketsFromApi
  js/gemini.js
Labels: enhancement

#16131 bitmex.parseTransaction unification
  js/bitmex.js
Labels: enhancement

#16130 bitfinex2 parseTransaction unification
  js/bitfinex2.js
Labels: enhancement

#16155 okx: add activate-option
  js/okx.js
Labels: enhancement

#16161 mexc: add apis
  js/mexc3.js
Labels: enhancement

#16160 bitifinex2 parseTransaction edits
  js/bitfinex2.js
Labels: bug

#16146 added fetchOpenInterest and fetchOpenInterestHistory to exchange.has
  js/base/Exchange.js
Labels: bug

#16171 Alpaca :: fetchOHLCV = true
  js/alpaca.js
Labels: bug

#16169 Php safe value n
  php/Exchange.php
Labels: bug

#16172 Alpaca :: fix ohlcv timestamp
  js/alpaca.js
Labels: bug

#16156 Ascendex fetch markets python fix
  js/ascendex.js
Labels: bug

#15001 Ndax parseLedgerEntry string math
  js/ndax.js
Labels: enhancement

#14875 Huobijp string math
  js/huobijp.js
Labels: enhancement

#16175 Bybit :: fix fetchmarkets
  js/bybit.js
Labels: bug

#16174 exchange: checkout whether symbols is undefined
  js/base/Exchange.js
Labels: enhancement

#16134 tokocrypto parseTransaction unification
  js/tokocrypto.js
Labels: enhancement

#14903 bitvavo.createOrder string math
  js/bitvavo.js
Labels: enhancement

#16178 Luno :: fix parse ledger
  js/luno.js
Labels: bug

#16179 cex: patch watchTickers
  js/pro/cex.js
Labels: bug

#16173 gate: add watchTickers
  js/pro/gate.js
Labels: enhancement

#16186 bybit: fix fetchDerivativesPositions ccxt/ccxt#16181
  js/bybit.js
Labels: bug

#16180 bybit - ohlcv default value
  js/bybit.js
Labels: bug

#16182 examples - simplified comments for margin script
  examples/js/margin-borrow-buy-sell-repay-example.js
Labels: enhancement

#16202 Remove pro badge
  js/hitbtc3.js
Labels: bug

#16205 php - authenticated websockets
  js/pro/exmo.js
  php/pro/Client.php
  php/pro/ClientTrait.php
Labels: bug, WS

#16198 huobi - watchTicker - allow different topics
  js/huobi.js
  js/pro/huobi.js
Labels: enhancement

#16209 Fix \ccxt\hitbtc3 and \ccxt\async\hitbtc3 test urls
  js/hitbtc3.js
Labels: bug

#16204 watchTicker - unify name option
  js/pro/bybit.js
  js/pro/kucoin.js
  wiki/ccxt.pro.manual.md
Labels: enhancement, WS

#16228 okx - fix side position
  js/okx.js
Labels: bug

#16115 alpaca - ws
  js/alpaca.js
  js/pro/alpaca.js
  js/pro/test/Exchange/test.watchOrderBook.js
  php/pro/test/Exchange/test_watch_order_book.php
  python/ccxt/pro/test/exchange/test_watch_order_book.py
Labels: enhancement, WS

#16249 Bitmex :: temporary balance fix
  js/bitmex.js
Labels: bug

#15041 base - handleoption replacements
  js/base/Exchange.js
Labels: important

#16150 btcmarkets parseTransaction unification minimum changes
  js/btcmarkets.js
Labels: enhancement

#16260 Travis :: Optimize tests
  .travis.yml
  build/push.sh
  js/bybit.js
  last-run.txt
  python/fastflake.sh
  tests-manager.sh
Labels: enhancement

#16263 Exmo parseTransaction unification
  js/exmo.js
Labels: enhancement

#16273 alpaca- py comments fix
  js/pro/alpaca.js
  python/ccxt/pro/test/exchange/test_watch_order_book.py
Labels: bug

#16265 hitbtc3 parseTransaction unification
  js/hitbtc3.js
Labels: enhancement

#16266 hitbtc unify parseTransaction
  js/hitbtc.js
Labels: enhancement

#16151 Coinbasepro parse transaction
  js/coinbasepro.js
Labels: enhancement

#16147 bitopro.parseTransaction unification
  js/bitopro.js
Labels: enhancement

#16133 currencycom.parseTransaction unification
  js/currencycom.js
Labels: enhancement

#16105 Issue Templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/NEW_EXCHANGE.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#16274 ws - pass proxy agent and headers
  js/pro/base/Exchange.js
Labels: bug

#16203 python - ws - headers
  python/ccxt/pro/base/aiohttp_client.py
  python/ccxt/pro/base/client.py
Labels: enhancement

#16276 Poloniex: editOrder
  js/poloniex.js
Labels: enhancement
