Repository ccxt/ccxt, pull requests merged in 2023-11, with the labels that each got.

#19744 feat(errors) - add `ApiEngineFailed` and `OperationFailed`
  ts/src/base/errorHierarchy.ts
Labels: enhancement

#19100 fix(php8) - promise interface & react update
  composer.json
  composer.lock
  php/pro/Future.php
Labels: bug

#19764 Digifinex: setMarginMode
  ts/src/digifinex.ts
Labels: enhancement

#19770 fix(okx): watchMyTrades
  ts/src/pro/okx.ts
Labels: bug

#19769 fix(exceptions) - OperationRejected
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
Labels: bug

#19766 Digifinex: addMargin, reduceMargin
  ts/src/digifinex.ts
Labels: enhancement

#19745 Huobi - currencies networks unification
  ts/src/huobi.ts
Labels: bug

#19701 kucoin: update apis
  ts/src/kucoin.ts
Labels: enhancement

#19784 bitopro: add apis
  ts/src/bitopro.ts
Labels: enhancement

#19786 bitstamp: add apis
  ts/src/bitstamp.ts
Labels: enhancement

#19782 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19787 bybit: support spot order in editOrder
  ts/src/bybit.ts
Labels: enhancement

#19761 feat(tests): add static tests
  build.sh
  examples/js/cli.js
  package.json
  php/Exchange.php
  php/async/Exchange.php
  php/test/test_async.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
  ts/src/base/Exchange.ts
  ts/src/test/static/data/binance.json
  ts/src/test/static/data/bingx.json
  ts/src/test/static/data/bitget.json
  ts/src/test/static/data/bitmart.json
  ts/src/test/static/data/bitmex.json
  ts/src/test/static/data/bybit.json
  ts/src/test/static/data/cryptocom.json
  ts/src/test/static/data/gate.json
  ts/src/test/static/data/huobi.json
  ts/src/test/static/data/kraken.json
  ts/src/test/static/data/krakenfutures.json
  ts/src/test/static/data/kucoin.json
  ts/src/test/static/data/kucoinfutures.json
  ts/src/test/static/data/okx.json
  ts/src/test/static/data/woo.json
  ts/src/test/static/markets/binance.json
  ts/src/test/static/markets/bingx.json
  ts/src/test/static/markets/bitget.json
  ts/src/test/static/markets/bitmart.json
  ts/src/test/static/markets/bitmex.json
  ts/src/test/static/markets/bybit.json
  ts/src/test/static/markets/coinbase.json
  ts/src/test/static/markets/coinbasepro.json
  ts/src/test/static/markets/cryptocom.json
  ts/src/test/static/markets/gate.json
  ts/src/test/static/markets/huobi.json
  ts/src/test/static/markets/kraken.json
  ts/src/test/static/markets/krakenfutures.json
  ts/src/test/static/markets/kucoin.json
  ts/src/test/static/markets/kucoinfutures.json
  ts/src/test/static/markets/okx.json
  ts/src/test/static/markets/phemex.json
  ts/src/test/static/markets/whitebit.json
  ts/src/test/static/markets/woo.json
  ts/src/test/test.ts
Labels: enhancement

#19499 feat(kuna): upgrade to v4 api
  ts/src/abstract/kuna.ts
  ts/src/kuna.ts
Labels: enhancement, new exchange

#19793 Manuals rewriting for exceptions & troubleshooting
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
  wiki/Manual.md
Labels: bug

#19806 fix(docs) - removal of leftover (QUICK)
  wiki/Manual.md
Labels: bug

#19803 bitforex.has["swap"] == false
  ts/src/bitforex.ts
Labels: enhancement

#19802 wazirx.has margin false
  ts/src/wazirx.ts
Labels: enhancement

#19800 BingX: fetchMyLiquidations
  ts/src/bingx.ts
Labels: enhancement

#19788 cli: add str encoding
  examples/py/cli.py
Labels: enhancement

#19804 Digifinex: createOrders
  ts/src/digifinex.ts
  ts/src/test/static/data/digifinex.json
  ts/src/test/static/markets/digifinex.json
Labels: enhancement

#19810 fix(bitget): connection and split trigger orders cache
  ts/src/pro/bitget.ts
  ts/src/test/static/data/bitget.json
Labels: bug

#19813 fix(kuna) - skip active (QUICK)
  skip-tests.json
Labels: bug

#19823 feat(bybit): add del-submembe endpoint
  ts/src/bybit.ts
Labels: enhancement

#19817 bitforex.has leverage methods
  ts/src/bitforex.ts
Labels: enhancement

#19816 wazirx.has margin/contract methods
  ts/src/wazirx.ts
Labels: enhancement

#19822 binance: support other signature in pro
  ts/src/pro/binance.ts
Labels: enhancement

#19820 example: add create order ws
  examples/ts/create-order-ws-example.ts
Labels: enhancement

#19838 update changelog [ci skip]
  CHANGELOG.md
Labels: enhancement

#19839 feat(tests): make brokerId tests transpilable
  build.sh
  package.json
  php/test/test_async.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  ts/src/test/static/test.ids.ts
  ts/src/test/test.ts
Labels: enhancement

#19850 fix(binance): watchOrders and watchMyTrades type
  ts/src/pro/binance.ts
  ts/src/test/test.ts
Labels: bug

#19635 tests - exact exception matching
  php/test/test_async.php
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/test/test.ts
Labels: bug

#19852 fix(Exchange.py): urlEncode stop mutating arg
  python/ccxt/base/exchange.py
  ts/src/test/static/data/binance.json
  ts/src/test/static/data/bybit.json
  ts/src/test/static/data/okx.json
Labels: bug

#19860 fix(bittrex): fetchCurrencies - add networks key with value of empty dict to fetchCurrencies response
  ts/src/bittrex.ts
Labels: bug

#19819 BingX: createOrders
  build/transpile.js
  ts/src/base/Exchange.ts
  ts/src/bingx.ts
  ts/src/test/static/data/bingx.json
  ts/src/test/test.ts
Labels: enhancement

#19864 fix(tests) - array
  ts/src/test/test.ts
Labels: bug

#19868 probit fetchTransactions fix
  ts/src/probit.ts
  ts/src/test/static/data/probit.json
  ts/src/test/static/markets/probit.json
  ts/src/test/test.ts
Labels: bug

#19865 fix(tests) - relative dir for PHP/PY
  ts/src/test/test.ts
Labels: bug

#19680 Coinlist integration
  skip-tests.json
  ts/src/abstract/coinlist.ts
  ts/src/coinlist.ts
  ts/src/test/static/data/coinlist.json
  ts/src/test/static/markets/coinlist.json
  wiki/Manual.md
Labels: new exchange

#19861 Ascendex: createOrders
  ts/src/ascendex.ts
  ts/src/test/static/data/ascendex.json
  ts/src/test/static/markets/ascendex.json
  ts/src/test/test.ts
Labels: enhancement

#19879 jsdoc: update link to open interest structure
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bybit.ts
  ts/src/delta.ts
  ts/src/gate.ts
  ts/src/huobi.ts
  ts/src/okx.ts
Labels: enhancement

#19872 Mexc: keepAliveListenKey catch error missing ['spot'] from URL
  ts/src/pro/mexc.ts
Labels: bug

#19848 hitbtc: update apis
  ts/src/hitbtc.ts
  ts/src/test/static/data/hitbtc.json
  ts/src/test/static/markets/hitbtc.json
Labels: enhancement

#19882 fix(tests) - remove unused imports
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
Labels: bug

#19892 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#19890 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#19889 Okx: add static tests, adjust posSide logic
  ts/src/okx.ts
  ts/src/test/static/data/okx.json
Labels: enhancement

#19899 fix(bitvavo): amount precision for markets defaults to the precision of the base currency instead of 8
  skip-tests.json
  ts/src/bitvavo.ts
Labels: bug

#19796 bybit parseSpotTrade fee fix
  ts/src/bybit.ts
Labels: bug

#15622 feat(Exchange): add watchPositions [ci deploy]
  build/transpileWS.js
  examples/js/watchPositions-many-exchanges-continuosly.d.ts
  examples/js/watchPositions-many-exchanges-continuosly.d.ts.map
  examples/js/watchPositions-many-exchanges-continuosly.js
  examples/js/watchPositions.d.ts
  examples/js/watchPositions.d.ts.map
  examples/js/watchPositions.js
  examples/js/watchPositionsForSymbols.d.ts
  examples/js/watchPositionsForSymbols.d.ts.map
  examples/js/watchPositionsForSymbols.js
  examples/php/watchPositions-many-exchanges-continuosly.php
  examples/php/watchPositions.php
  examples/php/watchPositionsForSymbols.php
  examples/py/watchPositions-many-exchanges-continuosly.py
  examples/py/watchPositions.py
  examples/py/watchPositionsForSymbols.py
  examples/ts/watchPositions-many-exchanges-continuosly.ts
  examples/ts/watchPositions.ts
  examples/ts/watchPositionsForSymbols.ts
  php/Exchange.php
  php/pro/ArrayCacheBySymbolBySide.php
  python/ccxt/async_support/base/ws/cache.py
  python/ccxt/base/exchange.py
  python/ccxt/pro/test/test_cache.py
  ts/src/base/Exchange.ts
  ts/src/base/ws/Cache.ts
  ts/src/bybit.ts
  ts/src/cryptocom.ts
  ts/src/gate.ts
  ts/src/huobi.ts
  ts/src/pro/binance.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bybit.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/gate.ts
  ts/src/pro/huobi.ts
  ts/src/pro/krakenfutures.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/okx.ts
  ts/src/pro/test/Exchange/test.watchPosition.ts
  ts/src/pro/test/Exchange/test.watchPositions.ts
  ts/src/pro/test/base/test.Cache.ts
  ts/src/pro/test/test.ts
  wiki/ccxt.pro.manual.md
Labels: enhancement, ws

#19901 fix(kuna) - skip
  skip-tests.json
Labels: bug

#19909 Manual: add number of contracts explanation to notes on createOrder [ci skip]
  wiki/Manual.md
Labels: enhancement

#19915 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19898 hitbtc: add fetchMarginMode
  build/export-exchanges.js
  build/transpile.js
  python/ccxt/base/types.py
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/hitbtc.ts
  ts/src/test/static/data/hitbtc.json
Labels: enhancement

#19919 update cli.ts to be same as cli.js
  examples/js/cli.js
  examples/ts/cli.ts
Labels: bug

#19921 kraken: update jsdoc
  ts/src/kraken.ts
Labels: enhancement

#19926 fix(mexc): patch withdraw
  ts/src/mexc.ts
Labels: bug

#19908 New unified method: fetchGreeks
  build/export-exchanges.js
  build/transpile.js
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/types.py
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bybit.ts
  ts/src/cryptocom.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/okx.ts
  wiki/Manual.md
Labels: enhancement

#19923 htx: createOrders
  ts/src/htx.ts
  ts/src/test/static/data/huobi.json
  ts/src/test/static/markets/huobi.json
Labels: enhancement

#19932 fix(bit2c) - skip temporarily
  skip-tests.json
Labels: bug

#19935 kraken: add start in fetchDeposits
  ts/src/kraken.ts
  ts/src/test/static/data/kraken.json
Labels: enhancement

#19934 fix(krakenfutures): patch watchOrders
  ts/src/pro/krakenfutures.ts
Labels: bug

#19937 [WIP] kucoin: update fetchOrderBook
  ts/src/kucoin.ts
Labels: enhancement

#19952 coinbase: patch parse trade
  ts/src/coinbase.ts
Labels: bug

#19962 fix(binance): parseWsPosition symbol [ci deploy]
  ts/src/pro/binance.ts
Labels: bug

#19950 Bybit: enable stopLoss and takeProfit with trigger orders
  ts/src/bybit.ts
  ts/src/test/static/data/bybit.json
Labels: bug

#19964 coinbase websocket order methods has
  ts/src/pro/coinbase.ts
Labels: enhancement

#19971 bybit: update
  ts/src/bybit.ts
Labels: enhancement

#19977 bybit: add missing apis
  ts/src/bybit.ts
Labels: enhancement

#19975 poloniexfutures.has rest ws methods
  ts/src/pro/poloniexfutures.ts
Labels: ws

#19902 Update build-ohlcv-many-symbols.py
  examples/ccxt.pro/py/build-ohlcv-many-symbols.py
Labels: bug, enhancement

#19983 fix(bitget): marginMode handling
  ts/src/bitget.ts
  ts/src/test/static/data/bitget.json
Labels: bug

#19807 feat(p2b): New Exchange
  skip-tests.json
  ts/src/abstract/p2b.ts
  ts/src/p2b.ts
  ts/src/test/static/data/p2b.json
  ts/src/test/static/markets/p2b.json
Labels: new exchange

#19760 base & examples - build bars using WebSockets live data [ci deploy]
  examples/ts/.eslintrc
  examples/ts/build-ohlcv-bars.ts
Labels: enhancement

#19987 fix(errors) - move `OperationFailed` exception to root
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
Labels: enhancement

#20021 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#20016 bitbank: add apis
  ts/src/bitbank.ts
Labels: enhancement

#20019 htx: add apis
  ts/src/htx.ts
Labels: enhancement

#20013 Okx: createOrder, postOnly, stopLoss and takeProfit
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: bug

#20011 Bitmart: parseOrderStatusByType
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
  ts/src/test/static/response/bitmart.json
Labels: bug

#20015 kucoin: remove method usage
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
Labels: enhancement

#19976 krakenfutures.has order methods
  ts/src/pro/krakenfutures.ts
Labels: enhancement

#20018 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#20024 fix(bitvavo): patch fetchMarkets
  ts/src/bitvavo.ts
Labels: bug

#20020 static tests & base & binance bugfixes
  build/transpile.js
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/coinbasepro.ts
  ts/src/hollaex.ts
  ts/src/test/static/response/binance.json
Labels: bug, enhancement

#20027 Hitbtc ws order methods
  ts/src/hitbtc.ts
  ts/src/pro/hitbtc.ts
  ts/src/test/static/request/hitbtc.json
Labels: ws

#20045 fix(template): return error code
  .git-templates/hooks/pre-push
Labels: enhancement

#19939 bitmex - `triggerPrice` unification and static tests
  ts/src/bitmex.ts
  ts/src/test/static/request/bitmex.json
  ts/src/test/static/response/bitmex.json
Labels: bug, enhancement

#20056 Bitmart: fetchOHLCV endpoint ratelimit weights
  ts/src/bitmart.ts
Labels: bug

#20058 bittrex.has ws non-watch methods
  ts/src/pro/bittrex.ts
Labels: enhancement

#20048 fix(bybit) - trigger order direction & tests
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: bug, enhancement

#20060 mexc.has: non-watch ws methods
  ts/src/pro/mexc.ts
Labels: enhancement, ws

#20061 htx.has: non-watch ws methods
  ts/src/pro/htx.ts
Labels: enhancement, ws

#20062 bybit.has: non-watch ws methods
  ts/src/pro/bybit.ts
Labels: enhancement, ws

#20063 bitvavo.has: ws non-watch methods
  ts/src/pro/bitvavo.ts
Labels: enhancement, ws

#20065 bitget.has: ws non-watch methods
  ts/src/pro/bitget.ts
Labels: enhancement, ws

#20066 bitmart.has: ws non-watch methods
  ts/src/pro/bitmart.ts
Labels: enhancement, ws

#20068 fix(docs) - trigger orders, stop loss orders, and some reorganisations
  wiki/Manual.md
Labels: bug

#17960 feat(exchange): `okex, huobipro, gateio, mexc3` - removal of old aliases
  skip-tests.json
  ts/src/huobipro.ts
  ts/src/mexc3.ts
  ts/src/okex.ts
  ts/src/okex5.ts
  ts/src/pro/huobipro.ts
  ts/src/pro/mexc3.ts
  ts/src/pro/okex.ts
Labels: enhancement

#20071 kucoin: update apis
  ts/src/kucoin.ts
Labels: enhancement

#20073 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#20069 mexc network update
  ts/src/mexc.ts
Labels: bug

#16769 feat(okx) - fetchPositionsForSymbol
  ts/src/base/Exchange.ts
  ts/src/okx.ts
Labels: enhancement

#20078 coinbasepro: add @see
  ts/src/coinbasepro.ts
Labels: enhancement

#20077 rename fetch positions "by symbol" into "for symbol"
  ts/src/base/Exchange.ts
  ts/src/kuna.ts
  ts/src/p2b.ts
Labels: bug

#20082 coinbase: update
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#20088 fix(gate) - transfer settle id
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: bug

#20090 fix(bybitWs): watchTickers
  ts/src/pro/bybit.ts
Labels: bug

#19985 alpaca: update apis
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
Labels: enhancement

#20094 fix(exchange): patch fee update by reference
  ts/src/base/Exchange.ts
  ts/src/test/static/response/bitget.json
Labels: bug

#19757 bitrue: integrate swap
  ts/src/bitrue.ts
  ts/src/test/static/markets/bitrue.json
  ts/src/test/static/request/bitrue.json
  ts/src/test/test.ts
Labels: enhancement

#20098 fix(manual) - about margin
  wiki/Manual.md
Labels: enhancement

#20057 container: replace python3 setup with pip3 install
  Dockerfile
Labels: enhancement

#20100 binance: update apis
  ts/src/binance.ts
Labels: bug

#19969 feat(poloniex): createOrderWs, cancelOrderWs, cancelOrdersWs, cancelAllOrdersWs
  ts/src/pro/poloniex.ts
Labels: enhancement, ws

#20101 kucoinfutures: remove test api
  ts/src/kucoinfutures.ts
Labels: enhancement

#20104 kucoinfutures: remove method
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
Labels: enhancement

#20102 phemex: update apis
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
Labels: enhancement

#20106 kraken: update doc
  doc/manual.rst
  doc/readme.rst
  ts/src/kraken.ts
Labels: enhancement

#20108 krakenfutures: remove method usage
  ts/src/krakenfutures.ts
  ts/src/test/static/request/krakenfutures.json
Labels: enhancement

#20109 wazirx: remove method usage
  ts/src/test/static/request/wazirx.json
  ts/src/wazirx.ts
Labels: enhancement

#20110 tokocrypto: remove method usage
  ts/src/test/static/request/tokocrypto.json
  ts/src/tokocrypto.ts
Labels: enhancement

#20111 binanceus margin,swap,future,option:has
  ts/src/binanceus.ts
Labels: enhancement

#20112 luno: remove method usage
  ts/src/luno.ts
  ts/src/test/static/request/luno.json
Labels: enhancement

#20113 bitmart: remove method usage
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
Labels: enhancement

#20114 mexc: add internal transfer api
  ts/src/mexc.ts
Labels: enhancement

#20116 bitmex fetchMarkets docstrings
  ts/src/bitmex.ts
Labels: enhancement

#20117 fix!(cryptocom): fetchPositions response returns numContracts as an absolute value, and also returns side
  ts/src/cryptocom.ts
  ts/src/test/static/markets/cryptocom.json
  ts/src/test/static/request/cryptocom.json
  ts/src/test/static/response/cryptocom.json
Labels: bug

#20119 fix(bybit): tickers handling
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#20126 fix(PHP): array type
  build/transpile.js
Labels: bug, important

#19360 proxy unification for WebSockets & reorganize for REST
  build/transpile.js
  examples/php/proxy-usage.php
  examples/php/sample-local-proxy-server-with-cors.php
  examples/py/proxy-usage.py
  examples/ts/proxy-usage.ts
  php/Exchange.php
  php/async/Exchange.php
  php/pro/Client.php
  php/pro/ClientTrait.php
  php/test/test_async.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/async_support/base/ws/aiohttp_client.py
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/Exchange/test.proxies.ts
  ts/src/test/test.ts
  wiki/Manual.md
Labels: enhancement

#18425 base - add `subType` in markets
  python/ccxt/base/types.py
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
Labels: enhancement

#20124 Gate - borrow & repay for margin
  ts/src/base/Exchange.ts
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#20149 python: only add tox requirement for qa
  python/setup.py
Labels: bug

#20154 ascendex: remove method
  ts/src/ascendex.ts
  ts/src/test/static/request/ascendex.json
Labels: enhancement

#20118 tests - run method oriented test & fix python tests
  php/test/test_async.php
  python/ccxt/test/test_async.py
  ts/src/test/test.ts
Labels: enhancement

#20159 PY fixes & test
  skip-tests.json
  ts/src/test/Exchange/test.proxies.ts
Labels: bug

#20160 kuna - temproary skip
  skip-tests.json
Labels: bug

#20162 Coinex: createOrders, cancelOrders
  ts/src/coinex.ts
  ts/src/test/static/request/coinex.json
Labels: enhancement

#20155 gate: remove method
  skip-tests.json
  ts/src/gate.ts
  ts/src/test/static/markets/gate.json
  ts/src/test/static/request/gate.json
Labels: enhancement

#20168 coinbase: add apis
  ts/src/coinbase.ts
Labels: enhancement

#20174 fix(binance): skip positions cache on spot balance
  ts/src/pro/binance.ts
Labels: bug

#20152 bundle: add rollup node resolve plugin
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement
