Repository ccxt/ccxt, pull requests merged in 2023-03, with the labels that each got.

#17005 coinex - contract markets precisions
  js/coinex.js
Labels: bug

#17002 Binance: fetchLedger
  js/binance.js
Labels: enhancement

#17008 fix(bybit): fix fetchOHLCV since
  js/bybit.js
Labels: bug

#17009 fix(bybit): remove isUnifiedMarginEnabled from ws
  js/pro/bybit.js
Labels: bug

#17012 fix(Bybit): timeframe parsing
  js/bybit.js
Labels: bug

#17025 fix(Bybit): add account type options
  js/bybit.js
Labels: bug

#17020 bybit: add fetchCanceledOrders
  js/bybit.js
Labels: enhancement

#17017 fix(ascendex): fix #17010
  js/pro/ascendex.js
Labels: bug

#17015 cex - incorrect currency precision parsing
  js/cex.js
Labels: bug

#17014 Fix Dockerfile
  Dockerfile
Labels: bug

#17026 fix(Gate): sandbox markets loading
  js/gate.js
Labels: bug

#17022 okx: add v5/trade/order-algo
  js/okx.js
Labels: enhancement

#17029 feat(bybit): v5 add funding balance
  js/bybit.js
Labels: enhancement

#17033 bybit: update fetchBalance
  js/bybit.js
Labels: enhancement

#17042 fix(bybit): setMarginMode leverage type
  js/bybit.js
Labels: bug

#17047 Coinbase Pro: Add bidVolume and askVolume to watchTicker
  js/pro/coinbasepro.js
Labels: enhancement

#17044 fix(binance): stream reconnect
  js/pro/binance.js
Labels: bug

#17056 fix(bybit): parseTicker default type
  js/bybit.js
Labels: bug

#17060 CONTRIBUTING.md: spelling fixes.
  CONTRIBUTING.md
Labels: bug, enhancement

#17061 bybit: patch fetchMarketLeverageTiers ccxt/ccxt#17055
  js/bybit.js
Labels: bug

#17065 bitget - fetchOHLCV for spot
  js/bitget.js
Labels: bug

#17067 fix(binance): increase default keep alive to 180000
  js/pro/binance.js
Labels: enhancement

#17049 [krakenfutures] fix amount precision
  js/krakenfutures.js
Labels: bug

#17066 fix(binance): uncatchable error in fetchOrderBookSnapshot
  js/pro/binance.js
Labels: bug

#17078 exchange - Flake8 fix qa
  python/fastflake.sh
  python/qa.py
Labels: bug

#17077 fix(huobi): catch watchOrderBookSnapshot uncatchable error
  js/pro/huobi.js
Labels: bug

#17079 base - ignore `build` folder in flake qa
  python/fastflake.sh
  python/qa.py
Labels: bug

#17080 fix(Exchange): fetchstatus info key
  js/base/Exchange.js
Labels: bug

#17073 bithumb fetchTickers fix
  js/bithumb.js
Labels: bug

#17089 Gate docs
  js/gate.js
Labels: enhancement

#17102 feat(bybit):: add v5 endpoint to fetchBalance [ci deploy]
  js/bybit.js
Labels: enhancement

#17104 fix(Bitfinex2): authenticate and watchOrders
  js/pro/bitfinex2.js
Labels: bug

#17108 bitget: add vip level apis
  js/bitget.js
Labels: enhancement

#17107 novadax.has["fetchDepositAddress"] == false
  js/novadax.js
Labels: enhancement

#17109 okx: update parseOrder ccxt/ccxt#15618
  js/okx.js
Labels: bug

#17068 bybit: upgrade pro to v5
  js/bybit.js
  js/pro/bybit.js
Labels: enhancement

#17091 binance.parseWsTrade string math
  js/pro/binance.js
Labels: enhancement

#17124 fix(cex): fix uncatchable error
  js/pro/cex.js
Labels: bug

#17139 sh: update cleanup.sh
  cleanup.sh
Labels: enhancement

#17140 npm: update package.json
  package.json
Labels: enhancement

#17126 feat: add docsify
  wiki/.nojekyll
  wiki/_coverpage.md
  wiki/_sidebar.md
  wiki/index.html
Labels: enhancement

#17137 okx: patch ccxt/ccxt#17125
  ts/src/okx.ts
Labels: bug

#17132 fix(luno): cleanup unused parameter from orderbook limit
  ts/src/pro/luno.ts
Labels: bug

#17151 fix(bybit,gate): sync market loading + postinstall fix + safeOrder [ci deploy]
  build/transpile.js
  postinstall.cjs
  ts/src/base/Exchange.ts
Labels: bug

#17152 woo: add average price ccxt/ccxt#17143
  ts/src/woo.ts
Labels: bug

#17163 fix(Phemex): add default posSide to editOrder
  ts/src/.eslintrc
  ts/src/phemex.ts
Labels: enhancement

#17165 fix(bybit): v5 uta spot market buy
  ts/src/bybit.ts
Labels: bug

#17161 package.json: set node version to 15.0.0 in engines
  package.json
Labels: enhancement

#17171 feat(TS): add more types and stub methods [ci deploy]
  build/export-exchanges.js
  examples/ts/fetch-orderbook.ts
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
Labels: enhancement

#17168 fix - emitTypes
  .travis.yml
  build/emitTypes.js
  cleanup.sh
  package.json
Labels: bug

#17188 fix(TS): init values for ws structures [ci deploy]
  examples/js/cli.js
  ts/src/base/Exchange.ts
Labels: bug, critical

#17115 fix: parsePrecision returns precision as a string number that is not scientific notation
  php/Exchange.php
  python/ccxt/base/decimal_to_precision.py
  ts/src/base/Exchange.ts
  ts/src/base/functions/number.ts
  ts/src/test/base/functions/test.number.ts
Labels: bug, enhancement

#17200 poloniexfutures.fetchOpenOrders fix to fetch open orders
  ts/src/poloniexfutures.ts
Labels: bug

#17199 Poloniexfutures parse order cost
  ts/src/poloniexfutures.ts
Labels: bug

#17204 feat(build): add cjs test [ci skip]
  package.json
  test-commonjs.cjs
  tests-manager.sh
Labels: enhancement

#17214 fix(kraken): watchOrderbook handleDeltas [ci deploy]
  ts/src/pro/kraken.ts
Labels: bug

#17198 feat(okx): fetchOHLCV retrieve base volume
  ts/src/okx.ts
Labels: bug

#17219 parseDepositAddresses undefined result fix [ci deploy]
  ts/src/base/Exchange.ts
  ts/src/huobi.ts
Labels: bug

#17217 Coinsph.ts
  ts/src/coinsph.ts
Labels: new exchange

#17229 [krakenfutures] Add `params.clientOrderId` to createOrder
  ts/src/krakenfutures.ts
Labels: enhancement

#17215 exmo order status
  ts/src/exmo.ts
Labels: enhancement

#17264 fix(binance): postOnly Orders [ci deploy]
  ts/src/base/Exchange.ts
  ts/src/binance.ts
Labels: bug

#17268 fix(mexc): GASNEO name as GAS
  ts/src/mexc.ts
  ts/src/mexc3.ts
Labels: enhancement

#17272 fix(bybit): v5 does not require symbol for spot trades
  ts/src/bybit.ts
Labels: bug

#17247 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#17265 fix(ascendex): fix #17256 python handle ping await error
  ts/src/pro/ascendex.ts
Labels: bug

#17278 fix(bybit): add symbol to fetchPositions
  ts/src/bybit.ts
Labels: bug

#17277 bitstamp parseTrade fix
  ts/src/bitstamp.ts
Labels: bug

#17286 fix(kucoin): handlePong
  ts/src/pro/kucoin.ts
Labels: bug

#17093 kraken handleTicker string math
  ts/src/pro/kraken.ts
Labels: enhancement

#17292 fix(bitpro,bitget): fix parseOHLCV and fetchOrderTrades [ci skip]
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bitmex.ts
  ts/src/bitopro.ts
  ts/src/coinbase.ts
  ts/src/coinbasepro.ts
  ts/src/gate.ts
  ts/src/hitbtc3.ts
  ts/src/kucoin.ts
  ts/src/mexc.ts
  ts/src/mexc3.ts
  ts/src/okx.ts
  ts/src/poloniex.ts
  ts/src/wavesexchange.ts
  ts/src/whitebit.ts
  ts/src/yobit.ts
Labels: bug

#17297 Binance, Bybit: fetchOHLCV inverse markets volume
  ts/src/binance.ts
  ts/src/bybit.ts
Labels: bug

#17282 handle with tif
  ts/src/base/Exchange.ts
  ts/src/gate.ts
Labels: bug

#17302 bybit: patch order fee
  ts/src/bybit.ts
Labels: bug

#17306 gate - update createMarketOrder flag
  ts/src/gate.ts
Labels: bug

#17186 Export-exchanges: remove ccxt import dependency [ci skip]
  build/export-exchanges.js
  package.json
Labels: enhancement

#17310 fix Exchange: safeMarket
  ts/src/base/Exchange.ts
  ts/src/bybit.ts
Labels: bug

#17315 fix(bybit,gate): polluting markets loading
  ts/src/bybit.ts
  ts/src/gate.ts
Labels: bug

#17314 okx fetchCurrencies fix
  ts/src/okx.ts
Labels: bug

#17094 idex handleTicker string math
  ts/src/pro/idex.ts
Labels: enhancement

#17319 Exchange: add types from pre-TypeScript conversion ccxt.d.ts.
  ts/src/base/Exchange.ts
Labels: enhancement

#17318 binance: Market['strike'] is a number, not a string
  ts/src/base/Exchange.ts
  ts/src/binance.ts
Labels: enhancement

#17328 fix coinex: signature [ci deploy]
  ts/src/coinex.ts
Labels: bug

#17343 feat(bybit): increase positions limit [ci skip]
  ts/src/bybit.ts
Labels: dependencies

#17342 Add OHLCVC type and typings for parseTimeframe() and buildOHLCVC().
  ts/src/base/functions/misc.ts
  ts/src/base/types.ts
Labels: enhancement

#17341 Add Exchang#fetchTime return type.
  ts/src/base/Exchange.ts
Labels: enhancement

#17345 Fix ZB and Hitbtc signing [ci deploy]
  ts/src/hitbtc.ts
  ts/src/static_dependencies/noble-hashes/md5.ts
  ts/src/test/base/functions/test.crypto.ts
Labels: bug

#17363 ignore binance in test
  ts/src/test/base/functions/test.binanceMarkets.ts
Labels: enhancement

#17359 bybit: add get announcement api
  ts/src/bybit.ts
Labels: enhancement

#17360 okx: update saving apis
  package.json
  ts/src/okx.ts
Labels: enhancement

#17358 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#17357 binance: patch ccxt/ccxt#17326
  ts/src/binance.ts
Labels: bug

#17356 fix(bitmex): fetchMarkets
  ts/src/bitmex.ts
Labels: bug

#17355 fix(bitmex): fix #17313
  ts/src/bitmex.ts
  ts/src/pro/bitmex.ts
Labels: bug

#17347 Exhange#setMarkets: Currency.numericId is a number and not a string.
  ts/src/base/Exchange.ts
Labels: enhancement

#17316 okx editOrder
  ts/src/okx.ts
Labels: enhancement

#17156 cryptocom - `fetchDepositWithdrawFees`
  ts/src/cryptocom.ts
Labels: enhancement

#15667 probit - websockets
  ts/src/pro/probit.ts
  ts/src/probit.ts
Labels: enhancement, WS

#17119 mexc3 fetchDeposits/fetchWithdrawals fixes
  ts/src/mexc3.ts
Labels: bug, enhancement

#17381 bybit: add rsa signature
  ts/src/bybit.ts
Labels: enhancement

#17138 feat(mexc3): add mexc3 websockets
  ts/src/abstract/mexc3.ts
  ts/src/mexc3.ts
  ts/src/pro/mexc3.ts
Labels: enhancement, WS

#17402 fix(ts): remove MessageEvent type due to incompatibility with ts5
  ts/src/base/ws/Client.ts
Labels: bug

#17407 fix(types): python3.7 support [ci deploy]
  python/ccxt/base/types.py
Labels: bug

#17408 fix(lbank): signature
  ts/src/lbank.ts
  ts/src/lbank2.ts
Labels: bug

#14798 Transpile examples
  build/transpile.js
  examples/ts/fetch-ohlcv.ts
  package-lock.json
  package.json
Labels: enhancement, important

#17409 fix(kucoin): watchOrders timestamp
  ts/src/pro/kucoin.ts
Labels: bug

#15128 base - safePosition & parsePosition updates
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/bitget.ts
  ts/src/bitmex.ts
  ts/src/btcex.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/currencycom.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/hitbtc3.ts
  ts/src/huobi.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/phemex.ts
  ts/src/woo.ts
  ts/src/zb.ts
Labels: important

#17387 bitget cancelOrders, fetchOpenOrders edits
  ts/src/bitget.ts
Labels: enhancement

#17414 fix(krakenfutures): fix markets clash
  ts/src/krakenfutures.ts
Labels: bug

#17415 ascendex parseTransaction fee
  ts/src/ascendex.ts
Labels: bug

#17420 safeCurrency - string type fix
  ts/src/base/Exchange.ts
Labels: bug

#17419 bitmart: update fetchContractMarkets ccxt/ccxt#17416
  ts/src/bitmart.ts
Labels: bug

#17424 krakenfutures: fix signing for private endpoints
  ts/src/krakenfutures.ts
Labels: bug
