Repository ccxt/ccxt, pull requests merged in 2023-09, with the labels that each got.

#19076 fix(okx): ws sandbox
  ts/src/pro/okx.ts
Labels: bug

#19075 feat(exmo): fetchBalance - margin wallet balance
  ts/src/exmo.ts
Labels: enhancement

#19072 fix(bequant): USD no longer has its currencyId changed to USDT
  ts/src/hitbtc.ts
Labels: bug

#19077 fix(bitmex): fetchFundingRates filtering
  ts/src/bitmex.ts
Labels: bug

#19081 fix(kucoin) - active fields
  skip-tests.json
  ts/src/kucoin.ts
Labels: bug

#19084 fix(base): duplicated markets with different ids
  ts/src/base/Exchange.ts
  ts/src/delta.ts
  ts/src/hitbtc.ts
  ts/src/yobit.ts
Labels: bug

#19095 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19074 feat(exmo): fetchMarkets - margin info
  ts/src/exmo.ts
Labels: enhancement

#19097 fix(base): BCH override
  ts/src/base/Exchange.ts
Labels: bug

#19098 fix(gate): order status
  ts/src/gate.ts
  ts/src/pro/gate.ts
Labels: bug

#19102 binance: update api rate limit
  ts/src/binance.ts
Labels: enhancement

#19094 unification - currency `type`
  ts/src/bigone.ts
  ts/src/bitfinex2.ts
  ts/src/bittrex.ts
  ts/src/kucoin.ts
  ts/src/latoken.ts
  ts/src/lykke.ts
  ts/src/ndax.ts
Labels: enhancement

#19109 fix(latoken): parseTicker response values corrected
  ts/src/latoken.ts
Labels: bug

#19112 fix(binance): bookTicker swap subscription
  ts/src/pro/binance.ts
Labels: bug

#19115 feat(kucoin) - triggerPriceType (QUICK)
  ts/src/kucoinfutures.ts
Labels: enhancement

#19126 bitget: add new market apis
  ts/src/bitget.ts
Labels: enhancement

#19124 feat(tests) - better output
  php/test/test_async.php
  python/ccxt/test/test_async.py
  ts/src/test/test.ts
Labels: enhancement

#19120 feat(exmo): fetchOrderTrades - margin
  ts/src/exmo.ts
Labels: enhancement

#19049 fix(base) - avoid `const array` issue (QUICK)
  ts/src/pro/bitfinex2.ts
  ts/src/pro/blockchaincom.ts
  ts/src/pro/luno.ts
  ts/src/test/base/functions/test.generic.ts
Labels: bug

#19132 fix(test) - PHP typo mistake (QUICK)
  php/test/test_async.php
Labels: bug

#19114 Composer - remove extra (QUICK)
  composer.json
  php/async/Exchange.php
  wiki/Manual.md
Labels: bug

#19107 feat(exmo): fetchMyTrades - margin
  ts/src/exmo.ts
Labels: enhancement

#19142 fix(bingx) - public trade limit (QUICK)
  ts/src/bingx.ts
Labels: enhancement

#19222 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19186 OKX(ws): should login business url
  ts/src/pro/okx.ts
Labels: bug

#18027 feat(hitbtc): websockets class updated from V1 to V3
  ts/src/pro/hitbtc.ts
Labels: enhancement, WS

#19235 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#19232 bigone.transfer add fund type, docstring update
  ts/src/bigone.ts
Labels: enhancement

#19231 fix(bigone): parseTransaction deposit/withdrawal type fix
  ts/src/bigone.ts
Labels: bug

#19228 hollaex.has: createPostOnlyOrder, createOrder docstrings
  ts/src/hollaex.ts
Labels: enhancement

#19224 bitopro: update rl
  ts/src/bitopro.ts
Labels: enhancement

#19238 fix(huobi): fix contract clientOrderId type
  ts/src/huobi.ts
Labels: bug

#19245 Bitmart: fetchOpenInterest
  ts/src/bitmart.ts
Labels: enhancement

#19241 fix(digifinex) - trade max limit for swap (QUICK)
  ts/src/digifinex.ts
Labels: bug

#19246 fix(bequant,hitbtc,fmfw) - fix max trade limit (QUICK)
  ts/src/hitbtc.ts
Labels: bug

#19240 fix(latoken) - min/max trade (QUICK)
  ts/src/latoken.ts
Labels: bug

#19163 fix(btctradeua) - comments (QUICK) [ci skip]
  ts/src/btctradeua.ts
Labels: bug

#19151 fix(bitso) - side & takerOrMaker
  ts/src/bitso.ts
Labels: bug

#19263 fix(wazirx) - max trade limit (QUICK)
  ts/src/wazirx.ts
Labels: bug

#19262 fix(probit) - trades max limit (QUICK)
  ts/src/probit.ts
Labels: bug

#19256 fix(deribit) - max trade limit (QUICK)
  ts/src/deribit.ts
Labels: bug

#19254 fix(bitvavo) - trades max limit (QUICK)
  ts/src/bitvavo.ts
Labels: bug

#19253 fix(bitmex) - trade limit max (QUICK)
  ts/src/bitmex.ts
Labels: bug

#19251 fix(kucoinfutures): fetchFundingRateHistory error handling and others
  ts/src/kucoin.ts
Labels: bug

#19248 fix(bitfinex2) - max trade limit (QUICK)
  ts/src/bitfinex2.ts
Labels: bug

#18556 bybit: migrate to v5 [ci deploy]
  ts/src/bybit.ts
Labels: enhancement

#19267 fix(poloniex): watchOrders fix when a symbol is passed
  ts/src/pro/poloniex.ts
Labels: bug

#19269 Bitmart: setLeverage
  ts/src/bitmart.ts
Labels: enhancement

#19268 bithumb: add apis, update api params
  ts/src/bithumb.ts
Labels: enhancement

#19265 feat(latoken): fetchBalance - type of "funding" accepted
  ts/src/latoken.ts
Labels: enhancement

#19270 fix(gate): order status
  ts/src/gate.ts
Labels: bug

#19242 Bigone stop orders, postOnly, timeInForce
  ts/src/bigone.ts
Labels: bug, enhancement

#19274 Bitmart: private contract endpoints
  ts/src/bitmart.ts
Labels: enhancement

#19272 fix(probit) - bug in fetchCurrencies (QUICK)
  ts/src/probit.ts
Labels: bug

#19116 feat(exmo): createOrder - trigger orders and margin orders
  ts/src/exmo.ts
Labels: enhancement

#19307 exmo(fix): ArgumentsRequired import missing
  ts/src/exmo.ts
Labels: bug

#19292 fix(huobi) - shadow vars rename (QUICK)
  ts/src/pro/huobi.ts
Labels: bug

#19291 fix(hitbtc) - shadow vars rename (QUICK)
  ts/src/pro/hitbtc.ts
Labels: bug

#19304 fix(lbank2) - pre shadow var (QUICK)
  ts/src/lbank2.ts
Labels: bug

#19303 fix(bitget) - pre shadow var (QUICK)
  ts/src/pro/bitget.ts
Labels: bug

#19302 fix(bitmex) - pre shadow var (QUICK)
  ts/src/pro/bitmex.ts
Labels: bug

#19300 fix(currencycom) - pre shadow var (QUICK)
  ts/src/pro/currencycom.ts
Labels: bug

#19299 fix(phemex) - pre shadow var (QUICK)
  ts/src/pro/phemex.ts
Labels: bug

#19298 fix(probit) - pre shadow var (QUICK)
  ts/src/probit.ts
Labels: bug

#19289 fix(coinbase) - shadow vars rename (QUICK)
  ts/src/pro/coinbase.ts
Labels: bug

#19288 fix(bybit) - shadow vars rename 2 (QUICK)
  ts/src/pro/bybit.ts
Labels: bug

#19287 fix(bitvavo) - shadow vars rename (QUICK)
  ts/src/pro/bitvavo.ts
Labels: bug

#19308 update changelog [ci skip]
  CHANGELOG.md
Labels: bug

#19301 fix(cryptocom) - pre shadow var (QUICK)
  ts/src/pro/cryptocom.ts
Labels: bug

#19297 fix(whitebit) - shadow vars rename (QUICK)
  ts/src/pro/whitebit.ts
Labels: bug

#19286 fix(bittrex) - shadow vars rename (QUICK)
  ts/src/pro/bittrex.ts
Labels: bug

#19285 fix(bitfinex2) - shadow vars rename (QUICK)
  ts/src/pro/bitfinex2.ts
Labels: bug

#19284 fix(binance) - shadow vars rename (~QUICK~)
  ts/src/pro/binance.ts
Labels: bug

#19283 fix(ascendex) - shadow vars rename (QUICK)
  ts/src/pro/ascendex.ts
Labels: bug

#19282 fix(okx) - shadow var recursion (QUICK)
  ts/src/okx.ts
Labels: bug

#19280 fix(deribit) - shadows var renamed (QUICK)
  ts/src/deribit.ts
Labels: bug

#19296 fix(poloniex) - shadow vars rename (QUICK)
  ts/src/pro/poloniex.ts
Labels: bug

#19313 bybit: update setMarginMode
  ts/src/bybit.ts
Labels: enhancement

#19312 bybit: remove method usage
  ts/src/bybit.ts
Labels: enhancement

#19294 fix(krakenfutures) - shadow vars rename (QUICK)
  ts/src/pro/krakenfutures.ts
Labels: bug

#19293 fix(huobijp) - shadow vars rename (QUICK)
  ts/src/pro/huobijp.ts
Labels: bug

#19279 fix(bitget) - shadow vars renamed (QUICK)
  ts/src/bitget.ts
Labels: bug

#19277 fix(kucoin): fetchPosion and realizedPnl
  ts/src/kucoinfutures.ts
Labels: enhancement

#19261 fix(lbank) - max trade limit (QUICK)
  ts/src/lbank.ts
Labels: bug

#19258 fix(huobijp) - max trade limit (QUICK)
  ts/src/huobijp.ts
Labels: bug

#19257 fix(huobi) - max trade limit (QUICK)
  ts/src/huobi.ts
Labels: bug

#19314 feat(kucoin): add watchTickers
  ts/src/pro/kucoin.ts
Labels: enhancement

#19295 fix(kucoinfutures) - shadow vars rename (QUICK)
  ts/src/pro/kucoinfutures.ts
Labels: bug

#19260 fix(lbank2) - max trade limit (QUICK)
  ts/src/lbank2.ts
Labels: bug

#19255 fix(currencycom) - max trade limit (QUICK)
  ts/src/currencycom.ts
Labels: bug

#19247 fix(binance) - max trade limit (~QUICK~)
  ts/src/binance.ts
Labels: bug

#19321 comments across different exchanges (QUICK)
  ts/src/binance.ts
  ts/src/bitbank.ts
  ts/src/bitfinex.ts
  ts/src/bitflyer.ts
  ts/src/bitforex.ts
  ts/src/bitget.ts
  ts/src/bitstamp1.ts
  ts/src/bl3p.ts
  ts/src/coinbasepro.ts
Labels: enhancement

#19319 fix(phemex) - pre shadow vars (QUICK)
  ts/src/pro/phemex.ts
Labels: bug

#19318 fix(kucoin) - pre shadow var (QUICK)
  ts/src/pro/kucoin.ts
Labels: bug

#19278 fix(bybit) - shadows var rename (QUICK)
  ts/src/bybit.ts
Labels: bug

#19122 fix(skips) - unskip mexc & removal phpskip (QUICK)
  skip-tests.json
  ts/src/test/test.ts
Labels: enhancement

#19338 bingx: add apis
  ts/src/bingx.ts
Labels: enhancement

#19337 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19335 Bitmart: fetchFundingRate
  ts/src/bitmart.ts
Labels: enhancement

#19334 gemini: add AuthenticationError
  ts/src/gemini.ts
Labels: enhancement

#19342 fix(bybit): watchOrders swap parsing
  ts/src/pro/bybit.ts
Labels: bug

#19333 bl3p.has: createStopOrder == false
  ts/src/bl3p.ts
Labels: enhancement

#19330 docs(bingx): createOrder - docstring update triggerPrice type
  ts/src/bingx.ts
Labels: bug

#19329 fix!(bkex): delist bkex
  ts/ccxt.ts
  ts/src/bkex.ts
Labels: enhancement

#19316 binance WS - pre shadow vars (~QUICK~)
  ts/src/pro/binance.ts
Labels: bug

#19290 fix(coinbasepro) - shadow vars rename (QUICK)
  ts/src/pro/coinbasepro.ts
Labels: bug

#19350 bingx: add fetchDepositAddress
  ts/src/bingx.ts
Labels: enhancement

#19349 Bitmart: fetchOrderBook, add swap support
  ts/src/bitmart.ts
Labels: enhancement

#19344 fix(bybit): error mapping
  build/export-exchanges.js
  ts/ccxt.ts
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
  ts/src/bybit.ts
Labels: bug

#19354 Bitmart: transfer, fetchTransfers, add swap support
  ts/src/bitmart.ts
Labels: enhancement

#19331 docs(bitrue): createOrder - update docstring
  ts/src/bitrue.ts
Labels: enhancement

#19359 bitfinex2: update apis
  ts/src/bitfinex2.ts
Labels: enhancement

#19358 bitbank: add @see
  ts/src/bitbank.ts
Labels: enhancement

#19365 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19367 Revert "Bybit: createOrder, remove stop order trigger direction"
  ts/src/bybit.ts
Labels: bug

#19364 Bitmart: cancelAllOrders, add swap support
  ts/src/bitmart.ts
Labels: enhancement

#19363 fix(kucoin) - exceptional w/d currency
  ts/src/kucoin.ts
Labels: bug

#19371 bitvavo - skip quoteVolume & baseVolume (QUICK)
  skip-tests.json
Labels: bug

#19373 krakenfutures - fix #19372 - add clientOrderId
  ts/src/krakenfutures.ts
Labels: bug

#19375 feat(bybit): add watchTickers
  ts/src/base/Exchange.ts
  ts/src/pro/bybit.ts
Labels: enhancement

#19117 feat(exmo): fetchOpenOrders, cancelOrder, editOrder - stop and margin orders
  ts/src/exmo.ts
Labels: enhancement

#19108 feat(binance) - cancelOrders implementation (contract only)
  ts/src/binance.ts
Labels: enhancement

#19379 feat(bitget): add watchTickers
  ts/src/pro/bitget.ts
Labels: enhancement

#19382 Bitmart: update several methods to v4
  ts/src/bitmart.ts
Labels: enhancement

#19386 Bitmart: fetchOpenOrders, add swap support
  ts/src/bitmart.ts
Labels: enhancement

#19387 binance: remove deprecated apis
  ts/src/binance.ts
Labels: enhancement

#19388 feat(woo): add watchBalance
  ts/src/pro/woo.ts
Labels: enhancement

#19276 fix(base) - ESLINT no shadow
  ts/src/.eslintrc
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/exmo.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bybit.ts
  ts/src/test/test.ts
Labels: bug

#19389 fix: watchXForSymbols example [ci skip]
  examples/py/multiple-subscriptions-watchXForSymbols.py
Labels: bug

#19394 bitflyer: add @see
  ts/src/bitflyer.ts
Labels: enhancement

#19392 Bitmart: fetchOrder, add swap support
  ts/src/bitmart.ts
Labels: enhancement

#19398 fix(bitfinex2): parseLedgerEntryType classification
  ts/src/bitfinex2.ts
Labels: bug

#19401 bitget: add @see
  ts/src/bitget.ts
Labels: enhancement

#19405 feat(phemex): add from/to endpoint to fetchOHLCV
  ts/src/phemex.ts
Labels: enhancement

#19393 Bybit: changed the triggerDirection for stop orders
  ts/src/bybit.ts
Labels: bug

#19409 Bitmart: fetchMyTrades, add swap support
  ts/src/bitmart.ts
Labels: enhancement

#19410 feat(bitmart): add cancelorder swap support
  ts/src/bitmart.ts
Labels: enhancement

#19408 binance.has fetchL3OrderBook and fetchWithdrawAddresses are false
  ts/src/binance.ts
Labels: enhancement

#19418 bybit: add new api
  ts/src/bybit.ts
Labels: enhancement

#19420 feat(coinbasepro): add since/until to fetchMyTrades and fetchOrders
  ts/src/coinbasepro.ts
Labels: enhancement

#19416 Bybit: editOrder, stopLoss takeProfit, enable values to be set to zero
  ts/src/bybit.ts
Labels: bug
