Repository ccxt/ccxt, pull requests merged in 2023-05, with the labels that each got.

#17717 hitbtc: createDepositAddress () returns a DepositAddressResponse
  ts/src/hitbtc.ts
Labels: bug

#17734 fix(xt): add adjustForTimeDifference inside options
  ts/src/xt.ts
Labels: bug

#17739 ccxt.pro manual removed duplicate watchOrders
  wiki/ccxt.pro.manual.md
Labels: enhancement

#17738 different exchanges - simple fix strings
  ts/src/bitget.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
  ts/src/poloniex.ts
  ts/src/stex.ts
Labels: bug

#17747 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#17742 kucoinfutures: adjust parseOrder cost
  ts/src/kucoinfutures.ts
Labels: bug

#17740 mexc.parseTrade 1,2 -> buy/sell
  ts/src/mexc.ts
Labels: bug

#17748 appveyor - use node v16 instead of v14
  appveyor.yml
Labels: enhancement

#17745 bitget: add p2p apis
  ts/src/bitget.ts
Labels: enhancement

#17737 Update huobi.ts
  ts/src/huobi.ts
Labels: bug

#17705 filterBySinceLimit and filterByValueSinceLimit both sort before filtering
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/btcturk.ts
  ts/src/pro/alpaca.ts
  ts/src/pro/ascendex.ts
  ts/src/pro/binance.ts
  ts/src/pro/bitfinex.ts
  ts/src/pro/bitfinex2.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bitmart.ts
  ts/src/pro/bitmex.ts
  ts/src/pro/bitopro.ts
  ts/src/pro/bitrue.ts
  ts/src/pro/bitstamp.ts
  ts/src/pro/bittrex.ts
  ts/src/pro/bitvavo.ts
  ts/src/pro/btcex.ts
  ts/src/pro/bybit.ts
  ts/src/pro/cex.ts
  ts/src/pro/coinbasepro.ts
  ts/src/pro/coinex.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/currencycom.ts
  ts/src/pro/deribit.ts
  ts/src/pro/exmo.ts
  ts/src/pro/gate.ts
  ts/src/pro/gemini.ts
  ts/src/pro/hitbtc.ts
  ts/src/pro/hollaex.ts
  ts/src/pro/huobi.ts
  ts/src/pro/huobijp.ts
  ts/src/pro/idex.ts
  ts/src/pro/independentreserve.ts
  ts/src/pro/kraken.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/luno.ts
  ts/src/pro/mexc.ts
  ts/src/pro/ndax.ts
  ts/src/pro/okcoin.ts
  ts/src/pro/okx.ts
  ts/src/pro/phemex.ts
  ts/src/pro/probit.ts
  ts/src/pro/upbit.ts
  ts/src/pro/wazirx.ts
  ts/src/pro/whitebit.ts
  ts/src/pro/woo.ts
  ts/src/whitebit.ts
Labels: bug, enhancement

#17752 Build: fix __init__ inside abstract/ [ci deploy]
  build/generateImplicitAPI.js
  python/ccxt/abstract/__init__.py
Labels: bug

#17761 Align ascii
  postinstall.js
Labels: enhancement

#17759 Binance: fetchCanceledOrders
  ts/src/binance.ts
Labels: bug

#17758 base - add info
  ts/src/base/Exchange.ts
Labels: bug

#17764 fix(Krakenfutures): fix postOnly
  ts/src/krakenfutures.ts
Labels: bug

#17765 fix(Idex): fechTransactionHelper calls
  ts/src/idex.ts
Labels: bug

#17503 Krakenfutures sockets
  pro-tests.json
  ts/src/krakenfutures.ts
  ts/src/pro/krakenfutures.ts
Labels: new exchange, WS

#17766 fix(binance): fetchCanceledOrders options support
  ts/src/binance.ts
Labels: bug

#17760 huobi createOrder default stopOperator for stop orders
  ts/src/huobi.ts
Labels: enhancement

#17772 bitget fetchOHLCV docstring @see
  ts/src/bitget.ts
Labels: enhancement

#17775 fix: filterByLimit
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: bug

#17770 binance parseWsOrder add reduceOnly.
  ts/src/pro/binance.ts
Labels: enhancement

#17777 fix(XT): fix active market
  ts/src/xt.ts
Labels: enhancement

#17746 bitget: update position api
  ts/src/bitget.ts
Labels: enhancement

#17778 feat(Phemex): add USD support to fetchFundingRateHistory
  ts/src/phemex.ts
Labels: enhancement

#17779 feat: transpile filterBySinceLimit/Value
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#17790 bitget - expiry 0 missing
  ts/src/bitget.ts
Labels: bug

#17789 bitmart - settleId
  ts/src/bitmart.ts
Labels: bug

#17788 currencycom - type fix
  ts/src/currencycom.ts
Labels: bug

#17798 stex: update links for jsdoc
  ts/src/stex.ts
Labels: enhancement

#17795 Huobi: fetchOrders, fetchOpenOrders, add trigger, stop-loss and take-profit support
  ts/src/huobi.ts
Labels: bug

#17785 huobi fetchCurrencies fix
  ts/src/huobi.ts
Labels: enhancement

#17792 bitget timeframes
  ts/src/bitget.ts
Labels: enhancement

#17806 fix(whitebit): signing in Python [ci deploy]
  ts/src/whitebit.ts
Labels: bug

#17804 feat(xt): remove bigInt usage
  ts/src/xt.ts
Labels: bug

#17809 fix(xt): php signing [ci deploy]
  ts/src/xt.ts
Labels: bug

#17811 bitget - fix milliseconds
  ts/src/bitget.ts
Labels: bug

#17807 Currencycom - fix margin
  ts/src/currencycom.ts
Labels: bug

#17805 bitmart - fix expiry
  ts/src/bitmart.ts
Labels: bug

#17815 fix(bybit): USDC market orders v1
  ts/src/bybit.ts
Labels: bug

#17813 Huobi: cancelOrder, trigger, stop-loss and take-profit support
  ts/src/huobi.ts
Labels: enhancement

#17819 fix: transpile python IndexType [ci skip]
  build/transpile.js
Labels: bug

#17816 Fix build_ohlcvc with single trade [ci skip]
  python/ccxt/base/exchange.py
  ts/src/base/functions/misc.ts
Labels: bug

#17829 fix(deribit): fix #17729
  ts/src/pro/deribit.ts
Labels: bug

#17823 Tests: move proxy to skip-tests.json [ci skip]
  keys.json
  skip-tests.json
  ts/src/test/test.ts
Labels: enhancement

#17832 fix(Coinex): Required positionId for reduceOnly orders
  ts/src/coinex.ts
Labels: enhancement

#17825 fix:php ArrayCache use in watchOrders and watchTrades
  build/transpile.js
  php/Exchange.php
Labels: bug

#17821 Huobi: cancelAllOrders, trigger stop-loss and take-profit support
  ts/src/huobi.ts
Labels: enhancement

#17834 fix(bitfinex2): checksum when length < 25
  ts/src/pro/bitfinex2.ts
Labels: bug

#17849 bybit: remove exceptions.ws
  ts/src/pro/bybit.ts
Labels: enhancement

#17848 coinbasepro: handle error message for ws
  ts/src/pro/coinbasepro.ts
Labels: enhancement

#17840 okx - funding rate integer
  ts/src/okx.ts
Labels: bug

#17859 binance: add sapiGetPortfolioAssetIndexPrice
  ts/src/binance.ts
Labels: enhancement

#17860 bybit: update fetchOpenInterestHistory
  ts/src/bybit.ts
Labels: enhancement

#17857 Binance: fetchTicker, fetchTickers, add option support
  ts/src/binance.ts
Labels: enhancement

#17225 fix(coinex): parse cfx deposit address correctly. fix #17197
  ts/src/coinex.ts
Labels: bug

#16349 Exchange.js unified currency structure
  build/transpile.js
  ts/src/base/Exchange.ts
Labels: enhancement

#17866 krakenfutures transfer remove amountToPrecision
  ts/src/krakenfutures.ts
Labels: bug

#17868 Binance: update python option examples [ci skip]
  examples/py/async-binance-cancel-option-order.py
  examples/py/async-binance-create-option-order.py
  examples/py/async-binance-fetch-option-OHLCV.py
  examples/py/async-binance-fetch-option-order.py
  examples/py/async-binance-fetch-option-orderbook.py
  examples/py/async-binance-fetch-option-position.py
  examples/py/async-binance-fetch-option-ticker.py
  ts/src/binance.ts
Labels: enhancement

#17879 feat(cryptocom): add since to cryptocom
  ts/src/cryptocom.ts
Labels: enhancement

#15664 blockchaincom - ws
  ts/src/blockchaincom.ts
  ts/src/pro/blockchaincom.ts
Labels: enhancement, WS

#17881 fix(bitget): remove symbol requirement from fetchOpenOrders
  ts/src/bitget.ts
Labels: enhancement

#17884 probit fetchCurrencies network precision fix
  ts/src/probit.ts
Labels: bug

#17883 xt new endpoints
  ts/src/xt.ts
Labels: enhancement

#17890 Coinbase: fetchOrders, fetchOrdersByStatus, fix since
  ts/src/coinbase.ts
Labels: enhancement

#17889 Gate: fetchTrades add option support
  ts/src/gate.ts
Labels: enhancement

#17892 feat(xt): add networkError
  ts/src/xt.ts
Labels: enhancement

#17887 xt parseMarket fixes
  ts/src/xt.ts
Labels: enhancement

#17871 exchange.currencyStructure -> exchange.safeCurrencyStructure
  ts/src/base/Exchange.ts
Labels: enhancement

#17896 fix build: add safeCurrencyStructure snake case
  build/transpile.js
Labels: bug

#17898 binance: add porfolio margin apis
  ts/src/binance.ts
Labels: enhancement

#16152 coinmate parseTransaction unification
  ts/src/coinmate.ts
Labels: enhancement

#17901 ascendex parseOrder fix
  ts/src/ascendex.ts
Labels: enhancement

#17912 fix(coinex): fetchTradingFee market handling
  ts/src/coinex.ts
Labels: bug

#17908 kucoinfutures: fetchPosition
  ts/src/kucoinfutures.ts
Labels: enhancement

#17906 bitget: ws subscribe stop orders channel 'ordersAlgo'
  ts/src/pro/bitget.ts
Labels: enhancement

#17914 fix(bitfinex): parseTicker marketId
  ts/src/bitfinex.ts
Labels: bug

#17913 fix(gate): fix status for partial orders and canceled orders
  ts/src/pro/gate.ts
Labels: bug

#17921 fix(phemex): ping pong handling
  ts/src/pro/phemex.ts
Labels: bug

#17927 filterByLimit is descending by default
  ts/src/base/Exchange.ts
Labels: bug

#17925 base - isInteger
  build/transpile.js
Labels: enhancement

#17928 bitget: update transfer / withdraw to v2 api
  ts/src/bitget.ts
Labels: enhancement

#15286 bitpanda - websockets
  php/pro/test/test.php
  skip-tests.json
  ts/src/bitpanda.ts
  ts/src/pro/bitpanda.ts
Labels: WS

#17931 xt parseTransaction fixes
  ts/src/xt.ts
Labels: enhancement

#17935 bitget: add user apis
  ts/src/bitget.ts
Labels: enhancement

#17943 bitget update apis
  ts/src/bitget.ts
Labels: enhancement

#17946 Fix field name
  python/ccxt/bitso.py
Labels: bug

#17945 feat(gate): fetchMyTrades, replace swap endpoint
  ts/src/gate.ts
Labels: enhancement

#17942 bitget: patch returned order is defined
  ts/src/bitget.ts
Labels: bug

#17933 Build: atomic builds and tests inside PR [ci skip]
  .travis.yml
  build.sh
Labels: enhancement

#17954 Okx: fetchTrades, add option support
  ts/src/okx.ts
Labels: enhancement

#17936 Binance: editOrder, add swap and future support
  ts/src/binance.ts
Labels: enhancement

#17957 build: fix return code [ci skip]
  build.sh
Labels: bug

#17944 Bitget: createOrder, add position stop-loss and take-profit
  ts/src/bitget.ts
Labels: enhancement

#17965 bybit: add new position apis
  ts/src/bybit.ts
Labels: enhancement

#17969 bitmart - add endpoint
  ts/src/bitmart.ts
Labels: enhancement

#17972 fix(mexc): remove await from checkRequiredCredentials
  ts/src/pro/mexc.ts
Labels: bug

#17963 Okx: fetchOpenInterestHistory, add option support
  ts/src/okx.ts
Labels: enhancement

#17974 fix(okx): fetchOpenInterestHistory in operator
  ts/src/okx.ts
Labels: bug

#17968 build: improve linting time
  .travis.yml
  build.sh
  package.json
  python/qa.py
  python/tox.ini
  ts/src/bybit.ts
  tsconfig.json
Labels: enhancement

#17977 bybit: update setPositionMode
  ts/src/bybit.ts
Labels: enhancement

#17981 fix(coinex): ws authentication flow + watchOrders [ci deploy]
  ts/src/pro/coinex.ts
Labels: bug

#17984 binance: add api sapiPostCapitalDepositCreditApply
  ts/src/binance.ts
Labels: enhancement

#17987 paymium: update jsdoc [ci skip]
  ts/src/paymium.ts
Labels: enhancement

#17970 remove - networkCodesToIds
  ts/src/base/Exchange.ts
Labels: enhancement

#17989 fix(kucoinfutures): add throw to fetchTickers [ci skip]
  ts/src/kucoinfutures.ts
Labels: bug

#17324 Poloniexfutures sockets
  pro-tests.json
  ts/src/poloniexfutures.ts
  ts/src/pro/poloniexfutures.ts
Labels: new exchange, WS

#17998 Phemex set leverage hedged
  ts/src/phemex.ts
Labels: enhancement

#18002 bybit: update fetchOpenInterestHistory
  ts/src/bybit.ts
Labels: enhancement

#18007 added skips - failing build
  skip-tests.json
Labels: bug

#18008 fix(woo): ws order cost - fix #17996
  ts/src/pro/woo.ts
Labels: bug

#18009 fix(bitfinex2): watchOrders timestamp - fix #18001
  ts/src/pro/bitfinex2.ts
Labels: bug

#17976 appveyor & travis - build.sh updates
  .travis.yml
  appveyor.yml
  build.sh
  php/pro/test/syntax.php
  php/test/syntax.php
  python/qa.py
Labels: enhancement

#18017 fix(mexc): fix watchOrders
  ts/src/pro/mexc.ts
Labels: bug

#18019 fix(Exchange.py): proper filter_by_limit casing
  build/transpile.js
Labels: enhancement

#18022 fix(bybit): remove expiry from swap markets
  ts/src/bybit.ts
Labels: bug

#18038 huobi - copy params
  ts/src/pro/huobi.ts
Labels: bug

#18036 mexc - params copy
  ts/src/mexc.ts
Labels: bug

#18035 bybit - copy params
  ts/src/bybit.ts
Labels: bug

#18034 xt - params copy
  ts/src/xt.ts
Labels: bug

#18029 bybit: update pagination for fetchOrders
  ts/src/bybit.ts
Labels: enhancement

#18039 phemex - params
  ts/src/pro/phemex.ts
Labels: bug

#18043 fix(bitget): watchBalance fix
  ts/src/pro/bitget.ts
Labels: bug

#18046 fix(binance): fix editOrder timestamp update, fix #18028
  ts/src/pro/binance.ts
Labels: bug

#18048 bitget- fix ohlcv timeframes
  ts/src/bitget.ts
Labels: bug

#18047 yobit - fetchtickers
  ts/src/yobit.ts
Labels: bug

#18023 fix(coinex): watchTickers - new watchTickers implementation
  ts/src/base/Exchange.ts
  ts/src/pro/coinex.ts
Labels: bug

#18055 fix(binance): editOrder ws timestamp, fix #18051
  ts/src/pro/binance.ts
Labels: bug

#18062 fix(krakenfutures): handle pong event properly
  ts/src/pro/krakenfutures.ts
Labels: bug

#16886 poloniex web sockets [ci deploy]
  skip-tests.json
  ts/src/poloniex.ts
  ts/src/pro/poloniex.ts
Labels: new exchange, WS

#18075 fix(Readme): update nuget link [ci skip]
  README.md
Labels: bug

#18083 Gate: createOrder, add option support
  ts/src/gate.ts
Labels: enhancement

#18085 Gate: fetchOrder, fetchOrdersByStatus, add option support
  ts/src/gate.ts
Labels: enhancement

#18087 mexc: add broker api
  ts/src/mexc.ts
Labels: enhancement

#18084 woo: add broker id
  ts/src/woo.ts
Labels: enhancement
