Repository ccxt/ccxt, pull requests merged in 2023-02, with the labels that each got.

#16704 bitbns: removed empty timeframes object
  js/bitbns.js
Labels: bug

#16712 Bitget :: fix parseBalance
  js/bitget.js
Labels: bug

#16706 coinbasepro parseNumber for describe fees
  js/coinbasepro.js
Labels: enhancement

#16705 binance pro parseTrade string math
  js/pro/binance.js
Labels: enhancement

#16711 Tests :: small refactor and improvements
  examples/php/cli.php
  js/test/test.js
  keys.json
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
Labels: enhancement

#16717 Bitmex :: add broker id
  js/bitmex.js
Labels: enhancement

#16714 Run-tests :: options forwarding + old bug fix
  js/test/test.js
  keys.json
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
  run-tests.js
Labels: bug, enhancement

#16715 huobi - implicit api
  js/huobi.js
Labels: enhancement

#16725 Mexc3 fetch ticker precise
  js/mexc3.js
Labels: enhancement

#16722 fetchcurrencies - removal of address
  js/bittrex.js
  js/currencycom.js
Labels: bug

#16687 Kucoinfutures fetchFundingRateHistory
  js/kucoin.js
  js/kucoinfutures.js
Labels: enhancement

#16731 okx - fetchPosition fix
  js/okx.js
Labels: bug

#16730 cli.py - unicode support
  examples/py/cli.py
Labels: bug

#16729 huobi - fix balance
  js/huobi.js
Labels: bug

#16744 Tests fix
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
  run-tests.js
Labels: bug

#16741 binance: patch ccxt/ccxt#16702
  js/binance.js
Labels: bug

#16740 binance: update apis
  js/binance.js
Labels: enhancement

#16733 delta - fix position
  js/bybit.js
  js/delta.js
  js/okx.js
Labels: bug

#16735 Bybit fetchDeposits, add until parameter, docstring edits
  js/bybit.js
Labels: enhancement

#16736 bybit.createReduceOnlyOrder["has"] === true
  js/bybit.js
Labels: enhancement

#16734 bitcoincom fees uses parseNumber
  js/pro/bitcoincom.js
Labels: enhancement

#16728 delta["options"]["fees"] uses string numbers
  js/delta.js
Labels: enhancement

#15903 ace: new exchange
  js/ace.js
Labels: new exchange

#16758 detla - zero fix
  js/delta.js
Labels: bug

#16745 bitget: fetchFundingHistory
  js/bitget.js
Labels: enhancement

#16742 Bitget: fetchCanceledOrders
  js/bitget.js
Labels: enhancement

#16751 exchange pro base - fix delay to match js
  python/ccxt/pro/base/exchange.py
Labels: bug

#16763 Tests python :: restore orders line
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
Labels: bug

#16771 JS: private tests fix
  js/test/test.js
Labels: bug

#16775 Woo :: fix swap market orders
  js/woo.js
Labels: bug

#16778 Fix fetchOHLCV
  js/kraken.js
  js/kucoinfutures.js
  js/poloniexfutures.js
Labels: bug

#16781 okx: Fix validation of posSide in setLeverage
  js/okx.js
Labels: enhancement

#16779 Bitget : Simulated SUSDT
  js/bitget.js
  js/pro/bitget.js
Labels: enhancement

#16788 Add max retries option
  js/pro/bitstamp.js
  js/pro/btcex.js
  js/pro/gate.js
  js/pro/kucoin.js
  js/pro/kucoinfutures.js
Labels: bug

#16789 Bitget Websocket private : updated to handle SUMCBL
  js/pro/bitget.js
Labels: bug

#16764 Moved parseIncomes from binance to base exchange
  js/base/Exchange.js
  js/binance.js
  js/huobi.js
  js/woo.js
Labels: enhancement

#16793 gate: fix parse_order for spot orders
  js/gate.js
Labels: bug

#16795 Huobi transfer margin
  js/huobi.js
Labels: enhancement

#16804 Woo :: fix createMarketBuyRequiresPrice
  js/woo.js
Labels: bug

#15521 test - reorganize for pre-transpilation stage
  js/test/test.js
  keys.json
Labels: enhancement, important

#16806 gate: add price_type ccxt/ccxt#16749
  js/gate.js
Labels: bug

#16815 huobi.fetchPositions check params for subType
  js/huobi.js
Labels: enhancement

#16814 transfer method does not add data via extend
  js/binance.js
  js/digifinex.js
  js/gate.js
  js/hitbtc.js
  js/hitbtc3.js
  js/whitebit.js
Labels: bug, enhancement

#16808 docstring - replace array for [string] or [object]
  js/btcex.js
  js/coinex.js
  js/pro/binance.js
  js/pro/bitrue.js
  js/pro/gate.js
  js/pro/wazirx.js
Labels: WS

#16807 coinex - watchTickers, fix watchTicker
  js/pro/coinex.js
Labels: bug, enhancement, WS

#16823 bybit - fetchOrders - fix #16822
  js/bybit.js
Labels: bug

#16821 Coinbase: fetchMyTrades, fix since
  js/coinbase.js
Labels: bug

#16824 Tests :: remove duplicated fetchBorrowInterest entry
  js/test/test.js
Labels: bug

#16811 coinex - watchOrderBook - allow multiple subscriptions
  js/pro/coinex.js
Labels: WS

#16826 Coinex :: fix fetchMyTrades
  js/coinex.js
Labels: bug

#16833 woo: update some endpoints to v3
  js/woo.js
Labels: enhancement

#16810 coinex - watchTrades - allow subscribe to several symbols
  js/pro/coinex.js
Labels: WS

#16840 Binance :: fix fetchMarkets
  js/binance.js
  js/binanceus.js
  keys.json
Labels: bug

#16846 deribit: check whether price is market_price ccxt/ccxt#16842
  js/deribit.js
Labels: bug

#16850 Bybit :: fix signature
  js/bybit.js
Labels: bug

#16854 okx: support authenticate for public ws ccxt/ccxt#16853
  js/pro/okx.js
Labels: bug

#16851 bitget.fetchDepositAddress add network param
  js/bitget.js
Labels: enhancement

#16816 Binance: createOrder, option support
  js/binance.js
Labels: enhancement

#16829 Binance: cancelAllOrders, add option support
  js/binance.js
Labels: enhancement

#16837 binance: add v4/sub-account/assets
  js/binance.js
Labels: enhancement

#16831 Independentreserve - websockets
  js/independentreserve.js
  js/pro/independentreserve.js
  js/pro/test/Exchange/test.watchTrades.js
  php/pro/test/Exchange/test_watch_trades.php
  python/ccxt/pro/test/exchange/test_watch_trades.py
Labels: enhancement, WS

#16861 binance - fix watchOrderbook in testnet
  js/pro/binance.js
Labels: bug

#16844 Binance: fetchBalance, add option support
  js/binance.js
Labels: enhancement

#16852 Binance: fetchTrades, add option support
  js/binance.js
Labels: enhancement

#15193 Ndax fetch deposits
  js/ndax.js
Labels: bug

#16863 huobi.fetchFundingHistory: all endpoints can take market symbol
  js/huobi.js
Labels: bug

#16868 Fix browserified version
  build/vss.js
Labels: bug

#16869 Vss global flag
  build/vss.js
Labels: bug

#16870 okx: add error codes
  js/okx.js
Labels: enhancement

#16872 bitflyer: fix markets conflict
  js/bitflyer.js
Labels: bug

#16874 Update mexc3
  js/mexc3.js
Labels: enhancement

#16882 Fix bug bitget sandbox mode
  js/bitget.js
Labels: bug

#16885 fix: bitget watchBalance swap
  js/pro/bitget.js
Labels: bug

#16792 feat: Add auto Changelog.md
  .travis.yml
  build/push.sh
Labels: enhancement

#16892 feat(Binance): support different ids in editOrder
  js/binance.js
Labels: enhancement

#16903 fix(Bybit): fetchWithdrawals since param
  js/bybit.js
Labels: bug

#16904 fix(Phemex): fetchOHLCV spot and contract
  js/phemex.js
Labels: bug

#16908 fix(Bitfinex2): fetchTrades symbol parsing
  js/bitfinex2.js
Labels: bug

#16910 fix(Bitfinex2): await client send
  js/pro/bitfinex2.js
Labels: bug

#16917 feat(Binance): add mark/index stream to watchOHLCV
  js/pro/binance.js
Labels: enhancement

#16916 Origin/exbugs
  js/gate.js
Labels: bug

#16921 fix(Bybit): fetchSpotOpenOrders symbol
  js/bybit.js
Labels: bug

#16924 okx: add new api
  js/okx.js
Labels: enhancement

#16922 coinbase: fix quote size for market buy order ccxt/ccxt#16918
  js/coinbase.js
Labels: bug

#16923 code - fixes for deposit address
  js/bybit.js
  js/digifinex.js
  js/gemini.js
  js/huobi.js
  js/okcoin.js
  js/okx.js
  js/probit.js
  js/upbit.js
Labels: bug

#15133 [new exchange] krakenfutures (re-added PR)
  js/krakenfutures.js
Labels: new exchange

#16927 fix(Binance): parseTrade spot margin trades
  js/binance.js
Labels: bug

#16928 feat(Okx): add positions history method
  js/okx.js
Labels: enhancement

#16934 btcex fetchMyTrades fix
  js/btcex.js
Labels: bug

#16947 bybit: patch fetchTransfers ccxt/ccxt#16945
  js/bybit.js
Labels: bug

#16948 feat(ccxt.d.ts): add transfer and setLeverage types
  ccxt.d.ts
Labels: enhancement

#16950 fix(Binance): fix parseTrades margin
  js/binance.js
Labels: bug

#16951 fix(Kucoin): fix transaction status
  js/kucoin.js
Labels: bug

#16971 fix(Krakenfutures): fix parseTicker
  js/krakenfutures.js
Labels: bug

#16972 krakenfutures : fix build
  js/krakenfutures.js
Labels: bug

#16954 bitget.fetchMarkets contract size is 1
  js/bitget.js
Labels: bug

#16953 fix(kucoin): watchBalance add info and time to balance structure
  js/pro/kucoin.js
Labels: bug

#16981 [krakenfutures] Fix fetchTicker to take market id
  js/base/Exchange.js
Labels: bug

#16995 fix(Gate): watchOrders without symbol
  js/pro/gate.js
Labels: bug

#16991 fix(gate): reset correctly orderbook after invalid nonce error
  js/pro/gate.js
Labels: bug

#16992 binance: add new sapis
  js/binance.js
Labels: enhancement

#16990 fix(huobi): unhandled errors
  js/pro/huobi.js
Labels: bug

#17000 fix(exmo): watchBalance info
  js/pro/exmo.js
Labels: bug
