Repository ccxt/ccxt, pull requests merged in 2023-08, with the labels that each got.

#18728 bitflyer.parseTransaction string math
  ts/src/bitflyer.ts
Labels: enhancement

#18730 probit.createOrder string math
  ts/src/probit.ts
Labels: enhancement

#18729 coinex withdraw takes params["network"]
  ts/src/coinex.ts
Labels: enhancement

#18745 fix(kucoin): orders using params["triggerPrice"] can be properly placed
  ts/src/kucoin.ts
Labels: bug

#18742 Bitfinex pro parse trade string math
  ts/src/pro/bitfinex.ts
Labels: enhancement

#18753 fix(bitmexWs): normalize orderbook amounts
  ts/src/pro/bitmex.ts
Labels: bug

#18751 kraken: add BalanceEx api
  ts/src/kraken.ts
Labels: enhancement

#18750 binance: add /papi/v1/asset-collection
  ts/src/binance.ts
Labels: enhancement

#18744 Huobijp parseTrade string math
  ts/src/huobijp.ts
Labels: enhancement

#18754 fix(kucoin) - networks re-enable with 2 retry
  ts/src/kucoin.ts
Labels: enhancement

#18428 Okx limits
  ts/src/okx.ts
Labels: enhancement

#18415 Bitfinex2 string math
  ts/src/pro/bitfinex2.ts
Labels: enhancement

#18761 bitget: add apis for copy trading
  ts/src/bitget.ts
Labels: enhancement

#18758 fix(bitfinex): handleOrderBook - string math
  ts/src/pro/bitfinex.ts
Labels: enhancement

#18757 fix(gate): php parseOrder - fix
  ts/src/gate.ts
Labels: bug

#18674 ContractUnavailable error type
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
  ts/src/okx.ts
Labels: enhancement

#18763 fix(bitget): orderbook checksum
  ts/src/pro/bitget.ts
Labels: bug

#18765 fix(bingx): add GTC by default for swap markets
  ts/src/bingx.ts
Labels: bug

#18764 fix(bittrex) - missing ohlcv
  ts/src/pro/bittrex.ts
Labels: enhancement

#18773 fix(bingx): default spot tif
  ts/src/bingx.ts
Labels: bug

#18772 woo: add apis
  ts/src/woo.ts
Labels: enhancement

#18774 fix(delta): fundingRate scale
  ts/src/delta.ts
Labels: bug

#18770 huobi: update fetchMyTrades
  ts/src/huobi.ts
Labels: bug

#18760 Bitget: update stopLoss and takeProfit implementation
  ts/src/bitget.ts
Labels: enhancement

#18777 fix(bitvavo): currency precision
  ts/src/bitvavo.ts
Labels: bug

#18776 feat(bingx): add standard futures
  ts/src/bingx.ts
Labels: enhancement

#18781 feat(deribit): add fetchFundingRate and fetchFundingRateHistory
  ts/src/deribit.ts
Labels: enhancement

#18783 feat(whitebit): add fundingRate methods
  ts/src/whitebit.ts
Labels: enhancement

#18788 kucoin - has == false for unimplementable methods
  ts/src/kucoin.ts
Labels: enhancement

#18782 feat(bitfinex2): add funding rate methods
  ts/src/bitfinex2.ts
Labels: enhancement

#18792 fix(poloniex): cancelOrder error
  ts/src/poloniex.ts
Labels: bug

#18793 huobi: add apis
  ts/src/huobi.ts
Labels: enhancement

#18798 CANCELED order status fixed parse bingx.py
  ts/src/bingx.ts
Labels: bug

#18790 base - move methods into transpilable area
  php/pro/ClientTrait.php
  python/ccxt/async_support/base/exchange.py
  ts/src/.eslintrc
  ts/src/base/Exchange.ts
Labels: enhancement

#18779 fix(bittrex) - cosmetical changes to watchOrderBook
  ts/src/pro/bittrex.ts
Labels: enhancement

#18803 Poloniex - allow multiple subscriptions
  ts/src/pro/poloniex.ts
Labels: bug

#18802 fix(tests) - exchangeId typo
  ts/src/test/test.ts
Labels: important

#18810 fix(bkex) - error exchange not available
  ts/src/bkex.ts
Labels: enhancement

#18821 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18820 bitget: add apis
  ts/src/bitget.ts
Labels: enhancement

#18811 fix(tests) - load markets
  ts/src/test/Exchange/test.loadMarkets.ts
  ts/src/test/test.ts
Labels: bug, enhancement, important

#14893 bit2c.createOrder string math
  ts/src/bit2c.ts
Labels: enhancement

#18823 feat(binance): update id
  ts/src/binance.ts
Labels: enhancement

#18822 fix(test) - markets
  ts/src/test/test.ts
Labels: bug

#18824 fix(bingx) - remove skip for loadmarkets
  skip-tests.json
Labels: enhancement

#18825 fix(test) - handling the temporary connectivity exception
  ts/src/test/test.ts
Labels: bug

#18819 fix(huobi): authenticate
  ts/src/pro/huobi.ts
Labels: bug

#18836 bingx: update
  ts/src/bingx.ts
Labels: enhancement

#18834 fix(gemini): fix indexOf for php
  ts/src/gemini.ts
Labels: bug

#18833 bingx: patch parseTrade
  ts/src/bingx.ts
Labels: bug

#18832 fix(upbit): parseOrder - precise math
  ts/src/upbit.ts
Labels: enhancement

#18838 fix build: bingx python linting
  ts/src/bingx.ts
Labels: bug

#18843 fix(bug): python pong
  python/ccxt/async_support/base/ws/aiohttp_client.py
Labels: bug

#18842 fix(multiple-exchanges) - rename of maxRetries into snapshotMaxRetries
  ts/src/base/Exchange.ts
  ts/src/pro/bitstamp.ts
  ts/src/pro/gate.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/mexc.ts
  ts/src/pro/poloniexfutures.ts
Labels: enhancement

#18849 fix(bingx): signature fix
  ts/src/bingx.ts
Labels: bug

#14858 cex Math -> Precise
  ts/src/cex.ts
Labels: enhancement

#18845 Ndax triggerPrice
  ts/src/ndax.ts
Labels: enhancement

#18841 Fetch position stop loss take profit
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmex.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/cryptocom.ts
  ts/src/currencycom.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/digifinex.ts
  ts/src/gate.ts
  ts/src/hitbtc.ts
  ts/src/huobi.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/phemex.ts
  ts/src/poloniexfutures.ts
  ts/src/woo.ts
Labels: enhancement

#18862 fix(whitebit): add loadMarkets to fetchTradingFees
  ts/src/whitebit.ts
Labels: bug

#18413 Tokocrypto string math
  ts/src/tokocrypto.ts
Labels: enhancement

#18868 fix!(bitfinex2): unify fetchPositions response
  ts/src/bitfinex2.ts
Labels: bug

#18866 fix(gate): parseOrder fixes related to filled and cost being set to 0
  ts/src/gate.ts
Labels: bug

#18882 feat(bitpanda): createOrder - unified params["triggerPrice"]
  ts/src/bitpanda.ts
Labels: enhancement

#18886 tokocrypto: createOrder - docstring and has updates
  ts/src/tokocrypto.ts
Labels: bug

#18889 fix(kucoin): ws error handling
  ts/src/kucoin.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/kucoinfutures.ts
Labels: bug

#18892 bingx: add apis
  ts/src/bingx.ts
Labels: enhancement

#18884 fix!(exmo): createOrder can place market orders, response is parsed using parseOrder
  ts/src/exmo.ts
Labels: bug

#18900 okx: update apis
  ts/src/okx.ts
Labels: enhancement

#18898 fix(alpaca): authenticate
  ts/src/pro/alpaca.ts
Labels: bug

#18894 Idex string math
  ts/src/pro/idex.ts
Labels: bug, enhancement

#18816 has[ws] == false
  ts/src/ace.ts
  ts/src/bit2c.ts
  ts/src/bitbns.ts
  ts/src/bitfinex2.ts
  ts/src/bl3p.ts
  ts/src/btcbox.ts
  ts/src/btctradeua.ts
  ts/src/btcturk.ts
  ts/src/coinone.ts
  ts/src/coinsph.ts
  ts/src/coinspot.ts
  ts/src/hitbtc.ts
  ts/src/wavesexchange.ts
  ts/src/yobit.ts
Labels: enhancement

#18932 fix(tokocrypto): add type 2 support for public methods
  ts/src/tokocrypto.ts
Labels: bug

#18906 `exchange.php` - add async fetch_markets
  php/async/Exchange.php
Labels: bug

#18929 Bitget: fetchMarkOHLCV, fetchIndexOHLCV
  ts/src/bitget.ts
Labels: enhancement

#18885 feat(hitbtc): params["triggerPrice"] unified
  ts/src/hitbtc.ts
Labels: enhancement

#18933 base - remove emulated ohlcv
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#18935 fix(bybit): watchTickers market selection
  ts/src/bybit.ts
  ts/src/pro/bybit.ts
Labels: bug

#18937 fix(binance) - add error code
  ts/src/binance.ts
Labels: bug

#18939 fix(phemex): fetchPosition - marginMode is parsed from response
  ts/src/phemex.ts
Labels: bug

#18895 `tests` - failed loadMarkets fix
  php/test/test_async.php
  python/ccxt/test/test_async.py
  ts/src/lykke.ts
  ts/src/test/test.ts
Labels: bug

#18909 fix(bitmart): ws auth
  ts/src/pro/bitmart.ts
Labels: bug

#18848 huobi & bittrex - option name change (simple)
  ts/src/base/Exchange.ts
  ts/src/pro/binance.ts
  ts/src/pro/bittrex.ts
  ts/src/pro/huobi.ts
  ts/src/pro/idex.ts
Labels: enhancement

#18943 fix(test) - allow empty value for lastTradeTimestamp
  ts/src/test/Exchange/base/test.order.ts
  ts/src/test/Exchange/base/test.trade.ts
Labels: enhancement

#18245 wavesexchange string math
  ts/src/wavesexchange.ts
Labels: enhancement

#18945 fix(bybit): market() override
  ts/src/bybit.ts
Labels: bug

#18951 feat(coinbasepro): add watchTickers
  ts/src/pro/coinbasepro.ts
Labels: enhancement

#18947 feat(binance) - error msg [QUICK]
  ts/src/binance.ts
Labels: enhancement

#18940 Bitget: fetchTrades add 'endTime' support
  ts/src/bitget.ts
Labels: enhancement

#18966 feat(coinbasepro): improve watchTicker parsing
  ts/src/pro/coinbasepro.ts
Labels: enhancement

#18962 bitget: add apis
  ts/src/bitget.ts
Labels: enhancement

#18961 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18258 exchange.parseWsOHLCVs
  build/transpile.js
  ts/src/base/Exchange.ts
Labels: enhancement

#18835 Lbank2: add contract API endpoints
  ts/src/lbank2.ts
Labels: enhancement

#18973 fetchMySettlementHistory: new options method
  ts/src/binance.ts
  ts/src/bybit.ts
  ts/src/cryptocom.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/okx.ts
Labels: enhancement

#18968 fix(bingx) - trade side & taker/maker [QUICK]
  ts/src/bingx.ts
Labels: bug

#18982 bitopro: patch signature
  ts/src/bitopro.ts
Labels: bug

#18983 bybit: add apis, update limit rate
  ts/src/bybit.ts
Labels: enhancement

#18985 fix(lbank2): python error mapping
  ts/src/lbank2.ts
Labels: bug

#18987 fix(poloniex): handle new ticker structure
  ts/src/poloniex.ts
Labels: enhancement

#18994 bitmart: add apis
  ts/src/bitmart.ts
Labels: enhancement

#18993 coinsph: add apis
  ts/src/coinsph.ts
Labels: enhancement

#18992 fix(base) - missing `accountsById` member [QUICK]
  php/Exchange.php
Labels: bug

#18991 fix(base) - missing badResponse, badRequest [QUICK]
  php/async/Exchange.php
Labels: bug

#18972 bingx: add apis
  ts/src/bingx.ts
Labels: enhancement

#19001 fix(bybit) - remove skip for tests
  skip-tests.json
  ts/src/bybit.ts
Labels: bug

#19006 fix(kucoinfutures): add loadMarkets to watchBalance
  ts/src/pro/kucoinfutures.ts
Labels: bug

#19014 fix(okx): watchTickers require list of symbols
  ts/src/pro/okx.ts
Labels: bug

#19017 fix(bingx): fetchTicker fix
  ts/src/bingx.ts
Labels: bug

#19019 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#19008 fix(test) - skip for auth [QUICK]
  ts/src/test/test.ts
Labels: bug

#19007 fix(test) - python exception
  python/ccxt/test/test_async.py
Labels: bug

#19018 fix(test) - array length [QUICK]
  ts/src/test/test.ts
Labels: bug

#18942 fix(base) - currencyToprecision force string
  ts/src/base/Exchange.ts
Labels: bug

#19022 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#19027 fix(bingx): spot ticker is public
  ts/src/bingx.ts
Labels: bug

#19032 bingx: patch signature
  ts/src/bingx.ts
Labels: bug

#19036 fix(phemex): side and price fix
  ts/src/phemex.ts
Labels: bug

#19044 mexc: add apis
  ts/src/mexc.ts
Labels: enhancement

#19046 composer: require react/promise-timer
  composer.json
  composer.lock
Labels: bug

#19041 fix(bitget): handle ws error
  ts/src/pro/bitget.ts
Labels: bug

#19050 fix `string` variable (QUICK)
  ts/src/pro/kraken.ts
Labels: bug

#19039 fix(wazirx): createOrder - stopPrice orders reduce stopPrice to allowed precision
  ts/src/wazirx.ts
Labels: enhancement

#19029 Strlen - php fix (QUICK?)
  ts/src/bybit.ts
  ts/src/coinsph.ts
  ts/src/krakenfutures.ts
  ts/src/okcoin.ts
  ts/src/okx.ts
  ts/src/probit.ts
  ts/src/upbit.ts
  ts/src/wavesexchange.ts
Labels: bug

#19052 fix(bitmex): base/quote volume inside ticker
  ts/src/bitmex.ts
Labels: bug

#19054 fix(gate): watchOHLCV return
  ts/src/pro/gate.ts
Labels: bug

#19059 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#19060 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#19058 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19057 bitget: update fetchMyTrades
  ts/src/bitget.ts
Labels: enhancement

#19061 huobi: add apis
  ts/src/huobi.ts
Labels: enhancement

#19051 different exchanges - fix `.length >` transpiling for array
  ts/src/pro/krakenfutures.ts
  ts/src/pro/probit.ts
  ts/src/pro/test/Exchange/test.watchOHLCV.ts
  ts/src/test/Exchange/base/test.market.ts
  ts/src/test/Exchange/test.fetchOHLCV.ts
  ts/src/test/Exchange/test.fetchOrderBooks.ts
Labels: bug
