Repository ccxt/ccxt, pull requests merged in 2023-12, with the labels that each got.

#20183 fix(exchange): fetchDeposits and fetchWithdrawals first argument is code instead of symbol
  ts/src/base/Exchange.ts
Labels: bug

#20172 Okx: standardize createMarketBuyOrderRequiresPrice
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#20200 fix(gate): add account section
  ts/src/gate.ts
Labels: bug

#20220 okx: add apis, update rate limit
  ts/src/okx.ts
Labels: enhancement

#20212 Bingx close all positions
  build/transpile.js
  ts/src/base/Exchange.ts
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#20182 feat(exchange): new methods closePosition and closeAllPositions
  ts/src/base/Exchange.ts
  ts/src/base/ws/Client.ts
Labels: enhancement

#20211 Close positions false
  ts/src/ace.ts
  ts/src/alpaca.ts
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/binanceus.ts
  ts/src/bit2c.ts
  ts/src/bitbank.ts
  ts/src/bithumb.ts
  ts/src/bitopro.ts
  ts/src/bitpanda.ts
  ts/src/bitso.ts
  ts/src/bitstamp.ts
  ts/src/bittrex.ts
  ts/src/bitvavo.ts
  ts/src/bl3p.ts
  ts/src/btcalpha.ts
  ts/src/btcbox.ts
  ts/src/btcmarkets.ts
  ts/src/btcturk.ts
  ts/src/bybit.ts
  ts/src/coinbase.ts
  ts/src/coincheck.ts
  ts/src/coinlist.ts
  ts/src/coinmate.ts
  ts/src/coinone.ts
  ts/src/coinsph.ts
  ts/src/coinspot.ts
  ts/src/gemini.ts
  ts/src/idex.ts
  ts/src/independentreserve.ts
  ts/src/indodax.ts
  ts/src/kucoin.ts
  ts/src/kuna.ts
  ts/src/latoken.ts
  ts/src/luno.ts
  ts/src/mercado.ts
  ts/src/mexc.ts
  ts/src/ndax.ts
  ts/src/novadax.ts
  ts/src/p2b.ts
  ts/src/wavesexchange.ts
  ts/src/wazirx.ts
  ts/src/woo.ts
  ts/src/yobit.ts
  ts/src/zonda.ts
Labels: enhancement

#20228 fix(errors) - inheritance fix
  ts/src/base/errors.ts
Labels: bug

#20226 remove debug from proxies
  ts/src/static_dependencies/proxies/http-proxy-agent/index.ts
  ts/src/static_dependencies/proxies/https-proxy-agent/index.ts
  ts/src/static_dependencies/proxies/https-proxy-agent/parse-proxy-response.ts
Labels: bug

#20221 cryptocom: remove transfer & fetchtransfer
  ts/src/cryptocom.ts
Labels: enhancement

#20234 Bitstamp: fetchOHLCV end time calculation
  ts/src/bitstamp.ts
Labels: bug

#20239 fix(bitmex) - empty numbers
  ts/src/bitmex.ts
  ts/src/test/static/request/bitmex.json
Labels: bug

#20241 Bingx close all positions
  ts/src/bingx.ts
Labels: enhancement

#20231 fix(okx) - ratelimit
  ts/src/okx.ts
Labels: bug

#20246 bingx.has closeAllPosition -> closeAllPositions
  ts/src/bingx.ts
Labels: bug

#20245 feat(bitget) - closeAllPositions
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: enhancement

#20248 fix(okx) - removal of incorrect map (QUICK)
  ts/src/okx.ts
Labels: bug

#20253 okx: add monthly statement api
  ts/src/okx.ts
Labels: enhancement

#20252 binance: add sor.order.test
  ts/src/pro/binance.ts
Labels: enhancement

#20251 bybit: update broker apis
  ts/src/bybit.ts
Labels: enhancement

#20254 hitbtc: update apis
  ts/src/hitbtc.ts
  ts/src/test/static/request/hitbtc.json
Labels: enhancement

#20107 upbit: remove method usage
  ts/src/test/static/currencies/upbit.json
  ts/src/test/static/markets/upbit.json
  ts/src/test/static/request/upbit.json
  ts/src/upbit.ts
Labels: enhancement

#20258 docs(bitmart,coinmate) fetchIsolatedBorrowRate docstring fixes
  ts/src/bitmart.ts
  ts/src/coinex.ts
Labels: enhancement

#20267 fix(bingx) - percent sign
  ts/src/bingx.ts
Labels: bug

#20271 cryptocom: add apis
  ts/src/cryptocom.ts
Labels: enhancement

#20276 woo: add insuranceFund
  ts/src/woo.ts
Labels: enhancement

#20277 bingx: update transaction status
  ts/src/bingx.ts
Labels: enhancement

#20293 fix(bybit): fetchTickers
  ts/src/bybit.ts
Labels: bug

#20295 fix(exchanges) - broken links updates (QUICK)
  ts/src/bybit.ts
  ts/src/pro/binance.ts
  ts/src/pro/bingx.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bybit.ts
  ts/src/pro/cex.ts
  ts/src/pro/coinbasepro.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/gate.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/okx.ts
Labels: bug

#20255 htx cross swap balance parse
  ts/src/htx.ts
Labels: bug

#20272 okx: remove method usage
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#20275 docs(closePosition, closeAllPositions)
  wiki/Manual.md
Labels: enhancement

#20279 Cryptocom close position
  ts/src/base/Exchange.ts
  ts/src/cryptocom.ts
  ts/src/test/static/markets/cryptocom.json
  ts/src/test/static/request/cryptocom.json
Labels: enhancement

#20265 Okx close position
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#20306 Binance: sign, origclientorderidlist length
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: bug

#20312 fix(bybit): fetchPositions exchange id handling
  ts/src/bybit.ts
Labels: bug

#20319 Socks proxy support for Websockets
  examples/ts/proxy-usage.ts
  php/Exchange.php
  php/pro/ClientTrait.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/test/base/custom/proxy-ws-test.ts
  wiki/Manual.md
Labels: enhancement

#20318 mexc: remove method usage
  ts/src/mexc.ts
  ts/src/test/static/request/mexc.json
Labels: enhancement

#20268 feat(bitmex): watchPositions && parsePosition fix
  ts/src/bitmex.ts
  ts/src/pro/bitmex.ts
Labels: enhancement

#20326 tokocrypto: remove method usage
  ts/src/test/static/request/tokocrypto.json
  ts/src/tokocrypto.ts
Labels: enhancement

#20327 digifinex: remove method usage
  ts/src/digifinex.ts
  ts/src/test/static/request/digifinex.json
Labels: enhancement

#20333 fix(bit2c) - orderbook test
  skip-tests.json
Labels: bug

#20351 fix(proxy) - typo
  ts/src/base/Exchange.ts
Labels: bug

#20342 Bitmart: trailing stop orders
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
Labels: enhancement

#20348 fix(package) - exchanges amount
  package.json
Labels: bug

#20337 okcoin add margin methods to has as false
  ts/src/okcoin.ts
Labels: enhancement

#19936 feat(phemex): withdraw method implementation
  ts/src/phemex.ts
  ts/src/test/static/currencies/phemex.json
  ts/src/test/static/request/phemex.json
Labels: enhancement

#20373 gate separated repayMargin and borrowMargin separated to repayCrossMa…
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#20375 has["repayCrossMargin"] === false, and repayIsolatedMargin
  ts/src/bitforex.ts
  ts/src/coinlist.ts
  ts/src/coinsph.ts
  ts/src/cryptocom.ts
  ts/src/kuna.ts
  ts/src/mexc.ts
  ts/src/tokocrypto.ts
  ts/src/wazirx.ts
  ts/src/whitebit.ts
Labels: enhancement

#20381 fix(tests) - proxyUrl test
  ts/src/test/Exchange/test.proxies.ts
Labels: bug

#20382 example file for `proxyUrl`
  examples/ts/proxy-usage.ts
Labels: bug

#20379 fix(test) - exception output
  php/test/test_async.php
Labels: bug

#20399 binance: patch watchOrders
  ts/src/pro/binance.ts
Labels: bug

#20398 feat(gate): closePosition
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#20400 bitmex.has["closePositions"] == false
  ts/src/binance.ts
  ts/src/bitmex.ts
Labels: enhancement

#20394 feat(kucoinfutures): closePosition
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
Labels: enhancement

#20405 fix(zaif): parseTicker remove timestamp from parsed data
  ts/src/zaif.ts
Labels: bug

#20142 coinone: update
  skip-tests.json
  ts/src/coinone.ts
  ts/src/test/static/currencies/coinone.json
  ts/src/test/static/markets/coinone.json
  ts/src/test/static/request/coinone.json
Labels: enhancement

#20424 Bitget: closePosition, closeAllPositions, v2
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: enhancement

#20422 py - proxy session handling
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: bug

#20427 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#20429 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#20428 coinbase: add apis
  ts/src/coinbase.ts
Labels: enhancement

#20438 bitget: update fetchOpenOrders
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: enhancement

#20437 Krakenfutures: createOrder, triggerPrice, stopLossPrice, takeProfitPrice
  ts/src/krakenfutures.ts
  ts/src/test/static/request/krakenfutures.json
Labels: enhancement

#20443 python socks proxy - session closing (2)
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: bug

#20440 binance: remove method usage fetch balance
  ts/src/binance.ts
  ts/src/test/static/markets/binance.json
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#20404 Kraken: createOrder, trailing stop orders
  ts/src/kraken.ts
  ts/src/test/static/request/kraken.json
Labels: enhancement

#20449 fix(gate): correct timestamp property in handleBalance
  ts/src/pro/gate.ts
Labels: bug

#20483 fix(binance): watchTicker remove default timestamp value of this.milliseconds
  ts/src/pro/binance.ts
Labels: bug

#20484 fix(bitmart): fetchTicker remove default timestamp value of this.milliseconds
  ts/src/bitmart.ts
Labels: bug

#20494 fix(python) - set proxy once for WS client
  python/ccxt/async_support/base/exchange.py
Labels: bug

#20486 proxy rework for PHP ws
  php/pro/Client.php
  php/pro/ClientTrait.php
Labels: bug

#20492 fix(bitfinex): watchTicker - removed timestamp data because it wasnt parsed from the response
  ts/src/pro/bitfinex.ts
Labels: bug

#20490 fix(bitfinex2,btcbox,kraken): fetchTicker - removed timestamp data because it wasnt parsed from the response
  ts/src/bitfinex2.ts
  ts/src/btcbox.ts
  ts/src/kraken.ts
Labels: bug

#20500 Delta: closeAllPositions
  ts/src/delta.ts
Labels: enhancement

#20499 Coinbase: parseOrder, stop orders
  ts/src/coinbase.ts
Labels: bug

#20493 fix(woo,kraken): watchTicker - removed timestamp data because it wasnt parsed from the response
  ts/src/pro/kraken.ts
  ts/src/pro/woo.ts
Labels: bug

#20496 fix(cex) - watchOrders removed default timestamp value of this.milliseconds from the response
  ts/src/pro/cex.ts
Labels: bug

#20505 Static tests exception handling
  php/async/Exchange.php
  php/test/test_async.php
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  ts/src/base/Exchange.ts
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
  ts/src/test/test.ts
Labels: enhancement

#20509 Update Exchange.ts `safeLedgerEntry`
  ts/src/base/Exchange.ts
Labels: bug

#20522 skipWs - bitrue
  skip-tests.json
Labels: bug

#20153 WS tests - unification & transpilation
  build.sh
  build/transpile.js
  build/transpileWS.js
  package-lock.json
  package.json
  php/pro/BaseCache.php
  php/pro/test/Cache.php
  php/pro/test/OrderBook.php
  php/pro/test/base/.gitkeep
  php/pro/test/custom/syntax.php
  php/pro/test/test.php
  php/test/custom/syntax.php
  php/test/test_async.php
  python/ccxt/async_support/base/ws/cache.py
  python/ccxt/pro/test/Exchange/table.py
  python/ccxt/pro/test/Exchange/test_order_book.py
  python/ccxt/pro/test/Exchange/test_ticker.py
  python/ccxt/pro/test/Exchange/test_watch_ohlcv.py
  python/ccxt/pro/test/Exchange/test_watch_order_book.py
  python/ccxt/pro/test/Exchange/test_watch_ticker.py
  python/ccxt/pro/test/Exchange/test_watch_trades.py
  python/ccxt/pro/test/base/.gitkeep
  python/ccxt/pro/test/test_async.py
  python/ccxt/pro/test/test_cache.py
  python/ccxt/pro/test/test_order_book.py
  python/ccxt/test/test_async.py
  run-tests-ws.js
  run-tests.js
  skip-tests.json
  ts/src/pro/test/.eslintrc
  ts/src/pro/test/Exchange/test.watchBalance.ts
  ts/src/pro/test/Exchange/test.watchMyTrades.ts
  ts/src/pro/test/Exchange/test.watchOHLCV.ts
  ts/src/pro/test/Exchange/test.watchOrderBook.ts
  ts/src/pro/test/Exchange/test.watchOrders.ts
  ts/src/pro/test/Exchange/test.watchPosition.ts
  ts/src/pro/test/Exchange/test.watchPositions.ts
  ts/src/pro/test/Exchange/test.watchTicker.ts
  ts/src/pro/test/Exchange/test.watchTrades.ts
  ts/src/pro/test/custom/fastMessageServer.ts
  ts/src/pro/test/custom/server.ts
  ts/src/pro/test/test.ts
  ts/src/test/.eslintrc
  ts/src/test/Exchange/base/test.orderBook.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/test.ts
Labels: enhancement

#20538 feat(bingx): closePosition implementation
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#20536 BingX: marketType ternary handling
  ts/src/pro/bingx.ts
Labels: bug

#20537 fix(phemex): setLeverage - can set leverage to values between -1 to -100 (for cross leverage trading)
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
Labels: bug

#20547 feat(binance): add apis
  ts/src/binance.ts
Labels: enhancement

#20506 bitvavo: add clientOrderId
  ts/src/bitvavo.ts
  ts/src/test/static/markets/bitvavo.json
  ts/src/test/static/request/bitvavo.json
Labels: enhancement

#20475 Bitget: createOrder, trailingStopPercent support
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: enhancement

#20481 Bitmart: createOrder, trailingStopPercent, triggerPrice
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
Labels: enhancement

#20519 BingX: trailing orders
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#20549 coinex: update apis
  ts/src/coinex.ts
  ts/src/test/static/request/coinex.json
  ts/src/test/static/response/coinex.json
Labels: enhancement

#20559 mexc: BEP20 network
  ts/src/mexc.ts
Labels: bug

#20560 Bitget: fetchOrder, type error
  ts/src/bitget.ts
Labels: bug

#20049 bit.team integration
  skip-tests.json
  ts/src/abstract/bitteam.ts
  ts/src/base/types.ts
  ts/src/bequant.ts
  ts/src/bitteam.ts
  ts/src/test/static/currencies/bitteam.json
  ts/src/test/static/markets/bitteam.json
  ts/src/test/static/request/bitteam.json
  ts/src/test/static/response/bitteam.json
Labels: new exchange

#20564 fix(okx): fetchDepositAddressesByNetwork
  ts/src/okx.ts
Labels: bug

#20565 fix(bitteam): remove this.number [ci deploy]
  ts/src/bitteam.ts
Labels: bug

#20569 fix(cex) - test skip
  skip-tests.json
Labels: bug

#20568 php async & sync
  build/transpile.js
  php/test/test_async.php
Labels: bug

#20573 deribit: remove method usage
  ts/src/deribit.ts
  ts/src/test/static/markets/deribit.json
  ts/src/test/static/request/deribit.json
Labels: enhancement

#20574 cex: remove method usage
  ts/src/cex.ts
  ts/src/test/static/request/cex.json
Labels: enhancement

#20582 fix: removed extra zaif file from ts/src
  ts/src/zaif.js
Labels: bug

#20589 bingx: update cancelAllOrders
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#20575 bitstamp: remove method usage
  ts/src/bitstamp.ts
  ts/src/test/static/request/bitstamp.json
Labels: enhancement

#20584 feat(binance): remove method from pro
  ts/src/pro/binance.ts
Labels: enhancement

#20586 poloniexfutures: remove method
  ts/src/poloniexfutures.ts
  ts/src/test/static/request/poloniexfutures.json
Labels: enhancement

#20585 bybit: handleMyTrades remove method usage
  ts/src/pro/bybit.ts
Labels: enhancement

#20588 lykke: remove method
  ts/src/lykke.ts
  ts/src/test/static/currencies/lykke.json
  ts/src/test/static/markets/lykke.json
  ts/src/test/static/request/lykke.json
Labels: enhancement

#20610 fix(Bybit): watchTickers
  ts/src/pro/bybit.ts
Labels: bug
