Repository ccxt/ccxt, pull requests merged in 2023-01, with the labels that each got.

#16298 bybit: add tax api
  js/bybit.js
Labels: enhancement

#16297 binance: add capital/contract/convertible-coins
  js/binance.js
Labels: enhancement

#16295 okx: update
  js/okx.js
Labels: enhancement

#16291 okx: add more withdraw networks ccxt/ccxt#16236
  js/okx.js
Labels: bug

#16290 python - watchTickers
  python/ccxt/pro/base/exchange.py
Labels: WS

#16299 fix parseLeverageTiers
  js/base/Exchange.js
Labels: bug

#16300 poloniex: add subaccounts api
  js/poloniex.js
Labels: enhancement

#16292 binance: update currency code when fetch fiat transactions ccxt/ccxt#16224
  js/binance.js
Labels: bug

#16314 Binance :: fetchDeposits/fetchWithdrawals fiat only
  js/binance.js
Labels: enhancement

#16317 bitopro: add bsc network
  js/bitopro.js
Labels: enhancement

#15663 btcex - websockets
  js/btcex.js
  js/pro/base/Exchange.js
  js/pro/btcex.js
  php/pro/ClientTrait.php
  python/ccxt/pro/base/exchange.py
Labels: enhancement, WS

#16312 bitmex: update official websocket endpoint
  js/pro/bitmex.js
Labels: enhancement

#16112 Poloniex Futures
  js/poloniexfutures.js
Labels: enhancement

#16328 Bybit :: stop order fix
  js/bybit.js
Labels: bug

#15002 therock.parseOrder string math
  js/therock.js
Labels: enhancement

#16159 binance: add watchTickers
  js/pro/binance.js
Labels: enhancement

#16059 woo: add edit order
  js/woo.js
Labels: enhancement

#14206 precisionFromString update
  js/base/functions/number.js
  js/digifinex.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement, critical

#16336 Bybit :: ticker fix
  js/bybit.js
Labels: bug

#16341 Kucoin :: fix fee
  js/kucoin.js
Labels: bug

#16360 binance: add new endpoints
  js/binance.js
Labels: enhancement

#16359 Wazirx: fix signing
  js/wazirx.js
Labels: bug

#16358 Bybit :: fix USDC set leverage
  js/bybit.js
Labels: bug

#15385 gemini - websockets
  js/gemini.js
  js/pro/gemini.js
  js/pro/test/pro-tests.json
Labels: new exchange, WS

#16367 gemini - add staking and earn api endpoints
  js/gemini.js
Labels: enhancement

#16374 gemini - ws - fix build
  js/pro/gemini.js
Labels: bug

#16380 Docker :: add php8.1 support
  Dockerfile
Labels: bug

#16383 Bybit :: fix fetchTickers
  js/bybit.js
Labels: bug

#16382 Improve cli parsing
  examples/js/cli.js
  examples/py/cli.py
Labels: enhancement

#16390 Cli parsing: identation
  examples/js/cli.js
  examples/py/cli.py
Labels: enhancement

#16391 bybit: check limit in watchOrderBook
  js/pro/bybit.js
Labels: enhancement

#16395 Ccxt.js :: expose PRO
  ccxt.js
Labels: bug

#16304 docs: update the Python proxy docs
  python/ccxt/base/exchange.py
  wiki/Install.md
Labels: enhancement

#16267 indodax parseTransaction unification min changes
  js/indodax.js
Labels: enhancement

#16399 Bitfinex :: fix swap orders placement
  js/bitfinex.js
  js/bitfinex2.js
Labels: bug

#14839 Woox: withdraw
  js/woo.js
Labels: enhancement

#16407 bybit: use tradeMode ccxt/ccxt#16402
  js/bybit.js
Labels: bug

#16411 Binance :: fix watchTickers
  js/pro/binance.js
Labels: bug

#16410 wavesexchange: update fetchTickers ccxt/ccxt#16229
  js/wavesexchange.js
Labels: bug

#16409 coinex.parseTransaction string math / updates
  js/coinex.js
Labels: enhancement

#16404 wazirx pro - string math
  js/pro/wazirx.js
Labels: enhancement

#16418 Bitget: fix spot fetchTickers
  js/bitget.js
Labels: bug

#16424 Bybit :: fix default position side
  js/bybit.js
Labels: bug

#16421 ccxt.pro :: update docs
  wiki/ccxt.pro.manual.md
Labels: enhancement

#16427 kucoin.transfer removed fields that are filled in when theres an error
  js/kucoin.js
Labels: bug

#16435 Kucoin pro :: fix limit type
  js/pro/kucoin.js
Labels: bug

#16426 kucoin createOrder isolated margin
  js/kucoin.js
Labels: enhancement

#16132 bitstamp parseTransaction unification
  js/bitstamp.js
Labels: enhancement

#16436 coinex: added fetchFundingRates method
  js/coinex.js
Labels: enhancement

#16439 Coinex :: fix build and safeMarket
  js/coinex.js
  js/pro/coinex.js
Labels: bug

#16438 bitget: added volume for watchOHLCV
  js/pro/bitget.js
Labels: enhancement

#16449 Delta unified networks
  js/delta.js
Labels: enhancement

#16448 delta fetchLedger string math
  js/delta.js
Labels: enhancement

#16455 Phemex :: fix fetchTicker
  js/phemex.js
Labels: bug

#16457 Gemini :: fix markets
  js/gemini.js
Labels: bug

#16465 mexc.fetchCurrencies network withdrawFee fix
  js/mexc3.js
Labels: bug

#16466 kraken parseOrder python id field is a string and not a string of an array in python
  js/kraken.js
Labels: bug

#16472 Fix strlen to count in ccxt/pro/binance.
  js/pro/binance.js
Labels: bug

#16469 okx: add api to get deposit withdraw status
  js/okx.js
Labels: enhancement

#16475 Syntax bugs fix
  js/coinbase.js
  js/pro/bitget.js
  keys.json
Labels: bug

#16422 Kucoinfutures websockets support
  js/kucoinfutures.js
  js/pro/base/Exchange.js
  js/pro/kucoinfutures.js
  js/pro/test/pro-tests.json
  php/pro/ClientTrait.php
  python/ccxt/pro/base/exchange.py
Labels: new exchange

#16471 woo: add timeInForce
  js/woo.js
Labels: enhancement

#16480 [Bybit] fix wrong price for trades
  js/bybit.js
Labels: bug

#16486 bitget, bitrue - update docstrings
  js/pro/bitget.js
  js/pro/bitrue.js
Labels: bug, WS

#16483 Bitfinex pro precise
  js/bitfinex.js
  js/pro/bitfinex.js
Labels: enhancement

#16482 kraken.parseWSOrder string math
  js/pro/kraken.js
Labels: enhancement

#16479 watchOrders/watchMyTrades support for binance isolated margin
  js/pro/binance.js
Labels: enhancement

#16490 coinex: fix timeframes
  js/pro/coinex.js
Labels: bug

#16498 Okx :: fix margin position side
  js/okx.js
Labels: bug

#16504 bitfinex: use body[0] ccxt/ccxt#16502
  js/bitfinex.js
Labels: bug

#16456 bybit: refactor fetchFundingRate
  js/bybit.js
Labels: enhancement

#16509 Gate :: add market buy requires price
  js/gate.js
Labels: bug

#16495 binance: update spot/option api endpoints
  js/binance.js
Labels: enhancement

#16513 fix build
  js/bybit.js
Labels: bug

#16508 binance: set createPostOnlyOrder true
  js/binance.js
Labels: enhancement

#16516 Binance :: fix fetchBidsAsks
  js/binance.js
Labels: bug

#16520 Binance :: add testnet link
  js/binance.js
Labels: bug

#16492 coinex - watchOHLCV - add error if listen to more than one symbol
  js/pro/coinex.js
Labels: WS

#16481 binance.parseWSOrder string math
  js/pro/binance.js
Labels: enhancement

#16511 gate createDepositAddress emulated
  js/gate.js
Labels: enhancement

#16523 Gate :: fix contract market order
  js/gate.js
Labels: bug

#16467 coinex: include fundingTimestamp calculation in parseFundingRate
  js/coinex.js
Labels: enhancement

#16528 Coinex :: fix build
  js/coinex.js
Labels: bug

#16530 [binance] Fix RSA key signatures
  build/transpile.js
  js/binance.js
  js/test/base/functions/test.crypto.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#16539 Gate pro :: fix multiple subscription
  js/pro/gate.js
Labels: bug

#16510 safeOrder has all fields
  js/base/Exchange.js
Labels: bug, enhancement

#16541 Bybit :: fix fetchFundingRate
  js/bybit.js
Labels: bug

#16433 bitget: add spot plan order
  js/bitget.js
Labels: enhancement

#16542 OKX :: fix contracts field
  js/okx.js
Labels: bug

#16531 gate fetchOpenInterestHistory
  js/gate.js
Labels: enhancement

#16547 binance: add self trade prevention
  js/binance.js
Labels: enhancement

#16558 Bitfinex2 :: fix symbol
  js/bitfinex2.js
Labels: bug

#16557 Wavesexchange :: fix fetchTicker
  js/wavesexchange.js
Labels: bug

#16565 bitget: update jsdoc
  js/bitget.js
Labels: enhancement

#16568 bybit: add unified account apis
  js/bybit.js
Labels: enhancement

#16564 Kucoin cancel all margin orders
  js/kucoin.js
Labels: enhancement

#16562 Kucoin fetch margin orders
  js/kucoin.js
Labels: enhancement

#16583 bybit: remove 1y from timeframe ccxt/ccxt#16582
  js/bybit.js
Labels: bug

#16580 Fix timestamp and datetime fields in \ccxt\async\Exchange.php
  js/base/Exchange.js
Labels: bug

#16571 Coinbase: cancelOrders, BadRequest
  js/coinbase.js
Labels: bug

#16595 [gateio] Fix bugs in watchOrderBook
  js/pro/gate.js
Labels: bug

#16592 binance: update postOnly in editOrder
  js/binance.js
Labels: enhancement

#16553 Kucoin create order margin stop
  js/kucoin.js
Labels: bug

#16594 bitopro: add postonly order
  js/bitopro.js
Labels: enhancement

#16609 Binance: fix balances
  js/binance.js
Labels: bug

#16588 [binance] Fix crash in fee parsing logic
  js/binance.js
Labels: bug

#16585 Btcex: fetchLeverage, fetchMarketLeverageTiers, fetchLeverageTiers
  js/btcex.js
Labels: bug

#16524 Coinbase: fetchOrder, fetchOrders, fetchOrdersByStatus
  js/coinbase.js
Labels: enhancement

#16613 gemini.fetchTicker docstring for params.fetchTickerMethod
  js/gemini.js
Labels: enhancement

#16612 zonda parseLedgerEntry amount returned as number
  js/zonda.js
Labels: bug

#16611 huobi -fix links cn to en
  js/huobi.js
Labels: bug

#16537 Coinbase: fetchTrades, fetchMyTrades
  js/coinbase.js
Labels: enhancement

#16601 fix: okx subaccount transfer out setting endpoint
  js/okx.js
Labels: bug

#16624 Php :: React\Http\Browser::request()
  php/async/Exchange.php
Labels: bug

#16615 base/functions/misc eslint error fixes
  js/base/functions/misc.js
Labels: bug

#16622 mexc3 - has
  js/bitmex.js
  js/bkex.js
  js/mexc3.js
Labels: bug

#16627 Bitget :: business bill endpoint
  js/bitget.js
Labels: enhancement

#16625 btcalpha fetchTicker and fetchTickers
  js/btcalpha.js
Labels: enhancement

#16630 Huobi :: update transfer
  js/huobi.js
Labels: bug, enhancement

#16619 kucoinfutures stopPrice order bug fix
  js/kucoinfutures.js
Labels: bug

#16637 Binance spot trailing fix and examples
  examples/php/binance-spot-trailing.php
  examples/py/binance-spot-trailing.py
  js/binance.js
Labels: enhancement

#16635 bybit - spot market buy order quantity - fix #16600
  js/bybit.js
Labels: bug

#16645 length fixes
  js/base/Exchange.js
  js/bybit.js
  js/coinex.js
  js/cryptocom.js
  js/okx.js
  js/poloniex.js
  js/pro/cex.js
  js/pro/coinex.js
  js/pro/woo.js
Labels: bug

#16643 mercado removed invalid api doc link
  js/mercado.js
Labels: enhancement

#16642 huobi - new links
  js/huobi.js
Labels: bug

#16653 Gemini :: fix sandbox markets loading
  js/gemini.js
Labels: bug

#16647 has["method"] === undefined mostly replaced with has["method"] === false
  js/bitbns.js
  js/bitfinex.js
  js/bitfinex2.js
  js/bitforex.js
  js/bitstamp1.js
  js/bittrex.js
  js/btcbox.js
  js/btctradeua.js
  js/buda.js
  js/bybit.js
  js/coinbase.js
  js/coinbasepro.js
  js/coinone.js
  js/coinspot.js
  js/deribit.js
  js/gemini.js
  js/hitbtc.js
  js/hollaex.js
  js/idex.js
  js/indodax.js
  js/itbit.js
  js/kuna.js
  js/lbank.js
  js/mercado.js
  js/oceanex.js
  js/poloniex.js
  js/tidex.js
  js/upbit.js
  js/whitebit.js
  js/yobit.js
  js/zaif.js
  js/zb.js
Labels: enhancement

#16659 Btcex: setLeverage
  js/btcex.js
Labels: enhancement

#16671 reenable fetchTickers on binance.us
  js/binanceus.js
Labels: bug

#16668 binance: update parseTransaction ccxt/ccxt#16666
  js/binance.js
Labels: bug

#16674 Kucoin :: fix parseOrder
  js/kucoin.js
Labels: bug

#16680 Gate :: fix watchBalance
  js/pro/gate.js
Labels: bug

#16681 Deribit :: triggerPrice fix
  js/deribit.js
Labels: bug

#16677 bitget: add fetchTransfers
  js/bitget.js
Labels: enhancement

#16634 [binance] URL encode RSA signatures
  js/binance.js
Labels: bug

#16700 New updates :: initialization fix
  js/pro/base/Exchange.js
Labels: bug
