Repository ccxt/ccxt, pull requests merged in 2023-07, with the labels that each got.

#18430 Crypto.com: set swap, future and option to true
  ts/src/cryptocom.ts
Labels: enhancement

#18429 Crypto.com: withdraw, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18423 base- remove old build remnants [ci skip]
  build.sh
Labels: enhancement

#18397 coinph: add apis
  ts/src/coinsph.ts
Labels: enhancement

#18433 feat(gate): fix fetchOpenInterestHistory
  ts/src/gate.ts
Labels: bug

#18409 Proxy - reorganization [ci skip]
  examples/html/basic-cors-proxy.html
  examples/html/binance-cors-proxy.html
  examples/html/bitmex-cors.html
  examples/php/sample-local-proxy-server-with-cors.php
  examples/py/proxies-for-synchronous-python.py
  examples/py/proxy-asyncio-aiohttp-python-3.py
  examples/py/proxy-asyncio-aiohttp-socks.py
  examples/py/proxy-sync-python-requests-2-and-3.py
  examples/py/sample-local-proxy-server-with-cors.py
  examples/ts/custom-proxy-agent-for-js.ts
  examples/ts/proxy-usage.ts
  examples/ts/sample-local-proxy-server-with-cors.ts
  wiki/Install.md
  wiki/Manual.md
Labels: enhancement

#18299 Bigone - fetch currencies (+networks unification)
  skip-tests.json
  ts/src/bigone.ts
Labels: enhancement

#18443 fix(base): fetchTime -> fetch_Time
  build/transpile.js
Labels: bug

#18440 bitget: add apis
  ts/src/bitget.ts
Labels: enhancement

#18439 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18435 okx - add method for fetchTrades
  ts/src/okx.ts
Labels: enhancement

#18447 fix(bybit): watchOrders [ci deploy]
  ts/src/pro/bybit.ts
Labels: bug

#18316 bigone - fetchDepositAddress & withdraw
  ts/src/bigone.ts
Labels: enhancement

#18451 bitstamp - skip bid ask
  skip-tests.json
Labels: bug

#18450 fix(watchOrders): filterBySymbolSinceLimit call
  ts/src/pro/alpaca.ts
  ts/src/pro/ascendex.ts
  ts/src/pro/binance.ts
  ts/src/pro/bitfinex.ts
  ts/src/pro/bitfinex2.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bitmart.ts
  ts/src/pro/bitmex.ts
  ts/src/pro/bitrue.ts
  ts/src/pro/bittrex.ts
  ts/src/pro/bitvavo.ts
  ts/src/pro/blockchaincom.ts
  ts/src/pro/cex.ts
  ts/src/pro/coinex.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/deribit.ts
  ts/src/pro/gemini.ts
  ts/src/pro/hollaex.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/mexc.ts
  ts/src/pro/okx.ts
  ts/src/pro/phemex.ts
  ts/src/pro/probit.ts
  ts/src/pro/wazirx.ts
  ts/src/pro/woo.ts
Labels: bug

#18455 Coinbase: fetchBidsAsks
  ts/src/coinbase.ts
Labels: enhancement

#18458 bitget: add apis
  ts/src/bitget.ts
Labels: enhancement

#18436 fix(throttler) - unified names in php
  php/async/Exchange.php
  php/async/Throttle.php
  php/pro/Client.php
  php/pro/ClientTrait.php
  php/test/base/test_throttle.php
Labels: enhancement

#18469 woo: remove apis GET /v1/client/info
  ts/src/woo.ts
Labels: enhancement

#18468 novadax: update jsdoc
  ts/src/novadax.ts
Labels: enhancement

#18467 oceanex: update jsdoc
  ts/src/oceanex.ts
Labels: enhancement

#18463 bitget parseTransaction edits
  ts/src/bitget.ts
Labels: enhancement

#18392 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#16526 bitvavo - networks unification
  ts/src/bitvavo.ts
Labels: enhancement

#18339 feat(binance): add support for websocket trading
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/pro/binance.ts
Labels: enhancement

#18453 Revert "multilang-edit"
  multilang.sh
Labels: bug

#18477 Crypto.com: fetchWithdrawals, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18442 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#18479 fix(base): fix uncatchable error in ws - fix #18445
  ts/src/base/Exchange.ts
Labels: bug

#16237 kucoin - networks unification
  skip-tests.json
  ts/src/kucoin.ts
Labels: enhancement

#18480 fix(base): protect filterByValueSinceLimit and protect filterBySinceLimit [ci deploy]
  ts/src/base/Exchange.ts
Labels: bug

#18482 deribit - fetchDepositWithdrawFees
  ts/src/deribit.ts
Labels: enhancement

#18470 kucoin - add chains in fetchCurrencies
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
Labels: enhancement

#18486 fix(base): ffilterBySinceLimit [ci deploy]
  ts/src/base/Exchange.ts
Labels: bug

#18490 Crypto.com: fetchDeposits, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18488 add errors
  php/async/Exchange.php
Labels: bug

#18483 deribit - fetchCurrencies
  skip-tests.json
  ts/src/deribit.ts
Labels: enhancement

#18476 docs: add pro functions to api spec
  jsdoc2md.js
  ts/src/coinbase.ts
  ts/src/pro/bitfinex2.ts
  ts/src/pro/kraken.ts
  ts/src/pro/poloniex.ts
Labels: enhancement

#18492 Crypto.com: migrate websockets to the unified API
  ts/src/pro/cryptocom.ts
Labels: enhancement

#18457 Huobi create order for margin orders
  ts/src/huobi.ts
Labels: enhancement

#18485 feat(cryptocom): add ws trading api
  ts/src/cryptocom.ts
  ts/src/pro/cryptocom.ts
Labels: enhancement

#18512 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#18511 huobi: add apis
  ts/src/huobi.ts
Labels: enhancement

#18509 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#18508 bitget: add apis
  ts/src/bitget.ts
Labels: enhancement

#18502 Bybit: fetchMarkets, add ETH and SOL option markets
  ts/src/bybit.ts
Labels: enhancement

#18516 fix(bybit): v5 :: creatOrder :: option markets
  ts/src/bybit.ts
Labels: bug

#18515 fix(Exchange.php): filterByLimit fix [ci deploy]
  ts/src/base/Exchange.ts
Labels: bug

#18517 feat(kraken): add transfer and transferOut
  ts/src/kraken.ts
Labels: enhancement

#18521 Bybit: option support
  ts/src/bybit.ts
Labels: enhancement

#18520 Bybit: fetchSettlementHistory
  ts/src/bybit.ts
Labels: enhancement

#18538 fix(bitmex): parseTransaction network parsing
  ts/src/bitmex.ts
Labels: bug, enhancement

#18540 kucoinfutures certified = true
  ts/src/kucoinfutures.ts
Labels: enhancement

#18537 Delta: adjust option naming
  ts/src/delta.ts
Labels: enhancement

#18544 fix(bybit): fetchPosition crash
  ts/src/bybit.ts
Labels: bug

#18534 feat(base) - mute web api failure (includes kucoin)
  ts/src/base/Exchange.ts
  ts/src/bigone.ts
  ts/src/gemini.ts
  ts/src/kucoin.ts
Labels: bug

#18542 Delta: fetchTicker, fetchTickers, add bid and ask data
  ts/src/delta.ts
Labels: enhancement

#18554 Delta: fetchFundingRate, fetchFundingRates
  ts/src/delta.ts
Labels: enhancement

#18553 bitget: patch fetchPosition ccxt/ccxt#18546
  ts/src/bitget.ts
Labels: bug

#18548 kucoin - correction of networknames
  ts/src/kucoin.ts
Labels: bug

#18531 bitget fetchCurrencies enhancement
  ts/src/bitget.ts
Labels: enhancement

#18557 feat(okx): add eth options
  ts/src/okx.ts
Labels: enhancement

#18558 feat(okx): watchTickers, watchMyTrades, createOrderWs, cancelOrderWs,… [ci deploy]
  ts/src/okx.ts
  ts/src/pro/okx.ts
Labels: enhancement

#17924 BingX Integration [ci deploy]
  skip-tests.json
  ts/src/abstract/bingx.ts
  ts/src/bingx.ts
Labels: new exchange

#18525 networks by id autogenerate
  build/transpile.js
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#18562 fix(gate) - remove createDepositAddress
  ts/src/gate.ts
Labels: bug

#18564 Okx: editOrder, remove market type restriction
  ts/src/okx.ts
Labels: enhancement

#18545 kucoin: update margin trading / lending to v3
  ts/src/kucoin.ts
Labels: enhancement

#18579 huobi: add apis
  ts/src/huobi.ts
Labels: enhancement

#18577 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18572 base - missing python error
  python/ccxt/base/exchange.py
Labels: bug, important

#18569 base - minor corrections
  build/transpile.js
  ts/src/base/Exchange.ts
Labels: bug

#18466 Fetch transactions deposits withdrawals name swap
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/bitfinex.ts
  ts/src/bitfinex2.ts
  ts/src/bitmex.ts
  ts/src/bitstamp.ts
  ts/src/btcmarkets.ts
  ts/src/coinbasepro.ts
  ts/src/coinmate.ts
  ts/src/currencycom.ts
  ts/src/exmo.ts
  ts/src/gemini.ts
  ts/src/hitbtc.ts
  ts/src/hitbtc3.ts
  ts/src/indodax.ts
  ts/src/latoken.ts
  ts/src/lykke.ts
  ts/src/novadax.ts
  ts/src/poloniex.ts
  ts/src/probit.ts
  ts/src/woo.ts
Labels: enhancement

#18449 tests - simplify run-tests
  run-tests.js
Labels: enhancement

#18585 fix(Bitbay,bitcoincom): set correct name
  ts/src/bitbay.ts
  ts/src/bitcoincom.ts
Labels: bug

#18587 Okx: fetchSettlementHistory, handle expired market id
  ts/src/okx.ts
Labels: enhancement

#18575 multiple exchanges - removal of networksById
  ts/src/bitrue.ts
  ts/src/bitvavo.ts
  ts/src/cex.ts
  ts/src/cryptocom.ts
  ts/src/delta.ts
  ts/src/digifinex.ts
  ts/src/gemini.ts
  ts/src/kucoin.ts
  ts/src/poloniex.ts
  ts/src/probit.ts
  ts/src/wavesexchange.ts
Labels: enhancement

#18574 bitmex - networks list
  ts/src/bitmex.ts
Labels: bug

#18565 okx - networks list
  ts/src/okx.ts
Labels: enhancement

#18588 mexc error remapping
  ts/src/mexc.ts
Labels: enhancement

#18568 bitmart - networks list
  ts/src/bitmart.ts
Labels: enhancement

#18567 hitbtc3 - all networks list
  ts/src/hitbtc3.ts
Labels: enhancement

#18591 fix(base): python exchange ws close [ci deploy]
  python/ccxt/async_support/base/exchange.py
Labels: bug

#18595 hitbtc3 - removal trx
  ts/src/hitbtc3.ts
Labels: bug

#18603 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18604 Delta: addMargin, reduceMargin
  ts/src/delta.ts
Labels: enhancement

#18596 mexc - unfied networks list
  ts/src/mexc.ts
Labels: enhancement

#18614 fix(base): emulated fetchMarketLeverageTiers
  ts/src/base/Exchange.ts
  ts/src/phemex.ts
Labels: bug

#18563 blockchaincom - unified networks list
  ts/src/blockchaincom.ts
Labels: enhancement

#18623 bingx - skip
  skip-tests.json
Labels: enhancement

#18622 okx - deposit tag added
  ts/src/okx.ts
Labels: bug

#16517 coinex - ws - fetchOHLCV
  build/transpile.js
  ts/src/base/Exchange.ts
  ts/src/base/functions/string.ts
  ts/src/pro/coinex.ts
Labels: WS

#18634 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#18636 feat(gate) - rate limit err
  ts/src/gate.ts
Labels: bug

#18632 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#18631 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18638 github template - remove duplicate [ci skip]
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/BUG_REPORT2.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#18644 Delta: fetchMarkOHLCV, fetchIndexOHLCV
  ts/src/delta.ts
Labels: enhancement

#18646 fix(python-base) - error badresponse
  python/ccxt/async_support/base/exchange.py
Labels: bug

#18651 feat(bitget): add privateMixGetPositionHistoryPosition
  ts/src/bitget.ts
Labels: enhancement

#18652 fix(bitstamp): 3d timeframe
  ts/src/bitstamp.ts
Labels: bug

#18639 fix(github-template) - short url
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: enhancement

#18658 fix!(hitbtc): hitbtc3 renamed to hitbtc
  ts/src/hitbtc.ts
  ts/src/hitbtc3.ts
Labels: bug

#18661 Delta: fetchLeverage
  ts/src/delta.ts
Labels: enhancement

#18660 feat(errors): added error type NoChange
  ts/src/base/errors.ts
Labels: enhancement

#18659 gate setPositionMode implementation
  ts/src/gate.ts
Labels: enhancement

#18655 Delta: setLeverage
  ts/src/delta.ts
Labels: enhancement

#18669 feat(bequant): upgrade to v3
  ts/src/bequant.ts
  ts/src/pro/bequant.ts
Labels: enhancement

#18670 fix(phemex): add contract size
  ts/src/phemex.ts
Labels: bug

#18677 fix(base) - badResponse
  python/ccxt/async_support/base/exchange.py
Labels: bug

#18675 Delta: fetchSettlementHistory, createExpiredOptionMarket
  ts/src/delta.ts
Labels: enhancement

#18673 fix(bequant) - add skip currency id
  skip-tests.json
Labels: enhancement

#18672 fix(binance) - editOrder for spot
  ts/src/binance.ts
Labels: bug, important

#18679 feat(bitget): add history OHLCV candles
  ts/src/bitget.ts
Labels: enhancement

#18448 tests - with multiple retries
  run-tests.js
  skip-tests.json
  ts/src/test/test.ts
Labels: enhancement

#18684 removed delisted exchanges from manual [ci skip]
  wiki/Manual.md
Labels: enhancement

#18689 fix(test) - add code
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: bug

#18687 Delta: finish swap and option support
  ts/src/delta.ts
Labels: enhancement

#18692 fix(bybit): ws spot orders parsing
  ts/src/pro/bybit.ts
Labels: bug

#18686 fix(binance): orders trade fee for one order with multiple trades
  ts/src/pro/binance.ts
Labels: bug

#18701 feat(coinbasepro): add sandbox mode
  ts/src/pro/coinbasepro.ts
Labels: enhancement

#18695 Bybit: fetchVolatilityHistory
  ts/src/binance.ts
  ts/src/bybit.ts
  ts/src/cryptocom.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/okx.ts
  wiki/Manual.md
Labels: enhancement

#18693 docs: update instructions on how to check if postOnly orders are available
  wiki/Manual.md
Labels: enhancement

#18706 fix(binanceWs): fetchOpenOrdersWs symbol requirement removal
  ts/src/pro/binance.ts
Labels: bug

#18707 fix(bitfinex): signature
  ts/src/bitfinex.ts
Labels: bug

#18678 feat(manual) - invalid api key errors
  wiki/Manual.md
Labels: enhancement

#18694 feat(kucoin) - standalone stop-loss & take-profit unification
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
Labels: enhancement

#18718 fix(bitget): reapply historical positions changes
  ts/src/bitget.ts
Labels: enhancement

#18720 feat(lbank2) - withdraw true
  ts/src/lbank2.ts
Labels: bug

#18719 feat(examples) - compare two exchange functionalities [ci skip]
  examples/ts/compare-two-exchanges-capabilities.ts
Labels: enhancement

#18709 feat(base) - fetchPositions for/by symbol - init
  ts/src/base/Exchange.ts
Labels: enhancement

#18723 feat(base): add position type
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
  ts/src/huobi.ts
  ts/src/krakenfutures.ts
  ts/src/kucoinfutures.ts
  ts/src/okx.ts
  ts/src/phemex.ts
Labels: enhancement
