Repository ccxt/ccxt, pull requests merged in 2023-04, with the labels that each got.

#17431 fix(gate): watchOrders and watchMyTrades
  ts/src/pro/gate.ts
Labels: bug

#17429 bybit: update timestamp of position
  ts/src/bybit.ts
Labels: bug

#17411 coinex editOrder
  ts/src/coinex.ts
Labels: enhancement

#17435 fix(phemex): usd markets handling
  ts/src/phemex.ts
Labels: bug

#17433 fix(binance): setMarginMod exception
  ts/src/binance.ts
Labels: bug

#17440 fix(Phemex): sandbox v2
  ts/src/phemex.ts
Labels: bug

#17445 fix(gate): fix #17443
  ts/src/pro/gate.ts
Labels: bug

#17441 poloniex handleErrors
  ts/src/poloniex.ts
Labels: enhancement

#17461 bybit: omit tp/sl and triggerPrice
  ts/src/bybit.ts
Labels: bug

#17454 coinex editOrder fix
  ts/src/coinex.ts
Labels: bug

#17468 fix(gate): fetchOHLCV limit switched to 999
  ts/src/gate.ts
Labels: bug

#17459 fix(poloniex): poloniex transfer update to new response format
  ts/src/poloniex.ts
Labels: bug

#17477 bitmart - postonly
  ts/src/bitmart.ts
Labels: bug

#17484 bitget: update apis
  ts/src/bitget.ts
Labels: enhancement

#17476 po bitget
  ts/src/bitget.ts
Labels: bug

#17473 postonly - mexc
  ts/src/mexc.ts
Labels: bug

#17471 huobi - spot po
  ts/src/huobi.ts
Labels: bug

#17470 okx - postonly
  ts/src/okx.ts
Labels: bug

#17472 krakenfutures - remove force stp type if stopPrice exists
  ts/src/krakenfutures.ts
Labels: bug

#17491 Fix wrong mexc "has" flags
  ts/src/mexc.ts
Labels: bug

#17493 fix(kucoin & mexc): removed commonCurrency BiFi->BIFIF
  ts/src/kucoin.ts
  ts/src/mexc.ts
Labels: bug

#17495 binance.fetchTrades add until and fetchTradesMethod param, docstring
  ts/src/binance.ts
Labels: enhancement

#17497 bybit: update fetchOrders
  ts/src/bybit.ts
Labels: enhancement

#17494 binance docstring @see
  ts/src/binance.ts
Labels: enhancement

#17486 bybit: set endTime when since is not empty
  ts/src/bybit.ts
Labels: bug

#17500 fix python: 3.7 types
  python/ccxt/base/types.py
Labels: bug

#17502 Revert "fix(kucoin & mexc): removed commonCurrency BiFi->BIFIF"
  ts/src/kucoin.ts
  ts/src/mexc.ts
Labels: bug

#17510 Websocket Client - arrayBuffer decode take into account byte length
  ts/src/base/ws/Client.ts
Labels: bug

#17509 fixes #17508
  ts/src/okx.ts
Labels: bug

#17519 [krakenfutures] sign url generation for python
  ts/src/krakenfutures.ts
Labels: bug

#17517 mexc: use market id ccxt/ccxt#17515
  ts/src/mexc.ts
Labels: bug

#17505 bybit: update editOrder
  ts/src/bybit.ts
Labels: enhancement

#17524 fix(bitget): canceledAndClosed default
  ts/src/bitget.ts
Labels: bug

#17529 mexc: add new api (capital/transfer/tranId)
  ts/src/mexc.ts
Labels: enhancement

#17528 bybit: update fetchBalance ccxt/ccxt#17520
  ts/src/bybit.ts
Labels: bug

#17531 fix key_exists: exception handling [ci deploy]
  python/ccxt/base/exchange.py
Labels: bug

#17530 woo: make some apis public
  ts/src/woo.ts
Labels: enhancement

#17533 fix(deribit): authenticate ws
  ts/src/pro/deribit.ts
Labels: bug

#17536 fix(poloniex): fix fetchTransactionsHelper
  ts/src/poloniex.ts
Labels: bug

#17548 fix(bitget): handle future markets
  ts/src/bitget.ts
Labels: bug

#17555 fix(okx): protect withdraw
  ts/src/okx.ts
Labels: bug

#17398 Bybit - postonly fix
  ts/src/bybit.ts
Labels: bug

#17556 fix php: WS client [ci deploy]
  php/pro/Client.php
Labels: bug

#17559 mexc: parse trade-side as bool not string
  ts/src/mexc.ts
Labels: bug

#17560 binance: fix fetchOpenInterestHistory
  ts/src/binance.ts
Labels: bug

#17558 types.ts formatting
  ts/src/base/types.ts
Labels: enhancement

#17563 fix(bybit): createOrder v3 stopPrice [ci deploy]
  ts/src/bybit.ts
Labels: bug

#17565 poloniex.fetchTrades: side added for public trades
  ts/src/poloniex.ts
Labels: bug

#17562 fix(bitfinex2): fix #17540 - bitfinex2 orderbook checksum
  ts/src/pro/bitfinex2.ts
Labels: bug

#17575 build: patch php extends for ccxt pro ccxt/ccxt#17573
  build/transpileWS.js
  php/pro/Client.php
Labels: bug

#17571 feat(examples): add html example for ccxt pro [ci skip]
  examples/ccxt.pro/html/watchTicker.html
Labels: enhancement, WS

#17574 fix(examples): fix html examples [ci skip]
  examples/html/basic-cors-proxy.html
  examples/html/basic-poller.html
  examples/html/basic-rate-limiting.html
  examples/html/basic.html
  examples/html/bitmex-browser-cors-proxy.js
  examples/html/bitmex-cors.html
Labels: bug

#17566 [Binance] Modify error codes
  js/src/binance.js
Labels: bug

#17118 New Exchange - XT [ci deploy]
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/abstract/xt.ts
  ts/src/base/Exchange.ts
  ts/src/xt.ts
Labels: new exchange

#17578 fix xt: logo [ci skip]
  ts/src/xt.ts
Labels: enhancement

#17579 mexc - fix OHLCV intervals
  ts/src/mexc.ts
Labels: bug

#17585 fix export-exchanges: alias
  build/export-exchanges.js
Labels: bug

#16932 feat(phemex):websockets support USDT using hedged perpetual API
  ts/src/phemex.ts
  ts/src/pro/phemex.ts
Labels: enhancement, WS

#17587 add tests to push.sh
  build/push.sh
  skip-tests.json
Labels: bug

#17589 fix mercado & paymium
  skip-tests.json
Labels: bug

#17591 mercado - skip
  skip-tests.json
Labels: enhancement

#17602 ndax: patch parseInt
  ts/src/pro/ndax.ts
Labels: bug

#17599 hollaex: patch parseInt ccxt/ccxt#17597
  ts/src/hollaex.ts
Labels: bug

#17613 woo parseTransaction unification
  ts/src/woo.ts
Labels: enhancement

#17610 poloniex parseTransaction unification
  ts/src/poloniex.ts
Labels: enhancement

#17614 Fix watch_order_book bug on testnet spot
  ts/src/pro/binance.ts
Labels: bug

#17618 fix(phemex): fetchOHLCV
  ts/src/phemex.ts
Labels: bug

#17624 fix incorrect content in dist/cjs/package.json [ci deploy]
  dist/cjs/package.json
  rollup.config.js
Labels: bug

#17586 python: fix urlencode bug ccxt/ccxt#17550
  python/ccxt/base/exchange.py
Labels: bug

#17570 fix: ws client send
  php/pro/Client.php
  php/pro/ClientTrait.php
  python/ccxt/async_support/base/ws/aiohttp_client.py
  python/ccxt/async_support/base/ws/client.py
  ts/src/base/Exchange.ts
  ts/src/base/ws/Client.ts
  ts/src/base/ws/Future.ts
Labels: bug, WS

#17605 test cleanup
  build/transpile.js
  js/src/test/base/test.timeout_hang.d.ts
  js/src/test/base/test.timeout_hang.js
  php/test/test_async.php
  php/test/test_sync.php
  python/ccxt/base/errors.py
  python/ccxt/test/base/__init__.py
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/test/.eslintrc
  ts/src/test/.eslintrc.ts
  ts/src/test/Exchange/base/test.ledgerEntry.ts
  ts/src/test/Exchange/test.fetchBorrowRate.ts
  ts/src/test/Exchange/test.fetchL2OrderBook.ts
  ts/src/test/Exchange/test.fetchLedger.ts
  ts/src/test/Exchange/test.fetchLedgerEntry.ts
  ts/src/test/base/errors/test.InsufficientFunds.ts
  ts/src/test/base/errors/test.InvalidNonce.ts
  ts/src/test/base/errors/test.InvalidOrder.ts
  ts/src/test/base/errors/test.OrderNotFound.ts
  ts/src/test/base/functions/test.binanceMarkets.ts
  ts/src/test/base/functions/test.throttle.ts
  ts/src/test/base/functions/test.timeout_hang.ts
  ts/src/test/test.ts
  tsconfig.json
Labels: enhancement

#17626 feat(phemex): add fetchFundingRateHistory
  ts/src/phemex.ts
Labels: enhancement

#17636 fix(gemini): pro authenticate
  ts/src/pro/gemini.ts
Labels: bug

#17641 fix test: protect access
  ts/src/test/test.ts
Labels: bug

#17629 tests - fix extend
  ts/src/test/test.ts
Labels: bug

#17644 fix(bigone): fetchBalance
  ts/src/bigone.ts
Labels: bug

#17648 fix(bybit): fetchPositions USDC
  ts/src/bybit.ts
Labels: bug

#17649 binance: add api managed-subaccount/deposit/address
  ts/src/binance.ts
Labels: enhancement

#17654 feat(Deribit): add spot markets
  ts/src/deribit.ts
Labels: bug

#17662 Ascendex fetch closed orders v2
  ts/src/ascendex.ts
Labels: enhancement

#17660 phemex fetchTickers
  ts/src/phemex.ts
Labels: enhancement

#17666 phemex : skip fetchTickers
  skip-tests.json
Labels: bug

#17663 Binance: add option support to transfer
  ts/src/binance.ts
Labels: enhancement

#17675 bybit: add spot-cross-margin-trade apis ccxt/ccxt#17655
  ts/src/bybit.ts
Labels: enhancement

#17676 tests - this/$this fix in php sync
  build/transpile.js
Labels: bug

#17673 mexc: update deposit address
  ts/src/mexc.ts
Labels: enhancement

#17680 fix(deribit): duplicated spot markets
  ts/src/deribit.ts
Labels: bug

#17623 yobit - fix arr
  ts/src/yobit.ts
Labels: bug

#17678 tests - fix `run-tests` skip
  run-tests.js
  skip-tests.json
Labels: bug

#17687 add missing `networks` across currencies
  ts/src/ascendex.ts
  ts/src/bitfinex2.ts
  ts/src/bitpanda.ts
  ts/src/bitstamp.ts
  ts/src/coinbasepro.ts
  ts/src/delta.ts
  ts/src/exmo.ts
  ts/src/gate.ts
  ts/src/hitbtc.ts
  ts/src/hollaex.ts
  ts/src/kraken.ts
  ts/src/kucoin.ts
  ts/src/latoken.ts
  ts/src/lykke.ts
  ts/src/ndax.ts
  ts/src/phemex.ts
  ts/src/probit.ts
  ts/src/stex.ts
  ts/src/timex.ts
Labels: bug

#17690 fix(webpack): webworkers usage [ci deploy]
  webpack.config.js
Labels: bug

#17692 Fixing URL for sandbox
  ts/src/krakenfutures.ts
Labels: bug

#17700 zonda: add links to jsdoc
  ts/src/zonda.ts
Labels: enhancement

#17682 [bybit] Fix watch_ticker to use symbol in same way as other exchanges
  ts/src/pro/bybit.ts
Labels: enhancement

#17698 upbit: add links to jsdoc
  ts/src/upbit.ts
Labels: enhancement

#17683 [base] .calculateFee not to return quote currency when feeSide=base
  ts/src/base/Exchange.ts
Labels: bug

#17674 Binance: fetchPosition, option support
  ts/src/binance.ts
Labels: enhancement

#17659 kucoin parseOrder fix
  ts/src/kucoin.ts
Labels: bug

#17711 fix(bitget): watchOrders multiple spot sub
  ts/src/pro/bitget.ts
Labels: bug

#17712 fix OrderType and OrderSide
  ts/src/base/types.ts
Labels: bug

#17709 tokocrypto: add links to jsdoc
  ts/src/tokocrypto.ts
Labels: enhancement

#17708 wazirx: add links to jsdoc
  ts/src/wazirx.ts
Labels: enhancement

#17707 yobit: add links to jsdoc
  ts/src/yobit.ts
Labels: enhancement

#17706 zaif: add links to jsdoc
  ts/src/zaif.ts
Labels: enhancement

#17696 fix - test issues [ci skip]
  ts/src/bitfinex2.ts
  ts/src/lbank2.ts
  ts/src/test/Exchange/base/test.market.ts
  ts/src/whitebit.ts
  ts/src/woo.ts
Labels: bug

#17716 huobi: safeCurrencyCode ()'s second argument is a Currency
  ts/src/huobi.ts
Labels: bug

#17714 bithumb: use currency code rather than currency object
  ts/src/bithumb.ts
Labels: bug

#17715 bitso: use currency rather than currency code for parseLedger ()
  ts/src/base/Exchange.ts
  ts/src/bitso.ts
  ts/src/timex.ts
Labels: bug
