Repository ccxt/ccxt, pull requests merged in 2023-06, with the labels that each got.

#18093 base - missing name
  build/transpile.js
Labels: bug

#18095 kucoin: update hf apis [ci deploy]
  ts/src/kucoin.ts
Labels: enhancement

#18102 Gate: fetchMyTrades, add option support
  ts/src/gate.ts
Labels: enhancement

#18103 bitmex - comments [ci skip]
  ts/src/bitmex.ts
Labels: bug

#18067 bitget: update timeInForce in createOrder
  ts/src/bitget.ts
Labels: enhancement

#18105 bitmex - deposit in parseTransaction
  ts/src/bitmex.ts
Labels: bug

#18107 fix(binance): fix #18078 canceled timestamp
  ts/src/pro/binance.ts
Labels: bug

#18116 bitstamp new endpoints
  ts/src/bitstamp.ts
Labels: enhancement

#18118 bybit: add api privateGetV5CustomerInfo
  ts/src/bybit.ts
Labels: enhancement

#17966 base - emulated fetch ohlcv removal
  examples/ts/build-ohlcv-bars.ts
  ts/src/base/Exchange.ts
Labels: enhancement, important

#18070 bitget: add swap order fee
  ts/src/bitget.ts
Labels: enhancement

#18132 Gate: fetchSettlementHistory
  ts/src/gate.ts
Labels: enhancement

#18126 feat(base): watchTicker emulate from watchTickers
  build.sh
  ts/src/base/Exchange.ts
Labels: enhancement

#18138 Fix private tests args.
  ts/src/test/test.ts
Labels: bug

#18139 bitforex new endpoints, fetchMyTrades
  ts/src/bitforex.ts
Labels: enhancement

#18144 binance: update apis
  ts/src/binance.ts
Labels: enhancement

#14910 waves - precision prop fix
  ts/src/wavesexchange.ts
Labels: enhancement

#18153 bitmex - fetchticker
  ts/src/bitmex.ts
Labels: bug

#18151 fix(bybit): restore options loading
  examples/js/cli.js
  examples/php/cli.php
  examples/py/cli.py
  examples/ts/cli.ts
  ts/src/bybit.ts
Labels: bug

#18156 fix(build): take exchanges.cfg into consideration
  build/transpile.js
Labels: bug

#18157 fix(gate): fix status for partially filled
  ts/src/pro/gate.ts
Labels: bug

#18158 Gate: fetchTicker, fetchTickers, add option support
  ts/src/gate.ts
Labels: enhancement

#18163 binance.addMargin amountToPrecision changed to costToPrecision
  ts/src/binance.ts
Labels: bug

#18173 Correct FAQ to cite TS as source language
  wiki/FAQ.md
Labels: bug, enhancement

#18174 feat(bybit): add pagination cursor
  ts/src/bybit.ts
Labels: enhancement

#18137 feat(gate): add networks
  ts/src/gate.ts
Labels: enhancement

#18184 binance - fetchLastPrices remove bv & qv
  ts/src/binance.ts
Labels: enhancement

#18182 binance - fetchLastPrices fix
  ts/src/binance.ts
Labels: bug

#18175 fix(binance): handle order's timestamp properly
  ts/src/base/types.ts
  ts/src/binance.ts
Labels: bug

#18190 bitbank: add apis
  ts/src/bitbank.ts
Labels: enhancement

#18189 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18188 woo: add apis
  ts/src/woo.ts
Labels: enhancement

#18191 [krakenfutures] fetchFundingRate(s)
  ts/src/krakenfutures.ts
Labels: enhancement

#18205 [base] Exchange.fetchFundingRate normalize symbol
  ts/src/base/Exchange.ts
Labels: enhancement

#18207 fix(bitget): fetchTickers parsing
  ts/src/bitget.ts
Labels: bug

#18206 Add status for bitso
  ts/src/bitso.ts
Labels: bug

#18170 fix(bitfinex2): fix #18169 - fix partially filled status
  ts/src/pro/bitfinex2.ts
Labels: bug

#18212 fix(bitget): executePrice not required when type is market [ci deploy]
  ts/src/bitget.ts
Labels: bug

#18220 private tests: fix runtime errors for Python and PHP.
  ts/src/test/Exchange/base/test.balance.ts
  ts/src/test/Exchange/test.fetchBalance.ts
  ts/src/test/test.ts
Labels: bug

#18224 build: fix WS regular transpiling [ci skip]
  build/transpile.js
Labels: bug

#18223 fix(bybit): fetchTickers parsing
  build.sh
  ts/src/bybit.ts
Labels: bug

#18225 fix(cli.py): support sync calls [ci skip]
  examples/py/cli.py
Labels: bug

#18203 feat(Crypto.com): fetchMarkets, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18186 bybit: use start in ws ohlcv stream
  ts/src/pro/bybit.ts
Labels: bug

#18129 Gate: fetchOHLCV, add option support
  ts/src/gate.ts
Labels: enhancement

#18228 Probit fetchTransactions, fetchDeposits, fetchWithdrawals according to pr#18210
  ts/src/probit.ts
Labels: enhancement

#18240 bybit: patch fetchOrders ccxt/ccxt#18234
  ts/src/bybit.ts
Labels: bug

#18237 base transpile - replaceAll & trim
  build/transpile.js
Labels: important

#18249 fix(xt): error handling when response is undefined
  ts/src/xt.ts
Labels: bug

#18248 currencycom & gemini - skip-tests
  skip-tests.json
Labels: bug

#18246 bybit: add broker api
  ts/src/bybit.ts
Labels: enhancement

#18229 transpiler makes decision to transpile based on mtime difference in seconds instead of milliseconds
  build/transpile.js
Labels: bug

#18218 [krakenfutures] fix fundingRate to return relative value
  ts/src/krakenfutures.ts
Labels: bug

#18213 okx - fetchTransfers
  ts/src/okx.ts
Labels: enhancement

#18202 xt - fetch currencies
  ts/src/xt.ts
Labels: enhancement

#18201 bitmex: add apis
  ts/src/bitmex.ts
Labels: enhancement

#18244 Exmo fetchCurrencies string math
  ts/src/exmo.ts
Labels: enhancement

#18243 Crypto.com: cancelAllOrders, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18238 Crypto.com: fetchOpenOrders, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18242 Crypto.com: cancelOrder, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18262 huobi: add error code
  ts/src/huobi.ts
Labels: enhancement

#18241 Crypto.com: fetchOrders, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18239 Crypto.com: fetchOrder, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18266 fix(binance): php testnet
  ts/src/binance.ts
Labels: bug

#18270 feat(binance): cancelAllOrders jsdoc [ci skip]
  ts/src/binance.ts
Labels: enhancement

#18272 bitget-fetchDepositWithdrawFees
  ts/src/bitget.ts
Labels: enhancement

#18271 ascendex `fetchDepositWithdrawFees`
  ts/src/ascendex.ts
Labels: enhancement

#18279 Crypto.com: fetchOHLCV, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18277 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#18255 added skips [ci skip]
  skip-tests.json
Labels: enhancement

#18280 examples - stoploss & takeprofit - transpilable
  examples/ts/.eslintrc
  examples/ts/create-order-position-with-takeprofit-stoploss.ts
Labels: enhancement

#18284 bitget: add apis
  ts/src/bitget.ts
Labels: enhancement

#18285 temporary enable of debug [ci skip]
  build.sh
Labels: enhancement

#18289 Crypto.com: fetchBalance, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18287 feat(bitget,bybit,kucoinfutures,okx): add lastUpdateTimestamp to order
  ts/src/base/Exchange.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/kucoinfutures.ts
  ts/src/okx.ts
Labels: enhancement

#18292 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#18283 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#18291 fetchDepositsWithdrawals
  ts/src/alpaca.ts
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bitfinex.ts
  ts/src/bitfinex2.ts
  ts/src/bitmex.ts
  ts/src/bitopro.ts
  ts/src/bitpanda.ts
  ts/src/bitrue.ts
  ts/src/bitso.ts
  ts/src/bitstamp.ts
  ts/src/btcmarkets.ts
  ts/src/cex.ts
  ts/src/coinbasepro.ts
  ts/src/coinmate.ts
  ts/src/cryptocom.ts
  ts/src/currencycom.ts
  ts/src/exmo.ts
  ts/src/gemini.ts
  ts/src/hitbtc.ts
  ts/src/hitbtc3.ts
  ts/src/indodax.ts
  ts/src/latoken.ts
  ts/src/lykke.ts
  ts/src/novadax.ts
  ts/src/okx.ts
  ts/src/poloniex.ts
  ts/src/tokocrypto.ts
  ts/src/wazirx.ts
  ts/src/woo.ts
Labels: enhancement

#18297 bitvavo-fetchDepositWithdrawFees
  ts/src/bitvavo.ts
Labels: enhancement

#18301 fix(pro): base exchange import
  python/ccxt/pro/__init__.py
Labels: bug

#18303 feat(xt): add lastUpdateTimestamp
  ts/src/xt.ts
Labels: enhancement

#18300 hitbtc/3 - skip id code
  skip-tests.json
Labels: enhancement

#18282 phemex createOrder - type 3
  examples/ts/.eslintrc
  examples/ts/phemex-create-order-position-with-takeprofit-stoploss.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/phemex.ts
Labels: enhancement

#18306 Crypto.com: fetchTickers, migrate to the unified API
  ts/src/base/Exchange.ts
  ts/src/cryptocom.ts
Labels: enhancement

#18307 Crypto.com: fetchLedger
  ts/src/cryptocom.ts
Labels: enhancement

#18308 bybit - fetchDepositWithdrawFees
  ts/src/bybit.ts
Labels: enhancement

#18295 Bittrex fetchDepositWithdrawFees
  ts/src/bittrex.ts
Labels: enhancement

#18273 Zonda fetch ticker v2
  ts/src/zonda.ts
Labels: enhancement

#16987 Proxies Unification
  build/transpile.js
  examples/php/proxy-usage.php
  examples/py/proxy-usage.py
  examples/ts/.eslintrc
  examples/ts/proxy-usage.ts
  php/Exchange.php
  php/async/Exchange.php
  php/static_dependencies/proxies/reactphp-http-proxy/LICENSE
  php/static_dependencies/proxies/reactphp-http-proxy/composer.json
  php/static_dependencies/proxies/reactphp-http-proxy/src/ProxyConnector.php
  php/test/test_async.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/errors.py
  python/ccxt/base/exchange.py
  python/ccxt/static_dependencies/__init__.py
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/static_dependencies/proxies/agent-base/README.md
  ts/src/static_dependencies/proxies/agent-base/helpers.ts
  ts/src/static_dependencies/proxies/agent-base/index.ts
  ts/src/static_dependencies/proxies/http-proxy-agent/LICENSE
  ts/src/static_dependencies/proxies/http-proxy-agent/index.ts
  ts/src/static_dependencies/proxies/https-proxy-agent/README.md
  ts/src/static_dependencies/proxies/https-proxy-agent/index.ts
  ts/src/static_dependencies/proxies/https-proxy-agent/parse-proxy-response.ts
  ts/src/test/test.ts
Labels: enhancement, important

#18321 Crypto.com: fetchOrderBook, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18318 Crypto.com: fetchAccounts
  ts/src/cryptocom.ts
Labels: enhancement

#18230 Crypto.com: createOrder, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18250 base - setSandboxMode transpilation
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#18320 bitget: add tax apis
  ts/src/bitget.ts
Labels: enhancement

#18319 binance: add new apis
  ts/src/binance.ts
Labels: enhancement

#18235 gemini - fetchCurrencies (+networks unification)
  ts/src/base/Exchange.ts
  ts/src/gemini.ts
Labels: enhancement

#18332 Crypto.com: fetchDepositAddressesByNetwork, migrate to the unified API
  ts/src/cryptocom.ts
Labels: enhancement

#18336 build: update decimalToPrecision links
  wiki/Manual.md
Labels: bug

#18337 fix(krakenfutures): charts sandbox api
  ts/src/krakenfutures.ts
Labels: bug

#18341 feat(krakenfutures): add lastUpdateTimestamp
  ts/src/krakenfutures.ts
Labels: enhancement

#18345 fix(mexc): change marginType to marginMode
  ts/src/mexc.ts
Labels: bug

#18317 Gemini - fetchDepositAddress [w] (+ networks)
  ts/src/gemini.ts
Labels: enhancement

#18348 fix(deribit): removed spot duplicated markets
  ts/src/deribit.ts
  ts/src/pro/deribit.ts
Labels: bug

#18326 kucoin-fetchDepositWithdrawFees
  ts/src/kucoin.ts
Labels: enhancement

#18355 fix(Exchange): remove conflicting error message
  ts/src/base/Exchange.ts
Labels: bug

#18350 okx - add endpoints
  ts/src/okx.ts
Labels: bug

#18333 Crypto.com: fetchSettlementHistory
  ts/src/cryptocom.ts
Labels: enhancement

#18324 bitmex-fetchDepositWithdrawFees
  ts/src/bitmex.ts
Labels: enhancement

#18089 fix(bitmex): spot/currencies precisions [ci deploy]
  ts/src/base/Exchange.ts
  ts/src/bitmex.ts
Labels: enhancement

#18357 examples: all_open_rders => all_open_orders
  examples/ts/create-order-position-with-takeprofit-stoploss.ts
  examples/ts/phemex-create-order-position-with-takeprofit-stoploss.ts
Labels: enhancement

#18356 kraken: add create / close a position example
  examples/ts/kraken-create-and-close-position.ts
Labels: enhancement

#18323 examples - stop-loss/take-profit minor correction
  examples/py/okx-position-takeprofit-stoploss.py
  examples/ts/create-order-position-with-takeprofit-stoploss.ts
Labels: enhancement

#18384 Crypto.com: fetchFundingRateHistory
  ts/src/cryptocom.ts
Labels: enhancement

#18389 feat(kraken): add postOnly support
  ts/src/kraken.ts
Labels: enhancement

#18264 okx - fix limited premature ending
  ts/src/okx.ts
Labels: bug

#18395 examples - proxy edit [ci skip]
  examples/ts/proxy-usage.ts
Labels: enhancement

#18396 Crypto.com: fetchPosition, fetchPositions
  ts/src/cryptocom.ts
Labels: enhancement

#18398 coinbase: add apis
  ts/src/coinbase.ts
Labels: enhancement

#18400 phemex parseTrade fix
  ts/src/phemex.ts
Labels: bug

#18401 Luno use this.parseNumber in parseLedgerEntry
  ts/src/luno.ts
Labels: bug

#18403 fix(binance): id fix [ci deploy]
  ts/src/binance.ts
Labels: bug

#18417 delta: add apis
  ts/src/delta.ts
Labels: enhancement

#18419 base - python proxies fix
  python/ccxt/base/exchange.py
Labels: bug

#18421 fix(okx): signature id fix [ci deploy]
  ts/src/okx.ts
Labels: bug

#18422 feat(base) - transpiler add startsWith endsWith
  build/transpile.js
Labels: enhancement

#18424 phemex parseTicker fix
  ts/src/phemex.ts
Labels: bug
