Repository ccxt/ccxt, pull requests merged in 2023-10, with the labels that each got.

#19400 feat(latoken): createOrder - unified params["stopPrice"], fetchOrder/fetchOpenOrders/fetchOrders/cancelOrder/cancelAllOrders - unified params["stop"]
  ts/src/latoken.ts
Labels: enhancement

#19424 fix(kucoin): chain id
  ts/src/kucoin.ts
Labels: bug

#19432 kucoin: add @see [ci skip]
  ts/src/kucoin.ts
Labels: enhancement

#19431 okx: fix handle_my_trades in php
  ts/src/pro/okx.ts
Labels: bug

#19430 binance: add @see [ci skip]
  ts/src/binance.ts
Labels: enhancement

#19402 okx: remove method
  ts/src/okx.ts
Labels: enhancement

#19434 fix(bitrue): ticker percantage scale
  ts/src/bitrue.ts
Labels: bug

#19435 Coinbasepro: add watchMyTradesForSymbols and watchOrdersForSymbols
  ts/src/base/Exchange.ts
  ts/src/coinbasepro.ts
  ts/src/pro/coinbasepro.ts
Labels: enhancement

#19436 BingX: createOrder, add reduceOnly and positionSide support
  ts/src/bingx.ts
Labels: bug

#19439 fix(binance): watchOrderbook (spot) max limit
  ts/src/pro/binance.ts
Labels: bug

#19446 fix(Exchange.py): bytes response in the sync version
  python/ccxt/base/exchange.py
Labels: bug

#19445 Bitmart: fetchPosition, fetchPositions
  ts/src/bitmart.ts
Labels: enhancement

#19450 fix(tests) - error message length correction
  php/test/test_async.php
  python/ccxt/test/test_async.py
  ts/src/test/test.ts
Labels: enhancement

#19444 PHP - feature to add method overload/override
  examples/php/method-overload-override.php
  php/Exchange.php
  wiki/Manual.md
Labels: enhancement

#19452 fix(bitget): fetchCanceledAndClosedOrders
  ts/src/bitget.ts
Labels: bug

#19449 fix(kraken): handle raw trades
  ts/src/base/Exchange.ts
  ts/src/kraken.ts
Labels: bug

#19467 kraken: add @see
  ts/src/kraken.ts
Labels: enhancement

#19466 okx: add @see
  ts/src/okx.ts
Labels: enhancement

#19463 whitebit: fetchOrderBook - parseToInt instead of parseNumber
  ts/src/whitebit.ts
Labels: enhancement

#19462 feat(kucoinfutures): fetchTime uses safeInteger instead of safeNumber
  ts/src/kucoinfutures.ts
Labels: enhancement

#19460 feat(idex): fetchTime uses safeInteger instead of safeNumber
  ts/src/idex.ts
Labels: enhancement

#19471 fix(coinsph): markets correctly list active status
  ts/src/coinsph.ts
Labels: bug

#19461 feat(kraken): parseLedgerEntry - string math
  ts/src/kraken.ts
Labels: enhancement

#19457 feat(coinex): fetchTime - uses safeInteger instead of safeNumber
  ts/src/coinex.ts
Labels: enhancement

#19442 feat(kuna): v4 implicit api paths
  ts/src/kuna.ts
Labels: enhancement

#19474 fix(kraken): parseOrder - rawTrades
  ts/src/kraken.ts
Labels: bug

#19475 php base - minor fixes
  php/async/Exchange.php
  php/pro/Client.php
Labels: bug

#19481 feat(mexc): fetchOHLCV endTime and pagination
  ts/src/mexc.ts
Labels: enhancement

#19477 fix(bitbns): fetchBalance returns amouts of used and total INR instead of undefined
  ts/src/bitbns.ts
Labels: bug

#19458 feat(coinfalcon): parseTransaction - string math
  ts/src/coinfalcon.ts
Labels: enhancement

#19483 bitmart: add broker api
  ts/src/bitmart.ts
Labels: enhancement

#19482 mexc: add apis
  ts/src/mexc.ts
Labels: enhancement

#19459 feat(exmo): handleOrderBook - string math
  ts/src/pro/exmo.ts
Labels: enhancement

#18650 Bingx ws [ci deploy]
  php/pro/test/Exchange/test_watch_trades.php
  python/ccxt/pro/test/exchange/test_watch_trades.py
  skip-tests.json
  ts/src/bingx.ts
  ts/src/pro/bingx.ts
  ts/src/pro/test/Exchange/test.watchTrades.ts
Labels: new exchange

#19464 wiki: update link for public / private api [ci skip]
  wiki/README.md
Labels: enhancement

#19497 fix(bingx): fetchPositions parsing
  ts/src/bingx.ts
Labels: bug

#19455 feat(btcmarkets): parseTransaction - string math
  ts/src/btcmarkets.ts
Labels: enhancement

#19415 Bitbns trigger orders
  ts/src/bitbns.ts
Labels: enhancement

#19502 fix(bitget): cancelAllOrders simplified
  ts/src/bitget.ts
Labels: enhancement

#19508 build: add pre-push hook
  .git-templates/hooks/pre-push
  python/setup.py
Labels: enhancement

#19515 fix(bybit) - temporarily skip tests
  skip-tests.json
Labels: enhancement

#19520 binance: update sign ccxt/ccxt#19511
  ts/src/binance.ts
Labels: bug

#19524 fix(deribit): fetchBalance
  ts/src/deribit.ts
Labels: bug

#19523 fix(tests) - ast transpiler update & integer
  package.json
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: enhancement

#19521 Binance check symbols type
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/pro/binance.ts
Labels: bug

#19519 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#19503 feat(okx) - listing timestamp
  ts/src/okx.ts
Labels: enhancement

#19529 fix: Coinex position response 'contracts'
  ts/src/coinex.ts
Labels: bug

#19527 feat(binance) - pair created ts
  ts/src/binance.ts
Labels: enhancement

#19525 feat(base): type fetchOpenInterest and fetchOpenInterestHistory
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bybit.ts
  ts/src/delta.ts
  ts/src/gate.ts
  ts/src/huobi.ts
  ts/src/okx.ts
Labels: enhancement

#19498 Coinspot: fetchMyTrades implementation
  ts/src/coinspot.ts
Labels: enhancement

#19538 fix(bybit): infer market type inside openOrders
  ts/src/bybit.ts
Labels: bug

#19548 binance: update @see
  ts/src/binance.ts
Labels: enhancement

#19547 binance: patch fetchTradingFee
  ts/src/binance.ts
Labels: bug

#19546 feat(bybit) - pair created ts
  ts/src/bybit.ts
Labels: enhancement

#19549 fix(okx): index OHLCV
  ts/src/okx.ts
Labels: bug

#19551 fix(bitget): fetchMyTrades, fetchDeposits and fetchWithdrawals ts
  ts/src/bitget.ts
Labels: enhancement

#19516 New unified methods: fetchLiquidations and fetchMyLiquidations
  build/export-exchanges.js
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/huobi.ts
  wiki/Manual.md
Labels: enhancement

#19550 poloniex: update apis
  ts/src/poloniex.ts
Labels: enhancement

#19557 pairs created timestamps (part 2)
  ts/src/cex.ts
  ts/src/coinbase.ts
  ts/src/coinbasepro.ts
  ts/src/coinex.ts
  ts/src/coinfalcon.ts
  ts/src/coinmate.ts
  ts/src/coinone.ts
  ts/src/cryptocom.ts
  ts/src/currencycom.ts
  ts/src/digifinex.ts
  ts/src/exmo.ts
  ts/src/gemini.ts
  ts/src/hitbtc.ts
  ts/src/huobijp.ts
  ts/src/idex.ts
  ts/src/independentreserve.ts
  ts/src/indodax.ts
Labels: enhancement

#19570 fix(bingx): parseTransaction
  ts/src/bingx.ts
Labels: bug

#19560 Bitget: borrowMargin, repayMargin
  ts/src/bitget.ts
Labels: enhancement

#19540 feat(ascendex) - pair created ts
  ts/src/ascendex.ts
Labels: enhancement

#19576 feat(latoken) - pair created ts
  ts/src/latoken.ts
Labels: enhancement

#19579 feat(poloniexfutures) - created ts pair
  ts/src/poloniexfutures.ts
Labels: enhancement

#19578 feat(poloniex) - pair created ts
  ts/src/poloniex.ts
Labels: enhancement

#19573 feat(krakenfutures) - pair created ts
  ts/src/krakenfutures.ts
Labels: enhancement

#19556 feat(hollaex) - market created ts
  ts/src/hollaex.ts
Labels: enhancement

#19581 poloniexfutures: add apis
  ts/src/poloniexfutures.ts
Labels: enhancement

#19589 fix(coinone): sign - encode payload
  ts/src/coinone.ts
Labels: bug

#19587 fix(poloniexfutures): fetchOpenOrders
  ts/src/poloniexfutures.ts
Labels: bug

#19580 kraken: add apis
  ts/src/kraken.ts
Labels: enhancement

#19555 feat(gate) - pair created ts
  ts/src/gate.ts
Labels: enhancement

#19554 feat(deribit) - pair create ts
  ts/src/deribit.ts
Labels: enhancement

#19553 feat(delta) - pair launch time
  ts/src/delta.ts
Labels: enhancement

#19542 feat(bitmart) - pair created ts
  ts/src/bitmart.ts
Labels: enhancement

#19584 empty pairs' creation timestamps
  ts/src/kraken.ts
  ts/src/kucoin.ts
  ts/src/kuna.ts
  ts/src/lbank.ts
  ts/src/lbank2.ts
  ts/src/luno.ts
  ts/src/lykke.ts
  ts/src/mercado.ts
  ts/src/mexc.ts
  ts/src/ndax.ts
  ts/src/novadax.ts
  ts/src/oceanex.ts
  ts/src/phemex.ts
  ts/src/probit.ts
  ts/src/tidex.ts
  ts/src/timex.ts
  ts/src/tokocrypto.ts
  ts/src/upbit.ts
  ts/src/wavesexchange.ts
  ts/src/wazirx.ts
  ts/src/whitebit.ts
  ts/src/yobit.ts
  ts/src/zaif.ts
  ts/src/zonda.ts
Labels: enhancement

#19594 Bitget: fetchBalance, add margin support
  ts/src/bitget.ts
Labels: enhancement

#19597 btcturk: add apis
  ts/src/btcturk.ts
Labels: enhancement

#19585 rename `assertTimestamp` into `assertTimestampAndDatetime` and create a separate method for `assertTimestamp`
  ts/src/test/Exchange/base/test.borrowInterest.ts
  ts/src/test/Exchange/base/test.borrowRate.ts
  ts/src/test/Exchange/base/test.depositWithdrawal.ts
  ts/src/test/Exchange/base/test.fundingRateHistory.ts
  ts/src/test/Exchange/base/test.ledgerEntry.ts
  ts/src/test/Exchange/base/test.ohlcv.ts
  ts/src/test/Exchange/base/test.openInterest.ts
  ts/src/test/Exchange/base/test.order.ts
  ts/src/test/Exchange/base/test.orderBook.ts
  ts/src/test/Exchange/base/test.position.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/Exchange/base/test.ticker.ts
  ts/src/test/Exchange/base/test.trade.ts
Labels: enhancement

#19574 feat(kucoinfutures) - pair created ts
  ts/src/kucoinfutures.ts
Labels: enhancement

#19544 feat(bittrex) - pair created ts
  ts/src/bittrex.ts
Labels: enhancement

#19543 feat(bitmex) - pair created ts
  ts/src/bitmex.ts
Labels: enhancement

#19528 feat(huobi) - pair create time
  build/transpile.js
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/huobi.ts
Labels: enhancement

#19604 Fix safe integer product
  ts/src/btcalpha.ts
Labels: bug

#19603 fix(coinone): parseOrder fix
  ts/src/coinone.ts
Labels: bug

#19606 fix(bybit): order fee spot
  ts/src/bybit.ts
Labels: bug

#19605 fix(gate) - safeTimestamp
  ts/src/gate.ts
  ts/src/kraken.ts
  ts/src/pro/hollaex.ts
  ts/src/pro/mexc.ts
  ts/src/whitebit.ts
  ts/src/woo.ts
Labels: bug

#19609 Bitget: createOrder, add margin support
  ts/src/bitget.ts
Labels: enhancement

#19610 fix(ascendex): reduceMargin no longer requires a negative number for amount
  ts/src/ascendex.ts
Labels: bug

#19613 fix(bitget,okx): handleUntilOption fix [ci deploy]
  ts/src/bitget.ts
  ts/src/okx.ts
Labels: bug

#19600 market structure
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/bit2c.ts
  ts/src/bitstamp1.ts
  ts/src/bl3p.ts
  ts/src/btcbox.ts
  ts/src/btctradeua.ts
  ts/src/coincheck.ts
  ts/src/coinspot.ts
  ts/src/paymium.ts
Labels: enhancement

#19615 feat(base) - add `safeIntegerMultiplied` (safe_integer_multiplied) method
  ts/src/base/functions/type.ts
Labels: bug

#19620 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#19619 Bitget: cancelOrder, add margin support
  ts/src/bitget.ts
Labels: enhancement

#19616 fix(Exchange.ts): WS error handling
  php/pro/Client.php
  php/pro/ClientTrait.php
  ts/src/base/Exchange.ts
Labels: bug

#19624 Bitget: fetchOpenOrders, fetchCanceledOrders, fetchClosedOrders, add margin support
  ts/src/bitget.ts
Labels: enhancement

#18747 kucoin watchOrders stop orders
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/pro/kucoin.ts
Labels: enhancement

#19630 fix(bybit): preserve fee signal
  ts/src/bybit.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: bug

#19628 fix(python-docs): see section [ci skip]
  build/transpile.js
Labels: bug

#19633 Bitget: fetchMyTrades, add margin support
  ts/src/bitget.ts
Labels: enhancement

#19631 Okcoin update
  ts/src/okcoin.ts
Labels: enhancement

#19637 update changelog [ci skip]
  CHANGELOG.md
Labels: bug

#19639 fix(bitget): cancelAllOrders default marginCoin
  ts/src/bitget.ts
Labels: bug

#19642 ascendex: add apis
  ts/src/ascendex.ts
Labels: enhancement

#19647 bitmart order status
  ts/src/bitmart.ts
Labels: bug

#19648 Krakenfutures :: add cancelOrders and fix signature
  ts/src/krakenfutures.ts
Labels: enhancement

#19651 Bitget: fetchMyLiquidations
  ts/src/bitget.ts
Labels: enhancement

#19654 gate: update apis
  ts/src/gate.ts
Labels: enhancement

#19655 fix(base): sortBy fix
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/ace.ts
  ts/src/base/Exchange.ts
  ts/src/base/functions/generic.ts
Labels: bug

#19638 Add createOrders
  build/transpile.js
  examples/ts/create-orders-example.ts
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
  python/ccxt/base/types.py
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/cryptocom.ts
  ts/src/gate.ts
  ts/src/krakenfutures.ts
  ts/src/oceanex.ts
  ts/src/okx.ts
  wiki/Manual.md
Labels: enhancement

#19085 fix(tests-currencies) - skip flag for FIAT deposit & withdraw for exchange (QUICK)
  skip-tests.json
  ts/src/test/Exchange/base/test.currency.ts
Labels: bug

#19662 Bitget: fetchBorrowRate
  ts/src/bitget.ts
Labels: enhancement

#19665 feat(kucoin): add order test and organize createOrder
  ts/src/kucoin.ts
Labels: enhancement

#19667 feat(kucoin): add createOrders
  ts/src/kucoin.ts
Labels: enhancement

#19663 bitopro: update @see
  ts/src/bitopro.ts
Labels: enhancement

#19679 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#19678 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#19676 Bitget: fetchBorrowInterest
  ts/src/bitget.ts
Labels: enhancement

#19670 feat(mexc): add createOrders
  ts/src/mexc.ts
Labels: enhancement

#19668 feat(cryptocom): add cancelOrders
  ts/src/cryptocom.ts
Labels: enhancement

#19702 gate: add @see
  ts/src/gate.ts
Labels: enhancement

#19704 bitrue: fix fetchBidsAsks
  ts/src/bitrue.ts
Labels: bug

#19700 feat(phemex): fetchBalance - throw error when fetching margin or future balance
  ts/src/phemex.ts
Labels: enhancement

#19695 Huobi: remove Hydro Protocol from commonCurrencies
  ts/src/huobi.ts
  ts/src/huobijp.ts
Labels: bug

#19689 Bitget: fetchMarketLeverageTiers, add margin support
  ts/src/bitget.ts
Labels: enhancement

#19698 bitopro: update cancelAllOrders
  ts/src/bitopro.ts
Labels: enhancement

#19694 Bitget: createOrders, add margin support
  ts/src/bitget.ts
Labels: enhancement

#19708 feat(build): speed up single transpilation [ci skip]
  build/transpile.js
Labels: enhancement

#19712 Bybit: remove commonCurrencies GASDAO
  ts/src/bybit.ts
Labels: bug

#19714 Ascendex: setMarginMode, setLeverage, and set future to false
  ts/src/ascendex.ts
Labels: bug

#19709 feat(bitvavo): pagination and jsdocs
  ts/src/bitvavo.ts
Labels: enhancement

#19715 Ascendex: fetchFundingHistory
  build/export-exchanges.js
  ts/ccxt.ts
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/bitget.ts
  ts/src/coinex.ts
  ts/src/gate.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/phemex.ts
  ts/src/poloniexfutures.ts
Labels: enhancement

#19699 bitget: update method
  ts/src/bitget.ts
Labels: enhancement

#19723 feat(hitbtc): createOrder - unified timeInForce and postOnly
  ts/src/hitbtc.ts
Labels: enhancement

#19719 gemini: update method
  ts/src/gemini.ts
Labels: enhancement

#19718 woo: update method
  ts/src/woo.ts
Labels: enhancement

#19732 phemex: update apis
  ts/src/phemex.ts
Labels: bug

#19611 huobi: update balance apis
  ts/src/huobi.ts
  ts/src/pro/huobi.ts
Labels: enhancement

#19734 cli: update log
  examples/js/cli.js
  examples/ts/cli.ts
Labels: enhancement

#19738 zonda: remove method
  ts/src/zonda.ts
Labels: enhancement

#19731 upbit: remove method
  ts/src/upbit.ts
Labels: enhancement

#19727 fix(base) - inarray/isarray
  ts/src/base/Exchange.ts
Labels: bug

#19742 fix(base): add axolotl as class method to match php and py
  ts/src/base/Exchange.ts
  ts/src/wavesexchange.ts
Labels: bug

#19754 docs(Exchange): extractParams - docstring
  ts/src/base/functions/misc.ts
Labels: enhancement

#19750 Bitmex: parseOrder, add remaining value for inverse orders
  ts/src/bitmex.ts
Labels: bug

#19747 fix(huobi): add check for out of order sequence, fix #19674
  ts/src/pro/huobi.ts
Labels: bug

#19763 Digifinex: fetchFundingHistory
  ts/src/digifinex.ts
Labels: enhancement
