Repository ccxt/ccxt, pull requests merged in 2024-01, with the labels that each got.

#20624 bybit: add error codes
  ts/src/bybit.ts
Labels: enhancement

#20630 fix(phemex) - fetchtickers market undefined
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
Labels: bug

#20627 coinsph: remove method usage
  ts/src/coinsph.ts
  ts/src/test/static/request/coinsph.json
Labels: enhancement

#20625 HTX: trailing percent orders
  ts/src/htx.ts
  ts/src/test/static/request/huobi.json
Labels: enhancement

#20636 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#20634 fix(delta): expired option markets conditional check
  ts/src/delta.ts
Labels: bug

#20635 HTX: fetchOrders, fetchOpenOrders, cancelOrder, cancelAllOrders, trailing support
  ts/src/htx.ts
  ts/src/test/static/request/huobi.json
Labels: enhancement

#20632 alpaca: fix us equity undefined quote
  ts/src/alpaca.ts
Labels: bug

#20649 fix(bingx) - createOrder & fetchOrder ids (long numbers issue)
  ts/src/bingx.ts
Labels: bug

#20657 feat(htx): setPositionMode
  ts/src/htx.ts
  ts/src/test/static/request/huobi.json
Labels: enhancement

#20639 Bitmex: createOrder, editOrder, add trailing support
  ts/src/bitmex.ts
  ts/src/test/static/request/bitmex.json
Labels: enhancement

#20676 fix(php) - clone deep extend
  php/Exchange.php
Labels: bug

#20678 fix(py) - timeout
  python/ccxt/base/exchange.py
Labels: bug

#20671 Bybit: createOrder, add trailingAmount support
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#20682 fix(coinbasepro): fetchTickers - docs no longer reference okx
  ts/src/pro/coinbasepro.ts
Labels: bug

#20693 Okx: trailing orders
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#20669 fix(bingx) - nested orders parsing & JSON handling
  ts/src/bingx.ts
  ts/src/test/static/response/bingx.json
Labels: bug

#20705 fix(php) - reduce huge unnecessary log
  php/test/test_async.php
Labels: bug

#20672 Binance: createOrder, trailingPercent orders
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#20695 fix(bitget) - watch tickers filter
  ts/src/pro/bitget.ts
Labels: bug

#20697 fix(bybit) - watch tickers filter
  ts/src/pro/bybit.ts
Labels: bug

#20673 Deribit: trailing order support
  ts/src/deribit.ts
  ts/src/test/static/markets/deribit.json
  ts/src/test/static/request/deribit.json
Labels: enhancement

#20723 feat(bitmart) - watchtickers for spot and update for swap
  ts/src/pro/bitmart.ts
Labels: bug, enhancement

#20699 fix(coibnasepro) - watch tickers filter
  ts/src/pro/coinbasepro.ts
Labels: bug

#20731 Bybit: fix fetchCurrencies RateLimitExceeded error
  ts/src/bybit.ts
Labels: bug

#20706 useProxy flag in tests
  build.sh
  package.json
  run-tests.js
  tests-manager.sh
  ts/src/test/test.ts
Labels: enhancement

#20736 fix(tests) - useProxy py
  python/ccxt/test/test_async.py
Labels: bug

#20685 feat(js) - load modules async
  ts/src/base/Exchange.ts
Labels: bug

#20758 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#20746 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#20755 Okx: fix fetchStatus
  ts/src/okx.ts
Labels: bug

#20744 fix(bitfinex): parseTransfer - removed made up timestamp data
  ts/src/bitfinex.ts
Labels: bug

#19696 feat(bigone): contract implicit api endpoints, fetchMarkets
  skip-tests.json
  ts/src/abstract/bigone.ts
  ts/src/bigone.ts
Labels: enhancement

#20753 fix(huobijp): createOrder - remove made up timestamp data
  ts/src/huobijp.ts
Labels: bug

#20748 fix(coinlist): fetchBalance - remove made up timestamp data
  ts/src/coinlist.ts
Labels: bug

#20752 fix(hitbtc): transfer - remove made up timestamp data
  ts/src/hitbtc.ts
Labels: bug

#20751 fix(gate): transfer - remove made up timestamp data
  ts/src/gate.ts
Labels: bug

#20749 fix(coinsph): fetchBalance - remove made up timestamp data
  ts/src/coinsph.ts
Labels: bug

#20759 fix(bingx): cancel swap orders by client order ids
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: bug

#20762 fix(binance): watchPositions
  ts/src/pro/binance.ts
Labels: bug

#20754 exchange: createTrailingAmountOrder, createTrailingPercentOrder
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/bybit.ts
  ts/src/deribit.ts
  ts/src/htx.ts
  ts/src/kraken.ts
  ts/src/okx.ts
  ts/src/test/static/request/bingx.json
  ts/src/woo.ts
Labels: enhancement

#20603 fix(htx): can place isolated margin orders
  ts/src/htx.ts
  ts/src/test/static/request/huobi.json
Labels: bug

#14873 Upbit decimal
  ts/src/upbit.ts
Labels: enhancement

#20765 feat(bigone): fetchTicker(s) - fetches contract tickers
  ts/src/bigone.ts
  ts/src/test/static/markets/bigone.json
  ts/src/test/static/request/bigone.json
Labels: enhancement

#20769 feat(bigone): fetchOrderBook - can fetch contract markets
  ts/src/bigone.ts
Labels: enhancement

#20775 fix(bitget) - trades limit (QUICK)
  ts/src/bitget.ts
Labels: bug

#20776 fix(coinlist) - max trades limit (QUICK)
  ts/src/coinlist.ts
Labels: bug

#20779 fix(gate) - max trades limit (QUICK)
  ts/src/gate.ts
Labels: bug

#20778 fix(gemini) - max trades limit
  ts/src/gemini.ts
Labels: bug

#20768 fix(probit) - max fetchtrades limit (QUICK)
  ts/src/probit.ts
Labels: bug

#20777 fix(coinone) - max trades limit (QUICK)
  ts/src/coinone.ts
Labels: bug

#20780 fix(kraken) - trades max limit (QUICK)
  ts/src/kraken.ts
Labels: bug

#20770 lbank: remove method usage
  ts/src/lbank.ts
  ts/src/test/static/request/lbank.json
Labels: enhancement

#20782 fix(oceanex) - trades max limit (QUICK)
  ts/src/oceanex.ts
Labels: bug

#20658 transpile: update process num when build parallel
  build/transpile.js
Labels: enhancement

#20786 fix(wavesexchange) - fix trades limit (QUICK)
  ts/src/wavesexchange.ts
Labels: bug

#20294 feat(okx) - watchOHLCVForSymbols
  ts/src/pro/okx.ts
Labels: enhancement

#20801 feat(bingx): add fetchMyTrades in spot market
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: enhancement

#20793 feat(bigone): fetchTrades, fetchOHLCV - error thrown if fetchTrades or fetchOHLCV called for contract markets
  ts/src/bigone.ts
Labels: enhancement

#20796 Coinbase: withdraw
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
  ts/src/test/test.ts
Labels: enhancement

#20808 fix(bigone): fetchMarkets uses /symbols endpoint
  ts/src/bigone.ts
  ts/src/test/static/markets/bigone.json
Labels: bug

#20542 revert - remove fetch last prices
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/binance.ts
  ts/src/binanceus.ts
  ts/src/htx.ts
  ts/src/test/Exchange/base/test.lastPrice.ts
  ts/src/test/Exchange/test.fetchLastPrices.ts
  ts/src/test/Exchange/test.fetchTickers.ts
  ts/src/test/static/markets/binance.json
  ts/src/test/static/markets/htx.json
  ts/src/test/static/request/binance.json
  ts/src/test/static/request/binanceus.json
  ts/src/test/static/request/htx.json
  ts/src/test/test.ts
Labels: bug

#20442 exchange: stop, stop loss and take profit functions
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/gate.ts
  ts/src/htx.ts
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
  ts/src/woo.ts
Labels: enhancement

#20826 fix(proxy) - undefined & null
  ts/src/base/Exchange.ts
Labels: bug

#20830 feat(ascendex): fetchBalance - can pass params["marginMode"]
  ts/src/ascendex.ts
Labels: enhancement

#20831 fix(bingx): has["margin"] = false
  ts/src/bingx.ts
Labels: bug

#20824 feat(coinone): add ws apis
  skip-tests.json
  ts/src/coinone.ts
  ts/src/pro/coinone.ts
Labels: enhancement

#20833 fix(krakenfutures) - watchTickers multi symbols
  ts/src/pro/krakenfutures.ts
Labels: bug

#20837 fix(binance) - watchtickers multi symbol
  ts/src/pro/binance.ts
Labels: bug

#20839 fix(kucoin) - watchTickers multi ticker
  ts/src/pro/kucoin.ts
Labels: bug

#20841 fix(poloniex) - watchTickers multi dict
  ts/src/pro/poloniex.ts
Labels: bug

#20847 fix(coinsph) - fetchtrades
  ts/src/coinsph.ts
Labels: bug

#20848 coinlist: add apis
  ts/src/coinlist.ts
Labels: enhancement

#20846 feat(coincheck): add pro
  skip-tests.json
  ts/src/coincheck.ts
  ts/src/pro/coincheck.ts
Labels: enhancement

#20622 feat(tests) - test WatchTickers & test fetchTickers updates (single & multi symbol tests)
  build/transpile.js
  skip-tests.json
  ts/src/pro/test/Exchange/test.watchTickers.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/Exchange/base/test.ticker.ts
  ts/src/test/Exchange/test.fetchTickers.ts
  ts/src/test/test.ts
Labels: enhancement

#20854 add skips
  skip-tests.json
Labels: bug

#20863 fix(whitebit) - has fetchstatus true
  ts/src/whitebit.ts
Labels: bug

#20858 docs(kraken): update kraken docs link
  ts/src/kraken.ts
Labels: bug

#20867 fix(root) - remove 'test.ts' file
  test.ts
Labels: bug

#20859 fix(kraken): rate limiter fixed for public methods
  ts/src/kraken.ts
Labels: bug

#20876 Deribit: fix fetchFundingRateHistory since
  ts/src/deribit.ts
  ts/src/test/static/request/deribit.json
Labels: bug

#20878 htx: add apis
  ts/src/htx.ts
Labels: enhancement

#20879 gate: add apis
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#20871 fix(dependencies) - ast-transpiler update
  package-lock.json
  package.json
Labels: bug

#20880 Deribit: fix fetchPositions linear currency
  ts/src/deribit.ts
  ts/src/test/static/request/deribit.json
Labels: bug

#20866 feat(run-tests) - warning & timeouts upgrade
  run-tests.js
Labels: enhancement

#15185 lbank - websockets
  skip-tests.json
  ts/src/lbank.ts
  ts/src/pro/lbank.ts
Labels: ws

#20891 poloniexfutures.has["fetchFundingRateHistory"]: false
  ts/src/poloniexfutures.ts
Labels: enhancement

#20893 mexc update docs link
  ts/src/mexc.ts
Labels: enhancement

#20892 ascendex.has["fetchOpenInterest,fetchOpenInterestHistory"] = false
  ts/src/ascendex.ts
Labels: enhancement

#20895 fix(binanceWs): watchPositions
  ts/src/pro/binance.ts
Labels: bug

#20908 fix(binanceus) - rate limits
  ts/src/binanceus.ts
Labels: bug, critical

#20899 fix(kucoinfutures) - fix funding value
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
  ts/src/test/static/response/kucoinfutures.json
Labels: bug

#18629 feat(bitvavo): ws trading
  build/validate-return-type.ts
  ts/src/base/Exchange.ts
  ts/src/bitvavo.ts
  ts/src/pro/bitvavo.ts
  ts/src/test/static/request/bitvavo.json
  ts/src/test/static/response/bitvavo.json
Labels: enhancement, ws

#20920 fix(gate): fetchLeverageTiers parsing
  ts/src/base/Exchange.ts
  ts/src/gate.ts
Labels: bug

#20932 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#20925 WsClient eslint errors fix
  ts/src/base/ws/WsClient.ts
Labels: enhancement

#20928 fix(bitopro): fix ws url and signature
  ts/src/pro/bitopro.ts
Labels: enhancement

#20934 novadax: add apis, update ratelimit
  ts/src/novadax.ts
Labels: enhancement

#20936 fix(bitrue): use proper orderbook type
  ts/src/pro/bitrue.ts
Labels: bug

#20937 feat(woo): fix fetchDepositAddress flag
  ts/src/test/static/request/woo.json
  ts/src/woo.ts
Labels: bug

#20958 bitget has
  ts/src/bitget.ts
Labels: enhancement

#20960 has["fetchFundingRate"]
  ts/src/bigone.ts
  ts/src/bitrue.ts
  ts/src/coinbasepro.ts
  ts/src/okcoin.ts
  ts/src/poloniex.ts
Labels: enhancement

#20972 bitfinex2: fetchOpenInterest
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#20978 feat(hitbtcPro): add sandbox mode
  ts/src/pro/hitbtc.ts
Labels: bug

#20954 fix(binanceus) - ratelimits 3
  ts/src/binanceus.ts
Labels: bug

#20980 Bitfinex2: fetchOpenInterestHistory
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#20950 bitopro: add watchMyTrades
  skip-tests.json
  ts/src/pro/bitopro.ts
Labels: enhancement

#20985 fix(phemex): position parsing
  ts/src/phemex.ts
  ts/src/test/static/response/phemex.json
Labels: bug

#20989 Bitfinex2: fetchLiquidations
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#20987 fix(gate): parse web trade id
  ts/src/gate.ts
  ts/src/test/static/response/gate.json
Labels: bug

#20988 fix(ws): freezing eror
  php/pro/Client.php
  php/pro/ClientTrait.php
  python/ccxt/async_support/base/exchange.py
  python/ccxt/async_support/base/ws/aiohttp_client.py
  ts/src/base/Exchange.ts
  ts/src/base/ws/Client.ts
Labels: bug, ws

#20995 bingx: add watchTicker
  ts/src/pro/bingx.ts
Labels: enhancement

#20998 fix(upbit): fetchDepositAddress takes params["network"]
  ts/src/upbit.ts
Labels: bug

#20297 Coinmetro integration [ci deploy]
  skip-tests.json
  ts/src/abstract/coinmetro.ts
  ts/src/coinmetro.ts
  ts/src/test/static/currencies/coinmetro.json
  ts/src/test/static/markets/coinmetro.json
  ts/src/test/static/request/coinmetro.json
  ts/src/test/static/response/coinmetro.json
  ts/src/test/test.ts
Labels: new exchange

#21004 feat(bitforex): cancelAllOrders
  ts/src/bitforex.ts
  ts/src/test/static/request/bitforex.json
Labels: enhancement

#21005 has["cancelAllOrders"]
  ts/src/bit2c.ts
  ts/src/bitbank.ts
  ts/src/bitbns.ts
  ts/src/bitflyer.ts
Labels: enhancement

#21008 Bitfinex2: setMargin
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#21020 fix(coinbase) - watchTickers for all markets
  ts/src/pro/coinbase.ts
Labels: enhancement

#21021 feat(coinbase) - fetchBidsAsks - multi symbol arguments support
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#21026 bitget has
  ts/src/bitget.ts
Labels: enhancement

#21022 feat(coinbase) - fetchtickers with multi symbols support
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#19649 base - exception handling
  ts/src/binance.ts
Labels: bug, enhancement

#21028 Bitfinex2: update createOrder
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
  ts/src/test/static/response/bitfinex2.json
Labels: enhancement

#21025 fix(hitbtc): reduceMargin, addMargin, can set marginMode
  ts/src/hitbtc.ts
  ts/src/test/static/request/hitbtc.json
  ts/src/test/static/response/hitbtc.json
Labels: bug

#21035 fix(exceptions) - Move OperationRejected, NoChange and MarginModeAlreadySet out of BadRequest
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
Labels: enhancement

#21033 feat(bitmex) - watchTickers
  ts/src/pro/bitmex.ts
Labels: enhancement

#20982 feat(p2b): websockets/pro implementation
  skip-tests.json
  ts/src/p2b.ts
  ts/src/pro/p2b.ts
Labels: enhancement, ws

#21038 feat(exceptions) - ratelimitexceeded out of DDOSprotection
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
Labels: bug, enhancement

#21037 feat(docs) - documentation of exception types - OperationFailed, OperationRejected, BadRequest
  wiki/Manual.md
Labels: bug

#21040 fix(okx): fetches first candle from start of since
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: bug

#21047 Digifinex: fetchTickers, safeMarket fourth argument error
  ts/src/digifinex.ts
  ts/src/test/static/request/digifinex.json
Labels: bug
