Repository ccxt/ccxt, pull requests merged in 2024-12, with the labels that each got.

#24410 fix(hyperliquid) - migrate to TICK_SIZE
  ts/src/hyperliquid.ts
  ts/src/test/static/currencies/hyperliquid.json
  ts/src/test/static/markets/hyperliquid.json
Labels: enhancement

#24429 test(hashkey) - skip
  skip-tests.json
  ts/src/hashkey.ts
Labels: bug

#24430 fix(kraken) - errors check & rewrite
  ts/src/kraken.ts
Labels: bug

#24435 feat(bitmex) - features
  ts/src/bitmex.ts
Labels: enhancement

#23980 feat(defx): new exchange
  ts/src/abstract/defx.ts
  ts/src/defx.ts
  ts/src/pro/defx.ts
  ts/src/test/static/currencies/defx.json
  ts/src/test/static/markets/defx.json
  ts/src/test/static/request/defx.json
  ts/src/test/static/response/defx.json
  ts/src/test/tests.ts
Labels: new exchange

#24443 refactor(bitfinex) - old into v1
  build/validate-types.ts
  skip-tests.json
  ts/src/abstract/bitfinex1.ts
  ts/src/bitfinex1.ts
  ts/src/pro/bitfinex1.ts
  ts/src/test/static/currencies/bitfinex1.json
  ts/src/test/static/markets/bitfinex1.json
  ts/src/test/static/request/bitfinex1.json
  ts/src/test/static/response/bitfinex1.json
Labels: enhancement

#24456 fix(probit) - watchTrades
  ts/src/pro/probit.ts
Labels: bug

#24454 feat(coinbase): add fetchDepositId, fetchDepositIds methods
  build/validate-types.ts
  ts/src/coinbase.ts
  wiki/Manual.md
Labels: enhancement

#24445 fix!(bitfinex) - bitfinex2
  skip-tests.json
  ts/src/abstract/bitfinex.ts
  ts/src/bitfinex.ts
  ts/src/pro/bitfinex.ts
  ts/src/test/static/currencies/bitfinex.json
  ts/src/test/static/markets/bitfinex.json
  ts/src/test/static/request/bitfinex.json
  ts/src/test/static/response/bitfinex.json
Labels: enhancement

#24451 refactor(features) - gtc to true as default
  ts/src/base/Exchange.ts
Labels: enhancement

#24448 hyperliquid - features implementation
  ts/src/hyperliquid.ts
Labels: enhancement

#24404 bitmart - `.features`
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bybit.ts
  ts/src/okx.ts
  ts/src/test/Exchange/test.features.ts
Labels: enhancement

#24482 feat(bingx): add fetchPositionHistory
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: enhancement

#24489 fix(features) - gtc (urgent)
  ts/src/base/Exchange.ts
Labels: bug

#24486 feat(kucoin) - features
  ts/src/kucoin.ts
Labels: enhancement

#24487 feat(kucoinfutures) - .features
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
Labels: enhancement

#24502 htx - features
  ts/src/htx.ts
Labels: enhancement

#24508 feat(digifinex): add spot <> swap to transfer
  ts/src/digifinex.ts
  ts/src/test/static/request/digifinex.json
  ts/src/test/static/response/digifinex.json
Labels: enhancement

#24514 feat(alpaca): fetchBalance
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
  ts/src/test/static/response/alpaca.json
Labels: enhancement

#24509 htx - `stop` rename into `trigger`
  ts/src/htx.ts
Labels: enhancement

#24480 docs(orders) - add stoploss order
  wiki/Manual.md
Labels: enhancement

#24525 cryptocom - features
  ts/src/cryptocom.ts
Labels: enhancement

#24531 stop to trigger
  ts/src/bitmart.ts
  ts/src/blofin.ts
  ts/src/coinex.ts
  ts/src/exmo.ts
  ts/src/hashkey.ts
  ts/src/kucoin.ts
  ts/src/okcoin.ts
  ts/src/okx.ts
  ts/src/phemex.ts
  ts/src/poloniexfutures.ts
  ts/src/pro/coinex.ts
  ts/src/pro/gate.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/okx.ts
  ts/src/vertex.ts
  ts/src/woo.ts
  ts/src/woofipro.ts
  ts/src/xt.ts
Labels: enhancement

#24532 params - `stop` to `trigger`
  ts/src/binance.ts
  ts/src/bitmart.ts
  ts/src/blofin.ts
  ts/src/defx.ts
  ts/src/kucoin.ts
  ts/src/okcoin.ts
  ts/src/okx.ts
  ts/src/poloniex.ts
  ts/src/poloniexfutures.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bybit.ts
  ts/src/pro/gate.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/okx.ts
  ts/src/vertex.ts
  ts/src/woo.ts
  ts/src/xt.ts
Labels: enhancement

#24222 docs(announcements) - add ^
  wiki/Manual.md
Labels: enhancement

#24534 `stopPrice` -> `triggerPrice`
  ts/src/ascendex.ts
  ts/src/bingx.ts
  ts/src/bit2c.ts
  ts/src/bitbank.ts
  ts/src/bitbns.ts
  ts/src/bitfinex.ts
  ts/src/bitfinex1.ts
  ts/src/bitflyer.ts
  ts/src/bitget.ts
  ts/src/bithumb.ts
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/bitopro.ts
  ts/src/bitrue.ts
  ts/src/bitso.ts
  ts/src/bitstamp.ts
  ts/src/bitteam.ts
  ts/src/bitvavo.ts
  ts/src/blockchaincom.ts
  ts/src/btcalpha.ts
  ts/src/btcbox.ts
  ts/src/btcmarkets.ts
  ts/src/bybit.ts
Labels: enhancement

#24533 feat(coinbase) - features
  ts/src/coinbase.ts
Labels: enhancement

#24517 mexc - features
  ts/src/mexc.ts
Labels: enhancement

#24537 feat(coinbaseinternational) - features
  ts/src/coinbaseinternational.ts
Labels: enhancement

#24546 feat(phemex): fetchFundingRate, add fundingRate field for linear swap
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
  ts/src/test/static/response/phemex.json
Labels: enhancement

#24536 refactor(bybit) - `stopPrice` to `triggerPrice`
  ts/src/bybit.ts
Labels: enhancement

#24569 feat(bitmart): fetchFundingRateHistory
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
  ts/src/test/static/response/bitmart.json
Labels: enhancement

#24574 feat(bitmart): fetchLedger and fetchFundingHistory
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
  ts/src/test/static/response/bitmart.json
Labels: enhancement

#24570 feat(okx) - sol staking endpoints
  ts/src/okx.ts
Labels: bug

#24547 docs(triggerDirection) - ascending/descending
  wiki/Manual.md
Labels: enhancement

#24579 mexc feature rename
  ts/src/mexc.ts
Labels: enhancement

#24575 feat(kraken) - features
  ts/src/kraken.ts
Labels: enhancement

#24600 fix(exchange) - handleOptionAndParams2
  ts/src/base/Exchange.ts
Labels: bug

#24614 feat(woox) - until missing
  ts/src/woo.ts
Labels: bug

#24599 fix(exchanges) - remove extra
  cs/ccxt/exchanges/bitbay.cs
  cs/ccxt/exchanges/hitbtc3.cs
  php/bitbay.php
  php/bitfinex2.php
  php/hitbtc3.php
  php/pro/bitfinex2.php
  python/ccxt/bitbay.py
  python/ccxt/bitfinex2.py
  python/ccxt/hitbtc3.py
  python/ccxt/pro/bitfinex2.py
Labels: bug

#24609 refactor(hashkey) - dry up
  ts/src/hashkey.ts
Labels: enhancement

#24610 hashkey -`features`
  ts/src/hashkey.ts
Labels: enhancement

#24596 feat(coinex) - features
  ts/src/coinex.ts
Labels: enhancement

#24611 feat(bitfinex): add fetchOpenInterests
  ts/src/bitfinex.ts
  ts/src/test/static/request/bitfinex.json
  ts/src/test/static/response/bitfinex.json
Labels: enhancement

#24612 feat(hitbtc): add fetchOpenInterests
  ts/src/hitbtc.ts
  ts/src/test/static/request/hitbtc.json
  ts/src/test/static/response/hitbtc.json
Labels: enhancement

#24615 woo (woox) - `features` implementation
  ts/src/woo.ts
Labels: enhancement

#24617 feat(bitfinex) - `features`
  ts/src/bitfinex.ts
Labels: enhancement

#24616 feat(woofipro) - `features` implementation
  ts/src/woofipro.ts
Labels: enhancement

#24578 krakenfutures - features
  ts/src/krakenfutures.ts
Labels: enhancement

#24640 fix(php) - E_STRICT removal
  build/transpile.ts
  examples/ccxt.pro/php/many-exchanges-many-accounts.php
  examples/ccxt.pro/php/watch-multiple-methods-multiple-exchanges.php
  examples/php/build-ohlcv-bars.php
  examples/php/cache-exchange-instance-reuse.php
  examples/php/cli.php
  examples/php/compare-two-exchanges-capabilities.php
  examples/php/create-order-position-with-takeprofit-stoploss.php
  examples/php/create-order-ws-example.php
  examples/php/create-orders-example.php
  examples/php/create-trailing-amount-order.php
  examples/php/create-trailing-percent-order.php
  examples/php/fetch-ohlcv-many-exchanges-continuosly.php
  examples/php/fetch-ohlcv.php
  examples/php/kraken-create-and-close-position.php
  examples/php/margin-loan-borrow-buy-sell-repay.php
  examples/php/method-overload-override.php
  examples/php/phemex-create-order-position-with-takeprofit-stoploss.php
  examples/php/proxy-usage.php
  examples/php/watch-OHLCV-For-Symbols.php
  examples/php/watch-OHLCV.php
  examples/php/watch-OrderBook-For-Symbols.php
  examples/php/watch-Trades-For-Symbols.php
  examples/php/watch-tickers.php
  examples/php/watchOHLCVForSymbols.php
  examples/php/watchOrderBookForSymbols.php
  examples/php/watchPositions-many-exchanges-continuosly.php
  examples/php/watchPositions.php
  examples/php/watchPositionsForSymbols.php
  examples/php/watchTradesForSymbols.php
  php/test/tests_helpers.php
  wiki/ccxt.pro.manual.md
Labels: enhancement

#24641 fix(php) - version numbers
  CONTRIBUTING.md
  README.md
  wiki/Install.md
Labels: bug

#24643 fix(php) - pow gmp
  php/static_dependencies/BI/BigInteger.php
Labels: bug

#24644 fix(gemini) - add triggerPrice
  ts/src/gemini.ts
Labels: bug

#24613 fix(woo) - stoploss/takeprofit price
  ts/src/woo.ts
Labels: bug

#24647 gemini - `features`
  ts/src/gemini.ts
Labels: enhancement

#24438 feat(bitstamp) - .features implementation
  ts/src/bitstamp.ts
Labels: enhancement

#24648 refactor(exchanges) - remove extra
  cs/ccxt/api/bitbay.cs
  cs/ccxt/api/hitbtc3.cs
  cs/ccxt/wrappers/bitbay.cs
  cs/ccxt/wrappers/hitbtc3.cs
  php/async/bitbay.php
  php/async/bitfinex2.php
  php/async/hitbtc3.php
  python/ccxt/async_support/bitbay.py
  python/ccxt/async_support/bitfinex2.py
  python/ccxt/async_support/hitbtc3.py
Labels: enhancement

#24646 gmp func - 2
  php/Precise.php
  php/static_dependencies/phpseclib/Math/BigInteger.php
Labels: enhancement

#24652 refactor(binance) - features
  ts/src/binance.ts
Labels: enhancement

#24651 refactor(mexc) - meta changes
  ts/src/mexc.ts
Labels: enhancement

#24656 bingx - features upd
  ts/src/bingx.ts
  ts/src/bitfinex.ts
Labels: enhancement

#24660 features - updates
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/bitstamp.ts
  ts/src/bybit.ts
  ts/src/coinbase.ts
  ts/src/coinbaseinternational.ts
  ts/src/coinex.ts
  ts/src/cryptocom.ts
  ts/src/gate.ts
  ts/src/gemini.ts
  ts/src/hashkey.ts
  ts/src/htx.ts
  ts/src/hyperliquid.ts
  ts/src/kraken.ts
  ts/src/krakenfutures.ts
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/woo.ts
  ts/src/woofipro.ts
Labels: enhancement

#24670 tests(static) - detect & retest exchanges
  build.sh
  ts/src/test/static/request/bequant.json
Labels: enhancement

#24619 tests(trades) - taker only
  ts/src/test/Exchange/test.fetchTrades.ts
Labels: enhancement

#24676 feat(htx): fetchOpenInterests
  ts/src/htx.ts
  ts/src/test/static/request/htx.json
  ts/src/test/static/response/htx.json
Labels: enhancement

#24687 feat(binance): add papiV2 endpoint
  ts/src/binance.ts
Labels: enhancement

#24685 fix(bitopro): patch watchOrderBook
  ts/src/pro/bitopro.ts
Labels: bug

#24686 fix(transpile): replace tsx with npx tsx
  build/transpile.sh
Labels: enhancement

#24704 feat(binance): editOrder, add portfolioMargin support
  ts/src/binance.ts
Labels: enhancement

#24708 fix(okx) - strike num
  ts/src/okx.ts
Labels: bug

#24709 fix(okx) - fetchmarkets retests
  skip-tests.json
Labels: enhancement

#24711 skip ellipx - ob2
  skip-tests.json
  ts/src/ellipx.ts
Labels: bug

#24710 fix(okx) - missing currency 'info'
  skip-tests.json
  ts/src/okx.ts
Labels: bug

#24713 ellipx - L2 ob skip
  skip-tests.json
  ts/src/ellipx.ts
Labels: bug

#24712 bybit skip q/b vol
  skip-tests.json
  ts/src/bybit.ts
Labels: bug
