Repository ccxt/ccxt, pull requests merged in 2024-07, with the labels that each got.

#22920 feat(base) - add marginMode type
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/base/types.ts
Labels: enhancement

#22903 kucoin - fetchMarkets, setLeverage, implicit api
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
Labels: enhancement

#22948 fix(lbank): cancelOrder, cancelAllOrders - unified response
  ts/src/lbank.ts
Labels: enhancement

#22951 fix(delta): cancelAllOrders - unified response
  ts/src/delta.ts
Labels: enhancement

#22950 fix(bitflyer): cancelOrder - unified response
  ts/src/bitflyer.ts
Labels: enhancement

#22960 fix(bybit): fetch balance for unified inverse account
  ts/src/bybit.ts
Labels: bug

#22958 fix(binance) - exceptions for OpRejected
  ts/src/binance.ts
Labels: bug

#22963 bingx: add coin-m endpoints
  ts/src/bingx.ts
Labels: enhancement

#22961 fix(bitopro): cancelOrder - unified response
  ts/src/bitopro.ts
Labels: enhancement

#22949 fix(bitget): cancelAllOrders - unified response
  ts/src/bitget.ts
Labels: enhancement

#22962 huobijp, htx: cancelAllOrders, cancelOrders - unified response
  ts/src/htx.ts
  ts/src/huobijp.ts
Labels: enhancement

#22970 bingx: fetchInverseSwapMarkets
  ts/src/bingx.ts
Labels: enhancement

#22972 feat(gate): add cancelOrders and cancelOrdersForSymbols
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#22977 htx: set minDeposit value in fetchCurrencies
  ts/src/htx.ts
Labels: bug

#22976 bingx: fetchOHLCV inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/markets/bingx.json
  ts/src/test/static/request/bingx.json
Labels: enhancement

#22983 Bigone cancel all orders
  ts/src/bigone.ts
Labels: enhancement

#22981 fix(latoken): cancelAllOrders - unified response
  ts/src/latoken.ts
Labels: enhancement

#22984 fix(alpaca): cancelAllOrders - unified response
  ts/src/alpaca.ts
Labels: enhancement

#22980 bingx: fetchOrderBook inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#22991 bingx: fetchFundingRate, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23004 bingx: fetchOpenInterest, add inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23003 fix(okx): handleErrors' response parameter expects dictionary input
  ts/src/pro/okx.ts
Labels: bug

#23020 hyperliquid: add fetchTradingFee & static-tests
  ts/src/hyperliquid.ts
  ts/src/test/static/request/hyperliquid.json
  ts/src/test/static/response/hyperliquid.json
Labels: enhancement

#22998 fix(binance) - message hashes
  ts/src/pro/binance.ts
Labels: bug

#23016 feat(exceptions) - BadResponse & CancelPending moved
  ts/src/base/errorHierarchy.ts
Labels: enhancement

#23001 fix!(exceptions) - ProxyError into InvalidProxySettings
  build/transpile.js
  php/async/Exchange.php
  python/ccxt/base/exchange.py
  python/ccxt/test/tests_helpers.py
  ts/src/base/Exchange.ts
  ts/src/base/errorHierarchy.ts
  ts/src/test/tests.helpers.ts
  ts/src/test/tests.ts
Labels: enhancement

#23000 tests - fix args
  ts/src/test/tests.helpers.ts
Labels: bug

#23027 fix(bingx) - watchTrades issue
  ts/src/pro/bingx.ts
Labels: bug

#22974 feat(wiki) - taker maker fees
  wiki/Manual.md
Labels: bug

#23032 fix(digifinex): cancelOrder(s) - unified response
  ts/src/digifinex.ts
Labels: enhancement

#17814 feat(xt): websocket implementation
  cs/ccxt/ws/Client.cs
  skip-tests.json
  ts/src/abstract/xt.ts
  ts/src/base/Exchange.ts
  ts/src/pro/bitmart.ts
  ts/src/pro/bitopro.ts
  ts/src/pro/coincheck.ts
  ts/src/pro/coinone.ts
  ts/src/pro/hyperliquid.ts
  ts/src/pro/xt.ts
  ts/src/xt.ts
Labels: enhancement, ws

#23031 fix(deribit): cancelAllOrders - unified response
  ts/src/deribit.ts
Labels: enhancement

#20541 fix(htx) - commonCurrencies
  ts/src/htx.ts
Labels: bug

#20543 fix(gate) - commoncurrencies
  ts/src/gate.ts
Labels: bug

#20544 fix(mexc) - commonCurrencies
  ts/src/mexc.ts
Labels: bug

#23029 bingx: cancelAllOrders, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23040 fix(binance): cancelAllOrders - unified response for contract and portfolio margin orders
  ts/src/binance.ts
Labels: enhancement

#23039 feat(dev): .gitignore - added .custom_gitignore
  .gitignore
Labels: enhancement

#22986 fix(bitfinex): cancelOrder, cancelAllOrders - unified response
  ts/src/bitfinex.ts
Labels: enhancement

#23048 fix(phemex): phemex keepAlive value reduced to 9000 to fix keepAlive error
  ts/src/pro/phemex.ts
Labels: bug

#23046 bingx: fetchTicker, fetchTickers add inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23049 bingx: fetchLeverage, add inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23041 fix(run-tests) - periphericals
  run-tests.js
Labels: enhancement

#22653 feat(timex): cancelOrder - response unification
  ts/src/timex.ts
Labels: enhancement

#23062 fix(cex): handleOrderBookUpdate - use safeInteger instead of safeNumber for incrementalId
  ts/src/pro/cex.ts
Labels: enhancement

#23056 bingx: setLeverage, add inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23060 fix(xt) - fetchCurrencies & watchOHLCV
  skip-tests.json
  ts/src/pro/xt.ts
  ts/src/xt.ts
Labels: bug

#23067 bingx: closePosition, closeAllPositions inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23061 fix(kraken): fetchLedger - timestamp millisecond data parsed correctly
  ts/src/kraken.ts
Labels: enhancement

#23064 feat(kucoin): watchMyTrades - params["method"] options, fixes: #23057
  ts/src/pro/kucoin.ts
Labels: enhancement

#23058 fix(php) - test for method
  php/test/tests_helpers.php
  ts/src/test/tests.helpers.ts
Labels: bug

#23074 fix(tests) - eslintrc <Q
  ts/src/pro/test/.eslintrc
Labels: bug

#23078 fix(kucoin): watchMyTrades - set method using options
  ts/src/pro/kucoin.ts
Labels: bug

#23065 mexc: update withdraw
  coin-ws.js
  ts/src/mexc.ts
Labels: bug

#23090 fix(binance): inverse positions parsing
  ts/src/binance.ts
  ts/src/test/static/response/binance.json
Labels: bug

#23099 fix(binance): fetchOpenInterest for option market
  ts/src/binance.ts
Labels: bug

#23103 base(type): use Dictionary<any)
  ts/src/base/ws/Client.ts
Labels: bug

#23112 feat(kraken): add watchBalance
  ts/src/pro/kraken.ts
Labels: enhancement

#23053 feat(binance) - watchOhlcvForSymbols
  ts/src/pro/binance.ts
Labels: enhancement

#23111 bingx: fetchPosition, fetchPositions inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: enhancement

#23120 cryptocom: add new staking endpoints
  ts/src/cryptocom.ts
Labels: enhancement

#23121 bingx: fetchBalance, add inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23116 fix(c#) - responses parsing
  cs/ccxt/base/Exchange.cs
Labels: bug, enhancement

#23059 feat(bybit) - watchOhlcvForSymbols
  ts/src/pro/bybit.ts
Labels: enhancement

#23119 fix(binance) - open orders rate limits
  ts/src/binance.ts
Labels: bug

#23045 Woo update (marginMode)
  ts/src/abstract/woo.ts
  ts/src/test/static/request/woo.json
  ts/src/test/static/response/woo.json
  ts/src/woo.ts
Labels: enhancement

#22150 checksum handling unification
  ts/src/base/Exchange.ts
  ts/src/base/errorHierarchy.ts
  ts/src/pro/binance.ts
  ts/src/pro/bitfinex2.ts
  ts/src/pro/bitget.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/gate.ts
  ts/src/pro/htx.ts
  ts/src/pro/independentreserve.ts
  ts/src/pro/kraken.ts
  ts/src/pro/okx.ts
  ts/src/pro/poloniexfutures.ts
Labels: enhancement

#23124 ace: update api
  ts/src/ace.ts
  ts/src/test/static/response/ace.json
Labels: enhancement

#17098 mercado.createOrder string math
  ts/src/mercado.ts
Labels: enhancement

#23138 alpaca: update static tests
  ts/src/test/static/request/alpaca.json
  ts/src/test/static/response/alpaca.json
Labels: enhancement

#23132 fix(xt, coinbaseinternational): type string = undefined updated to STR
  ts/src/coinbaseinternational.ts
  ts/src/xt.ts
Labels: bug

#23128 fix(errors.ts): ChecksumError type
  ts/src/base/errors.ts
Labels: bug

#23130 bingx: fetchMyLiquidations, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23141 feat(independentreserve): withdraw implementation
  ts/src/independentreserve.ts
  ts/src/test/static/currencies/independentreserve.json
  ts/src/test/static/request/independentreserve.json
Labels: enhancement

#23136 chore: isFiat types
  ts/src/whitebit.ts
  ts/src/zonda.ts
Labels: enhancement

#23135 chore: types for ids.length
  ts/src/pro/okx.ts
  ts/src/pro/oxfun.ts
  ts/src/yobit.ts
Labels: enhancement

#23137 fix(base) - add watchTicker emulated and fix fetchtickerWs
  ts/src/base/Exchange.ts
Labels: bug, enhancement

#23148 fix(runtests) - remove unnecessary untils
  run-tests.js
  skip-tests.json
  ts/src/test/tests.ts
Labels: bug, enhancement

#23126 python - fix
  python/ccxt/test/tests_helpers.py
  python/ccxt/test/tests_init.py
Labels: bug

#23152 bingx: fetchTradingFee
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23153 feat(woo): add pagination to fetchFundingHistory
  ts/src/woo.ts
Labels: enhancement

#23146 fix types & comparisons
  ts/src/bitfinex.ts
  ts/src/bitfinex2.ts
  ts/src/pro/bitmart.ts
  ts/src/pro/gate.ts
  ts/src/pro/gemini.ts
  ts/src/pro/onetrading.ts
  ts/src/pro/vertex.ts
  ts/src/pro/woo.ts
  ts/src/pro/woofipro.ts
Labels: bug

#23162 fix(mexc) - skip vwap test ^Q
  skip-tests.json
Labels: bug

#23167 feat(bigone): add more test
  ts/src/test/static/request/bigone.json
  ts/src/test/static/response/bigone.json
Labels: enhancement

#23166 feat(ascendex): add more tests
  ts/src/test/static/request/ascendex.json
  ts/src/test/static/response/ascendex.json
Labels: enhancement

#23173 feat(binance): update static-tests
  ts/src/test/static/request/binance.json
Labels: enhancement

#23117 feat(hyperliquid) - watchTickers
  ts/src/hyperliquid.ts
  ts/src/pro/hyperliquid.ts
Labels: enhancement

#23183 chore: isFiat return type
  ts/src/whitebit.ts
  ts/src/zonda.ts
Labels: enhancement

#23188 chore: safe methods param types
  ts/src/base/Exchange.ts
Labels: enhancement

#23182 chore: types for parameters on base exchange
  ts/src/base/Exchange.ts
Labels: enhancement

#23186 chore: parseAccount types
  ts/src/base/Exchange.ts
Labels: enhancement

#23181 fix(bithumb) - parallel requests & others
  ts/src/bithumb.ts
Labels: bug

#23157 tests - multi updates
  build/transpile.js
  cs/tests/BaseTest.Helpers.cs
  php/test/tests_helpers.php
  python/ccxt/test/tests_helpers.py
  ts/src/test/tests.helpers.ts
  ts/src/test/tests.ts
Labels: bug, enhancement

#23131 chore(tests): types for pro tests
  ts/src/pro/test/Exchange/test.watchBidsAsks.ts
  ts/src/pro/test/Exchange/test.watchMyTrades.ts
  ts/src/pro/test/Exchange/test.watchOHLCV.ts
  ts/src/pro/test/Exchange/test.watchOHLCVForSymbols.ts
  ts/src/pro/test/Exchange/test.watchOrderBook.ts
  ts/src/pro/test/Exchange/test.watchOrderBookForSymbols.ts
  ts/src/pro/test/Exchange/test.watchOrders.ts
  ts/src/pro/test/Exchange/test.watchPosition.ts
  ts/src/pro/test/Exchange/test.watchPositions.ts
  ts/src/pro/test/Exchange/test.watchTicker.ts
  ts/src/pro/test/Exchange/test.watchTrades.ts
  ts/src/pro/test/Exchange/test.watchTradesForSymbols.ts
Labels: enhancement

#23198 bingx: fetchOpenOrders, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23197 bingx: cancelOrder, add inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23211 bingx: fetchOrder, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23118 Update test.safeMethods.ts
  cs/tests/BaseTest.Bridge.cs
  ts/src/base/Exchange.ts
  ts/src/base/functions/type.ts
  ts/src/bitget.ts
  ts/src/test/base/test.safeMethods.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#23217 bingx: fetchClosedOrders, fetchCanceledOrders inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23219 bingx: setMarginMode inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23218 bingx: fetchMarginMode, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23221 fix(krakenfutures): concurrent authentication
  ts/src/pro/krakenfutures.ts
Labels: bug

#23224 fix(types.cs): watchBalance type cast
  cs/ccxt/base/Exchange.Types.cs
Labels: bug

#23226 defaultNetworkCode fixed
  ts/src/base/Exchange.ts
Labels: bug

#18990 base - unify `describe` & other objects
  cs/ccxt/base/Exchange.Options.cs
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/binance.ts
Labels: bug

#23240 bingx: fetchMyTrades, inverse swap support
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23248 fix(cs) - handling message
  cs/ccxt/ws/Client.cs
Labels: bug

#23255 poloniex: update docs
  ts/src/poloniex.ts
  ts/src/poloniexfutures.ts
  ts/src/pro/poloniex.ts
  ts/src/pro/poloniexfutures.ts
Labels: enhancement

#23271 fix(doc): fetchMarginMode => fetchMarginModes
  ts/src/ascendex.ts
  ts/src/binance.ts
  ts/src/hitbtc.ts
Labels: bug

#21184 Blofin - WebSockets
  build/csharpTranspiler.ts
  ts/src/base/Exchange.ts
  ts/src/blofin.ts
  ts/src/pro/blofin.ts
Labels: enhancement, ws

#23274 fix(woo): new ws url
  skip-tests.json
  ts/src/pro/woo.ts
Labels: bug
