Repository ccxt/ccxt, pull requests merged in 2024-02, with the labels that each got.

#21039 fix(bybit): set-collateral-switch and set-collateral-switch-batch are both POST
  ts/src/bybit.ts
Labels: bug

#21048 bitfinex2: cancelOrders
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#21043 timex update docs url
  ts/src/timex.ts
Labels: bug

#21051 coinbase: add apis
  ts/src/coinbase.ts
Labels: enhancement

#21054 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#21044 has["fetchDepositAddress"] == false
  ts/src/bitforex.ts
  ts/src/krakenfutures.ts
  ts/src/lbank.ts
  ts/src/poloniexfutures.ts
Labels: enhancement

#21042 docs(lbank): lbank docstrings reference lbank instead of lbank2
  ts/src/lbank.ts
Labels: bug

#21050 bitfinex2: createOrders
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#20966 filterBySinceLimit returns the [limit] records after since instead of the [limit] most recent records
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/okx.ts
  ts/src/test/static/response/binance.json
  ts/src/test/static/response/bitget.json
  ts/src/test/static/response/bybit.json
  ts/src/test/static/response/kraken.json
  ts/src/test/static/response/kucoin.json
  ts/src/test/static/response/kucoinfutures.json
  ts/src/test/static/response/okx.json
Labels: bug

#21062 deribit: fetchOHLCV, missing the first candle in some cases
  ts/src/deribit.ts
  ts/src/test/static/request/deribit.json
Labels: bug

#21064 bitfinex2: add the remaining swap support
  ts/src/bitfinex2.ts
  ts/src/test/static/request/bitfinex2.json
Labels: enhancement

#21060 fix(htx) - order parsing and tests
  ts/src/htx.ts
  ts/src/test/static/response/htx.json
Labels: bug

#21071 fix(gate) - tickers default TZ
  ts/src/gate.ts
Labels: bug

#21093 binance: fetchBalance, portfolio margin
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21086 fix(binance): watchPositions safeSymbol and watchMyTrades parser, fix #21076
  ts/src/pro/binance.ts
Labels: bug

#21081 fix!(krakenfutures): update fees structure
  ts/src/krakenfutures.ts
Labels: bug

#21080 fix(bitget): fetchOHLCV - correctly calls history method if since timestamp is > 31 days ago
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: bug

#21101 fix(binance): restore ws url port
  ts/src/pro/binance.ts
Labels: bug

#21105 binance: createOrder, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21097 feat(gemini) - watchTradesForSymbols
  ts/src/pro/gemini.ts
Labels: bug

#21107 feat(gemini) - watchOrderBookForSymbols
  ts/src/pro/gemini.ts
Labels: enhancement

#21117 fix(bybit): remove marginMode from parsePosition
  ts/src/bybit.ts
  ts/src/test/static/response/bybit.json
Labels: bug

#21122 feat(C#): update docs
  CONTRIBUTING.md
  wiki/Install.md
Labels: enhancement

#21126 binance: cancelAllOrders, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21123 binance: fetchOpenOrders, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21128 feat(kucoin): watchOrderBook add level2Depth5 & level2Depth50 method
  ts/src/pro/kucoin.ts
Labels: enhancement

#20371 Blofin implementation
  ts/src/abstract/blofin.ts
  ts/src/blofin.ts
  ts/src/test/static/currencies/blofin.json
  ts/src/test/static/markets/blofin.json
  ts/src/test/static/request/blofin.json
  ts/src/test/static/response/blofin.json
  ts/src/test/test.ts
Labels: new exchange

#21132 fix(mexc): watchOrderBook assigns timestamp for contract markets
  ts/src/pro/mexc.ts
Labels: bug

#21133 fix(krakenfutures): parseMyTrades returns symbol with response
  ts/src/krakenfutures.ts
  ts/src/test/static/markets/krakenfutures.json
  ts/src/test/static/response/krakenfutures.json
Labels: bug

#21134 binance: fetchOrder, portfolio margin
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21135 docs(okx): fetchOpenOrders remove till from docstring
  ts/src/okx.ts
Labels: enhancement

#21137 binance: cancelOrder, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21138 bitso: add @see
  ts/src/bitso.ts
Labels: enhancement

#21142 binance: setPositionMode, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21146 btcmarkets: add @see
  ts/src/btcmarkets.ts
Labels: enhancement

#21139 bitstamp: add @see
  ts/src/bitstamp.ts
Labels: enhancement

#21140 bl3p: add @see
  ts/src/bl3p.ts
Labels: enhancement

#21144 btcbox: add @see
  ts/src/btcbox.ts
Labels: enhancement

#21147 coinbase: add preview in createOrder
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#21143 btcalpha: add @see
  ts/src/btcalpha.ts
Labels: enhancement

#21141 blockchaincom: add @see
  ts/src/blockchaincom.ts
Labels: enhancement

#21145 binance: setLeverage, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21129 bitmart - subscribe multiple + watchOrderBookForSymbols
  ts/src/pro/bitmart.ts
Labels: enhancement

#21162 fix .length on some exchanges <QUICK>
  ts/src/coinbase.ts
  ts/src/coinlist.ts
  ts/src/coinmetro.ts
Labels: bug

#21161 binance: fetchLeverageTiers, portfolio margin
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21159 binance: borrowCrossMargin, repayCrossMargin, portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21130 bitmart - watchTradesForSymbols
  ts/src/pro/bitmart.ts
Labels: enhancement

#21158 feat(okx): fetchOpenOrders - params["ordType"] is no longer required when params["trigger"] = true
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#21168 phemex.has: closePosition = false
  ts/src/phemex.ts
Labels: enhancement

#21156 feat(bingx): editOrder
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: enhancement

#21046 fix(ascendex): fetchDepositAddress - accepts params["network"]
  ts/src/ascendex.ts
  ts/src/test/static/request/ascendex.json
  ts/src/test/static/response/ascendex.json
Labels: enhancement

#21169 fix(bitget) - coins that contain $ sign
  ts/src/bitget.ts
  ts/src/test/static/currencies/bitget.json
  ts/src/test/static/request/bitget.json
Labels: bug

#21173 docs(mexc): exchange name in docstrings changed from mexc3 to mexc
  ts/src/mexc.ts
Labels: bug

#21174 binance: fetchPositonsRisk, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21178 feat(bybit): fetchOHLCV - add params["until"]
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#21177 binance: fetchLedger, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21180 binance: fetchAccountPositions, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21179 binance: fetchFundingHistory, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21157 feat(bingx): createOrder - added params["triggerPrice"] for spot orders
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#21186 binance: fetchMyTrades, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21187 binance: fetchBorrowInterest, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21175 fix!(mexc): fetchDepositAddressesByNetwork returns an object indexed by network code
  ts/src/base/Exchange.ts
  ts/src/mexc.ts
  ts/src/test/static/response/mexc.json
Labels: bug

#21206 binance: fetchTradingFee, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21207 binance: fetchOrders, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21209 fix(coinbase): v2 methods signature
  ts/src/coinbase.ts
Labels: bug

#21072 feat(gate) - watchTickers and watchBidsAsks
  build/transpile.js
  cs/ccxt/base/Exchange.Options.cs
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/pro/gate.ts
Labels: enhancement

#21216 binance: fetchMyLiquidations, add portfolio margin support
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21219 binance: fetchOpenOrder
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#21215 coinbase: fetchCurrencies and fetchDepositAddressesByNetwork
  ts/src/coinbase.ts
Labels: enhancement

#21172 fix(bingx)!: fetchDepositAddress renamed to fetchDepositAddressesByNetwork. fetchDepositAddress reimplemented to return a single deposit address structure
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: bug

#21217 feat(exchange): fetchDepositAddress uses fetchDepositAddressesByNetwork if fetchDepositAddress is not implemented
  ts/src/base/Exchange.ts
Labels: enhancement

#21224 transpile - support for windows users
  build/transpile.bat
Labels: enhancement

#21236 okx: add apis
  ts/src/okx.ts
Labels: enhancement

#21235 hitbtc: add apis
  ts/src/hitbtc.ts
Labels: enhancement

#21233 bithumb: add apis
  ts/src/bithumb.ts
Labels: enhancement

#21234 feat(docker): add dotnet sdk
  Dockerfile
Labels: enhancement

#21225 fix(transpile.bat) - simplify and better check
  build/transpile.bat
Labels: bug

#21227 coinbase.fetchDepositAddressesByNetwork docstring
  ts/src/coinbase.ts
Labels: enhancement

#21237 coincheck: add @see
  ts/src/coincheck.ts
Labels: enhancement

#21238 btcturk: add @see
  ts/src/btcturk.ts
Labels: enhancement

#21230 timex: fetchDepositAddress, implodeParams used in sign
  ts/src/test/static/request/timex.json
  ts/src/timex.ts
Labels: bug, enhancement

#21231 fix(coinbase): fetchBalance - limit parameter removed for v2
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: bug

#21245 latoken, mercado, oceanex - fetchDepositAddress = false
  ts/src/latoken.ts
  ts/src/mercado.ts
  ts/src/oceanex.ts
Labels: enhancement

#21251 fix(bitget): watchOrderBook
  cs/ccxt/ws/OrderBookSide.cs
  ts/src/pro/bitget.ts
Labels: bug

#21232 feat(idex): fetchDepositAddress
  ts/src/idex.ts
  ts/src/test/static/request/idex.json
Labels: enhancement

#21247 feat(indodax): fetchDepositAddresses, fetchDepositAddress
  ts/src/indodax.ts
  ts/src/test/static/currencies/indodax.json
  ts/src/test/static/markets/indodax.json
  ts/src/test/static/request/indodax.json
Labels: enhancement

#21273 hollaex: update
  ts/src/hollaex.ts
  ts/src/test/static/request/hollaex.json
Labels: enhancement

#21280 fix(okx): history position parsing
  ts/src/okx.ts
  ts/src/test/static/markets/okx.json
  ts/src/test/static/response/okx.json
Labels: bug

#21281 idex: update
  ts/src/idex.ts
Labels: enhancement

#21286 upbit: add fetchDeposit and fetchWithdrawal
  ts/src/test/static/request/upbit.json
  ts/src/upbit.ts
Labels: enhancement

#21289 indodax: update
  ts/src/indodax.ts
  ts/src/test/static/request/indodax.json
Labels: enhancement

#21295 feat(independentreserve): fetchDepositAddress
  ts/src/independentreserve.ts
  ts/src/test/static/currencies/independentreserve.json
  ts/src/test/static/request/independentreserve.json
Labels: enhancement

#21242 fix(package.json) - add csharp tests command [QUICK]
  package.json
Labels: enhancement

#21297 has: fetchDepositAddress = false
  ts/src/btcalpha.ts
  ts/src/btcmarkets.ts
  ts/src/btcturk.ts
Labels: enhancement

#21300 binance: fix parseMarket, strike price
  ts/src/binance.ts
Labels: bug

#21293 Fix WS timeouts - 1
  php/test/test_async.php
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/pro/ascendex.ts
  ts/src/test/test.ts
Labels: bug

#21301 upbit: createOrder, timeInForce
  ts/src/upbit.ts
Labels: enhancement

#21312 Bybit: fix cursor parameter
  ts/src/bybit.ts
Labels: bug

#21317 bybit: fetchMyLiquidations
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#21313 fix(tests) - symbols order [QUICK]
  ts/src/test/test.ts
Labels: bug

#21319 fix(exchange): compare None as Int in get_object_value_from_key_list
  python/ccxt/base/exchange.py
Labels: bug

#21335 binance.pro.has
  ts/src/pro/binance.ts
Labels: enhancement

#21334 feat(binance): fetchClosedOrdersWs
  ts/src/pro/binance.ts
Labels: enhancement

#21342 gemini - watchBidsAsks
  ts/src/pro/gemini.ts
Labels: enhancement

#21341 fix(mexc): php urlencode
  php/Exchange.php
Labels: bug

#21340 feat(cli.cs): add --test --testnet flag
  cs/cli/Program.cs
Labels: enhancement

#21296 feat(bl3p): createDepositAddress
  ts/src/bl3p.ts
  ts/src/test/static/currencies/bl3p.json
  ts/src/test/static/markets/bl3p.json
  ts/src/test/static/request/bl3p.json
Labels: enhancement

#21306 inheritance WS - > REST
  build/csharpTranspiler.ts
  build/transpile.js
  build/transpileWS.js
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/pro/bequant.ts
Labels: enhancement

#21354 fix(package.json) - ast transpiler update
  package-lock.json
  package.json
Labels: enhancement

#21355 fix(bitcoincom) - ws inheritance
  ts/src/pro/bitcoincom.ts
Labels: bug

#21358 fix(okx): fetchPosition - position timestamp changed to the start time of the position instead of the last updated time
  ts/src/okx.ts
  ts/src/test/static/response/okx.json
Labels: bug

#21370 fix(bitget) - negative open
  skip-tests.json
Labels: bug

#21329 bitfinex2 - test WS fixes
  build/transpile.js
  skip-tests.json
  ts/src/pro/bitfinex2.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: bug

#21360 fix(bitrue) - enable ws test
  skip-tests.json
Labels: enhancement

#21362 fix(bitvavo) - unskip
  skip-tests.json
Labels: enhancement

#21361 fix(bitstamp) - unskip ws
  skip-tests.json
Labels: enhancement

#21323 feat(binance): fetchTradesWs
  ts/src/pro/binance.ts
Labels: enhancement

#21349 feat(binance): fetchOHLCVWs
  ts/src/binance.ts
  ts/src/pro/binance.ts
Labels: enhancement

#21395 feat(binance): fetchPositionMode
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21391 fix(Exchange): has add missing methods
  ts/src/base/Exchange.ts
Labels: bug

#21398 fix(huobi) - fetchStatus temp fix
  ts/src/htx.ts
Labels: bug

#21408 coinbase: add fetchTime
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#21405 coinbase: increase limit for fetchBalance
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#21403 bingx: update
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#21363 unskip blockchaincom & remove seq number checks
  cs/ccxt/ws/Exchange.WsBridge.cs
  cs/ccxt/ws/OrderBook.cs
  skip-tests.json
  ts/src/pro/blockchaincom.ts
Labels: bug

#21389 feat(binance): fetchTradingLimits
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21388 feat(binance): fetchCanceledAndClosedOrders
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21412 fix(cryptocom) - unskip ws
  skip-tests.json
  ts/src/pro/cryptocom.ts
Labels: bug

#21409 skip(bitfinex2) - skips
  skip-tests.json
Labels: bug

#21415 fix(gemini) - unskip
  skip-tests.json
  ts/src/pro/gemini.ts
Labels: bug

#21414 fix(deribit) - unskip
  skip-tests.json
  ts/src/pro/deribit.ts
Labels: bug

#21411 fix(bitvavo) - de-proxified
  skip-tests.json
  ts/src/bitvavo.ts
  ts/src/pro/bitvavo.ts
Labels: bug

#21407 fix(bitso) - skip ob ask bid
  skip-tests.json
Labels: bug

#21422 coinbase: deposit, fetchDeposit
  ts/src/coinbase.ts
Labels: enhancement

#21410 fix(bequant) - spead skips
  skip-tests.json
Labels: bug

#21282 feat(build): add tsBuildFile
  build/transpile.sh
  package.json
Labels: enhancement

#21283 binance: portfolio margin websocket support
  ts/src/pro/binance.ts
Labels: enhancement

#21357 feat(binance): fetchLedgerEntry (options only)
  ts/src/binance.ts
Labels: enhancement

#21449 few skips
  skip-tests.json
Labels: bug

#21452 kraken - unskip ws
  skip-tests.json
  ts/src/pro/kraken.ts
Labels: bug

#21413 fix(currencycom) - unskip
  skip-tests.json
  ts/src/pro/currencycom.ts
Labels: bug

#21455 fix(upbit) - return ws test (QUICK)
  skip-tests.json
  ts/src/upbit.ts
Labels: bug

#21454 remove skip exchanges
  skip-tests.json
Labels: bug

#21330 fix(bitget) - ws tests
  skip-tests.json
  ts/src/pro/bitget.ts
Labels: bug
