Repository ccxt/ccxt, pull requests merged in 2024-03, with the labels that each got.

#21463 mexc: fetchLeverage
  ts/src/mexc.ts
  ts/src/test/static/request/mexc.json
Labels: enhancement

#21461 bitmex: fetchLeverage, fetchLeverages
  ts/src/base/Exchange.ts
  ts/src/bitmex.ts
  ts/src/test/static/request/bitmex.json
Labels: enhancement

#21417 fix(mexc) - unskip
  cs/ccxt/ws/Exchange.WsBridge.cs
  cs/ccxt/ws/OrderBook.cs
  cs/tests/BaseTest.Helpers.cs
  skip-tests.json
  ts/src/pro/mexc.ts
Labels: bug

#21356 bitmex - watchTicker & watchTickers & ws tests return
  skip-tests.json
  ts/src/pro/bitmex.ts
Labels: bug

#21440 feat(exchange): new method fetchMarginModes
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/exchange.py
  python/ccxt/base/types.py
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/hitbtc.ts
  ts/src/test/Exchange/base/test.marginMode.ts
  ts/src/test/Exchange/test.fetchMarginMode.ts
  ts/src/test/Exchange/test.fetchMarginModes.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/request/hitbtc.json
  ts/src/test/test.ts
Labels: enhancement

#21472 skip bitfinex2 & delta
  skip-tests.json
Labels: bug

#21478 fix(wazirx) - fT ask skip
  skip-tests.json
Labels: bug

#21473 bitmex & type assertions
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: bug

#21483 fix(probit): fetchTransactions correct default value for response
  ts/src/probit.ts
Labels: bug

#21481 fix(bitrue): fetchWithdrawals uses correct default type for response
  ts/src/bitrue.ts
  ts/src/test/static/request/bitrue.json
Labels: bug

#21486 fix(alpaca): handleCryptoMessage uses safeString instead of safeValue
  ts/src/pro/alpaca.ts
Labels: bug

#21485 fix(whitebit): handleMessage uses safeString for result instead of safeMessage
  ts/src/pro/whitebit.ts
Labels: bug

#21480 fix(alpaca): fetchTrades uses correct default type for response
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
Labels: bug

#21484 fix(kuna): fetchTrades - fix request param, default value for response
  ts/src/kuna.ts
  ts/src/test/static/request/kuna.json
Labels: bug

#21498 Fix(types.cs): info list
  cs/ccxt/base/Exchange.Types.cs
Labels: bug

#21499 fix(mexc) - ws ob nonce
  ts/src/pro/mexc.ts
Labels: bug

#21479 safeValue -> safeBool
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmex.ts
  ts/src/blofin.ts
  ts/src/lbank.ts
  ts/src/okx.ts
  ts/src/pro/binance.ts
  ts/src/pro/bitfinex2.ts
  ts/src/pro/bitget.ts
  ts/src/pro/bitvavo.ts
  ts/src/pro/bybit.ts
  ts/src/pro/coinex.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/gate.ts
  ts/src/pro/independentreserve.ts
  ts/src/pro/kraken.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/okx.ts
  ts/src/pro/woo.ts
  ts/src/test/test.ts
  ts/src/woo.ts
Labels: enhancement

#21482 fix(woo): fetchTrades uses correct default type for response
  ts/src/test/static/request/woo.json
  ts/src/woo.ts
Labels: bug

#21475 deribit - WS implementations
  ts/src/base/Exchange.ts
  ts/src/pro/deribit.ts
Labels: enhancement

#21344 bitmart - watchTicker & watchTickers reorg using MultiSubscriptions
  skip-tests.json
  ts/src/pro/bitmart.ts
  ts/src/test/Exchange/test.fetchTrades.ts
Labels: bug

#21507 coinbase - upgrades
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: bug

#21523 wazirx: add apis
  ts/src/wazirx.ts
Labels: enhancement

#21521 bingx: fetchMarginMode
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#21520 kucoinfutures: closeAllPositions = false
  ts/src/kucoinfutures.ts
Labels: enhancement

#21522 blofin: fetchLeverages
  ts/src/blofin.ts
  ts/src/test/static/markets/blofin.json
  ts/src/test/static/request/blofin.json
Labels: enhancement

#21514 fix(ascendex): remove made up timestamp data
  ts/src/ascendex.ts
Labels: bug

#21515 fix(bitmart): parse network ids
  ts/src/bitmart.ts
Labels: bug

#21518 bitfinex2.has, createOrderRequest docstring
  ts/src/bitfinex2.ts
Labels: enhancement

#21533 bitmart - ticker check
  skip-tests.json
Labels: bug

#21534 fix(deribit) - undefined type [QUICK]
  ts/src/pro/deribit.ts
Labels: bug

#21535 fix(mexc) - ticker spread test skip [QUICK]
  skip-tests.json
Labels: bug

#21536 fix(bithumb) - tests fix skip [QUICK]
  skip-tests.json
Labels: bug

#21537 fix(delta) - timeout skip [QUICK]
  skip-tests.json
Labels: bug

#21554 coinex: add fetchLeverage, fetchLeverages
  ts/src/coinex.ts
  ts/src/test/static/request/coinex.json
Labels: enhancement

#21548 fix(okx): transfer - remove made up timestamp data
  ts/src/okx.ts
Labels: bug

#21553 krakenfutures: add fetchLeverages
  ts/src/krakenfutures.ts
  ts/src/test/static/request/krakenfutures.json
Labels: enhancement

#21549 kraken.parseOrder uses safeDict
  ts/src/kraken.ts
Labels: bug

#21550 fix(tokocrypto): fetchTrades - correct default type for response
  ts/src/tokocrypto.ts
Labels: bug

#21552 fix(kucoinfutures): fetchMyTrades - correct default type
  ts/src/kucoinfutures.ts
Labels: bug

#21556 wazirx: update
  skip-tests.json
  ts/src/test/static/request/wazirx.json
  ts/src/wazirx.ts
Labels: enhancement

#21513 fix(bitget) - fetchOHLCV reorganization
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: bug

#21576 bitget: add fetchMarginMode
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: enhancement

#21570 fix(gemini) - promise all markets
  ts/src/gemini.ts
Labels: bug

#21575 fix(binance): fetchMarkets - correctly loops through options["fetchMarkets"]
  ts/src/binance.ts
Labels: bug

#21584 fix(lbank) - ws tests
  skip-tests.json
  ts/src/pro/lbank.ts
Labels: bug

#21586 fix(yobit): handleErrors
  ts/src/test/static/currencies/yobit.json
  ts/src/test/static/markets/yobit.json
  ts/src/test/static/request/yobit.json
  ts/src/test/static/response/yobit.json
  ts/src/yobit.ts
Labels: bug

#21593 fix(bitfinex2) - incorrect keys [QUICK]
  skip-tests.json
Labels: bug

#21598 fix(coinbase): require payload for GET v2 private endpoint
  ts/src/coinbase.ts
Labels: bug

#21600 blofin: add fetchMarginMode
  ts/src/blofin.ts
  ts/src/test/static/request/blofin.json
Labels: enhancement

#21601 delta: add fetchMarginMode
  ts/src/delta.ts
  ts/src/test/static/request/delta.json
Labels: enhancement

#21604 docs(exchange, btcmarkets): calculateFee docstring
  ts/src/base/Exchange.ts
  ts/src/btcmarkets.ts
Labels: enhancement

#21594 some issues
  skip-tests.json
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: bug

#21602 kucoin: add exchange broker implicit API endpoints
  ts/src/kucoin.ts
Labels: enhancement

#21609 base/types.ts remove extra space
  ts/src/base/types.ts
Labels: bug

#21610 chore: setSandboxMode - parameter types
  ts/src/binance.ts
  ts/src/gate.ts
  ts/src/okx.ts
  ts/src/woo.ts
Labels: enhancement

#21611 fix(lbank) - skip ohlcv watch [QUICK]
  skip-tests.json
Labels: bug

#21612 fix(ts) - windows support
  package.json
Labels: bug

#21617 feat(bingx): add TRAILING_TP_SL and test order
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#21619 fix(btcmarkets): gave value to desription tag
  ts/src/btcmarkets.ts
Labels: bug

#21623 build skips [QUICK]
  skip-tests.json
Labels: bug

#21626 fix(bitmart) - ts [QUICK]
  ts/src/pro/test/Exchange/test.watchTrades.ts
Labels: bug

#21624 fix(currencycom) - handle trades [QUICK]
  ts/src/pro/currencycom.ts
Labels: bug

#21633 doc: add info in status structure
  doc/manual.rst
Labels: enhancement

#21632 fix(bitfinex2) - funding fees fix [QUICK]
  ts/src/bitfinex2.ts
Labels: bug

#21631 fix(bitget) - iteration [QUICK]
  ts/src/pro/bitget.ts
Labels: bug

#21627 fix(bitmart) - handling issues
  ts/src/pro/bitmart.ts
Labels: bug

#21629 fix(transpiler) - reverse
  build/transpile.js
Labels: bug

#21636 bitget: minor update
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: enhancement

#21653 fix(gate): patch fetchFundingHistory
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: bug

#21654 fix(exchange): patch error message when call fetchPaginatedCallDynamic
  ts/src/base/Exchange.ts
Labels: bug

#21655 fix build issues - 3 [QUICK]
  skip-tests.json
Labels: bug

#21657 krakenfutures - add historical fetchTrades
  ts/src/base/Exchange.ts
  ts/src/krakenfutures.ts
  ts/src/test/static/request/krakenfutures.json
Labels: bug

#21673 gate: patch parseOrder
  ts/src/gate.ts
Labels: bug

#21672 fix(lbank) - side fix [QUICK]
  ts/src/pro/lbank.ts
Labels: bug

#21671 hitbtc: update errors
  ts/src/hitbtc.ts
Labels: enhancement

#21676 fix(gemini) - skipWs [QUICK]
  skip-tests.json
Labels: bug

#21677 fix(gemini) - swap true
  ts/src/gemini.ts
Labels: bug

#21692 gate: add fetchLeverage and fetchLeverages
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#21674 fix(base) - load proxy handling
  ts/src/base/Exchange.ts
Labels: bug

#21689 fix(bitmart) - skip currencyid
  skip-tests.json
Labels: bug

#21688 fix(gate) - skips
  skip-tests.json
Labels: bug

#21638 hyperliquid: add ws pro
  skip-tests.json
  ts/src/hyperliquid.ts
  ts/src/pro/hyperliquid.ts
Labels: new exchange

#21698 docs: examples/ts/watch-OHLCV.ts
  examples/ts/watch-OHLCV.ts
Labels: enhancement

#21699 docs(mexc): createOrder - docstring
  ts/src/mexc.ts
Labels: enhancement

#21641 object specific tests skips; fix build issues
  skip-tests.json
  ts/src/test/Exchange/base/test.market.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/test.ts
Labels: bug

#21695 fix(php): remove undefined types
  build/transpile.js
Labels: bug

#21635 test methods - checks for response arrays
  ts/src/pro/test/Exchange/test.watchMyTrades.ts
  ts/src/pro/test/Exchange/test.watchOHLCV.ts
  ts/src/pro/test/Exchange/test.watchOrders.ts
  ts/src/pro/test/Exchange/test.watchPositions.ts
  ts/src/pro/test/Exchange/test.watchTickers.ts
  ts/src/pro/test/Exchange/test.watchTrades.ts
  ts/src/test/Exchange/base/test.balance.ts
  ts/src/test/Exchange/base/test.orderBook.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/Exchange/base/test.trade.ts
  ts/src/test/Exchange/test.fetchAccounts.ts
  ts/src/test/Exchange/test.fetchBorrowInterest.ts
  ts/src/test/Exchange/test.fetchClosedOrders.ts
  ts/src/test/Exchange/test.fetchCurrencies.ts
  ts/src/test/Exchange/test.fetchDepositWithdrawals.ts
  ts/src/test/Exchange/test.fetchDeposits.ts
  ts/src/test/Exchange/test.fetchFundingRateHistory.ts
  ts/src/test/Exchange/test.fetchLastPrices.ts
  ts/src/test/Exchange/test.fetchLedger.ts
  ts/src/test/Exchange/test.fetchLedgerEntry.ts
  ts/src/test/Exchange/test.fetchLeverageTiers.ts
  ts/src/test/Exchange/test.fetchMarginModes.ts
  ts/src/test/Exchange/test.fetchMarketLeverageTiers.ts
  ts/src/test/Exchange/test.fetchMarkets.ts
  ts/src/test/Exchange/test.fetchMyTrades.ts
  ts/src/test/Exchange/test.fetchOHLCV.ts
  ts/src/test/Exchange/test.fetchOpenInterestHistory.ts
  ts/src/test/Exchange/test.fetchOpenOrders.ts
  ts/src/test/Exchange/test.fetchOrders.ts
  ts/src/test/Exchange/test.fetchPositions.ts
  ts/src/test/Exchange/test.fetchTickers.ts
  ts/src/test/Exchange/test.fetchTrades.ts
  ts/src/test/Exchange/test.fetchTradingFees.ts
  ts/src/test/Exchange/test.fetchWithdrawals.ts
Labels: bug, enhancement

#21690 Update types.ts with more Str
  ts/src/base/types.ts
Labels: enhancement

#21703 fix(ascendex) - skip currency-id [QUICK]
  skip-tests.json
Labels: bug

#21719 ascendex: add fetchMarginMode and fetchMarginModes
  ts/src/ascendex.ts
  ts/src/test/static/request/ascendex.json
Labels: enhancement

#21713 chore: string->Str when variable can be undefined
  ts/src/base/Exchange.ts
  ts/src/bitfinex2.ts
  ts/src/bitrue.ts
  ts/src/blofin.ts
  ts/src/cex.ts
  ts/src/gate.ts
  ts/src/idex.ts
  ts/src/kucoinfutures.ts
  ts/src/poloniexfutures.ts
  ts/src/pro/bitvavo.ts
  ts/src/pro/bybit.ts
  ts/src/pro/cex.ts
  ts/src/pro/coinbase.ts
  ts/src/pro/kucoin.ts
  ts/src/pro/poloniex.ts
  ts/src/test/test.ts
Labels: enhancement

#21718 ascendex: add fetchLeverage and fetchLeverages
  ts/src/ascendex.ts
  ts/src/test/static/request/ascendex.json
Labels: enhancement

#21711 chore: add types LastPrice, LastPrices
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
Labels: enhancement

#21710 bingx: add keepAliveListenKey
  ts/src/pro/bingx.ts
Labels: enhancement

#21705 fix(gate) - fetchOHLCV since & limit for contracts
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: bug

#21737 fix(okx): fundingRateHistory pagination
  ts/src/okx.ts
Labels: bug

#21740 btcturk: update timeframes
  ts/src/btcturk.ts
Labels: bug

#21724 fix(bitget) - fetchOHLCV
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: bug

#21686 fix(huobi) - fetchOHLCV
  ts/src/htx.ts
  ts/src/test/static/request/htx.json
Labels: bug

#21744 fix(krakenfutures) - watchTrades reverse timestamp
  ts/src/pro/krakenfutures.ts
Labels: bug

#21722 skips - reorg
  skip-tests.json
  ts/src/test/Exchange/base/test.market.ts
  ts/src/test/test.ts
Labels: bug

#21752 fix(bitmart) - code 70003 [QUICK]
  ts/src/bitmart.ts
  ts/src/coinex.ts
Labels: bug

#21763 fix(deribit) - skip [QUICK]
  skip-tests.json
Labels: bug

#21708 chore: added type AccountStructure to be returned by fetchAccounts
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/exchange.py
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/coinbase.ts
  ts/src/coinbasepro.ts
  ts/src/coinlist.ts
  ts/src/cryptocom.ts
  ts/src/currencycom.ts
  ts/src/deribit.ts
  ts/src/htx.ts
  ts/src/huobijp.ts
  ts/src/kraken.ts
  ts/src/kucoin.ts
  ts/src/luno.ts
  ts/src/mexc.ts
  ts/src/ndax.ts
  ts/src/novadax.ts
  ts/src/okx.ts
  ts/src/woo.ts
Labels: enhancement

#21772 bingx: minor update
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#21779 fix(coinbaseinternational): rename errors to exceptions
  ts/src/pro/coinbaseinternational.ts
Labels: bug

#21771 binance: add apis
  ts/src/binance.ts
Labels: enhancement

#21769 feat(coinbase): add pagination in fetchLedger
  ts/src/coinbase.ts
Labels: bug

#21579 chore: added types to safeMarket header
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitflyer.ts
  ts/src/bithumb.ts
  ts/src/bybit.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/okx.ts
Labels: enhancement

#21797 docs(base/exchange): checkRequiredCredentials - docstring
  ts/src/base/Exchange.ts
Labels: enhancement

#21806 remove extra empty lines from stderr
  run-tests.js
Labels: enhancement

#21804 fix(delta) - skip cs tests [QUICK]
  skip-tests.json
Labels: bug

#21805 fix(base-cs) - fetchStatus from emulated to null [QUICK]
  cs/ccxt/base/Exchange.Options.cs
Labels: bug

#21220 binance - reorganizing exception codes
  ts/src/binance.ts
Labels: enhancement

#21758 chore(exchange): convertTradingViewToOHLCV, convertOHLCVToTradingView parameter type
  ts/src/base/Exchange.ts
Labels: enhancement

#21757 chore(exchange): isRoundNumber parameter type
  ts/src/base/Exchange.ts
Labels: enhancement

#21810 fix(kraken): update docstring @see links
  ts/src/kraken.ts
Labels: enhancement

#21794 `delta.ts` `marketsByNumericId` and `currenciesByNumericId` update
  ts/src/delta.ts
  ts/src/test/static/request/delta.json
  ts/src/test/static/response/delta.json
Labels: enhancement

#21807 fix(hyperliquid): fetchOHLCV - timestamp for candle is opening timestamp
  ts/src/binance.ts
  ts/src/hyperliquid.ts
  ts/src/test/static/response/hyperliquid.json
Labels: bug

#21815 fix(delta): parseLedgerEntry fix
  ts/src/delta.ts
Labels: bug

#21829 okx: update error code & withdraw status code
  ts/src/okx.ts
Labels: enhancement

#21831 skips
  skip-tests.json
Labels: bug

#21827 fix(coinbase): allow params in fetchAccountId
  ts/src/coinbase.ts
Labels: bug

#21852 gate: add apis
  ts/src/gate.ts
Labels: enhancement

#21847 cex - trades sequence
  ts/src/pro/cex.ts
Labels: bug

#21842 fix(coinbaseinternational): api docs link
  ts/src/coinbaseinternational.ts
Labels: bug

#21761 chore(exchange): marketIds, marketSymbols, marketCodes parameter type
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#21366 tests - symbols selection
  cs/tests/BaseTest.Helpers.cs
  php/test/test_async.php
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/test/test.ts
Labels: bug

#21606 chore(binance): isInverse, isLinear - param types
  build/transpile.js
  python/ccxt/base/types.py
  python/ccxt/binance.py
  ts/src/binance.ts
Labels: enhancement

#21853 fix(test) - ohlcv
  skip-tests.json
  ts/src/test/Exchange/base/test.ohlcv.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: enhancement

#21854 feat(tests) - watchBidsAsks
  ts/src/base/Exchange.ts
  ts/src/pro/gemini.ts
  ts/src/pro/test/Exchange/test.watchBidsAsks.ts
  ts/src/test/Exchange/base/test.ticker.ts
  ts/src/test/test.ts
Labels: enhancement

#21867 deribit: new methods, fetchOption and fetchOptionChain
  build/export-exchanges.js
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/types.py
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/deribit.ts
  ts/src/test/static/request/deribit.json
  wiki/Manual.md
Labels: enhancement

#21873 bingx - zero contractSize <Q
  skip-tests.json
Labels: bug

#21877 binance: add fetchOption
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#21880 gate: add fetchOption, fetchOptionChain
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#21878 bybit: add fetchOption, fetchOptionChain
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#21871 okx - fetchtickers updates
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#21888 deribit: parseOption fix currency code bug
  ts/src/deribit.ts
Labels: bug

#21879 delta: add fetchOption
  ts/src/delta.ts
  ts/src/test/static/markets/delta.json
  ts/src/test/static/request/delta.json
Labels: enhancement

#21881 okx: add fetchOption, fetchOptionChain
  ts/src/okx.ts
  ts/src/test/static/markets/okx.json
  ts/src/test/static/request/okx.json
Labels: enhancement

#21904 feat(kucoinfutures) - fetchTickers
  skip-tests.json
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
Labels: enhancement

#21910 fix(doc): remove redundant n char
  ts/src/pro/bybit.ts
  ts/src/pro/woo.ts
Labels: bug

#21912 fix(cex) - updates watchTrades / handleTrades
  ts/src/pro/cex.ts
Labels: bug

#21866 bithumb: add pro
  skip-tests.json
  ts/src/bithumb.ts
  ts/src/pro/bithumb.ts
Labels: enhancement

#21843 skips <Q
  skip-tests.json
  ts/src/gemini.ts
Labels: bug

#21915 fix(bingx) - skip <Q
  skip-tests.json
Labels: bug

#21916 fix(krakenfutures) - skip contractSize
  skip-tests.json
Labels: bug

#21914 fix(test) - contractSize for contracts
  ts/src/test/Exchange/base/test.market.ts
Labels: bug

#21903 fix(kucoin): funds should truncate with quoteIncrement when it's market order
  ts/src/kucoin.ts
  ts/src/test/static/markets/kucoin.json
  ts/src/test/static/request/kucoin.json
Labels: bug

#21923 fix(coinex): parsePosition obtains correct symbol
  ts/src/coinex.ts
  ts/src/test/static/response/coinex.json
Labels: bug
