Repository ccxt/ccxt, pull requests merged in 2024-09, with the labels that each got.

#23612 feat(tests) - static data updater
  package.json
  utils/update-static-json.ts
Labels: enhancement

#23622 feat(okx) - bills history since 2021
  ts/src/okx.ts
Labels: enhancement

#23619 fix(indodax): create limit order
  ts/src/indodax.ts
Labels: bug

#23623 fix(skip) - bingx skip
  skip-tests.json
Labels: bug

#23600 exchanges - promise.all
  ts/src/ascendex.ts
  ts/src/bitfinex.ts
  ts/src/bitfinex2.ts
  ts/src/gate.ts
  ts/src/gemini.ts
  ts/src/independentreserve.ts
  ts/src/test/static/request/ascendex.json
  ts/src/test/tests.ts
Labels: enhancement

#23616 feat(hyperliquid): fetchLedger / fetchDeposits / fetchWithdrawals
  ts/src/hyperliquid.ts
  ts/src/test/static/request/hyperliquid.json
  ts/src/test/static/response/hyperliquid.json
Labels: enhancement

#23631 feat(binance, bybit): add unWatchOHLCVForSymbols
  ts/src/pro/binance.ts
  ts/src/pro/bybit.ts
Labels: bug

#23636 fix(hyperliquid): correct market id in fetchMytrade
  ts/src/hyperliquid.ts
  ts/src/test/static/response/hyperliquid.json
Labels: bug

#23641 fix(bitbay, hitbtc3) - remove aliases
  ts/src/bitbay.ts
  ts/src/hitbtc3.ts
Labels: bug

#23651 kraken: update doc
  ts/src/pro/kraken.ts
Labels: enhancement

#23643 fix(doc) - trigger order lines
  wiki/Manual.md
Labels: bug

#23654 fix(gate): createOrderWs swap market orders
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: bug

#23674 fix(cli) - readable stringify
  examples/js/cli.js
  examples/ts/cli.ts
Labels: bug

#22913 feat(binance) - margin field in fetchCurrencies & margin data in fetchMarkets
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/test/Exchange/base/test.market.ts
  ts/src/test/static/currencies/binance.json
  ts/src/test/static/markets/binance.json
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/hashkey.json
  ts/src/test/static/response/paradex.json
  utils/update-static-json.ts
Labels: enhancement

#23678 fix(docs) - cross isolated readme ^Q
  wiki/Manual.md
Labels: bug

#23679 fix(currencycom,htx,mexc) - unrealized Pnl
  ts/src/currencycom.ts
  ts/src/htx.ts
  ts/src/mexc.ts
  ts/src/test/static/response/htx.json
Labels: bug

#23688 binance - `trigger`
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#23696 feat(phemex): add watchTickers
  ts/src/pro/phemex.ts
Labels: enhancement

#23704 fix(okx): allow custom params in watchPositions
  ts/src/pro/okx.ts
Labels: bug

#23698 fix(mexc) - loading rl
  ts/src/mexc.ts
Labels: bug, enhancement

#23727 feat(test) - repeat pause increase
  ts/src/test/tests.ts
Labels: bug

#21587 readme - build ohlc bars !Q
  wiki/Manual.md
Labels: bug

#23733 fix(deno): check whether self is undefined
  ts/src/base/Exchange.ts
  ts/src/base/functions/misc.ts
  ts/src/base/ws/WsClient.ts
Labels: bug

#23652 feat(mexc): add watchBidsAsks
  ts/src/pro/mexc.ts
Labels: enhancement

#23644 feat(bybit): add watchBidsAsks
  ts/src/pro/bybit.ts
Labels: enhancement

#23470 fix(python) - unclosed connection leak
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
Labels: bug

#23760 htx: add @see
  ts/src/pro/htx.ts
Labels: enhancement

#23759 kraken: add watchBidsAsks
  ts/src/pro/kraken.ts
Labels: enhancement

#23767 feat(bitmart): createOrder, add stopLossPrice and takeProfitPrice
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
Labels: enhancement

#23803 feat(bitget): add watchBidsAsks
  ts/src/pro/bitget.ts
Labels: enhancement

#23801 fix(bybit): parseLedgerEntry, parseToNumeric on undefined value
  ts/src/bybit.ts
Labels: bug

#23814 Bybit: add conversion trade methods
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#23802 feat(binance): repayCrossMargin alternative endpoint
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#23758 okx: add apis, update error code
  ts/src/okx.ts
Labels: enhancement

#23750 feat(bitmart): add watchBidsAsks
  ts/src/pro/bitmart.ts
Labels: enhancement

#23832 fix(cs) - cli null exchanges
  cs/cli/Program.cs
Labels: bug

#23835 kucoin - new endpoints, new methods ..
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
Labels: enhancement

#23805 feat(docs) - string (fixed-point) math ^
  wiki/Manual.md
Labels: enhancement

#23844 Add FundingRate and FundingRates type usage to fetchFundingRate(s)
  build/validate-types.ts
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitfinex2.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/blofin.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/digifinex.ts
  ts/src/gate.ts
  ts/src/hashkey.ts
  ts/src/hitbtc.ts
  ts/src/htx.ts
  ts/src/krakenfutures.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/oxfun.ts
  ts/src/phemex.ts
  ts/src/poloniexfutures.ts
  ts/src/test/static/response/ascendex.json
  ts/src/test/static/response/hashkey.json
  ts/src/test/static/response/kucoinfutures.json
  ts/src/test/static/response/vertex.json
  ts/src/vertex.ts
  ts/src/whitebit.ts
  ts/src/woo.ts
  ts/src/woofipro.ts
  ts/src/xt.ts
  wiki/Manual.md
Labels: enhancement
