Repository ccxt/ccxt, pull requests merged in 2024-06, with the labels that each got.

#22688 feat(okx): Simple earn fixed endpoints
  ts/src/okx.ts
Labels: enhancement

#22686 fix(btcturk): cancelOrder - response unification
  ts/src/btcturk.ts
Labels: enhancement

#22684 fix(btcalpha): cancelOrder - unified response
  ts/src/btcalpha.ts
Labels: enhancement

#22690 fix(coincheck): cancelOrder - unified response
  ts/src/coincheck.ts
Labels: enhancement

#22676 feat(bl3p): cancelOrder - response unification
  ts/src/bl3p.ts
Labels: enhancement

#22669 Bitstamp cancel order
  ts/src/bitstamp.ts
Labels: enhancement

#22629 fix(bingx) - watch multiple
  cs/ccxt/ws/Client.cs
  skip-tests.json
  ts/src/pro/bingx.ts
Labels: enhancement

#22710 fix(woo): cancelAllOrders - unified response
  ts/src/woo.ts
Labels: enhancement

#22713 fix(coinmate): cancelOrder - unified response
  ts/src/coinmate.ts
Labels: enhancement

#22711 fix(bithumb): cancelOrder - unified response
  ts/src/bithumb.ts
Labels: enhancement

#22715 fix(coinspot): cancelOrder - unified response, remove dynamic method call
  ts/src/coinspot.ts
Labels: enhancement

#22714 fix(coinone): cancelOrder - unified response
  ts/src/coinone.ts
Labels: enhancement

#22722 fix(indodax): cancelOrder - unified response
  ts/src/indodax.ts
Labels: enhancement

#22724 feat(upbit): watch private topic
  ts/src/pro/upbit.ts
  ts/src/upbit.ts
Labels: enhancement

#22728 fix(bitget) - watchOrder calculation of remaining & filled
  ts/src/pro/bitget.ts
Labels: bug

#22721 fix(independentreserve): cancelOrder - unify response
  ts/src/independentreserve.ts
Labels: enhancement

#22745 fix(kraken): cancelOrder(s), cancelAllOrders - unify response
  ts/src/kraken.ts
Labels: enhancement

#22746 woo: update doc
  ts/src/pro/woo.ts
Labels: enhancement

#22744 fix(krakenfutures): cancelAllOrders - unify response
  ts/src/krakenfutures.ts
Labels: enhancement

#22723 fix(kucoin): cancelOrder - unify response
  ts/src/kucoin.ts
Labels: enhancement

#22754 fix(upbit): ws options
  ts/src/pro/upbit.ts
Labels: bug

#22678 fix(blockchaincom): cancelOrder, cancelAllOrders unified response
  ts/src/blockchaincom.ts
Labels: enhancement

#22762 fix(bitget) - margin ws orders
  ts/src/pro/bitget.ts
Labels: bug

#22764 fix(mexc): pro - keepAlive changed to 8000, fixes error: Connection to wss://wbs.mexc.com/ws timed out due to a ping-pong keepalive missing on time
  ts/src/pro/mexc.ts
Labels: bug

#22778 fix(tradeogre): cancelAllOrders - unify response
  ts/src/tradeogre.ts
Labels: enhancement

#22776 fix(tradeogre): createOrder - BadRequest thrown if type is "market", ArgumentsRequired thrown if price argument is missing
  ts/src/tradeogre.ts
Labels: enhancement

#22585 fix(bybit): pro - changed keepAlive value to 18000
  ts/src/pro/bybit.ts
Labels: bug

#22772 feat(binance): add internal payment history
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#22775 fix(wavesexchange): cancelOrder - response wrapped in safeOrder
  ts/src/wavesexchange.ts
Labels: enhancement

#22685 fix(btcmarkets): cancelOrder(s) - unified response
  ts/src/btcmarkets.ts
Labels: enhancement

#22786 fix(bitmex): guard handleOrderBook
  ts/src/pro/bitmex.ts
Labels: bug

#22793 fix(ndax): cancelAllOrders - unified response
  ts/src/ndax.ts
Labels: enhancement

#22792 fix(lykke): cancelOrder, cancelAllOrders - response unification
  ts/src/lykke.ts
Labels: enhancement

#22790 fix(woo): keepAlive set to 9000 to fix ping-pong keepAlive error
  ts/src/pro/woo.ts
Labels: bug

#22797 fix(luno): cancelOrder - response unification
  ts/src/luno.ts
Labels: enhancement

#22354 New exchange: ox.fun
  skip-tests.json
  ts/src/abstract/oxfun.ts
  ts/src/oxfun.ts
  ts/src/pro/oxfun.ts
  ts/src/test/static/currencies/oxfun.json
  ts/src/test/static/markets/oxfun.json
  ts/src/test/static/request/oxfun.json
  ts/src/test/static/response/oxfun.json
  ts/src/test/test.ts
Labels: new exchange

#22803 fix(bingx) - migrate to ticksize
  ts/src/bingx.ts
  ts/src/test/static/markets/bingx.json
Labels: enhancement

#22806 feat(binance): add new apis
  ts/src/binance.ts
Labels: enhancement

#22802 fix(bitteam) - ticksize migration
  ts/src/bitteam.ts
  ts/src/test/static/currencies/bitteam.json
  ts/src/test/static/markets/bitteam.json
Labels: enhancement

#22808 fix(tokocrypto) - migration to TICK_SIZE
  ts/src/test/static/currencies/tokocrypto.json
  ts/src/test/static/markets/tokocrypto.json
  ts/src/tokocrypto.ts
Labels: enhancement

#22834 fix(bingx): restore safeValue inside handleOHLCV
  ts/src/pro/bingx.ts
Labels: bug

#22835 fix(bingx) - spot /swap candles
  ts/src/pro/bingx.ts
Labels: bug

#22845 fix(ace): signature for private methods, [TypeError] Cannot use in operator to search for 0 in timeStamp
  ts/src/ace.ts
Labels: bug

#22811 binance - migration to TICK_SIZE
  ts/src/binance.ts
  ts/src/test/static/currencies/binance.json
  ts/src/test/static/currencies/binanceus.json
  ts/src/test/static/markets/binance.json
  ts/src/test/static/markets/binanceus.json
Labels: enhancement

#22753 Kraken cancel order
  ts/src/kraken.ts
Labels: enhancement

#22851 fix build skips ^Q
  skip-tests.json
Labels: bug

#22854 fix(hyperliquid): cancelOrder(s) unified response
  ts/src/hyperliquid.ts
Labels: bug

#22855 fix(coinbase): cancelOrder - unify response
  ts/src/coinbase.ts
Labels: bug

#22856 fix(bitso): cancelOrder - unify response
  ts/src/bitso.ts
Labels: bug

#22853 fix(coinbaseinternational): loadMarkets at beginning of subscribe and subscribeMultiple
  ts/src/pro/coinbaseinternational.ts
Labels: bug

#22867 fix(base): correct microseconds in c#
  cs/ccxt/base/Exchange.Time.cs
Labels: bug

#22881 feat(build): update transpile script
  build/transpile.sh
Labels: enhancement

#22883 fix(okx): keepAlive changed to 18000 to fix ping-pong keepAlive error
  ts/src/pro/okx.ts
Labels: bug

#22889 fix(bybit): add pagination in fetchOpenOrders
  ts/src/bybit.ts
Labels: bug

#22894 fix(krakenfutures): add history url in test api
  ts/src/krakenfutures.ts
Labels: bug

#22901 hyperliquid: remove extend param
  ts/src/hyperliquid.ts
Labels: bug

#22899 parseIsolatedBorrowRate - header params
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/coinex.ts
  ts/src/htx.ts
Labels: enhancement

#22509 New exchange: vertex
  build/transpile.js
  cs/ccxt/base/Exchange.ETH.cs
  cs/ccxt/base/Exchange.Precise.cs
  php/Precise.php
  php/test/test_async.php
  php/test/test_sync.php
  python/ccxt/base/precise.py
  python/ccxt/test/test_async.py
  python/ccxt/test/test_sync.py
  skip-tests.json
  ts/src/abstract/vertex.ts
  ts/src/base/Precise.ts
  ts/src/base/functions/type.ts
  ts/src/pro/vertex.ts
  ts/src/static_dependencies/ethers/hash/typed-data.ts
  ts/src/test/static/currencies/vertex.json
  ts/src/test/static/markets/vertex.json
  ts/src/test/static/request/vertex.json
  ts/src/test/static/response/vertex.json
  ts/src/test/test.ts
  ts/src/vertex.ts
Labels: new exchange

#22907 fix(vertex): correct request id in python
  ts/src/vertex.ts
Labels: bug

#22908 fix(bingx) - max leverage markets ^Q
  ts/src/bingx.ts
Labels: bug

#22912 fix(bingx) - remove leverage
  ts/src/bingx.ts
Labels: bug

#22918 fix(kucoin): update watchMyTrades
  ts/src/pro/kucoin.ts
Labels: bug

#22921 fix(python) - ruff syntax
  build.sh
Labels: bug

#22914 fix(phemex): cancelAllOrders response unification
  ts/src/phemex.ts
Labels: enhancement

#22922 fix(woo): createMarketBuy/Sell with cost
  ts/src/test/static/request/woo.json
  ts/src/woo.ts
Labels: bug

#22924 fix(vertex) - ticker ts
  ts/src/pro/vertex.ts
Labels: bug

#22926 fix(ascendex): cancelAllOrders - unified response
  ts/src/ascendex.ts
Labels: enhancement

#22934 fix(kucoin): correct price and amount in watchMyTrades
  ts/src/pro/kucoin.ts
Labels: bug
