Repository ccxt/ccxt, pull requests merged in 2024-05, with the labels that each got.

#22344 bybit: add api
  ts/src/bybit.ts
Labels: enhancement

#21905 coinbase: add new conversion methods
  ts/src/coinbase.ts
Labels: enhancement

#22348 fix(proxy) - explanations
  ts/src/base/Exchange.ts
Labels: bug

#22355 feat: can assign sandbox mode using options in exchange constructor
  cs/ccxt/base/Exchange.cs
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#22364 generic.ts omit function type
  ts/src/base/functions/generic.ts
Labels: enhancement

#22362 chore: totp method types
  ts/src/base/functions/totp.ts
Labels: enhancement

#22363 chore: jwt function types
  ts/src/base/functions/rsa.ts
Labels: enhancement

#22206 feat(binance): fetchIsolatedBorrowRates
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#22374 feat(hitbtc): "type"=="swap" used for "derivatives" account
  ts/src/hitbtc.ts
Labels: enhancement

#22368 fix(bingx) - operationfailed
  ts/src/bingx.ts
Labels: bug

#22376 fix(docs) - operationFailed operationRejected
  wiki/Manual.md
Labels: bug

#22373 feat: ws/Client.ts types
  ts/src/base/ws/Client.ts
  ts/src/pro/hitbtc.ts
  ts/src/pro/poloniex.ts
Labels: enhancement

#22357 chore: misc.ts types
  ts/src/base/functions/misc.ts
Labels: enhancement

#22359 chore: numbers.ts types
  ts/src/base/Exchange.ts
  ts/src/base/functions/number.ts
  ts/src/bybit.ts
  ts/src/cryptocom.ts
  ts/src/phemex.ts
  ts/src/pro/independentreserve.ts
  ts/src/pro/poloniex.ts
Labels: enhancement

#22382 chore: WsClient - types
  ts/src/base/ws/WsClient.ts
Labels: enhancement

#22393 zaif: patch customNonce
  ts/src/zaif.ts
Labels: bug

#22369 chore: errors.ts types
  build/export-exchanges.js
Labels: enhancement

#22370 chore: Precise.ts types
  ts/src/base/Precise.ts
Labels: enhancement

#22417 fix(bybit): WS trade endpoint
  build/transpile.js
  ts/src/pro/bybit.ts
Labels: bug

#22415 fix(exchange): networkIdToCode
  ts/src/base/Exchange.ts
  ts/src/htx.ts
Labels: bug

#22424 decimalToPrecision types
  ts/src/ascendex.ts
  ts/src/base/functions/number.ts
  ts/src/bitmart.ts
  ts/src/bitstamp.ts
  ts/src/coinlist.ts
  ts/src/poloniex.ts
  ts/src/wavesexchange.ts
Labels: enhancement

#22429 fix(indodax): patch fetchTickers
  ts/src/indodax.ts
Labels: bug

#22422 fix(base) - handleTriggerAndParams
  ts/src/base/Exchange.ts
Labels: bug

#22420 fix(bitget) - WS orders
  ts/src/pro/bitget.ts
Labels: bug, enhancement

#22439 fix(exchange): add missing has key
  cs/ccxt/base/Exchange.Options.cs
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: bug

#22435 Transfer types
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/bigone.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitfinex.ts
  ts/src/bitfinex2.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bitrue.ts
  ts/src/bitstamp.ts
  ts/src/blofin.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/coinlist.ts
  ts/src/deribit.ts
  ts/src/digifinex.ts
  ts/src/gate.ts
  ts/src/hitbtc.ts
  ts/src/htx.ts
  ts/src/kraken.ts
  ts/src/krakenfutures.ts
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
  ts/src/latoken.ts
  ts/src/mexc.ts
  ts/src/novadax.ts
  ts/src/okcoin.ts
  ts/src/okx.ts
  ts/src/paymium.ts
  ts/src/phemex.ts
  ts/src/poloniex.ts
  ts/src/whitebit.ts
  ts/src/woo.ts
  ts/src/zonda.ts
Labels: enhancement

#22430 extend in php
  build/transpile.js
  php/Exchange.php
Labels: enhancement

#22244 feat(base) - safeIntegerOmitZero
  ts/src/base/Exchange.ts
  ts/src/bitget.ts
  ts/src/latoken.ts
Labels: bug

#22437 parseConversion types
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/coinbase.ts
  ts/src/okx.ts
  ts/src/woo.ts
Labels: enhancement

#22438 parseLeverage types
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bitmex.ts
  ts/src/blofin.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/currencycom.ts
  ts/src/delta.ts
  ts/src/gate.ts
  ts/src/hitbtc.ts
  ts/src/krakenfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/woo.ts
Labels: enhancement

#22445 chore: parseGreeks types
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bybit.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/okx.ts
Labels: enhancement

#22444 parseOption types
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bybit.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/gate.ts
  ts/src/okx.ts
Labels: enhancement

#22196 woofipro: new dex
  cs/ccxt/base/Exchange.Crypto.cs
  cs/ccxt/base/Exchange.Encode.cs
  cs/ccxt/base/Exchange.Options.cs
  php/Exchange.php
  php/test/test_async.php
  python/ccxt/base/exchange.py
  python/ccxt/test/test_async.py
  skip-tests.json
  ts/src/abstract/woofipro.ts
  ts/src/base/Exchange.ts
  ts/src/base/functions/crypto.ts
  ts/src/base/functions/encode.ts
  ts/src/base/functions/rsa.ts
  ts/src/pro/woofipro.ts
  ts/src/test/static/currencies/woofipro.json
  ts/src/test/static/markets/woofipro.json
  ts/src/test/static/request/woofipro.json
  ts/src/test/static/response/woofipro.json
  ts/src/test/test.ts
  ts/src/woofipro.ts
Labels: new exchange

#22456 bybit: add api
  ts/src/bybit.ts
Labels: enhancement

#22459 fix(bybit): update fetchLeverageTiers
  ts/src/base/Exchange.ts
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: bug

#22468 bitget assets implicit endpoints, fixes: #22464
  ts/src/bitget.ts
Labels: enhancement

#22436 chore: parseMarginModification types
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/coinex.ts
  ts/src/delta.ts
  ts/src/digifinex.ts
  ts/src/exmo.ts
  ts/src/gate.ts
  ts/src/hitbtc.ts
  ts/src/hyperliquid.ts
  ts/src/okx.ts
  ts/src/phemex.ts
Labels: enhancement

#22455 feat(woo): update pro
  ts/src/pro/woo.ts
Labels: enhancement

#22491 fix(docs) - position mode
  wiki/Manual.md
Labels: enhancement

#22490 fix(coinbase) - fetchTickers market types
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: enhancement

#22443 fix(phemex) - funding fees
  ts/src/phemex.ts
Labels: bug

#22506 fix(waves) - static tests
  ts/src/test/static/request/wavesexchange.json
Labels: enhancement

#22507 fix(bybit): fetchPaginatedCallCursor exception fix
  ts/src/base/Exchange.ts
Labels: bug

#22504 fix(bitrue): sign with query params
  ts/src/bitrue.ts
Labels: bug

#22510 fix(bitget) - watch parse orders
  ts/src/pro/bitget.ts
Labels: bug

#22042 feat(base) - handleParamString2, handleParamInteger2
  ts/src/base/Exchange.ts
  ts/src/pro/cryptocom.ts
Labels: bug

#22549 fix(bybit): fetchFundingRateHistory pagination
  ts/src/bybit.ts
Labels: bug

#22565 fix(kucoin): invalid order error mapping
  ts/src/kucoin.ts
Labels: bug

#22572 fix(whitebit) - add market order by cost endpoint
  ts/src/test/static/request/whitebit.json
  ts/src/whitebit.ts
Labels: enhancement

#22573 bingx: patch cost in parseOrder
  ts/src/bingx.ts
  ts/src/test/static/response/bingx.json
Labels: bug

#22598 fix(poloniexfutures) - timestamp
  ts/src/poloniexfutures.ts
Labels: bug

#22385 chore: types.ts - types
  ts/src/base/functions/type.ts
Labels: enhancement

#22465 Leverage tiers types
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
  ts/src/gate.ts
  ts/src/htx.ts
  ts/src/krakenfutures.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/phemex.ts
Labels: enhancement

#22615 docs(mexc): pro - docstrings for pro methods updated from mexc3 to mexc
  ts/src/pro/mexc.ts
Labels: bug

#22612 fix(coinbase) - WS fixes
  ts/src/pro/coinbase.ts
Labels: bug

#22613 fix(tests) - args
  ts/src/test/test.ts
Labels: bug

#22611 fix(base) - handleParamBool & handleParamBool2
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#22624 chore: update changelog
  CHANGELOG.md
Labels: bug

#22579 fix(coinbase) - add usePrivate option
  ts/src/coinbase.ts
Labels: enhancement

#22630 feat(base) - findNearestCeiling
  ts/src/base/Exchange.ts
Labels: enhancement

#13882 feat(base): uncamelcase python/php base invocations programatically
  build/transpile.js
  php/Exchange.php
  python/ccxt/base/exchange.py
Labels: enhancement

#22635 alpaca cancelOrder unified response
  ts/src/alpaca.ts
Labels: enhancement

#22647 fix(okx) - await
  ts/src/pro/okx.ts
Labels: bug

#22610 bitget hedge mode
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: bug

#22652 feat(whitebit): cancelOrder, cancelAllOrders - response unification
  ts/src/whitebit.ts
Labels: enhancement

#22654 paymium: cancelOrder - unified response
  ts/src/paymium.ts
Labels: enhancement

#22649 feat(zonda): new deposit & withdrawal endpoints
  ts/src/zonda.ts
Labels: enhancement

#22648 feat(bit2c): cancelOrder - unified response
  ts/src/bit2c.ts
Labels: enhancement

#22651 feat(zaif): cancelOrder - unification
  ts/src/zaif.ts
Labels: enhancement

#20604 feat(htx): closePosition
  ts/src/htx.ts
  ts/src/test/static/markets/htx.json
  ts/src/test/static/request/htx.json
Labels: enhancement

#22667 feat(bitbank): cancelOrder - response unification
  ts/src/bitbank.ts
Labels: enhancement

#22665 feat(bingx): cancelOrders, cancelAllOrders - response unification
  ts/src/bingx.ts
Labels: enhancement

#22673 fix(woofipro): signHash in php
  ts/src/woofipro.ts
Labels: bug

#22674 fix(bitmart): remove abs for percentage in ticker
  ts/src/bitmart.ts
Labels: bug
