Repository ccxt/ccxt, pull requests merged in 2024-11, with the labels that each got.

#24136 feat(alpaca): add fetchMyTrades support
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
Labels: enhancement

#24142 fix(bitmart): update maxlimit
  ts/src/bitmart.ts
Labels: bug

#24140 feat(alpaca): add fetchTicker and fetchTickers support
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
  ts/src/test/static/response/alpaca.json
Labels: enhancement

#24146 fix(xt) - trades parsing
  ts/src/test/static/response/xt.json
  ts/src/xt.ts
Labels: bug

#24147 test(statics) - add supported flags ^
  cs/tests/Program.cs
  python/ccxt/test/tests_helpers.py
Labels: enhancement

#24152 feat(alpaca): add fetchDepositAddress
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
  ts/src/test/static/response/alpaca.json
Labels: enhancement

#24155 feat(coinbase) - fetchDepositsWithdrawals
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
  ts/src/test/static/response/coinbase.json
Labels: bug, enhancement

#24132 fix(hyperliquid): update rl
  ts/src/hyperliquid.ts
Labels: bug

#24169 feat(alpaca): withdraw, fetchDepositsWithdrawals
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
Labels: enhancement

#24149 feat(cli) - static request & response auto-writing
  examples/js/cli.js
  examples/ts/cli.ts
  utils/update-static-request-response.js
Labels: enhancement

#24199 fix(cli) - auto injection fixes
  examples/js/cli.js
  examples/ts/cli.ts
Labels: bug

#24201 fix(bitvavo): ws deadlock with multiple calls
  ts/src/bitvavo.ts
  ts/src/pro/bitvavo.ts
  ts/src/test/static/request/bitvavo.json
Labels: bug

#24205 fix(bybit) - reorg USDC
  ts/src/bybit.ts
Labels: enhancement

#24200 refactor(bybit) - stop & trigger
  ts/src/bybit.ts
Labels: enhancement

#24208 feat(mexc): watchTicker, watchTickers add miniTicker support
  ts/src/pro/mexc.ts
Labels: enhancement

#24172 feat(alpaca): editOrder
  ts/src/alpaca.ts
  ts/src/test/static/request/alpaca.json
Labels: enhancement

#24229 test(ws) - casing
  python/ccxt/pro/test/exchange/test_watch_balance.py
  python/ccxt/pro/test/exchange/test_watch_bids_asks.py
  python/ccxt/pro/test/exchange/test_watch_liquidations.py
  python/ccxt/pro/test/exchange/test_watch_liquidations_for_symbols.py
  python/ccxt/pro/test/exchange/test_watch_my_trades.py
  python/ccxt/pro/test/exchange/test_watch_ohlcv.py
  python/ccxt/pro/test/exchange/test_watch_ohlcv_for_symbols.py
  python/ccxt/pro/test/exchange/test_watch_order_book.py
  python/ccxt/pro/test/exchange/test_watch_order_book_for_symbols.py
  python/ccxt/pro/test/exchange/test_watch_orders.py
  python/ccxt/pro/test/exchange/test_watch_position.py
  python/ccxt/pro/test/exchange/test_watch_positions.py
  python/ccxt/pro/test/exchange/test_watch_ticker.py
  python/ccxt/pro/test/exchange/test_watch_tickers.py
  python/ccxt/pro/test/exchange/test_watch_trades.py
  python/ccxt/pro/test/exchange/test_watch_trades_for_symbols.py
  python/ccxt/test/tests_helpers.py
Labels: bug

#24233 feat(binance): add staking apis
  ts/src/binance.ts
Labels: enhancement

#24231 hyperliquid: update timeframes
  ts/src/hyperliquid.ts
Labels: bug

#24242 feat(gate): fetchTime
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
  ts/src/test/static/response/gate.json
Labels: enhancement

#24243 test(exchanges): static response, fetchBorrowInterest
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
  ts/src/test/static/response/bitget.json
  ts/src/test/static/response/bitmart.json
  ts/src/test/static/response/coinex.json
  ts/src/test/static/response/kucoin.json
Labels: enhancement

#24234 feat(exchanges): LeverageTier type usage
  build/validate-types.ts
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
  ts/src/gate.ts
  ts/src/hashkey.ts
  ts/src/htx.ts
  ts/src/krakenfutures.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/oxfun.ts
  ts/src/phemex.ts
  ts/src/test/static/response/ascendex.json
  ts/src/xt.ts
  wiki/Manual.md
Labels: enhancement

#24244 fix(hyperliquid): correct spot market
  ts/src/hyperliquid.ts
Labels: bug

#24248 coinex cancelOrders fix
  ts/src/coinex.ts
  ts/src/test/static/request/coinex.json
Labels: bug

#24256 feat(binance): fetchMarginMode
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#24269 feat(phemex) - add createOrder stoploss & takeprofit limit price & triggerType params
  ts/src/phemex.ts
  ts/src/test/static/markets/phemex.json
  ts/src/test/static/request/phemex.json
  ts/src/test/static/response/phemex.json
  wiki/Manual.md
Labels: bug, enhancement

#24264 feat(kucoinfutures): createOrder cost param
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
  ts/src/test/static/response/kucoinfutures.json
Labels: enhancement

#24277 fix(bitvavo): use requestId in crude ws
  ts/src/bitvavo.ts
  ts/src/pro/bitvavo.ts
  ts/src/test/static/request/bitvavo.json
Labels: bug

#24291 kucoin - leverage param
  ts/src/kucoinfutures.ts
Labels: bug

#24296 fix(phemex) - space in symbols
  ts/src/phemex.ts
Labels: bug

#23629 feat(features) - initial
  build/transpile.js
  cs/ccxt/base/Exchange.Options.cs
  cs/tests/BaseTest.Helpers.cs
  php/Exchange.php
  php/test/tests_helpers.php
  python/ccxt/base/exchange.py
  python/ccxt/test/tests_helpers.py
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bybit.ts
  ts/src/okx.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/Exchange/test.features.ts
  ts/src/test/tests.helpers.ts
  ts/src/test/tests.ts
  wiki/Manual.md
Labels: enhancement

#24311 test(static) - writer updates
  utils/update-static-request-response.js
Labels: bug

#24315 feat(bingx) - features
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/bingx.ts
  ts/src/test/Exchange/test.features.ts
Labels: enhancement

#24317 remove token_bucket
  build/transpile.js
  python/ccxt/test/tests_helpers.py
Labels: bug

#24334 fix(bybit): options tickers
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: bug

#24345 feat(bitget) - `.features` implementation
  ts/src/bitget.ts
Labels: enhancement

#24300 feat(phemex) - trigger orders
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
  ts/src/test/static/response/phemex.json
Labels: bug, enhancement

#24351 feat(features) - marginMode
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/okx.ts
  ts/src/test/Exchange/test.features.ts
  wiki/Manual.md
Labels: enhancement

#24335 fix(okx) - currencies & fees & static tests
  ts/src/base/Exchange.ts
  ts/src/okx.ts
  ts/src/test/static/currencies/okx.json
  ts/src/test/static/markets/okx.json
Labels: enhancement

#24349 refactor(static-tests-updaters) - reorg
  examples/js/cli.js
  examples/ts/cli.ts
  package.json
  utils/update-static-request-response.js
  utils/update-static-tests-data.js
Labels: enhancement

#24151 New exchange: Ellipx
  ts/src/abstract/ellipx.ts
  ts/src/ellipx.ts
  ts/src/test/static/currencies/ellipx.json
  ts/src/test/static/markets/ellipx.json
  ts/src/test/static/request/ellipx.json
  ts/src/test/static/response/ellipx.json
Labels: new exchange

#24390 feat(bingx): add twap order
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: enhancement

#24393 gate - features
  ts/src/gate.ts
Labels: enhancement

#24402 fix(bitrue): correct listenkey
  ts/src/bitrue.ts
  ts/src/pro/bitrue.ts
Labels: bug

#24406 fix(probit) - safe markets
  ts/src/pro/probit.ts
Labels: enhancement

#24273 idex - DECIMAL_PLACES into TICK_SIZE
  ts/src/idex.ts
Labels: enhancement

#24389 tests related fixes
  package.json
  run-tests.js
  ts/src/test/tests.ts
Labels: bug

#24413 feat(kraken): update editOrder endpoint
  ts/src/kraken.ts
  ts/src/test/static/request/kraken.json
Labels: enhancement

#24412 fix(tests) - static updater
  utils/update-static-tests-data.js
Labels: bug, important

#23356 fix(base) - static tests full msg
  ts/src/test/tests.ts
Labels: enhancement
