Repository ccxt/ccxt, pull requests merged in 2024-10, with the labels that each got.

#23850 feat(kraken): createOrder, add trailingPercent support
  ts/src/kraken.ts
  ts/src/test/static/request/kraken.json
Labels: enhancement

#23898 fix(tests) - proxy ip (Q)
  examples/ts/proxy-usage.ts
  skip-tests.json
Labels: enhancement, important

#23893 fix(tests) - oxfun skip (Q)
  skip-tests.json
Labels: bug

#23892 fix(tests) - kucoin taker (Q)
  skip-tests.json
Labels: bug

#23906 fix(mexc): resolve until in fetchOrders
  ts/src/mexc.ts
  ts/src/test/static/request/mexc.json
Labels: bug

#23887 feat(base) - fix currency to precision
  ts/src/base/Exchange.ts
  ts/src/bitrue.ts
  ts/src/bitvavo.ts
  ts/src/huobijp.ts
Labels: bug

#23905 feat(exchanges): fetchFundingInterval and fetchFundingIntervals
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/poloniexfutures.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/request/bitget.json
  ts/src/test/static/request/coinex.json
  ts/src/test/static/request/digifinex.json
  ts/src/test/static/request/kucoinfutures.json
  ts/src/test/static/request/mexc.json
  ts/src/test/static/request/okx.json
  ts/src/test/static/request/poloniexfutures.json
  ts/src/test/static/request/woo.json
  ts/src/test/static/request/woofipro.json
  ts/src/test/static/request/xt.json
  ts/src/woo.ts
  ts/src/woofipro.ts
  ts/src/xt.ts
  wiki/Manual.md
Labels: enhancement

#23790 upbit: add watchTickers
  ts/src/pro/upbit.ts
Labels: enhancement

#23926 fix(tests) - oxfun skip ^
  skip-tests.json
Labels: bug

#23903 feat(vertex): update encoding
  cs/ccxt/base/Exchange.cs
  php/async/Exchange.php
  php/static_dependencies/ratchet/pawl/src/WebSocket.php
  ts/src/pro/vertex.ts
  ts/src/vertex.ts
Labels: enhancement

#23934 few skips ^
  skip-tests.json
Labels: bug, enhancement

#23936 tests - use proxy
  ts/src/test/tests.ts
Labels: enhancement

#23943 feat(base) - parseCurrencies & parseCurrency
  ts/src/.eslintrc
  ts/src/base/Exchange.ts
  ts/src/bitvavo.ts
  ts/src/coinbaseinternational.ts
  ts/src/kuna.ts
  ts/src/timex.ts
Labels: enhancement

#23960 fix(binanceus) - margin currencies
  ts/src/binance.ts
Labels: bug

#23954 feat(bingx): add fetchMarkPrice
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#23956 feat(okx): add fetchMarkPrice
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#23541 fix(bitso) - safeNetwork removal
  ts/src/bitso.ts
Labels: enhancement

#23971 fix(okx): use oiUsd as openinterest value
  ts/src/okx.ts
  ts/src/test/static/response/okx.json
Labels: bug

#23966 fix(bitmart): correct change in ticker
  ts/src/bitmart.ts
  ts/src/test/static/response/bitmart.json
Labels: bug

#23992 fix(types): add limits.market
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/base/types.ts
Labels: bug

#24001 fix(hyperliquid): add more order status
  ts/src/hyperliquid.ts
Labels: bug

#23996 test(market) - skip min/max for inactive markets
  ts/src/test/Exchange/base/test.market.ts
Labels: enhancement

#24010 docs(static-tests) - fix ^
  CONTRIBUTING.md
Labels: bug

#24032 docs(ws) - fixes
  wiki/ccxt.pro.md
Labels: bug

#24028 feat(okx) - api updates
  ts/src/okx.ts
Labels: enhancement

#24030 test(ndax) - skip ^
  skip-tests.json
Labels: enhancement

#24026 feat(cli) - request ^
  examples/ts/cli.ts
Labels: enhancement

#24035 fix(hyperliquid): position size
  ts/src/hyperliquid.ts
  ts/src/kucoin.ts
  ts/src/test/static/response/hyperliquid.json
Labels: bug

#24046 fix(cli) - ts fix `info` removal
  examples/ts/cli.ts
  ts/src/test/tests.ts
Labels: bug

#24047 test(comments) - minor change ^
  ts/src/test/tests.ts
Labels: enhancement

#24045 fix(php) - unsubscribe error
  php/async/Exchange.php
Labels: bug

#24011 feat(exchanges): fetchLongShortRatio, fetchLongShortRatioHistory
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/ccxt.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bybit.ts
  ts/src/okx.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/request/bitget.json
  ts/src/test/static/request/bybit.json
  ts/src/test/static/request/okx.json
  wiki/Manual.md
Labels: enhancement

#24059 fix(kucoin) - update withdraw endpoint
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
Labels: enhancement

#24057 fix(kucoin) - createDepositAddress & static tests
  ts/src/kucoin.ts
  ts/src/test/static/currencies/kucoin.json
  ts/src/test/static/request/kucoin.json
  ts/src/test/static/response/kucoin.json
Labels: enhancement

#24068 feat(coinex): closePosition
  ts/src/coinex.ts
  ts/src/test/static/request/coinex.json
Labels: enhancement

#23589 Coincatch integration
  skip-tests.json
  ts/src/abstract/coincatch.ts
  ts/src/coincatch.ts
  ts/src/pro/coincatch.ts
  ts/src/test/static/currencies/coincatch.json
  ts/src/test/static/markets/coincatch.json
  ts/src/test/static/request/coincatch.json
  ts/src/test/static/response/coincatch.json
  ts/src/test/tests.ts
Labels: new exchange

#24075 feat(gate): fetchBorrowInterest
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#24079 fix(binance) - asyn end slash ^
  ts/src/binance.ts
Labels: bug

#24016 fix(gate) - trigger orders updates
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
  ts/src/test/static/response/gate.json
Labels: bug

#24050 fix(tests) - types and fixes for exchanges
  ts/src/hyperliquid.ts
  ts/src/test/static/response/alpaca.json
  ts/src/test/static/response/ascendex.json
  ts/src/test/static/response/bitvavo.json
  ts/src/test/static/response/bybit.json
  ts/src/test/static/response/woo.json
  ts/src/test/static/response/woofipro.json
  ts/src/test/tests.ts
Labels: bug

#24074 feat(gate): borrowCrossMargin, repayCrossMargin unifiedAccount
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: enhancement

#24063 test(kucoin) - withdraw resp
  ts/src/test/static/response/kucoin.json
Labels: enhancement

#24054 fix(kucoin) - auto migration detect
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
Labels: bug

#24091 fix(kucoin): handle_my_trade in php
  ts/src/pro/kucoin.ts
  ts/src/pro/onetrading.ts
Labels: bug

#24098 fix(coinex) - network codes unified, withdraw & fetchDepositAddress
  ts/src/coinex.ts
  ts/src/test/static/request/coinex.json
Labels: bug

#24105 fix(bitmex): correct fee
  ts/src/bitmex.ts
  ts/src/test/static/response/bitmex.json
Labels: bug

#23543 fix(hitbtc) - remove safeNetwork
  ts/src/hitbtc.ts
Labels: enhancement

#24097 fix(cs) - this.limits
  cs/ccxt/base/Exchange.Options.cs
Labels: bug

#24110 fix(htx) - trigger orders support ^
  ts/src/htx.ts
Labels: bug

#24120 feat(phemex): fetchMarkets add create time
  ts/src/phemex.ts
  ts/src/test/static/currencies/phemex.json
  ts/src/test/static/markets/phemex.json
Labels: enhancement

#23726 isSandboxMode
  cs/ccxt/base/Exchange.Options.cs
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/bybit.ts
Labels: enhancement
