Repository ccxt/ccxt, pull requests merged in 2024-04, with the labels that each got.

#22006 fix(readme) - minor !Q
  README.md
Labels: enhancement

#22007 fix(mexc) - comment
  ts/src/mexc.ts
Labels: enhancement

#21981 fix(import-export) - all errors
  build/export-exchanges.js
Labels: bug, critical

#22018 fix(kucoin): fetchBalance, cross margin
  ts/src/kucoin.ts
  ts/src/test/static/response/kucoin.json
Labels: bug

#22019 fix(base) - safeCurrency instead of id
  ts/src/base/Exchange.ts
Labels: bug

#22015 fix(binance): addMargin, reduceMargin amount < 1 fix
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
Labels: bug

#22020 gate - comments
  ts/src/gate.ts
Labels: enhancement

#22008 bitget - fix currency ID vs CODE
  ts/src/bitget.ts
  ts/src/test/static/currencies/bitget.json
  ts/src/test/static/request/bitget.json
Labels: bug

#22021 fix(cryptocom): add safeDict in fetchPosition
  ts/src/cryptocom.ts
  ts/src/test/static/response/cryptocom.json
Labels: bug

#22012 krakenfutures - fix markets contractSize
  ts/src/base/Exchange.ts
  ts/src/krakenfutures.ts
  ts/src/test/static/markets/krakenfutures.json
  ts/src/test/static/request/krakenfutures.json
Labels: bug

#22029 skip - poloniexfutures spread
  skip-tests.json
Labels: bug

#22034 fix(mexc): stop infinite loop caused by fetchLeverageTiers
  ts/src/mexc.ts
Labels: bug

#22023 fix(bitget) - zero ts ticker
  ts/src/bitget.ts
Labels: bug

#22022 fix(base) - commonCurrencies fix & parseDWF fix
  ts/src/base/Exchange.ts
Labels: bug

#22043 fix: common_currency_code python tranpilation no longer causes error 'AttributeError: list object has no attribute "values"'
  ts/src/base/Exchange.ts
Labels: bug

#22049 bingx: update apis
  ts/src/bingx.ts
  ts/src/test/static/request/bingx.json
Labels: enhancement

#22031 fix(gemini) - nonce
  ts/src/gemini.ts
Labels: bug, enhancement

#22036 bybit: add apis
  ts/src/bybit.ts
Labels: enhancement

#21875 feat: fetchMarginAdjustmentHistory
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitfinex2.ts
  ts/src/bitget.ts
  ts/src/bitmex.ts
  ts/src/bitrue.ts
  ts/src/bybit.ts
  ts/src/coinbaseinternational.ts
  ts/src/coinex.ts
  ts/src/cryptocom.ts
  ts/src/delta.ts
  ts/src/digifinex.ts
  ts/src/exmo.ts
  ts/src/gate.ts
  ts/src/hitbtc.ts
  ts/src/htx.ts
  ts/src/hyperliquid.ts
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/phemex.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/request/coinex.json
  ts/src/test/static/request/okx.json
  ts/src/test/static/response/binance.json
  ts/src/woo.ts
  wiki/Manual.md
Labels: enhancement

#22068 fix(gemini): replace * when fetch market from web
  ts/src/gemini.ts
Labels: bug

#22061 fix(kucoinfutures) - fix sub
  ts/src/pro/kucoinfutures.ts
Labels: bug, enhancement

#22050 feat(kucoin) - watchBidsAsks
  ts/src/pro/kucoin.ts
  ts/src/pro/kucoinfutures.ts
Labels: bug, enhancement

#22079 revert commonCurrencyCode & fix fDWF currencies
  ts/src/base/Exchange.ts
  ts/src/kraken.ts
Labels: bug

#22089 fix(php): remove define_rest_api
  php/Exchange.php
Labels: bug

#22090 bybit: add broker api
  ts/src/bybit.ts
Labels: enhancement

#22026 fix(base) - convertMarketIdExpireDate
  ts/src/base/Exchange.ts
  ts/src/deribit.ts
Labels: bug

#22096 feat(probit): fetchDepositsWithdrawals
  ts/src/probit.ts
Labels: bug

#22097 encode types
  ts/src/base/functions/encode.ts
  ts/src/base/functions/rsa.ts
Labels: enhancement

#22099 refactor(exchange): parseLeverageTiers accepts either a dictionary or an array
  ts/src/base/Exchange.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
Labels: enhancement

#22107 binance: fix fetchIndexOHLCV inverse pair parameter
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: bug

#22093 krakenfutures - watch multiple all streams - orderbook(s), trades(s), ticker(s), bidasks
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/pro/kraken.ts
  ts/src/pro/krakenfutures.ts
Labels: enhancement

#22035 binance: add POST /api/v3/orderList/oco
  ts/src/binance.ts
Labels: enhancement

#22118 fix(tests) - latoken !Q
  skip-tests.json
Labels: bug

#22013 errors autogeneration
  build/export-exchanges.js
  ts/src/base/errorHierarchy.ts
  ts/src/base/errors.ts
Labels: bug

#21957 htx - reorganization fetchMarkets & fetchTickers
  ts/src/htx.ts
  ts/src/test/static/request/htx.json
Labels: bug, enhancement

#22134 fix(skip) - poloniex curr !Q
  skip-tests.json
Labels: bug

#22131 fix(ecdsa): unify the ecdsa signing
  cs/cli/Program.cs
  examples/py/cli.py
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/functions/crypto.ts
  ts/src/base/functions/rsa.ts
  ts/src/coinbase.ts
Labels: bug

#22138 fix(poloniexfutures) - timestamps fix in tickers
  ts/src/poloniexfutures.ts
Labels: bug

#22129 handleMarketTypeAndParams - add defaultValue parameter
  ts/src/base/Exchange.ts
  ts/src/okx.ts
Labels: enhancement

#21457 tests - watchOrderBookForSymbols, watchTradesForSymbols, watchOHLCVForSymbols
  build/csharpTranspiler.ts
  cs/tests/BaseTest.Helpers.cs
  run-tests.js
  skip-tests.json
  ts/src/pro/binance.ts
  ts/src/pro/poloniexfutures.ts
  ts/src/pro/test/Exchange/test.watchOHLCVForSymbols.ts
  ts/src/pro/test/Exchange/test.watchOrderBookForSymbols.ts
  ts/src/pro/test/Exchange/test.watchTradesForSymbols.ts
  ts/src/test/Exchange/base/test.orderBook.ts
  ts/src/test/test.ts
Labels: enhancement

#22152 fix(kraken): patch parse ws order
  cs/ccxt/base/Exchange.SafeMethods.cs
  ts/src/kraken.ts
  ts/src/test/static/response/kraken.json
Labels: bug

#22160 fix(coinbase): futures markets loading
  ts/src/coinbase.ts
  ts/src/test/static/markets/coinbase.json
  ts/src/test/static/request/coinbase.json
Labels: bug

#22172 fix(cs) - RL cost and proper headers handling
  cs/ccxt/base/Exchange.Generic.cs
  cs/ccxt/base/Exchange.cs
  cs/ccxt/base/Throttler.cs
Labels: bug

#22177 fix(c#) - throttler
  cs/ccxt/base/Exchange.cs
  cs/ccxt/base/Throttler.cs
Labels: bug

#22167 new method: createConvertTrade
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/okx.ts
  ts/src/test/static/request/bitget.json
  ts/src/test/static/request/okx.json
  ts/src/woo.ts
  wiki/Manual.md
Labels: enhancement

#22192 docs(kucoin): update some @see links
  ts/src/kucoin.ts
Labels: enhancement

#22188 fix(kucoin) - commoncurrencies handled
  ts/src/bybit.ts
  ts/src/kucoin.ts
  ts/src/test/static/currencies/kucoin.json
  ts/src/test/static/request/kucoin.json
Labels: bug

#22164 fix(bitget) - handleerrors msg
  ts/src/bitget.ts
Labels: bug

#22202 fix(tsx) - ext static depth
  ts/src/static_dependencies/jsencrypt/lib/jsrsasign/asn1-1.0.ts
  ts/src/static_dependencies/jsencrypt/lib/jsrsasign/yahoo.d.ts
Labels: bug

#22215 fix(bingx) - minors !Q
  ts/src/bingx.ts
Labels: bug

#22212 fix(poloniexfutures) - ts !Q
  ts/src/poloniexfutures.ts
Labels: bug

#22166 wazirx.handleMessage - replace.inArray with string.includes
  ts/src/pro/wazirx.ts
Labels: enhancement

#22195 new methods: fetchConvertTrade, fetchConvertTradeHistory
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/okx.ts
  ts/src/test/static/currencies/binance.json
  ts/src/test/static/request/binance.json
  ts/src/test/static/request/bitget.json
  ts/src/test/static/request/okx.json
  ts/src/test/static/request/woo.json
  ts/src/woo.ts
  wiki/Manual.md
Labels: enhancement

#22153 feat(whitebit): add v4 apis
  ts/src/test/static/request/whitebit.json
  ts/src/whitebit.ts
Labels: enhancement

#20788 tests - argvs parsing
  cs/tests/Program.cs
  php/test/test_async.php
  python/ccxt/test/test_async.py
  run-tests.js
  ts/src/test/test.ts
Labels: bug

#22127 fix(kucoin) - chain id currency, network precisions, etc
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
Labels: bug, enhancement

#22219 coinex: update doc
  ts/src/coinex.ts
Labels: bug

#22245 fix(binance) - watch method fixes !Q
  skip-tests.json
Labels: bug

#22248 fix(coinbase): fetchOHLCV - until timestamp converted to seconds
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
Labels: bug

#22253 fix(test) - exmo qv <> bv check fix
  ts/src/test/test.ts
Labels: bug

#22249 docs(binance): fetchTickers - added params["type"] to docstring
  ts/src/binance.ts
Labels: enhancement

#22100 feat(all): add cancelAllOrdersAfter
  build/csharpTranspiler.ts
  ts/src/abstract/bingx.ts
  ts/src/abstract/woo.ts
  ts/src/base/Exchange.ts
  ts/src/bingx.ts
  ts/src/bitmex.ts
  ts/src/htx.ts
  ts/src/hyperliquid.ts
  ts/src/kraken.ts
  ts/src/krakenfutures.ts
  ts/src/kucoinfutures.ts
  ts/src/okx.ts
  ts/src/test/static/request/bingx.json
  ts/src/test/static/request/bitmex.json
  ts/src/test/static/request/htx.json
  ts/src/test/static/request/kraken.json
  ts/src/test/static/request/krakenfutures.json
  ts/src/test/static/request/okx.json
  ts/src/test/static/request/whitebit.json
  ts/src/test/static/request/woo.json
  ts/src/whitebit.ts
  ts/src/woo.ts
  wiki/Manual.md
Labels: enhancement

#22262 bybit.pro streaming["keepAlive"] changed from 20000 to 19000
  ts/src/pro/bybit.ts
Labels: bug

#22246 feat(coinbase): public endpoints added for fetchTicker, fetchMarkets, fetchOHLCV, and fetchOrderBook
  skip-tests.json
  ts/src/coinbase.ts
  ts/src/test/static/request/coinbase.json
  ts/src/test/static/response/coinbase.json
Labels: enhancement

#22247 feat(coinbase): public websocket endpoints for watchOrderBook, watchTicker, watchTickers, watchTrades
  skip-tests.json
  ts/src/pro/coinbase.ts
Labels: enhancement

#22098 generic.ts types
  ts/src/base/functions/generic.ts
  ts/src/bitfinex.ts
  ts/src/bitflyer.ts
  ts/src/indodax.ts
  ts/src/wazirx.ts
Labels: enhancement

#22271 feat(okx) - fetchPositionMode
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#22273 feat(okx) - createOrder automatic hedge-mode
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: enhancement

#22270 ts-node tsx migration
  build.sh
  build/transpile.bat
  package-lock.json
  package.json
Labels: enhancement

#22291 feat(coinmetro): add new endpoint to fetchBalance
  ts/src/abstract/coinmetro.ts
  ts/src/coinmetro.ts
  ts/src/test/static/request/coinmetro.json
Labels: enhancement

#22205 Borrow rate types and parsers
  build/transpile.js
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/base/Exchange.ts
  ts/src/base/types.ts
  ts/src/binance.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bybit.ts
  ts/src/coinex.ts
  ts/src/digifinex.ts
  ts/src/htx.ts
  ts/src/okx.ts
Labels: enhancement

#22319 fix(binance): linear swap taker fee
  ts/src/binance.ts
Labels: bug

#22065 feat(whitebit): fetchDepositsWithdrawals
  ts/src/test/static/request/whitebit.json
  ts/src/whitebit.ts
Labels: enhancement

#22301 feat: separated forced transpilation from --multiprocess
  build/transpile.js
  build/transpileWS.js
  package.json
Labels: enhancement

#22342 fix(poloniex) - skip
  skip-tests.json
Labels: bug
