Repository ccxt/ccxt, pull requests merged in 2024-08, with the labels that each got.

#23293 fix(types.cs): remove duplicated info
  cs/ccxt/base/Exchange.Types.cs
Labels: bug

#23286 fix(bequant): correctws url
  ts/src/pro/bequant.ts
Labels: bug

#23288 fix(types): update MarketInterface so fields can be undefined
  ts/src/base/types.ts
Labels: enhancement

#23280 fix(cli) - ts
  examples/ts/cli.ts
Labels: bug

#23308 fix(package): add starkware module [ci deploy]
  python/ccxt/static_dependencies/starknet/models/__init__.py
  python/ccxt/static_dependencies/starkware/__init__.py
  python/ccxt/static_dependencies/sympy/core/__init__.py
Labels: bug

#23312 fix(kucoin): patch parseWsTrade
  ts/src/pro/kucoin.ts
Labels: bug

#23300 feat(woo): replace orderbook with orderbookupdate
  ts/src/pro/woo.ts
Labels: enhancement

#23252 feat(binance) - OHLCV with timezone param support
  ts/src/pro/binance.ts
Labels: enhancement

#23297 chore(ace): method param types
  ts/src/ace.ts
Labels: enhancement

#23317 feat(yobit) - fetchTickers all
  ts/src/yobit.ts
Labels: bug, enhancement

#23329 alpaca: add @see
  ts/src/pro/alpaca.ts
Labels: enhancement

#23330 bitfinex: add @see
  ts/src/pro/bitfinex.ts
Labels: enhancement

#23225 binance - new endpoints (fetchPositions / fetchAccountPositions / fetchPositionRisk)
  ts/src/binance.ts
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#23332 fix(bybit): fetchTransfers with currency parsing
  ts/src/bybit.ts
  ts/src/test/static/response/bybit.json
Labels: bug

#23340 fix(binance) - php parsing
  ts/src/binance.ts
  ts/src/test/static/response/binance.json
Labels: bug

#23343 fix(bybit): handle inverse futures subscription
  ts/src/pro/bybit.ts
Labels: bug

#23267 feat(bitmart): update futures to v2
  ts/src/bitmart.ts
  ts/src/pro/bitmart.ts
  ts/src/test/static/request/bitmart.json
  ts/src/test/static/response/bitmart.json
Labels: enhancement

#23359 fix(woo): watch private
  ts/src/pro/woo.ts
Labels: bug

#23363 feat(bithumb): update doc
  ts/src/bithumb.ts
  ts/src/test/static/currencies/bithumb.json
  ts/src/test/static/markets/bithumb.json
  ts/src/test/static/request/bithumb.json
  ts/src/test/static/response/bithumb.json
Labels: enhancement

#23366 fix(kraken): oflags handling
  ts/src/kraken.ts
Labels: bug

#23371 fix(binance) - watchLiquidations ^Q
  ts/src/pro/binance.ts
Labels: bug

#23375 fix(kraken): oflags
  ts/src/kraken.ts
  ts/src/test/static/request/kraken.json
Labels: bug

#23374 feat(kraken): update
  ts/src/kraken.ts
  ts/src/test/static/request/kraken.json
Labels: enhancement

#23378 build: skip-tests
  build/dummy.txt
Labels: bug

#23382 fix(py) - remove this
  python/ccxt/base/exchange.py
Labels: bug

#23295 fix: watchPositions - handleOption used instead of safeBool to get option for awaitPositionsSnapshot
  ts/src/base/Exchange.ts
  ts/src/pro/binance.ts
  ts/src/pro/bybit.ts
  ts/src/pro/cryptocom.ts
  ts/src/pro/gate.ts
  ts/src/pro/kucoinfutures.ts
  ts/src/pro/vertex.ts
  ts/src/pro/woo.ts
  ts/src/pro/woofipro.ts
Labels: enhancement

#23266 binance: update apis
  ts/src/binance.ts
  ts/src/pro/binance.ts
  ts/src/test/static/request/binance.json
Labels: enhancement

#23392 fix(poloniex): fetchOpenOrders
  ts/src/poloniex.ts
  ts/src/test/static/response/poloniex.json
Labels: bug

#23395 fix(bitmart): update createSwapOrderRequest
  ts/src/bitmart.ts
  ts/src/test/static/request/bitmart.json
Labels: bug

#23376 checkaddress - unified
  cs/ccxt/base/Exchange.Options.cs
  cs/ccxt/base/Exchange.cs
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: enhancement

#23401 fix(base): remove starknet js json
  ts/src/static_dependencies/starknet/index.ts
  ts/src/static_dependencies/starknet/utils/hash/classHash.ts
  ts/src/static_dependencies/starknet/utils/json.ts
Labels: bug

#23402 fix(yobit) - BCHN to BSV
  ts/src/yobit.ts
Labels: enhancement

#23403 fix(exchange): watchOHLCVForSymbols in dotnet
  build/csharpTranspiler.ts
  cs/ccxt/base/Exchange.TranspileHelpers.cs
  cs/ccxt/base/Exchange.Types.cs
  ts/src/base/Exchange.ts
Labels: bug

#23400 fix(waves) - createOrder params
  ts/src/wavesexchange.ts
Labels: bug

#22315 feat(binance): check 30 days interval in fetchConvertTradeHistory
  ts/src/binance.ts
Labels: enhancement

#23418 fix(gate): edit order size type
  ts/src/gate.ts
  ts/src/test/static/request/gate.json
Labels: bug

#23411 fix(phemex) - no closed orders in fetchOrders
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
Labels: bug

#23410 fix(npm) - silent
  utils/package-test.sh
Labels: enhancement

#23423 fix(binance): parseLeverage
  ts/src/binance.ts
Labels: bug

#23428 fix(binance): correct signature for simple-earn
  ts/src/binance.ts
Labels: bug

#23435 fix(binance): watchOHLCV - exchange-specific id
  ts/src/pro/binance.ts
Labels: bug

#23432 feat(kraken): remove requirement for currency code argument in fetchDeposits
  ts/src/kraken.ts
  ts/src/test/static/request/kraken.json
Labels: bug

#23436 fix(gate): handleErrors inside watchMethods
  ts/src/pro/gate.ts
Labels: bug

#23441 fix(binance): watchLiquidationsForSymbols should use lowercase id
  ts/src/pro/binance.ts
Labels: bug

#23451 fix(okx): watchLiquidationsForSymbols subscription
  ts/src/pro/okx.ts
Labels: bug

#23455 fix(okx): error on closing positions:
  ts/src/pro/okx.ts
Labels: bug

#23437 feat(errors) - ManualInteractionRequired ^Q
  ts/src/base/errorHierarchy.ts
  ts/src/bybit.ts
Labels: enhancement

#23464 feat(bitget): add unWatchOrderBook
  ts/src/pro/bitget.ts
Labels: bug

#23406 fix(binance) - tickers inverse quote volume
  ts/src/binance.ts
Labels: bug

#23426 feat(wiki) - custom ws handling
  wiki/ccxt.pro.manual.md
Labels: enhancement

#23466 bingx: update @see
  ts/src/pro/bingx.ts
Labels: enhancement

#23463 feat(ascendex): add watchTradesForSymbols
  ts/src/pro/ascendex.ts
Labels: enhancement

#23176 Hashkey integration
  skip-tests.json
  ts/src/abstract/hashkey.ts
  ts/src/hashkey.ts
  ts/src/pro/hashkey.ts
  ts/src/test/static/currencies/hashkey.json
  ts/src/test/static/markets/hashkey.json
  ts/src/test/static/request/hashkey.json
  ts/src/test/static/response/hashkey.json
Labels: new exchange

#23471 fix(krakenfutures): patch parseOrder
  ts/src/krakenfutures.ts
Labels: bug

#23484 fix(base): use two parameters when call fetchPaginatedCallCursor in f…
  ts/src/base/Exchange.ts
Labels: bug

#23488 fix(readme) - watchOrderBookForSymbols
  wiki/ccxt.pro.manual.md
Labels: bug

#23519 fix(base): paginationTimestamp shoud add one for forward
  ts/src/base/Exchange.ts
Labels: bug

#23518 fix(base): correct return type for fetchPositionHistory
  ts/src/base/Exchange.ts
  ts/src/coinex.ts
  ts/src/test/static/response/bybit.json
Labels: bug

#23506 fix(c#) - parseToInt
  cs/ccxt/base/Exchange.TranspileHelpers.cs
  ts/src/test/static/request/kraken.json
Labels: bug

#23521 remove cs Sending
  cs/ccxt/ws/Client.cs
Labels: enhancement

#23523 fix(docs) - cors snippet example
  wiki/Manual.md
Labels: enhancement

#23534 fix(mexc) - remove networksById
  ts/src/mexc.ts
Labels: bug

#23532 fix(kraken,mexc): network space fix
  ts/src/kraken.ts
  ts/src/mexc.ts
  ts/src/test/static/currencies/kraken.json
  ts/src/test/static/request/kraken.json
Labels: bug

#23549 fix(base): get_object_value_from_key_list
  python/ccxt/base/exchange.py
Labels: bug

#23544 fix(okcoin) - remove safeNetwork
  ts/src/okcoin.ts
Labels: enhancement

#23540 fix(bitfinex2) - remove safeNetwork
  ts/src/bitfinex2.ts
Labels: enhancement

#23538 fix(huobijp) - remove safenetwork
  ts/src/huobijp.ts
Labels: bug

#23539 fix(okx) - remove safenetwork
  ts/src/okx.ts
Labels: bug

#23542 fix(coinex) - remove safeNetwork
  ts/src/coinbaseinternational.ts
  ts/src/coinex.ts
Labels: bug

#23556 fix(bitmart) - remove safenetwork
  ts/src/bitmart.ts
Labels: enhancement

#23336 bingx: websocket pro, inverse swap support
  ts/src/bingx.ts
  ts/src/pro/bingx.ts
Labels: enhancement

#23585 fix(binance): update rl for withdraw history api
  ts/src/binance.ts
Labels: bug

#23582 fix(kucoin) - handle HighFrequency (hf) accounts
  ts/src/kucoin.ts
  ts/src/test/static/request/kucoin.json
Labels: bug, enhancement

#23590 kucoin - corrections of 'safe' methods
  ts/src/kucoin.ts
Labels: bug

#23593 fix(kucoin) - static tests
  ts/src/test/static/request/kucoin.json
Labels: enhancement

#23595 fix(hyperliquid): fetchOrder with clientOrderId
  ts/src/hyperliquid.ts
  ts/src/test/static/request/hyperliquid.json
  ts/src/test/static/response/hyperliquid.json
Labels: bug
