Repository ccxt/ccxt, pull requests merged in 2025-06, with the labels that each got.

#26104 fix(woo): fetchCurrencies reorg, networks, fetchDepositAddress, Withdraw
  ts/src/test/static/currencies/woo.json
  ts/src/test/static/markets/woo.json
  ts/src/test/static/request/woo.json
  ts/src/test/static/response/woo.json
  ts/src/woo.ts
Labels: bug, enhancement

#26163 fix(bitget): market parse field opentime
  ts/src/bitget.ts
  ts/src/test/static/markets/bitget.json
Labels: bug

#26161 fix(gate): parse markets spot & swap 'created' timestamps
  ts/src/gate.ts
  ts/src/test/static/markets/gate.json
Labels: bug, enhancement

#26159 fix(build): remove new line
  build/export-exchanges.js
  python/ccxt/pro/__init__.py
Labels: bug

#26184 feat(clipy): add --no-load-markets
  examples/py/cli.py
Labels: enhancement

#26182 feat(phemex): fetchDepositAddress update endpoint, MKR defaultNetworks
  ts/src/phemex.ts
  ts/src/test/static/request/phemex.json
  ts/src/test/static/response/phemex.json
Labels: enhancement

#26142 fix(kraken): market amount precision
  ts/src/kraken.ts
  ts/src/test/static/currencies/kraken.json
  ts/src/test/static/markets/kraken.json
  ts/src/test/static/request/kraken.json
  ts/src/test/static/response/kraken.json
Labels: bug, enhancement

#26193 skip python coinbase tests
  run-tests.js
  skip-tests.json
Labels: bug

#26191 skip(paradex): bid/ask watchtickers
  skip-tests.json
Labels: bug

#26194 feat(bitget): UTA endpoints and fetchUtaMarkets
  go/v4/bitget_api.go
  ts/src/bitget.ts
Labels: enhancement

#26206 fix(bybit): cost rounding
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
  ts/src/test/static/response/bybit.json
Labels: bug

#26223 Hollaex exchange update
  ts/src/hollaex.ts
  ts/src/test/static/markets/hollaex.json
  ts/src/test/static/request/hollaex.json
  ts/src/test/static/response/hollaex.json
Labels: enhancement

#26240 go: update exchange_throttler
  go/v4/exchange_throttler.go
Labels: bug

#26247 chore(gate): retest props
  skip-tests.json
  ts/src/gate.ts
Labels: enhancement

#26246 chore(fmfwio): prop test
  skip-tests.json
  ts/src/fmfwio.ts
Labels: bug

#26137 fix!(coinlist): delist
  cs/ccxt/api/coinlist.cs
  cs/ccxt/exchanges/coinlist.cs
  cs/ccxt/wrappers/coinlist.cs
  go/v4/coinlist.go
  go/v4/coinlist_api.go
  go/v4/coinlist_wrapper.go
  php/abstract/coinlist.php
  php/async/abstract/coinlist.php
  php/async/coinlist.php
  php/coinlist.php
  python/ccxt/abstract/coinlist.py
  python/ccxt/async_support/coinlist.py
  python/ccxt/coinlist.py
  skip-tests.json
  ts/ccxt.ts
  ts/src/abstract/coinlist.ts
  ts/src/coinlist.ts
  ts/src/test/static/currencies/coinlist.json
  ts/src/test/static/markets/coilist.json
  ts/src/test/static/markets/coinlist.json
  ts/src/test/static/request/coinlist.json
  ts/src/test/static/response/coinlist.json
Labels: enhancement

#26227 chore(cryptocom): unskip tests
  skip-tests.json
  ts/src/cryptocom.ts
Labels: enhancement

#26226 chore(modetrade): skip test redo
  skip-tests.json
  ts/src/modetrade.ts
  ts/src/test/Exchange/test.fetchCurrencies.ts
Labels: enhancement

#26057 feat(kraken): update watchMultiHelper methods to v2
  ts/src/kraken.ts
  ts/src/pro/kraken.ts
Labels: enhancement, ws

#26266 fix(kraken): update ping/pong & authentication
  ts/src/pro/kraken.ts
Labels: bug

#26265 chore(bitmex): remove unskip & dummy change trigger retest
  skip-tests.json
  ts/src/bitmex.ts
Labels: enhancement

#26260 test(tickers): fix tolerance for quotevol/basevol comparison
  ts/src/test/Exchange/base/test.ticker.ts
Labels: bug

#26270 test(ticker): fix check for negative values, & bitmex
  skip-tests.json
  ts/src/bitmex.ts
  ts/src/test/Exchange/base/test.ticker.ts
Labels: bug

#26283 fix(php): in_array strict
  php/Exchange.php
Labels: bug

#26277 fix(php): is_associative fix
  php/Exchange.php
Labels: enhancement

#26244 fix(exmo): fetchCurrencies multi req
  skip-tests.json
  ts/src/exmo.ts
Labels: enhancement
