Repository ccxt/ccxt, pull requests merged in 2025-01, with the labels that each got.

#24703 features corrections
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bitfinex.ts
  ts/src/bitget.ts
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/bybit.ts
  ts/src/coinbase.ts
  ts/src/coinex.ts
  ts/src/cryptocom.ts
  ts/src/gate.ts
  ts/src/htx.ts
  ts/src/hyperliquid.ts
  ts/src/kraken.ts
  ts/src/krakenfutures.ts
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
  ts/src/mexc.ts
  ts/src/okx.ts
  ts/src/test/Exchange/test.features.ts
  ts/src/woo.ts
  ts/src/woofipro.ts
  wiki/Manual.md
Labels: enhancement

#24721 feat(blofin): adding copy trading endpoints to urls
  ts/src/blofin.ts
Labels: enhancement

#24723 fix(myokx) - swap/future
  ts/src/myokx.ts
  ts/src/pro/myokx.ts
Labels: bug

#24725 fix(hashkey) - buy sell taker maker fix
  ts/src/hashkey.ts
  ts/src/test/static/response/hashkey.json
Labels: bug

#24724 tests(lykke) - try with proxy
  skip-tests.json
  ts/src/lykke.ts
Labels: bug

#24726 fix(binance) - ws closing signal
  ts/src/pro/binance.ts
Labels: important

#24479 tests(features) - gtc
  ts/src/gate.ts
  ts/src/hyperliquid.ts
  ts/src/test/Exchange/test.features.ts
Labels: enhancement

#24739 feat(bybit) - networks mappings ^
  ts/src/bybit.ts
Labels: enhancement

#24740 bybit - fetchDepositAddress unification
  ts/src/bybit.ts
Labels: enhancement

#24742 feat(bitget) - networks list ^
  ts/src/bitget.ts
Labels: enhancement

#24743 refactor(bitget) - networks methods
  ts/src/bitget.ts
Labels: enhancement

#23931 fix(base) - disable last json response
  php/Exchange.php
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
  ts/src/coinbase.ts
  wiki/Manual.md
Labels: enhancement

#24765 fix(bingx) - ws balance incoming
  ts/src/pro/bingx.ts
Labels: bug

#24766 feat(ace) - features
  ts/src/ace.ts
Labels: enhancement

#24767 feat(alpaca) - features
  ts/src/alpaca.ts
Labels: enhancement

#24769 feat(ascendex) - features
  ts/src/ascendex.ts
Labels: enhancement

#24770 feat(bigone) - features
  ts/src/bigone.ts
Labels: enhancement

#24771 feat(binanceus) - features
  ts/src/binanceus.ts
Labels: enhancement

#24772 feat(bit2c) - features
  ts/src/bit2c.ts
Labels: enhancement

#24777 feat(bitbank) - features
  ts/src/bitbank.ts
Labels: enhancement

#24778 feat(bitbns) - features
  ts/src/bitbns.ts
Labels: enhancement

#24783 feat(bitflyer) - features
  ts/src/bitflyer.ts
Labels: enhancement

#24784 feat(bithumb) - features
  ts/src/bithumb.ts
Labels: enhancement

#24785 feat(bitopro) - features
  ts/src/bitopro.ts
Labels: enhancement

#14772 tests - `createOrder`
  build/csharpTranspiler.ts
  cs/tests/BaseTest.Bridge.cs
  ts/src/test/Exchange/base/test.order.ts
  ts/src/test/Exchange/base/test.sharedMethods.ts
  ts/src/test/Exchange/base/test.trade.ts
  ts/src/test/Exchange/test.createOrder.ts
  ts/src/test/tests.ts
Labels: enhancement

#24786 bitrue - spot & swap
  ts/src/bitrue.ts
Labels: enhancement

#24787 feat(bitso) - features
  ts/src/bitso.ts
Labels: enhancement

#24792 feat(bitvavo) - features
  ts/src/bitvavo.ts
Labels: enhancement

#24796 feat(blofin) - features
  ts/src/blofin.ts
Labels: enhancement

#24788 feat(bitteam) - features
  ts/src/bitteam.ts
Labels: enhancement

#24794 feat(bl3p) - features
  ts/src/bl3p.ts
Labels: enhancement

#24795 feat(blockchaincom) - features
  ts/src/blockchaincom.ts
Labels: enhancement

#24793 ace & alpaca - minor edits
  ts/src/ace.ts
  ts/src/alpaca.ts
Labels: enhancement

#24798 feat(btcalpha) - features
  ts/src/btcalpha.ts
Labels: enhancement

#24799 feat(btcbox) - features
  ts/src/btcbox.ts
Labels: enhancement

#24800 feat(btcmarkets) - features
  ts/src/btcmarkets.ts
Labels: enhancement

#24804 feat(btcturk) - features
  ts/src/btcturk.ts
Labels: enhancement

#24807 feat(cex) - features
  ts/src/cex.ts
Labels: enhancement

#24808 fix(bybit) - fetchBalance parsing
  ts/src/bybit.ts
  ts/src/test/static/response/bybit.json
Labels: enhancement

#24826 fix(krakenfutures): escape when marginlevels is undefined
  ts/src/krakenfutures.ts
Labels: bug

#24827 feat(coinbaseexchange) - features
  ts/src/coinbaseexchange.ts
Labels: enhancement

#24837 feat(coinmetro) - features
  ts/src/coinmetro.ts
Labels: enhancement

#24828 feat(coincatch) - features
  ts/src/coincatch.ts
Labels: enhancement

#24833 feat(features) - coincheck
  ts/src/coincheck.ts
Labels: enhancement

#24840 feat(coinspot) - features
  ts/src/coinspot.ts
Labels: enhancement

#24834 feat(coinlist) - features
  ts/src/coinlist.ts
Labels: enhancement

#24836 feat(coinmate) - features
  ts/src/coinmate.ts
Labels: enhancement

#24838 feat(coinone) - features
  ts/src/coinone.ts
Labels: enhancement

#24839 feat(coinsph) - features
  ts/src/coinsph.ts
Labels: enhancement

#24844 fix(krakenfutures): correct leverage tiers
  ts/src/krakenfutures.ts
  ts/src/test/static/request/krakenfutures.json
Labels: bug

#24849 feat(phemex) - features
  ts/src/phemex.ts
Labels: enhancement

#24854 feat(poloniexfutures) - features
  ts/src/poloniexfutures.ts
Labels: enhancement

#24855 feat(upbit) - features
  ts/src/upbit.ts
Labels: enhancement

#24852 feat(poloniex) - features
  ts/src/poloniex.ts
Labels: enhancement

#24639 feat: adding timeDifference option
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/coinbase.ts
  ts/src/gate.ts
  ts/src/htx.ts
  ts/src/okx.ts
  ts/src/woo.ts
Labels: enhancement

#24866 feat(defx) - features
  ts/src/defx.ts
Labels: enhancement

#24881 feat(deribit) - features
  ts/src/deribit.ts
Labels: enhancement

#24882 feat(digifinex) - features
  ts/src/digifinex.ts
Labels: enhancement

#24884 feat(ellipx) - features
  ts/src/ellipx.ts
Labels: enhancement

#24885 feat(exmo) - features
  ts/src/exmo.ts
Labels: enhancement

#24886 feat(hitbtc) - features
  ts/src/hitbtc.ts
Labels: enhancement

#24891 feat(idex) - features
  ts/src/idex.ts
Labels: enhancement

#24887 feat(hollaex) - features
  ts/src/hollaex.ts
Labels: enhancement

#24888 feat(huobijp) - features
  ts/src/huobijp.ts
Labels: enhancement

#24906 feat(novadax) - features
  ts/src/novadax.ts
Labels: enhancement

#24901 feat(luno) - features
  ts/src/luno.ts
Labels: enhancement

#24903 feat(mercado) - features
  ts/src/mercado.ts
Labels: enhancement

#24894 feat(independentreserve) - features
  ts/src/independentreserve.ts
Labels: enhancement

#24902 feat(lykke) - features
  ts/src/lykke.ts
Labels: enhancement

#24900 feat(bitget) - fetchOhlcv useHistoryEndpoint
  ts/src/bitget.ts
Labels: enhancement

#24895 feat(indodax) - features
  ts/src/indodax.ts
Labels: enhancement

#24898 feat(lbank) - features
  ts/src/lbank.ts
Labels: enhancement

#24896 feat(kuna) - features
  ts/src/kuna.ts
Labels: enhancement

#24916 feat(oxfun) - features
  ts/src/oxfun.ts
Labels: enhancement

#24913 feat(okcoin) - features
  ts/src/okcoin.ts
Labels: enhancement

#24478 fix(static-updater) - tsx support
  package.json
  utils/update-static-json.ts
  utils/update-static-tests-data.js
Labels: bug

#24897 feat(latoken) - features
  ts/src/latoken.ts
Labels: enhancement

#24918 feat(paradex) - features
  ts/src/paradex.ts
Labels: enhancement

#24904 feat(myokx) - features
  ts/src/myokx.ts
Labels: enhancement

#24914 feat(onetrading) - features
  ts/src/onetrading.ts
Labels: enhancement

#24905 feat(ndax) - features
  ts/src/ndax.ts
Labels: enhancement

#24909 feat(oceanex) - features
  ts/src/oceanex.ts
Labels: enhancement

#24931 feat(paymium) - features
  ts/src/paymium.ts
Labels: enhancement

#24936 feat(tradeogre) - features
  ts/src/tradeogre.ts
Labels: enhancement

#24934 feat(timex) - features
  ts/src/timex.ts
Labels: enhancement

#24932 feat(probit) - features
  ts/src/probit.ts
Labels: enhancement

#24935 feat(tokocrypto) - features
  ts/src/tokocrypto.ts
Labels: enhancement

#24947 fix(coinex) - SOL network fix ^
  ts/src/coinex.ts
Labels: enhancement

#24055 fix(kucoin) - fetchCurrencies new data
  ts/src/base/Exchange.ts
  ts/src/kucoin.ts
  ts/src/test/static/currencies/kucoin.json
  ts/src/test/static/request/kucoin.json
  ts/src/test/static/response/kucoin.json
Labels: enhancement

#24956 fix(kucoin) - parsing networks & fees
  ts/src/kucoin.ts
Labels: enhancement

#24957 fix(blofin) - features ohlcv
  ts/src/blofin.ts
Labels: bug

#24955 fix(binance) - historical trades
  ts/src/binance.ts
Labels: bug

#24989 fix(cli) - c#
  cs/cli/Program.cs
Labels: enhancement

#24979 fix(htx) - sign order
  ts/src/htx.ts
Labels: bug

#25018 chore(astt) - update ^
  package-lock.json
  package.json
Labels: enhancement

#24962 feat(wazirx) - features
  ts/src/wazirx.ts
Labels: enhancement

#24959 feat(vertex) - features
  ts/src/vertex.ts
Labels: enhancement

#24966 feat(yobit) - features
  ts/src/yobit.ts
Labels: enhancement

#24968 feat(zonda) - features
  ts/src/zonda.ts
Labels: enhancement

#24967 feat(zaif) - features
  ts/src/zaif.ts
Labels: enhancement

#24961 feat(wavesexchange) - features
  ts/src/wavesexchange.ts
Labels: enhancement

#24581 fix(binance) - zero prices
  ts/src/base/Exchange.ts
  ts/src/binance.ts
  ts/src/test/Exchange/base/test.lastPrice.ts
  ts/src/test/Exchange/test.fetchLastPrices.ts
  ts/src/test/base/test.safeMethods.ts
Labels: enhancement

#25043 fix(php) - safeNumberOmitZero
  build/transpile.ts
Labels: bug

#25045 fix(binance): keepAliveListenKey
  ts/src/pro/binance.ts
Labels: bug

#25007 binance features updates (part 1)
  ts/src/binance.ts
  ts/src/test/static/markets/binance.json
  ts/src/test/static/request/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#25049 fix(deribit) - fetchFundingRateHistory pagination
  ts/src/deribit.ts
Labels: bug

#25064 deribit - fix 2
  python/ccxt/async_support/deribit.py
  python/ccxt/deribit.py
  ts/src/deribit.ts
Labels: bug

#24548 feat(base) - handleTriggerDirectionAndParams
  ts/src/base/Exchange.ts
Labels: enhancement

#25071 refactor(test) - remove unused var
  ts/src/test/tests.ts
Labels: enhancement

#25081 fix(bitmex) - features ^
  skip-tests.json
  ts/src/bitmex.ts
  ts/src/test/Exchange/test.features.ts
Labels: bug

#25082 feat(features) - add arguments
  ts/src/ace.ts
  ts/src/base/Exchange.ts
  ts/src/bigone.ts
  utils/dev-helpers/required-symbols-for-methods.ts
Labels: enhancement

#25087 feat(features) - symbolRequired (batch 1)
  ts/src/ace.ts
  ts/src/alpaca.ts
  ts/src/ascendex.ts
  ts/src/base/Exchange.ts
  ts/src/bigone.ts
  ts/src/binance.ts
  ts/src/bingx.ts
  ts/src/bit2c.ts
  ts/src/bitbank.ts
  ts/src/bitbns.ts
  ts/src/bitfinex.ts
  ts/src/bitflyer.ts
  ts/src/bitget.ts
  ts/src/bithumb.ts
  ts/src/bitmart.ts
  ts/src/bitmex.ts
  ts/src/bitopro.ts
  ts/src/bitrue.ts
  ts/src/bitso.ts
  ts/src/bitstamp.ts
  ts/src/bitteam.ts
  ts/src/bitvavo.ts
  ts/src/blockchaincom.ts
  ts/src/blofin.ts
  ts/src/btcalpha.ts
  ts/src/btcbox.ts
  ts/src/btcmarkets.ts
  ts/src/btcturk.ts
  ts/src/bybit.ts
  ts/src/cex.ts
  ts/src/coinbase.ts
  ts/src/coinbaseexchange.ts
  ts/src/coinbaseinternational.ts
  ts/src/coincatch.ts
  ts/src/coincheck.ts
  ts/src/coinex.ts
  ts/src/coinlist.ts
  ts/src/coinmate.ts
  ts/src/coinmetro.ts
  ts/src/coinone.ts
  ts/src/coinsph.ts
  ts/src/coinspot.ts
  ts/src/cryptocom.ts
  ts/src/currencycom.ts
  ts/src/test/Exchange/test.features.ts
Labels: enhancement

#25096 test(exceptions) - exception message readable
  ts/src/test/tests.ts
Labels: enhancement

#25094 feat(symbolRequired) - batch 2
  python/ccxt/async_support/base/ws/fast_client.py
  ts/src/defx.ts
  ts/src/delta.ts
  ts/src/deribit.ts
  ts/src/digifinex.ts
  ts/src/ellipx.ts
  ts/src/exmo.ts
  ts/src/gate.ts
  ts/src/gemini.ts
  ts/src/hashkey.ts
  ts/src/hitbtc.ts
  ts/src/hollaex.ts
  ts/src/htx.ts
  ts/src/huobijp.ts
  ts/src/hyperliquid.ts
  ts/src/idex.ts
  ts/src/independentreserve.ts
  ts/src/indodax.ts
  ts/src/kraken.ts
  ts/src/krakenfutures.ts
  ts/src/kucoin.ts
  ts/src/kucoinfutures.ts
  ts/src/kuna.ts
  ts/src/latoken.ts
  ts/src/lbank.ts
  ts/src/luno.ts
  ts/src/lykke.ts
  ts/src/mercado.ts
  ts/src/mexc.ts
  ts/src/ndax.ts
  ts/src/novadax.ts
  ts/src/oceanex.ts
  ts/src/okcoin.ts
  ts/src/okx.ts
  ts/src/onetrading.ts
  ts/src/oxfun.ts
  ts/src/p2b.ts
  ts/src/paradex.ts
  ts/src/phemex.ts
  ts/src/poloniex.ts
  ts/src/poloniexfutures.ts
  ts/src/probit.ts
  ts/src/test/Exchange/test.features.ts
  ts/src/timex.ts
  ts/src/tokocrypto.ts
  ts/src/tradeogre.ts
  ts/src/upbit.ts
  ts/src/vertex.ts
  ts/src/wavesexchange.ts
  ts/src/wazirx.ts
  ts/src/whitebit.ts
  ts/src/woo.ts
  ts/src/woofipro.ts
  ts/src/xt.ts
  ts/src/yobit.ts
  ts/src/zaif.ts
  ts/src/zonda.ts
  utils/dev-helpers/required-symbols-for-methods.ts
Labels: enhancement

#25114 revert(python) - parse frame
  python/ccxt/async_support/base/ws/fast_client.py
Labels: bug
