Repository ccxt/ccxt, pull requests merged in 2025-09, with the labels that each got.

#26754 Clear orderbook if `loadOrderBook` was not successful (#26753 )
  ts/src/base/Exchange.ts
Labels: bug

#26749 feat(handleTriggerPrices): implement
  ts/src/base/Exchange.ts
Labels: enhancement

#26797 fix(delta): assets request
  ts/src/delta.ts
Labels: bug

#26801 coincatch exchange - update createOrder
  ts/src/coincatch.ts
  ts/src/test/static/markets/coincatch.json
  ts/src/test/static/request/coincatch.json
Labels: enhancement

#26680 fix(okx): createOrder SL & TP attached
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: bug

#26823 fix(Coincatch): exchange fetchPosition updated
  ts/src/coincatch.ts
Labels: bug

#26822 feat(kucoinfutures): setPositionMode
  ts/src/kucoinfutures.ts
  ts/src/test/static/request/kucoinfutures.json
  ts/src/test/static/response/kucoinfutures.json
Labels: enhancement

#26846 fix(go): parseLastPrice base method
  build/goTranspiler.ts
  go/v4/exchange_interface.go
Labels: enhancement

#26709 feat(bitget): watchOrderBook, uta support
  ts/src/pro/bitget.ts
Labels: enhancement

#26449 feat: add Backpack exchange
  skip-tests.json
  ts/src/abstract/backpack.ts
  ts/src/backpack.ts
  ts/src/pro/backpack.ts
  ts/src/test/static/currencies/backpack.json
  ts/src/test/static/markets/backpack.json
  ts/src/test/static/request/backpack.json
  ts/src/test/static/response/backpack.json
  ts/src/test/tests.ts
Labels: new exchange

#26857 fix(hyperliquid): throw error in fetchDeposits
  ts/src/hyperliquid.ts
Labels: bug

#26809 feat(bitget): watchBalance, watchPositions, watchOrders uta support
  ts/src/pro/bitget.ts
Labels: enhancement

#26877 fix(php): transpiled parts
  php/Exchange.php
Labels: bug

#25473 fix(c#) - undefined currencies
  cs/ccxt/base/Exchange.Options.cs
  python/ccxt/base/exchange.py
Labels: enhancement

#24706 supported features & snippets
  ts/src/base/Exchange.ts
  wiki/FAQ.md
  wiki/Manual.md
Labels: enhancement

#26896 refactor(bigone): ohlcv error
  ts/src/bigone.ts
Labels: enhancement

#26897 fix(backpack): test watchTrades & skip ^
  skip-tests.json
  ts/src/pro/test/Exchange/test.watchTrades.ts
Labels: enhancement

#26886 fix(kucoin): isFiat logic ^
  ts/src/kucoin.ts
Labels: bug

#26907 fix(okx): sl tp order with trigger
  ts/src/okx.ts
  ts/src/test/static/currencies/okx.json
  ts/src/test/static/markets/okx.json
  ts/src/test/static/request/okx.json
  ts/src/test/static/response/okx.json
Labels: bug

#26921 feat(okx): cancelOrders, add new algoClOrdId support
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
  ts/src/test/static/response/okx.json
Labels: enhancement

#26929 fix(gemini): fetchMarkets inarray fix
  ts/src/gemini.ts
Labels: bug

#26930 fix(apex): fetchOHLCV
  ts/src/apex.ts
  ts/src/test/static/response/apex.json
Labels: bug

#26932 fix(htx): fix ws trades
  ts/src/htx.ts
  ts/src/pro/htx.ts
Labels: bug
