Repository ccxt/ccxt, pull requests merged in 2025-04, with the labels that each got.

#25594 fix(derive): add creation_timestamp
  ts/src/derive.ts
  ts/src/test/static/response/derive.json
Labels: bug

#25586 fix(krakenfutures) - unskip ^
  skip-tests.json
  ts/src/pro/krakenfutures.ts
Labels: bug

#25587 fix(coinbase) - unskip tests ^
  skip-tests.json
  ts/src/coinbase.ts
Labels: bug

#25589 fix(bitmart) - watchTrades fix
  skip-tests.json
  ts/src/pro/bitmart.ts
Labels: bug

#25590 tests(ace) - unskip ^
  skip-tests.json
Labels: bug

#25591 fix(ascendex) - unskip tests ^
  skip-tests.json
  ts/src/ascendex.ts
Labels: bug

#25605 fix(woo): inverse false ^
  ts/src/woo.ts
Labels: bug

#25607 tests(binance) - unksip networks ^
  skip-tests.json
  ts/src/binance.ts
Labels: enhancement

#25600 fix(okx) - expiry time for future/option
  ts/src/okx.ts
Labels: bug

#25604 fix(woofipro) - inverse false ^
  ts/src/woofipro.ts
Labels: bug

#25602 fix(derive) - linear inverse ^
  ts/src/derive.ts
Labels: bug

#25599 tests(ace) - unskip markets ^
  skip-tests.json
  ts/src/ace.ts
Labels: enhancement

#25601 fix(defx) - market inverse ^
  ts/src/defx.ts
Labels: bug

#25608 fix(derive): options linear ^
  ts/src/derive.ts
Labels: bug

#25597 tests(binanceus) - fetchStatus unskip ^
  skip-tests.json
Labels: enhancement

#25624 fix(bitget) - market precision
  skip-tests.json
  ts/src/bitget.ts
Labels: bug

#25614 fix(ascedex): currency id str ^
  ts/src/ascendex.ts
Labels: bug

#25625 tests(bitget): ws orderbook field ^
  skip-tests.json
  ts/src/pro/bitget.ts
Labels: bug

#25616 tests(binance): unskip ticker & precision ^
  skip-tests.json
  ts/src/binance.ts
Labels: enhancement

#25634 fix(bitrue): orderbook & retest
  skip-tests.json
  ts/src/bitrue.ts
Labels: bug

#25636 feat(bybit): define most method types
  ts/src/bybit.ts
Labels: enhancement

#25635 chore(tests): minor comment
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: bug

#25618 chore(skips): empty entries ^
  skip-tests.json
Labels: enhancement

#25644 refactor(base): reorg removeRepeatedElementsFromArray
  build/transpile.ts
  ts/src/base/Exchange.ts
  ts/src/test/base/test.removeRepeatedElementsFromArray.ts
  ts/src/test/base/tests.init.ts
Labels: enhancement

#25672 fix(gate): btc inverse contractSize fix
  ts/src/gate.ts
Labels: bug

#25670 test(ace): skip temp ^
  skip-tests.json
Labels: enhancement

#25665 tests(ascendex): skip bid ask ^
  skip-tests.json
  ts/src/pro/ascendex.ts
Labels: enhancement

#25664 delist(bitpanda): remove old alias
  ts/ccxt.ts
  ts/src/bitpanda.ts
  ts/src/pro/bitpanda.ts
  ts/src/pro/onetrading.ts
Labels: enhancement

#25648 duplicate folders/files ^
  js/src/pro/test/base/test.Cache.d.ts
  js/src/pro/test/base/test.Cache.js
  js/src/pro/test/base/test.OrderBook.d.ts
  js/src/pro/test/base/test.OrderBook.js
  python/ccxt/pro/test/Exchange/test_watch_balance.py
  python/ccxt/pro/test/Exchange/test_watch_bids_asks.py
  python/ccxt/pro/test/Exchange/test_watch_liquidations.py
  python/ccxt/pro/test/Exchange/test_watch_liquidations_for_symbols.py
  python/ccxt/pro/test/Exchange/test_watch_my_trades.py
  python/ccxt/pro/test/Exchange/test_watch_ohlcv.py
  python/ccxt/pro/test/Exchange/test_watch_ohlcv_for_symbols.py
  python/ccxt/pro/test/Exchange/test_watch_order_book.py
  python/ccxt/pro/test/Exchange/test_watch_order_book_for_symbols.py
  python/ccxt/pro/test/Exchange/test_watch_orders.py
  python/ccxt/pro/test/Exchange/test_watch_position.py
  python/ccxt/pro/test/Exchange/test_watch_positions.py
  python/ccxt/pro/test/Exchange/test_watch_ticker.py
  python/ccxt/pro/test/Exchange/test_watch_tickers.py
  python/ccxt/pro/test/Exchange/test_watch_trades.py
  python/ccxt/pro/test/Exchange/test_watch_trades_for_symbols.py
Labels: bug

#25632 chore(onetrading): comment ^
  skip-tests.json
Labels: enhancement

#25630 fix(bitopro): ws unskip (minor changes)
  skip-tests.json
  ts/src/pro/bitopro.ts
Labels: enhancement

#25627 tests(bitmart): unskip fields ^
  skip-tests.json
  ts/src/bitmart.ts
Labels: enhancement

#25622 chore(reorg): validate types ^
  build/validate-types.ts
  ts/src/base/Exchange.ts
Labels: enhancement

#25620 chore(bitcoincom): delist (remove) inexistent old alias ^
  skip-tests.json
  ts/ccxt.ts
  ts/src/abstract/bitcoincom.ts
  ts/src/bitcoincom.ts
  ts/src/pro/bitcoincom.ts
Labels: enhancement

#25619 fix(bitbns) - active & unskip ^
  skip-tests.json
  ts/src/bitbns.ts
Labels: bug

#25650 test(assertions): enhance tests
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: enhancement

#25669 test(markets): complete reorg
  ts/src/test/Exchange/base/test.market.ts
Labels: enhancement

#23316 fix(docs) - precisions
  wiki/Manual.md
Labels: bug

#25675 bitopro skip timestamp ^
  skip-tests.json
Labels: enhancement

#25623 unskip bitflyer ^
  skip-tests.json
  ts/src/bitflyer.ts
Labels: bug, enhancement

#25677 chore(skips): sort alphabetically ^
  skip-tests.json
Labels: enhancement

#25681 fix(tests): skip json ^
  skip-tests.json
Labels: bug, important

#25682 fix(okx): fetchohlcv
  ts/src/okx.ts
  ts/src/test/static/request/okx.json
Labels: bug

#25684 doc(order): stoploss & params
  wiki/Manual.md
Labels: enhancement

#25690 test(market): fix precision issues ^
  ts/src/test/Exchange/base/test.market.ts
Labels: bug, enhancement

#25691 test(bitmart): skip watchOB bid-ask ^
  skip-tests.json
Labels: enhancement

#25693 test(bitflyer): no settleId ^
  skip-tests.json
  ts/src/test/Exchange/base/test.market.ts
Labels: bug

#25698 fix(safeCurrencyStructure): withdraw/deposit/active
  ts/src/base/Exchange.ts
  ts/src/okx.ts
  ts/src/test/Exchange/test.fetchCurrencies.ts
Labels: bug

#25703 feat(coinlist): add missing endpoints
  ts/src/coinlist.ts
Labels: enhancement

#25696 test(coinex): skip precision & networks ^
  skip-tests.json
Labels: bug

#25695 test(bitopro): skip l2 ^
  skip-tests.json
Labels: enhancement

#25694 test(ace): skip temp ^
  skip-tests.json
Labels: enhancement

#25719 feat(coinlist): add fetchFundingRate
  ts/src/coinlist.ts
  ts/src/test/static/markets/coinlist.json
  ts/src/test/static/request/coinlist.json
  ts/src/test/static/response/coinlist.json
Labels: enhancement

#25718 fix(binance): deposit address & reversedNetworks
  ts/src/binance.ts
  ts/src/test/static/currencies/binance.json
  ts/src/test/static/markets/binance.json
  ts/src/test/static/response/binance.json
Labels: enhancement

#25724 test(skips): add type ^
  skip-tests.json
Labels: bug

#25725 ace - skip further ^
  skip-tests.json
Labels: bug

#25756 feat(okx): April 17 2025 changelog
  ts/src/okx.ts
Labels: enhancement

#25751 feat(xt): add editOrder
  ts/src/test/static/request/xt.json
  ts/src/test/static/response/xt.json
  ts/src/xt.ts
Labels: enhancement

#25778 feat(bitget): fetchFundingRate, alternative method
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
  ts/src/test/static/response/bitget.json
Labels: enhancement

#25782 fix(gate): watchPostions fix close positions error
  ts/src/pro/gate.ts
Labels: bug

#25752 chore(binance): remove malta MT
  ts/src/binance.ts
Labels: enhancement

#25783 feat(bitget): fetchFundingRate, updated response
  ts/src/bitget.ts
  ts/src/test/static/response/bitget.json
Labels: enhancement

#25787 feat(apex): multiple fixes
  skip-tests.json
  ts/src/apex.ts
Labels: enhancement

#25788 fix(cex): fetchtickers open price
  ts/src/cex.ts
Labels: enhancement

#25785 fix(bitmex): market states & expiry for perps
  ts/src/bitmex.ts
Labels: bug

#25786 fix(precision): base safeCurrencyStructure change for currency wide precision
  ts/src/base/Exchange.ts
Labels: bug

#25809 test(currencies): fix check ^
  ts/src/test/Exchange/test.fetchCurrencies.ts
Labels: bug

#25817 test(shared-methods): add extra extend for empty values
  skip-tests.json
  ts/src/test/Exchange/base/test.sharedMethods.ts
Labels: enhancement

#25819 fix(hitbtc & bequant): currency type ^
  skip-tests.json
  ts/src/hitbtc.ts
Labels: bug

#25829 fix(probit): type currency ^
  ts/src/probit.ts
Labels: bug

#25820 fix!(ace): delist
  cs/ccxt/api/ace.cs
  cs/ccxt/exchanges/ace.cs
  cs/ccxt/wrappers/ace.cs
  go/v4/ace.go
  go/v4/ace_api.go
  go/v4/ace_wrapper.go
  php/abstract/ace.php
  php/ace.php
  php/async/abstract/ace.php
  php/async/ace.php
  python/ccxt/abstract/ace.py
  python/ccxt/ace.py
  python/ccxt/async_support/ace.py
  ts/ccxt.ts
  ts/src/abstract/ace.ts
  ts/src/ace.ts
  ts/src/test/static/currencies/ace.json
  ts/src/test/static/markets/ace.json
  ts/src/test/static/request/ace.json
  ts/src/test/static/response/ace.json
Labels: enhancement

#25095 fix(coinbase) - WS orderbook
  skip-tests.json
  ts/src/coinbase.ts
  ts/src/pro/coinbase.ts
  ts/src/test/static/currencies/coinbase.json
  ts/src/test/static/markets/coinbase.json
  ts/src/test/static/response/coinbase.json
Labels: bug

#25813 fix(mexc): fetchCurrencies
  ts/src/mexc.ts
  ts/src/test/static/currencies/mexc.json
Labels: bug, enhancement

#25828 fix(phemex): currency type ^
  skip-tests.json
  ts/src/phemex.ts
Labels: bug, enhancement

#25822 test(binancecoinm): remove skip
  skip-tests.json
Labels: enhancement

#25826 fix(whitebit): missing key ^
  ts/src/whitebit.ts
Labels: bug

#25824 fix(woo): currency & market fields
  ts/src/woo.ts
Labels: bug

#25797 fix(bitget): fetchOHLCV reorganize
  ts/src/bitget.ts
  ts/src/test/static/request/bitget.json
Labels: bug

#25825 fix(xt): currency type
  ts/src/xt.ts
Labels: bug
