Repository ccxt/ccxt, pull requests merged in 2025-05, with the labels that each got.

#25827 fix(timex): safeTrade ^
  ts/src/test/static/request/timex.json
  ts/src/test/static/response/timex.json
  ts/src/timex.ts
Labels: bug

#25851 fix(bitopro): networks key ^
  ts/src/bitopro.ts
Labels: bug

#25840 fix(hyperliquid): currency type ^
  ts/src/hyperliquid.ts
Labels: duplicate

#25839 fix(bitrue): currency type ^
  ts/src/bitrue.ts
Labels: bug

#25838 fix(poloniex): currency type ^
  ts/src/poloniex.ts
Labels: enhancement

#25842 fix(kraken): fc type ^
  ts/src/kraken.ts
Labels: bug

#25843 fix(hollaex): fc type ^
  ts/src/hollaex.ts
Labels: enhancement

#25844 fix(delta): fc type ^
  ts/src/delta.ts
Labels: bug

#25845 fix(deribit): fc type ^
  ts/src/deribit.ts
Labels: bug

#25841 fix(huobijp): currency networks ^
  ts/src/huobijp.ts
Labels: enhancement

#25849 fix(bitmex): currency type ^
  ts/src/bitmex.ts
Labels: bug

#25850 fix(bitvavo): fc type ^
  ts/src/bitvavo.ts
Labels: bug

#25846 fix(coinone): currency type field ^
  ts/src/coinone.ts
Labels: bug

#25847 fix(coinlist): currency type ^
  ts/src/coinlist.ts
Labels: bug

#25848 fix(coinex): fc type ^
  ts/src/coinex.ts
Labels: enhancement

#25857 fix(whitebit): crypto type
  ts/src/whitebit.ts
Labels: bug

#25856 fix(htx): currency type
  ts/src/htx.ts
Labels: bug

#25854 chore(ace): remove json skip ^
  skip-tests.json
Labels: enhancement

#25866 fix(delta): correct expiry when no mfetched market
  ts/src/delta.ts
Labels: bug

#25867 test(coinone): major currencies skip
  skip-tests.json
Labels: bug

#25869 fix(bingx): safe currency
  skip-tests.json
  ts/src/bingx.ts
Labels: bug

#25871 fix(bitmat): currency related things
  skip-tests.json
  ts/src/bitmart.ts
Labels: bug

#25873 retest htx
  skip-tests.json
  ts/src/htx.ts
Labels: enhancement

#25870 fix(bitget): fix fetchCurrencies
  skip-tests.json
  ts/src/bitget.ts
  ts/src/test/Exchange/base/test.currency.ts
Labels: bug

#25868 refactor(ticker): minor
  ts/src/test/Exchange/base/test.market.ts
  ts/src/test/Exchange/base/test.ticker.ts
Labels: bug

#25883 test(htx): remove proxy
  skip-tests.json
Labels: bug

#25887 feat(bybit): change createOrder stopLossPrice endpoint
  ts/src/bybit.ts
  ts/src/test/static/request/bybit.json
Labels: enhancement

#25881 fix(htx): null bid-ask
  ts/src/htx.ts
Labels: bug

#25886 fix(htx): python base & certificates addition
  python/ccxt/async_support/base/exchange.py
  ts/src/htx.ts
Labels: bug

#25889 test(orderbook): amend all orderbook tests
  skip-tests.json
  ts/src/test/Exchange/base/test.orderBook.ts
  ts/src/test/tests.ts
Labels: enhancement

#25890 test(bingx): bv compare ^
  skip-tests.json
  ts/src/bingx.ts
Labels: enhancement

#25896 fix(bitget): parse tickers fix
  skip-tests.json
  ts/src/bitget.ts
Labels: bug

#25895 fix(bitfinex): fetchTickers & parseTicker
  skip-tests.json
  ts/src/bitfinex.ts
  ts/src/test/static/response/bitfinex.json
Labels: bug

#25910 test(apex): skip spread
  skip-tests.json
  ts/src/apex.ts
Labels: enhancement

#25901 refactor: remove l2 skips
  skip-tests.json
Labels: enhancement

#25909 upbit - skips
  skip-tests.json
  ts/src/upbit.ts
Labels: enhancement

#25898 fix(bitmex): fetchMarkets
  skip-tests.json
  ts/src/bitmex.ts
Labels: bug

#25900 fix(bitopro): currency type
  ts/src/bitopro.ts
Labels: bug

#25922 fix(coinbase): revert USD
  ts/src/coinbase.ts
  ts/src/pro/coinbase.ts
  ts/src/test/static/markets/coinbase.json
  ts/src/test/static/response/coinbase.json
Labels: bug

#25915 test(btcturk): retest loadmarkets fields
  skip-tests.json
  ts/src/btcturk.ts
Labels: bug

#25911 fix(bitvavo): multiple fields in fetchCurrencies
  skip-tests.json
  ts/src/bitvavo.ts
Labels: enhancement

#25914 test(btcmarkets): retest
  skip-tests.json
  ts/src/btcmarkets.ts
Labels: enhancement

#25908 test(bitteam): retest
  skip-tests.json
  ts/src/bitteam.ts
Labels: bug

#25906 test(bitso): unskip ohlcv
  skip-tests.json
  ts/src/bitso.ts
Labels: bug

#25925 fix(bybit): createOrder, option category param
  ts/src/bybit.ts
Labels: bug

#25913 test(btcalpha): unskip
  skip-tests.json
  ts/src/btcalpha.ts
Labels: enhancement

#25897 feat(bitget): type crypto & fiat
  skip-tests.json
  ts/src/bitget.ts
Labels: enhancement

#25928 fix(bybit): option markets types & revert tests
  ts/src/bybit.ts
  ts/src/test/Exchange/base/test.market.ts
Labels: bug

#25918 fix(bigone): fetchCurrencies reorganize
  skip-tests.json
  ts/src/base/Exchange.ts
  ts/src/bigone.ts
Labels: enhancement

#25946 test(coinbase): skip spread OB
  skip-tests.json
  ts/src/pro/coinbase.ts
Labels: bug

#25949 fix(bitfinex): deposit withdraw statuses, extra fixes
  ts/src/bitfinex.ts
Labels: bug, enhancement

#25945 fix(apex): fetchCurrencies reorg & field fixes
  ts/src/apex.ts
Labels: bug

#25941 refactor(bingx): fetchCurrencies
  ts/src/bingx.ts
  ts/src/test/static/currencies/bingx.json
  ts/src/test/static/markets/bingx.json
  ts/src/test/static/request/bingx.json
  ts/src/test/static/response/bingx.json
Labels: enhancement

#25943 fix(proxies): some updates
  examples/ts/proxy-usage.ts
  ts/src/base/Exchange.ts
Labels: enhancement

#25950 refactor(bitfinex): networks reorg
  ts/src/bitfinex.ts
  ts/src/test/static/currencies/bitfinex.json
  ts/src/test/static/markets/bitfinex.json
  ts/src/test/static/request/bitfinex.json
Labels: bug

#25939 fix(bitget): max candles back
  ts/src/bitget.ts
Labels: bug

#25957 skip defx field ^
  skip-tests.json
Labels: enhancement

#25958 skip field cryptocom ^
  skip-tests.json
Labels: enhancement

#25959 fix(bithumb): ws timestamp for trades
  ts/src/pro/bithumb.ts
Labels: bug

#25964 fix(apex): correct symbol
  ts/src/apex.ts
Labels: bug

#25955 feat(bitget): networks & base status
  ts/src/base/Exchange.ts
  ts/src/bitget.ts
  ts/src/test/static/currencies/bitget.json
  ts/src/test/static/markets/bitget.json
  ts/src/test/static/request/bitget.json
  ts/src/test/static/response/bitget.json
Labels: bug

#25960 refactor(cex): fetchCurrencies
  ts/src/cex.ts
  ts/src/test/static/currencies/cex.json
  ts/src/test/static/markets/cex.json
  ts/src/test/static/response/cex.json
Labels: enhancement

#25962 fix(coinbase): fetchCurrencies rework
  ts/src/coinbase.ts
  ts/src/test/static/currencies/coinbase.json
  ts/src/test/static/markets/coinbase.json
  ts/src/test/static/request/coinbase.json
Labels: bug, enhancement

#25966 fix(coinbaseexchange): fetchCurrencies & networks
  skip-tests.json
  ts/src/coinbaseexchange.ts
  ts/src/test/static/currencies/coinbaseexchange.json
  ts/src/test/static/markets/coinbaseexchange.json
  ts/src/test/static/request/coinbaseexchange.json
  ts/src/test/static/response/coinbaseexchange.json
Labels: bug, enhancement

#25938 feat(cli) allow set custom parameters for any exchange method
  examples/js/cli.js
  examples/ts/cli.ts
Labels: enhancement

#25979 fix(coinex): fetchCurrencies reorg
  ts/src/coinex.ts
Labels: enhancement

#25967 fix(coincatch): fetchCurrencies reorg & unified networks
  skip-tests.json
  ts/src/coincatch.ts
  ts/src/test/static/currencies/coincatch.json
  ts/src/test/static/request/coincatch.json
  ts/src/test/static/response/coincatch.json
Labels: bug

#25944 feat(kraken): createOrderWs, editOrderWs, update to v2
  ts/src/kraken.ts
  ts/src/pro/kraken.ts
Labels: enhancement

#25983 fix(coinone): fetchCurrencies
  skip-tests.json
  ts/src/coinone.ts
  ts/src/test/static/currencies/coinone.json
  ts/src/test/static/markets/coinone.json
  ts/src/test/static/request/coinone.json
  ts/src/test/static/response/coinone.json
Labels: bug, enhancement

#25981 fix(coinmetro): fetchCurrencies
  skip-tests.json
  ts/src/coinmetro.ts
  ts/src/test/static/currencies/coinmetro.json
  ts/src/test/static/markets/coinmetro.json
  ts/src/test/static/request/coinmetro.json
  ts/src/test/static/response/coinmetro.json
Labels: bug

#25917 fix(bybit): fetchCurrencies reorg & tests
  skip-tests.json
  ts/src/bybit.ts
  ts/src/test/static/currencies/bybit.json
  ts/src/test/static/markets/bybit.json
  ts/src/test/static/request/bybit.json
  ts/src/test/static/response/bybit.json
Labels: enhancement

#25980 fix(coinlist): fetchCurrencies reorg
  ts/src/coinlist.ts
  ts/src/test/static/currencies/coilist.json
  ts/src/test/static/markets/coilist.json
  ts/src/test/static/request/coinlist.json
  ts/src/test/static/response/coinlist.json
Labels: bug

#25985 feat(cryptocom): fetchCurrencies
  ts/src/cryptocom.ts
  ts/src/test/static/currencies/cryptocom.json
  ts/src/test/static/markets/cryptocom.json
  ts/src/test/static/request/cryptocom.json
  ts/src/test/static/response/cryptocom.json
Labels: enhancement

#25984 feat(coinsph): fetchCurrencies
  ts/src/coinsph.ts
  ts/src/test/static/currencies/coinsph.json
  ts/src/test/static/markets/coinsph.json
  ts/src/test/static/request/coinsph.json
  ts/src/test/static/response/coinsph.json
Labels: enhancement

#25912 feat(btcbox): fetchMarkets
  skip-tests.json
  ts/src/btcbox.ts
Labels: bug

#25907 delist(bl3p): shut down
  cs/ccxt/api/bl3p.cs
  cs/ccxt/exchanges/bl3p.cs
  cs/ccxt/wrappers/bl3p.cs
  go/v4/bl3p.go
  go/v4/bl3p_api.go
  go/v4/bl3p_wrapper.go
  js/ccxt.d.ts
  js/ccxt.js
  js/src/abstract/bl3p.d.ts
  js/src/abstract/bl3p.js
  js/src/bl3p.d.ts
  js/src/bl3p.js
  php/abstract/bl3p.php
  php/async/abstract/bl3p.php
  php/async/bl3p.php
  php/bl3p.php
  python/ccxt/abstract/bl3p.py
  python/ccxt/async_support/bl3p.py
  python/ccxt/bl3p.py
  skip-tests.json
  ts/ccxt.ts
  ts/src/abstract/bl3p.ts
  ts/src/bl3p.ts
  ts/src/test/static/currencies/bl3p.json
  ts/src/test/static/markets/bl3p.json
  ts/src/test/static/request/bl3p.json
  ts/src/test/static/response/bl3p.json
Labels: enhancement

#25902 fix(bitrue): fetchCurrencies full restructure
  skip-tests.json
  ts/src/bitrue.ts
Labels: bug

#25862 chore(tests-manager.sh): remove
  tests-manager.sh
Labels: enhancement

#25998 feat(paradex): add fetchGreeks
  cs/ccxt/base/Exchange.Types.cs
  python/ccxt/base/types.py
  ts/src/base/types.ts
  ts/src/paradex.ts
  ts/src/test/static/markets/paradex.json
  ts/src/test/static/request/paradex.json
  ts/src/test/static/response/paradex.json
  wiki/Manual.md
Labels: enhancement

#26010 fix(ellipx): fetchCurrencies reorg & static tests
  skip-tests.json
  ts/src/ellipx.ts
  ts/src/test/static/currencies/ellipx.json
  ts/src/test/static/markets/ellipx.json
  ts/src/test/static/request/ellipx.json
  ts/src/test/static/response/ellipx.json
Labels: bug, enhancement

#26007 fix(derive): safeCurrencystructure & static tests
  ts/src/derive.ts
  ts/src/test/static/currencies/derive.json
  ts/src/test/static/markets/derive.json
  ts/src/test/static/request/derive.json
  ts/src/test/static/response/derive.json
Labels: enhancement

#26005 fix(delta): fetchCurrencies
  ts/src/delta.ts
  ts/src/test/static/currencies/delta.json
  ts/src/test/static/markets/delta.json
  ts/src/test/static/request/delta.json
  ts/src/test/static/response/delta.json
Labels: enhancement

#26023 fix(gemini): add SOL quote currency
  ts/src/gemini.ts
Labels: bug

#26018 Blofin - positionMode and marginMode methods implementation
  ts/src/blofin.ts
  ts/src/test/static/request/blofin.json
  ts/src/test/static/response/blofin.json
Labels: enhancement

#26030 fix(hyperliquid): fetchCurrencies struct
  ts/src/hyperliquid.ts
  ts/src/test/static/currencies/hyperliquid.json
  ts/src/test/static/markets/hyperliquid.json
  ts/src/test/static/request/hyperliquid.json
  ts/src/test/static/response/hyperliquid.json
Labels: bug

#26028 fix(hitbtc): fetchCurrencies reorg
  ts/src/hitbtc.ts
  ts/src/test/static/currencies/hitbtc.json
  ts/src/test/static/markets/hitbtc.json
  ts/src/test/static/request/hitbtc.json
  ts/src/test/static/response/hitbtc.json
Labels: bug

#26035 feat!(idex): delist
  cs/ccxt/api/idex.cs
  cs/ccxt/exchanges/idex.cs
  cs/ccxt/wrappers/idex.cs
  go/v4/idex.go
  go/v4/idex_api.go
  go/v4/idex_wrapper.go
  php/abstract/idex.php
  php/async/abstract/idex.php
  php/async/idex.php
  php/idex.php
  php/pro/idex.php
  python/ccxt/abstract/idex.py
  python/ccxt/async_support/idex.py
  python/ccxt/idex.py
  python/ccxt/pro/idex.py
  skip-tests.json
  ts/ccxt.ts
  ts/src/abstract/idex.ts
  ts/src/idex.ts
  ts/src/pro/idex.ts
  ts/src/test/static/currencies/idex.json
  ts/src/test/static/markets/idex.json
  ts/src/test/static/request/idex.json
  ts/src/test/static/response/idex.json
Labels: enhancement

#26025 fix(gemini): fetchCurrencies safeStruct
  ts/src/gemini.ts
  ts/src/test/static/currencies/gemini.json
  ts/src/test/static/markets/gemini.json
Labels: bug

#26048 fix(mexc): fetchCurrencies fields
  ts/src/mexc.ts
Labels: bug

#26045 fix(python): remove python/ccxt/pro/test/Exchange directory
  python/ccxt/pro/test/Exchange/test_watch_balance.py
  python/ccxt/pro/test/Exchange/test_watch_bids_asks.py
  python/ccxt/pro/test/Exchange/test_watch_liquidations.py
  python/ccxt/pro/test/Exchange/test_watch_liquidations_for_symbols.py
  python/ccxt/pro/test/Exchange/test_watch_my_trades.py
  python/ccxt/pro/test/Exchange/test_watch_ohlcv.py
  python/ccxt/pro/test/Exchange/test_watch_ohlcv_for_symbols.py
  python/ccxt/pro/test/Exchange/test_watch_order_book.py
  python/ccxt/pro/test/Exchange/test_watch_order_book_for_symbols.py
  python/ccxt/pro/test/Exchange/test_watch_orders.py
  python/ccxt/pro/test/Exchange/test_watch_position.py
  python/ccxt/pro/test/Exchange/test_watch_positions.py
  python/ccxt/pro/test/Exchange/test_watch_ticker.py
  python/ccxt/pro/test/Exchange/test_watch_tickers.py
  python/ccxt/pro/test/Exchange/test_watch_trades.py
  python/ccxt/pro/test/Exchange/test_watch_trades_for_symbols.py
Labels: bug

#26040 kuna - delist
  cs/ccxt/api/kuna.cs
  cs/ccxt/exchanges/kuna.cs
  cs/ccxt/wrappers/kuna.cs
  go/v4/kuna.go
  go/v4/kuna_api.go
  go/v4/kuna_wrapper.go
  php/abstract/kuna.php
  php/async/abstract/kuna.php
  php/async/kuna.php
  php/kuna.php
  python/ccxt/abstract/kuna.py
  python/ccxt/async_support/kuna.py
  python/ccxt/kuna.py
  skip-tests.json
  ts/ccxt.ts
  ts/src/abstract/kuna.ts
  ts/src/kuna.ts
  ts/src/test/static/currencies/kuna.json
  ts/src/test/static/markets/kuna.json
  ts/src/test/static/request/kuna.json
  ts/src/test/static/response/kuna.json
Labels: bug

#26006 fix(deribit): fetchCurrencies & static tests
  ts/src/deribit.ts
  ts/src/test/static/currencies/deribit.json
  ts/src/test/static/markets/deribit.json
  ts/src/test/static/request/deribit.json
  ts/src/test/static/response/deribit.json
Labels: enhancement

#26051 fix(ndax): fetchCurrencies reorg
  ts/src/ndax.ts
  ts/src/test/static/currencies/ndax.json
  ts/src/test/static/markets/ndax.json
  ts/src/test/static/request/ndax.json
  ts/src/test/static/response/ndax.json
Labels: enhancement

#26053 fix(onetrading): fetchCurrencies struct
  ts/src/onetrading.ts
  ts/src/test/static/currencies/onetrading.json
  ts/src/test/static/request/onetrading.json
  ts/src/test/static/response/onetrading.json
Labels: bug

#26060 fix(bitget): withdraw precision
  ts/src/bitget.ts
  ts/src/test/static/currencies/bitget.json
  ts/src/test/static/markets/bitget.json
  ts/src/test/static/request/bitget.json
  ts/src/test/static/response/bitget.json
Labels: bug

#26061 fix(coinbase): fetchMarketV3
  ts/src/coinbase.ts
Labels: bug

#26064 fix(python): wsSocksProxy fix
  python/ccxt/async_support/base/exchange.py
Labels: bug, enhancement

#26073 fix(hyperliquid): fees
  ts/src/hyperliquid.ts
Labels: bug

#26081 fix(mexc): ob initialization
  ts/src/pro/mexc.ts
Labels: bug

#26100 feat(whitebit): fetchCurrencies reorg & networks implementation
  ts/src/test/static/currencies/whitebit.json
  ts/src/test/static/markets/whitebit.json
  ts/src/test/static/request/whitebit.json
  ts/src/test/static/response/whitebit.json
  ts/src/whitebit.ts
Labels: bug, enhancement

#26016 refactor(gate): fetchCurrencies change
  ts/src/gate.ts
  ts/src/test/static/currencies/gate.json
  ts/src/test/static/markets/gate.json
  ts/src/test/static/request/gate.json
  ts/src/test/static/response/gate.json
Labels: bug, enhancement

#26108 fix(xt): fetchCurrencies reorg
  ts/src/test/static/currencies/xt.json
  ts/src/test/static/markets/xt.json
  ts/src/xt.ts
Labels: bug, enhancement

#26111 fix(coinmetro): precision fix
  ts/src/coinmetro.ts
Labels: bug

#26107 fix!(woofipro): unify fetchCurrencies > networks
  ts/src/test/static/currencies/woofipro.json
  ts/src/test/static/markets/woofipro.json
  ts/src/test/static/request/woofipro.json
  ts/src/woofipro.ts
Labels: bug, enhancement
