Repository ccxt/ccxt, pull requests merged in 2025-03, with the labels that each got.

#25400 fix(bybit): correct volume key in parse ws ohlcv
  ts/src/pro/bybit.ts
Labels: bug

#25322 feat(hyperliquid): add editOrders
  ts/src/hyperliquid.ts
  ts/src/pro/hyperliquid.ts
Labels: enhancement

#25412 fix(bitrue): replace fromIdx with until
  ts/src/bitrue.ts
Labels: bug

#23581 Cryptomus integration
  skip-tests.json
  ts/src/abstract/cryptomus.ts
  ts/src/cryptomus.ts
  ts/src/test/static/currencies/cryptomus.json
  ts/src/test/static/markets/cryptomus.json
  ts/src/test/static/request/cryptomus.json
  ts/src/test/static/response/cryptomus.json
Labels: new exchange

#25426 fix(gate): fetchFundingRates inverse
  ts/src/gate.ts
  ts/src/htx.ts
  ts/src/test/static/request/gate.json
  ts/src/test/static/response/gate.json
Labels: bug

#25449 feat(whitebit): add endpoints
  ts/src/whitebit.ts
Labels: enhancement

#25444 feat(bitget): update fetchCanceledAndClosedOrders
  ts/src/bitget.ts
Labels: enhancement

#25370 feat(whitebit): add fetchFundingHistory
  ts/src/whitebit.ts
Labels: enhancement

#25458 feat(cli): read keys.json
  build/goTranspiler.ts
  go/cli/main.go
Labels: enhancement

#25376 feat(whitebit): add conversion methods
  ts/src/test/static/request/whitebit.json
  ts/src/test/static/response/whitebit.json
  ts/src/whitebit.ts
Labels: enhancement

#25471 fix(gotranspiler) - types completed
  build/goTranspiler.ts
Labels: enhancement

#25441 fix(retries) - base
  python/ccxt/async_support/base/exchange.py
  python/ccxt/base/exchange.py
  ts/src/base/Exchange.ts
Labels: bug

#25472 feat(luno): createDepositAddress, fetchDepositAddress
  ts/src/luno.ts
Labels: enhancement

#25477 chore(deps): update ^
  package-lock.json
  package.json
Labels: enhancement

#25469 fix(csharpTranspiler) - types completed
  build/csharpTranspiler.ts
Labels: enhancement

#25468 fix(transpiler) - types completed
  build/transpile.ts
Labels: enhancement

#25492 feat(paradex): update apis
  ts/src/paradex.ts
  ts/src/test/static/request/paradex.json
Labels: enhancement

#25478 feat(whitebit): add fetchPosition, fetchPositions, fetchPositionHistory
  build/transpile.ts
  ts/src/test/static/request/whitebit.json
  ts/src/test/static/response/whitebit.json
  ts/src/whitebit.ts
Labels: enhancement

#25513 feat(bybit): update apis
  ts/src/bybit.ts
  ts/src/pro/bybit.ts
Labels: enhancement

#25538 tests(static): fix string & number issues
  examples/ts/cli.ts
Labels: bug

#25543 fix(kraken) - commoncurrencies
  ts/src/kraken.ts
Labels: bug

#25550 docs(readme): minor
  README.md
Labels: enhancement

#25553 feat(okx) - full networks unif
  ts/src/okx.ts
Labels: bug, enhancement

#25466 feat(base) - handleRequestNetwork
  ts/src/base/Exchange.ts
  ts/src/test/base/test.handleMethods.ts
Labels: enhancement

#25560 fix(okx) - zksync ^
  ts/src/okx.ts
Labels: enhancement

#25378 poloniex & poloniexfutures - v3 Update & merger
  skip-tests.json
  ts/ccxt.ts
  ts/src/abstract/poloniexfutures.ts
  ts/src/poloniex.ts
  ts/src/poloniexfutures.ts
  ts/src/pro/poloniexfutures.ts
  ts/src/test/static/currencies/poloniex.json
  ts/src/test/static/markets/poloniex.json
  ts/src/test/static/request/poloniex.json
  ts/src/test/static/request/poloniexfutures.json
  ts/src/test/static/response/poloniex.json
  ts/src/test/static/response/poloniexfutures.json
  ts/src/test/tests.ts
Labels: enhancement

#25567 fix(bingx) - implicit balance endpoint ^
  ts/src/bingx.ts
Labels: enhancement

#25566 chore(poloniex) - ws skip tests ^
  skip-tests.json
Labels: enhancement

#25565 fix(cex) - missing active key ^
  ts/src/cex.ts
Labels: bug

#25569 feat(whitebit): createDepositAddress
  ts/src/whitebit.ts
Labels: enhancement

#25573 fix(poloniex) - features missing symbol req
  ts/src/poloniex.ts
Labels: bug

#25568 feat(whitebit): fetchCrossBorrowRate
  ts/src/whitebit.ts
Labels: enhancement

#25582 fix(derive): rename deriveWalletAddress
  ts/src/pro/derive.ts
Labels: bug

#25564 refactor & fix(okx) - fetchCurrencies
  ts/src/base/Exchange.ts
  ts/src/okx.ts
Labels: enhancement
